/* Real-browser object-set acceptance. Run only in a permitted localhost browser.
 * Anonymous plans; block every external/backend request. Source tests are not a
 * substitute for executing this file. No security overrides or paid API calls. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const url=process.env.APP_URL||'http://127.0.0.1:8947/',out=process.env.RPG_REPORT_DIR||path.resolve('tools/assets/rpg-pack-contract/object-set-evidence');
if(!/^http:\/\/(127\.0\.0\.1|localhost):\d+\/$/.test(url))throw Error('Loopback APP_URL required');
const fixture={walls:[],rooms:[{id:'anonymous-room',x:0,y:0,w:6000,d:4000,floor:1,n:'匿名の確認室'}],items:[{id:'anonymous-chair',type:'fmp-Chair01',x:1100,y:1000,w:520,d:550,rot:12,floor:1,futureField:{keep:[1,2]}},{id:'anonymous-unknown',type:'anonymous-unknown',x:4000,y:2000,w:100,d:100,rot:0,floor:1,custom:{keep:true}}],floorCount:1,startMode:'blank'};
const handleDialog=d=>d.type()==='confirm'&&d.message()==='現在の未保存の編集を、選んだ間取りJSONへ置き換えますか？'?d.accept():d.dismiss();
async function ready(page){await page.waitForFunction(()=>window.PlanLibrary&&window.AssetPackPicker?.getRegistry()&&PlanLibrary.panes.size&&[...PlanLibrary.panes.values()].every(p=>p.ready));await page.evaluate(()=>PlanLibrary.ready);await page.locator('#app-loading').waitFor({state:'hidden'});await page.locator('#preset-choice-modal').waitFor({state:'hidden'});}
async function install(page){await page.locator('#import-file').setInputFiles({name:'anonymous-object-set.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture))});await page.waitForFunction(()=>DATA.items.some(i=>i.id==='anonymous-chair'));}
const snapshot=page=>page.evaluate(()=>({plan:serializeDataSnapshot(),id:__editorPlanId,history:HISTORY.slice(),redo:REDO_HISTORY.slice(),dirty:DIRTY}));
async function open(page){await page.locator('#asset-conversion-open').click();await page.locator('#asset-conversion-dialog').waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelector('[data-conversion="rows"]').children.length===DATA.items.length);}
async function selectBulk(page,pack='rpg-mansion'){await page.selectOption('[data-conversion="pack"]',pack);await page.locator('[data-conversion="review"]>summary').click();await page.locator('[data-conversion="all"]').click();}
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||'/usr/bin/chromium',headless:true,chromiumSandbox:true}),report={checks:[],errors:[],visualStatus:'running'};fs.mkdirSync(out,{recursive:true});
 try{
  const context=await browser.newContext({viewport:{width:1440,height:1050}});await context.route('**/*',route=>{const u=new URL(route.request().url());return ['blob:','data:'].includes(u.protocol)||u.origin===new URL(url).origin&&!u.pathname.startsWith('/api/')?route.continue():route.abort();});
  const page=await context.newPage();page.on('dialog',handleDialog);page.on('pageerror',e=>report.errors.push(e.message));await page.goto(url+'?preset=blank');await ready(page);await install(page);await page.locator('#save-btn').click();await page.waitForFunction(()=>!DIRTY&&!SHARED.saveBusy);
  const original=await snapshot(page),sourceHead=await page.evaluate(async()=> (await PlanLibrary.repo.read(__editorPlanId)).revision.id);
  assert.equal(await page.locator('#catalogue-pack').count(),0);assert.equal(await page.locator('#asset-conversion-open').count(),1);
  await open(page);assert.equal(await page.locator('.object-set-operation').count(),2);assert.equal(await page.locator('[data-conversion="copy"]').isChecked(),true);assert.equal(await page.locator('[data-conversion="pack"]').inputValue(),'japanese-standard');
  await page.selectOption('[data-conversion="list-pack"]','rpg-mansion');await page.selectOption('[data-conversion="pack"]','rpg-mansion');assert.deepEqual(await snapshot(page),original);assert.equal(await page.evaluate(()=>AssetPackPicker.getSelection()),'japanese-standard');await page.keyboard.press('Escape');assert.deepEqual(await snapshot(page),original);report.checks.push('draft dropdowns and Escape preserve native data/history/identity; default copy is checked');
  await open(page);await selectBulk(page);assert.match(await page.locator('[data-conversion="summary"]').innerText(),/1点を差し替え \/ 1点を保持/);await page.locator('[data-conversion="name"]').fill('匿名の洋館コピー');await page.locator('[data-conversion="create"]').click();await page.locator('#asset-conversion-dialog').waitFor({state:'hidden'});await page.waitForFunction(()=>PlanLibrary.retained.length===2);
  assert.deepEqual(await snapshot(page),original);const copy=await page.evaluate(async original=>{const id=PlanLibrary.retained.find(id=>id!==original);return {id,record:await PlanLibrary.repo.read(id),draft:await PlanLibrary.repo.get('drafts',JSON.stringify([PlanLibrary.session,id]))};},original.id);assert.notEqual(copy.id,original.id);assert.equal(copy.record.payload.items[0].type,'rpg-mansion-chair-01');assert.deepEqual(copy.record.payload.items[1],JSON.parse(original.plan).items[1]);assert.equal(copy.draft.dirty,true);assert.equal(copy.draft.cataloguePack,'rpg-mansion');assert.equal(await page.evaluate(async()=> (await PlanLibrary.repo.read(__editorPlanId)).revision.id),sourceHead);report.checks.push('checked copy reuses actual independent repository/CAS and preserves source saved head and live editor');
  await open(page);await selectBulk(page);await page.locator('[data-conversion="copy"]').uncheck();await page.locator('[data-conversion="create"]').click();await page.locator('#asset-conversion-dialog').waitFor({state:'hidden'});const converted=await snapshot(page);assert.equal(converted.id,original.id);assert.equal(converted.history.length,original.history.length+1);assert.equal(converted.dirty,true);assert.equal(converted.redo.length,0);assert.equal(await page.evaluate(async()=> (await PlanLibrary.repo.read(__editorPlanId)).revision.id),sourceHead);
  await page.evaluate(()=>undoAction());assert.equal((await snapshot(page)).plan,original.plan);await page.evaluate(()=>redoAction());assert.equal((await snapshot(page)).plan,converted.plan);await page.evaluate(()=>undoAction());report.checks.push('unchecked mode is one actual native Undo/Redo step, stays dirty and does not immediately replace saved head');
  await open(page);await selectBulk(page);await page.evaluate(()=>{DATA.items[0].x+=17;markDirty();});const edited=await snapshot(page);await page.locator('[data-conversion="create"]').click();assert.match(await page.locator('[data-conversion="status"]').innerText(),/更新/);assert.deepEqual(await snapshot(page),edited);assert.equal(await page.evaluate(()=>PlanLibrary.retained.length),2);await page.locator('[data-conversion="close"]').click();report.checks.push('stale native edit prevents applying reviewed objects to newer data');
  await open(page);await selectBulk(page);await page.evaluate(()=>{window.__originalDerive=PlanLibrary.repo.derive;PlanLibrary.repo.derive=async()=>{throw new DOMException('Anonymous injected quota','QuotaExceededError');};});const beforeFailure=await snapshot(page);await page.locator('[data-conversion="create"]').click();await page.waitForFunction(()=>document.querySelector('[data-conversion="status"]').textContent.includes('quota'));assert.deepEqual(await snapshot(page),beforeFailure);assert.equal(await page.evaluate(()=>PlanLibrary.retained.length),2);await page.evaluate(()=>{PlanLibrary.repo.derive=window.__originalDerive;delete window.__originalDerive;});await page.locator('[data-conversion="close"]').click();report.checks.push('actual repository derive failure preserves original and allows closing/retry');
  // The same native dialog and source snapshot on mobile. Geometry assertions
  // become evidence only when this permitted-browser script actually executes.
  for(const width of [320,390,768]){
   const mobile=await context.newPage();mobile.on('dialog',handleDialog);await mobile.setViewportSize({width,height:960});await mobile.goto(url+'?preset=blank');await ready(mobile);await install(mobile);await mobile.locator('#bnav-tools').click();await open(mobile);await selectBulk(mobile);
   const box=await mobile.locator('#asset-conversion-dialog').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=width&&box.height<=960);await mobile.locator('[data-conversion="create"]').scrollIntoViewIfNeeded();assert.ok((await mobile.locator('[data-conversion="create"]').boundingBox()).height>=40);await mobile.screenshot({path:path.join(out,'object-set-dialog-'+width+'.png')});await mobile.keyboard.press('Escape');await mobile.close();
  }
  report.checks.push('320/390/768px modal containment, scroll, apply/cancel and touch targets');assert.deepEqual(report.errors,[]);report.visualStatus='passed';await context.close();
 }catch(e){report.visualStatus='failed';report.failure=e.stack;throw e;}finally{fs.writeFileSync(path.join(out,'object-set-browser-results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
