/* Actual explicit list-only controls and catalogue placement. Run only in a
 * permitted localhost browser. Anonymous data, no backend or security bypass. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
const url=process.env.APP_URL||'http://127.0.0.1:8947/',out=process.env.RPG_REPORT_DIR||path.resolve('tools/assets/rpg-pack-contract/picker-evidence');
if(!/^http:\/\/(127\.0\.0\.1|localhost):\d+\/$/.test(url))throw Error('Loopback APP_URL required');
const ready=async page=>{await page.waitForFunction(()=>window.AssetPackPicker?.getRegistry()&&window.EditorPane&&window.__editorPlanId);await page.evaluate(()=>comparisonCatalogueReady);await page.locator('#app-loading').waitFor({state:'hidden'});await page.locator('#preset-choice-modal').waitFor({state:'hidden'});};
async function choose(page,pack){await page.locator('#asset-conversion-open').click();await page.selectOption('[data-conversion="list-pack"]',pack);await page.locator('[data-conversion="list-apply"]').click();await page.locator('[data-conversion="close"]').click();}
const snapshot=page=>page.evaluate(()=>({data:serializeDataSnapshot(),history:HISTORY.slice(),redo:REDO_HISTORY.slice(),dirty:DIRTY,id:__editorPlanId}));
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||'/usr/bin/chromium',headless:true,chromiumSandbox:true}),report={checks:[],errors:[],visualStatus:'running'};fs.mkdirSync(out,{recursive:true});
 try{
  const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.route('**/*',route=>{const u=new URL(route.request().url());return ['blob:','data:'].includes(u.protocol)||u.origin===new URL(url).origin&&!u.pathname.startsWith('/api/')?route.continue():route.abort();});const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));page.on('dialog',d=>d.dismiss());await page.goto(url+'?preset=blank');await ready(page);
  const initial=await snapshot(page);const searchOrder=await page.evaluate(()=>{const search=document.getElementById('object-search');return {first:search.firstElementChild.textContent,entry:search.lastElementChild.id,old:document.getElementById('catalogue-pack')!==null};});assert.equal(searchOrder.first,'すべてのオブジェクトを検索');assert.equal(searchOrder.entry,'asset-conversion-open');assert.equal(searchOrder.old,false);
  for(const pack of ['rpg-mansion','japanese-standard','rpg-mansion'])await choose(page,pack);assert.deepEqual(await snapshot(page),initial);report.checks.push('search is first; only explicit list apply changes candidates without plan/history/dirty/identity changes');
  await page.locator('#object-search-input').fill('椅子');assert.equal(await page.locator('#object-search-results [data-tool]').count(),6);assert.equal(await page.locator('#object-search-results [data-tool="rpg-mansion-chair-01"]').count(),1);await page.locator('#object-search-results [data-tool="rpg-mansion-chair-01"]').click();
  const loc=await page.evaluate(()=>({x:ST.panX+2600*ST.zoom*.05,y:ST.panY+1800*ST.zoom*.05}));await page.locator('#c2d').click({position:loc});assert.equal(await page.evaluate(()=>DATA.items.filter(i=>i.type==='rpg-mansion-chair-01').length),1);const placed=await snapshot(page);await page.evaluate(()=>undoAction());assert.equal((await snapshot(page)).data,initial.data);await page.evaluate(()=>redoAction());assert.equal((await snapshot(page)).data,placed.data);
  await page.evaluate(()=>ST.selected=DATA.items.find(i=>i.type==='rpg-mansion-chair-01'));await choose(page,'japanese-standard');assert.equal(await page.evaluate(()=>ST.selected.type),'rpg-mansion-chair-01');report.checks.push('real search card + canvas placement use native Undo/Redo; changing list preserves selected placed RPG object');
  await choose(page,'rpg-mansion');const before=await snapshot(page);const requests=[];context.on('request',r=>requests.push(r.url()));const metrics=await page.evaluate(()=>EditorPane.metrics());await page.evaluate(()=>{for(let i=0;i<100;i++)AssetPackPicker.setSelection(i%2?'rpg-mansion':'japanese-standard');});assert.deepEqual(await snapshot(page),before);assert.equal(requests.filter(x=>/\.glb(?:\?|$)/.test(x)).length,0);assert.deepEqual(await page.evaluate(()=>EditorPane.metrics()),metrics);report.checks.push('100 programmatic catalogue switches retain native data/history/models and trigger no model requests');
  // Use the actual comparison popup and its native plan picker. No alternative
  // workspace implementation or obsolete open/saveWorkspace APIs.
  const popup=context.waitForEvent('page');await page.locator('#compare-launch').click();const compare=await popup;compare.on('dialog',d=>d.dismiss());await compare.waitForFunction(()=>window.PlanLibrary&&PlanLibrary.panes.size===1&&[...PlanLibrary.panes.values()].every(p=>p.ready));await compare.locator('[data-library-new]').click();await compare.locator('.library-dialog input').fill('Anonymous second plan');await compare.getByRole('button',{name:'作成して開く',exact:true}).click();await compare.waitForFunction(()=>PlanLibrary.panes.size===2&&[...PlanLibrary.panes.values()].every(p=>p.ready));const frames=compare.frames().filter(f=>f.url().includes('editorPane='));assert.equal(frames.length,2);for(const frame of frames)await ready(frame);await choose(frames[0],'rpg-mansion');await choose(frames[1],'japanese-standard');assert.equal(await frames[0].evaluate(()=>AssetPackPicker.getSelection()),'rpg-mansion');assert.equal(await frames[1].evaluate(()=>AssetPackPicker.getSelection()),'japanese-standard');await compare.screenshot({path:path.join(out,'independent-object-lists.png')});await compare.close();report.checks.push('comparison native panes have independent list selections');
  const fallback=await context.newPage();await fallback.route('**/packs/rpg-mansion/manifest.json',r=>r.fulfill({status:404,body:'missing'}));await fallback.goto(url+'?preset=blank');await ready(fallback);assert.equal(await fallback.evaluate(()=>AssetPackPicker.setSelection('rpg-mansion')),'japanese-standard');assert.equal(await fallback.locator('#asset-conversion-open').count(),0);assert.equal(await fallback.locator('#object-search-input').count(),1);await fallback.close();report.checks.push('missing optional pack leaves ordinary search and Japanese catalogue available');
  for(const width of [320,390]){const mobile=await context.newPage();await mobile.setViewportSize({width,height:960});await mobile.goto(url+'?preset=blank');await ready(mobile);await mobile.locator('#bnav-tools').click();await choose(mobile,'rpg-mansion');await mobile.locator('#object-search-input').fill('椅子');assert.equal(await mobile.locator('#object-search-results [data-tool]').count(),6);const input=await mobile.locator('#object-search-input').boundingBox(),entry=await mobile.locator('#asset-conversion-open').boundingBox();assert.ok(input.y<entry.y&&entry.height>=40&&entry.width<=width);await mobile.screenshot({path:path.join(out,'search-first-'+width+'.png')});await mobile.close();}report.checks.push('mobile tools sheet retains search-first order and compact 40px dialog target');
  assert.deepEqual(report.errors,[]);report.visualStatus='passed';await context.close();
 }catch(e){report.visualStatus='failed';report.failure=e.stack;throw e;}finally{fs.writeFileSync(path.join(out,'picker-browser-results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
