'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const url=process.env.APP_URL||'http://127.0.0.1:8947/',out=path.resolve('tools/assets/rpg-pack-contract/expansion-evidence');
const fixture={walls:[],rooms:[{id:'room',x:0,y:0,w:7000,d:6000,floor:1,n:'サロン'}],items:[{id:'chair',type:'fmp-Chair01',x:2200,y:1900,w:520,d:550,h:1000,rot:0,floor:1,finishColors:{wood:'#634638'},custom:{keep:true}},{id:'sofa',type:'fmp-Sofa01',x:3000,y:700,w:2000,d:850,h:950,rot:0,floor:1},{id:'bed',type:'fmp-Bed02',x:5000,y:900,w:1600,d:2100,h:2000,rot:90,floor:1},{id:'unknown',type:'unknown-keep',x:700,y:700,w:100,d:100,h:100,rot:0,floor:1}],floorCount:1,startMode:'blank'};
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-webgl']});const report={checks:[],errors:[]};
try{
 const context=await browser.newContext({viewport:{width:1700,height:1050}}),requests=[];await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin===new URL(url).origin&&!u.pathname.startsWith('/api/')||['blob:','data:'].includes(u.protocol))return route.continue();return route.abort();});context.on('request',r=>requests.push(r.url()));
 const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto(url+'?preset=blank');await page.waitForFunction(()=>window.AssetPackPicker?.getRegistry()?.listPacks().some(p=>p.count===50));
 await page.evaluate(p=>applyJsonImport(stageJsonImport(JSON.stringify(p))),fixture);
 const approve=async f=>{await f.waitForFunction(()=>document.querySelector('[data-conversion="rows"]').children.length===4);for(const i of [0,1,2])await f.locator('[data-conversion="rows"] tr[data-index="'+i+'"] input').check();};
 const snapshot=f=>f.evaluate(()=>({data:serializeDataSnapshot(),history:HISTORY.slice(),redo:REDO_HISTORY.slice(),dirty:DIRTY}));const original=await snapshot(page);
 assert.equal(requests.filter(x=>x.includes('/rpg-mansion/models/')).length,0);
 await page.click('#asset-conversion-open');await page.waitForFunction(()=>document.querySelector('[data-conversion="rows"]').children.length===4);
 assert.match(await page.locator('[data-conversion="summary"]').textContent(),/0点を対応/);await page.click('[data-conversion="all"]');assert.match(await page.locator('[data-conversion="summary"]').textContent(),/3点を対応/);await page.click('[data-conversion="none"]');assert.match(await page.locator('[data-conversion="summary"]').textContent(),/0点を対応/);await approve(page);assert.match(await page.locator('[data-conversion="summary"]').textContent(),/3点を対応/);
 await page.locator('[data-conversion="rows"] tr[data-index="2"] input').uncheck();assert.match(await page.locator('[data-conversion="summary"]').textContent(),/2点を対応/);
 assert.deepEqual(await snapshot(page),original);assert.equal(requests.filter(x=>x.includes('/rpg-mansion/models/')).length,0);
 await page.screenshot({path:path.join(out,'conversion-preview.png'),fullPage:true});
 await page.click('[data-conversion="close"]');assert.deepEqual(await snapshot(page),original);report.checks.push('candidate/table preview lazy: no GLB preload; cancel and exclusions preserve source');
 // Cancel an actual renderer child while its first RPG model is gated.
 let release,seenResolve;const gate=new Promise(r=>release=r),seen=new Promise(r=>seenResolve=r);
 await page.route('**/rpg-mansion-chair-01.glb*',async route=>{seenResolve();await gate;await route.continue().catch(()=>{});});
 // Routes on the page also apply to its comparison child requests.
 await page.click('#asset-conversion-open');await approve(page);await page.waitForFunction(()=>!document.querySelector('[data-conversion="capture"]').disabled);
 await page.click('[data-conversion="capture"]');await Promise.race([seen,new Promise((_,rej)=>{const t=setTimeout(()=>rej(Error('GLB gate not reached')),90000);t.unref();})]);
 await page.click('[data-conversion="stop"]');assert.equal(await page.locator('iframe[title="比較用の読み取り専用3D"]').count(),0);release();await page.unroute('**/rpg-mansion-chair-01.glb*');assert.deepEqual(await snapshot(page),original);report.checks.push('cancel delayed comparison GLB disposes preview child and leaves source/history intact');
 await page.click('[data-conversion="capture"]');await page.waitForSelector('[data-conversion="images"] img',{timeout:120000});assert.equal(await page.locator('[data-conversion="images"] img').count(),2);
 assert.deepEqual(await snapshot(page),original);await page.screenshot({path:path.join(out,'conversion-before-after-3d.png'),fullPage:true});report.checks.push('existing real renderer produces before/after same-camera images without installing into source');
 await page.locator('[data-conversion="images"]').screenshot({path:path.join(out,'conversion-3d-pair.png')});
 await page.locator('[data-conversion="rows"] tr[data-index="2"] input').uncheck();
 await page.locator('[data-conversion="name"]').fill('洋館テスト');await page.click('[data-conversion="create"]');await page.waitForFunction(()=>ParallelEditors.plans.size===2&&[...ParallelEditors.panes.values()].every(p=>p.ready));
 assert.deepEqual(await snapshot(page),original);const plans=await page.evaluate(()=>[...ParallelEditors.plans.values()].map(p=>({id:p.id,name:p.name,plan:p.plan})));
 assert.deepEqual(plans[0].plan,JSON.parse(original.data));assert.equal(plans[1].plan.items[0].type,'rpg-mansion-chair-01');assert.equal(plans[1].plan.items[3].type,'unknown-keep');assert.equal(plans[1].plan.items[2].type,'fmp-Bed02');
 let [a,b]=page.frames().filter(f=>f.url().includes('editorPane='));await page.evaluate(()=>ParallelEditors.saveWorkspace());const bBefore=await snapshot(b),aBefore=await snapshot(a);assert.equal(await b.evaluate(()=>AssetPackPicker.getSelection()),'rpg-mansion');
 await a.click('#asset-conversion-open');await approve(a);await a.waitForFunction(()=>!document.querySelector('[data-conversion="create"]').disabled);await a.locator('[data-conversion="name"]').fill('paneの洋館案');await a.click('[data-conversion="create"]');await page.waitForFunction(()=>ParallelEditors.plans.size===3&&[...ParallelEditors.panes.values()].every(p=>p.ready));
 assert.deepEqual(await snapshot(b),bBefore);assert.deepEqual(await page.evaluate(id=>ParallelEditors.plans.get(id).plan,plans[0].id),JSON.parse(aBefore.data));assert.equal(await a.evaluate(()=>DATA.items[0].type),'rpg-mansion-chair-01');report.checks.push('standalone and pane conversion add separate plans; original record and other pane remain unchanged');
 const sourceRecordBeforeQuota=await page.evaluate(async id=>JSON.stringify(await ParallelEditors.readSavedPane(id)),plans[0].id);await a.evaluate(()=>captureViewState());const cloneBeforeQuota=await a.evaluate(()=>serializeDataSnapshot());
 await a.evaluate(async()=>{const original=StorageAdapter.save;StorageAdapter.save=async()=>{throw new DOMException('Synthetic quota','QuotaExceededError');};try{await EditorPane.save();}catch(e){window.__quotaFailure=e.name;}finally{StorageAdapter.save=original;}});assert.equal(await a.evaluate(()=>window.__quotaFailure),'QuotaExceededError');assert.equal(await a.evaluate(()=>serializeDataSnapshot()),cloneBeforeQuota);assert.equal(await a.evaluate(()=>DIRTY),true);assert.equal(await page.evaluate(async id=>JSON.stringify(await ParallelEditors.readSavedPane(id)),plans[0].id),sourceRecordBeforeQuota);report.checks.push('injected save quota failure retains dirty clone and original record; normal save can retry');
 await a.evaluate(()=>EditorPane.save());await page.evaluate(()=>ParallelEditors.saveWorkspace());await page.evaluate(()=>ParallelEditors.loadWorkspace());await page.waitForFunction(()=>[...ParallelEditors.panes.values()].every(p=>p.ready));[a,b]=page.frames().filter(f=>f.url().includes('editorPane='));
 assert.equal(await b.evaluate(()=>DATA.items[0].assetPackConversion.sourceType),'fmp-Chair01');assert.deepEqual(await b.evaluate(()=>DATA.items[0].custom),{keep:true});report.checks.push('comparison save/reload retains conversion provenance, mixed IDs and custom fields');
 const convertedBefore=await b.evaluate(()=>serializeDataSnapshot());await b.evaluate(()=>placeItem('rpg-mansion-chest-01',900,900));await b.evaluate(()=>undoAction());assert.equal(await b.evaluate(()=>serializeDataSnapshot()),convertedBefore);await b.evaluate(()=>redoAction());assert.equal(await b.evaluate(()=>DATA.items.at(-1).type),'rpg-mansion-chest-01');await b.evaluate(()=>undoAction());
 const downloadPromise=page.waitForEvent('download');await b.evaluate(()=>exportPlan());const download=await downloadPromise;await download.saveAs(path.join(out,'mixed-converted-plan.json'));const exported=JSON.parse(fs.readFileSync(path.join(out,'mixed-converted-plan.json')));await b.evaluate(p=>applyJsonImport(stageJsonImport(JSON.stringify(p))),exported);assert.deepEqual(await b.evaluate(()=>DATA.items),exported.items);report.checks.push('converted mixed plan native undo/redo and JSON export/import retain IDs and metadata');
 // Return one pane to original. A changed source invalidates the preview.
 await page.evaluate(id=>ParallelEditors.select([...ParallelEditors.panes.values()][0].id,id),plans[0].id);
 await a.click('#asset-conversion-open');await approve(a);await a.waitForFunction(()=>!document.querySelector('[data-conversion="create"]').disabled);await a.evaluate(()=>{DATA.items[0].x+=17;});await a.click('[data-conversion="create"]');assert.match(await a.locator('[data-conversion="status"]').textContent(),/更新されました/);assert.equal(await page.evaluate(()=>ParallelEditors.plans.size),3);await a.click('[data-conversion="close"]');report.checks.push('stale source cannot commit the prior conversion preview');
 await page.evaluate(()=>ParallelEditors.addPlan({walls:[],rooms:[],items:[],startMode:'blank'},'Fourth synthetic plan'));
 await a.click('#asset-conversion-open');await approve(a);await a.waitForFunction(()=>!document.querySelector('[data-conversion="create"]').disabled);const fullBefore=await snapshot(a);await a.click('[data-conversion="create"]');assert.match(await a.locator('[data-conversion="status"]').textContent(),/4案まで/);assert.equal(await page.evaluate(()=>ParallelEditors.plans.size),4);assert.deepEqual(await snapshot(a),fullBefore);await a.click('[data-conversion="close"]');report.checks.push('four-plan limit blocks before mutation');
 const broken=await context.newPage();await broken.route('**/conversion-map.json',r=>r.fulfill({status:503,body:'unavailable'}));await broken.goto(url+'?preset=blank');await broken.waitForFunction(()=>window.AssetPackPicker?.getRegistry());await broken.evaluate(p=>applyJsonImport(stageJsonImport(JSON.stringify(p))),fixture);const brokenBefore=await snapshot(broken);await broken.click('#asset-conversion-open');await broken.waitForFunction(()=>document.querySelector('[data-conversion="status"]').textContent.includes('読み込めません'));assert.equal(await broken.locator('[data-conversion="create"]').isDisabled(),true);assert.deepEqual(await snapshot(broken),brokenBefore);await broken.close();report.checks.push('missing mapping fails closed with source untouched');
 // Mobile dialog and targets remain within viewport and scroll.
 const mobile=await context.newPage();await mobile.setViewportSize({width:390,height:844});await mobile.goto(url+'?preset=blank');await mobile.waitForFunction(()=>window.AssetPackPicker?.getRegistry());await mobile.evaluate(p=>applyJsonImport(stageJsonImport(JSON.stringify(p))),fixture);await mobile.evaluate(()=>AssetPackConversionUI.open());await approve(mobile);await mobile.waitForFunction(()=>!document.querySelector('[data-conversion="create"]').disabled);
 const box=await mobile.locator('#asset-conversion-dialog').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=390);await mobile.locator('[data-conversion="create"]').scrollIntoViewIfNeeded();await mobile.screenshot({path:path.join(out,'conversion-mobile.png'),animations:'disabled',style:'.offline-preview-banner{visibility:hidden!important}'});report.checks.push('390px native modal stays within viewport and scrolls to create/cancel');
 assert.deepEqual(report.errors,[]);report.status='passed';
}catch(e){report.status='failed';report.failure=e.stack;throw e;}finally{fs.writeFileSync(path.join(out,'conversion-browser-results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
