import fs from 'node:fs';import assert from 'node:assert/strict';
const pw=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const b=await (pw.chromium||pw.default.chromium).launch({args:['--use-angle=metal']});
const dir='docs/quality-review/ceiling-designer';fs.mkdirSync(dir,{recursive:true});
try{const p=await b.newPage({viewport:{width:1440,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8932/');await p.waitForFunction(()=>window.CeilingDesigner&&getFmpItem('fmp-CeilingFan01'));
 await p.evaluate(()=>{const r=DATA.rooms.find(r=>r.floor===1&&r.w>2000&&r.d>2000&&roomHasCoverAbove(r)&&!roomCeilingProfile(r));if(!r)throw Error('No test room');window.testRoom=r;r.ceiling={type:'flat',heightMm:2300};r.ceilingAreas=[];ST.floor=r.floor;CeilingDesigner.open();});
 async function point(x,y){return await p.evaluate(({x,y})=>{const rr=DATA.rooms.filter(r=>r.floor===ST.floor&&!r.hidden3D);const x1=Math.min(...rr.map(r=>r.x)),y1=Math.min(...rr.map(r=>r.y)),x2=Math.max(...rr.map(r=>r.x+r.w)),y2=Math.max(...rr.map(r=>r.y+r.d));const b=document.querySelector('.ceiling-designer canvas').getBoundingClientRect(),s=Math.min((b.width-70)/(x2-x1),(b.height-70)/(y2-y1)),ox=(b.width-(x2-x1)*s)/2-x1*s,oy=(b.height-(y2-y1)*s)/2-y1*s;return{x:b.left+ox+(testRoom.x+x)*s,y:b.top+oy+(testRoom.y+y)*s};},{x,y});}
 await p.locator('.ceiling-designer [data-tool]').selectOption('lower');const a=await point(300,300),z=await point(1300,1300);await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(z.x,z.y,{steps:10});await p.mouse.up();assert.equal(await p.evaluate(()=>testRoom.ceilingAreas.length),1);
 await p.locator('.ceiling-designer [data-tool]').selectOption('light-down');const l=await point(800,800);await p.mouse.click(l.x,l.y);const old=await p.evaluate(()=>DATA.items.at(-1).elev);
 await p.locator('.ceiling-designer [data-tool]').selectOption('select');const edge=await point(400,400);await p.mouse.click(edge.x,edge.y);const inp=p.locator('.ceiling-designer [data-fields] label').filter({hasText:'天井からの段差'}).locator('input');await inp.fill('-250');await inp.dispatchEvent('change');assert.equal(await p.evaluate(()=>DATA.items.at(-1).elev),old-100);
 await p.locator('.ceiling-designer [data-undo]').click();assert.equal(await p.evaluate(()=>DATA.items.at(-1).elev),old);await p.locator('.ceiling-designer [data-redo]').click();assert.equal(await p.evaluate(()=>DATA.items.at(-1).elev),old-100);
 await p.locator('.ceiling-designer [data-tool]').selectOption('raise');const ra=await point(1600,400),rz=await point(2000,1100);await p.mouse.move(ra.x,ra.y);await p.mouse.down();await p.mouse.move(rz.x,rz.y,{steps:5});await p.mouse.up();assert.equal(await p.evaluate(()=>DATA.rooms.find(r=>r.id===testRoom.id).ceilingAreas.length),2);
 await p.screenshot({path:`${dir}/plan.png`});await p.locator('.ceiling-designer [data-3d]').click();await p.waitForFunction(()=>document.querySelector('.ceiling-3d canvas')?.width>1);await p.waitForTimeout(800);await p.screenshot({path:`${dir}/underside.png`});
 const data=await p.evaluate(()=>{const r=DATA.rooms.find(r=>r.id===testRoom.id);const a=r.ceilingAreas[0];const group=CeilingDesigner.ceilingGroup(r,floorBaseY(r.floor)+roomCeilingHeightM(r),new THREE.MeshStandardMaterial({side:THREE.DoubleSide}),[],null);group.updateMatrixWorld(true);const rays=r.ceilingAreas.map(a=>{const ray=new THREE.Raycaster(new THREE.Vector3((r.x+a.x+a.w/2)*U,floorBaseY(r.floor)-1,(r.y+a.y+a.d/2)*U),new THREE.Vector3(0,1,0));return Math.abs(ray.intersectObject(group,true)[0].point.y-(floorBaseY(r.floor)+roomCeilingHeightM(r)+a.offset*U-.012))<.001;});return{rays,cleanup:group.userData.b,saved:JSON.parse(serializeDataSnapshot()).rooms.find(q=>q.id===r.id).ceilingAreas[0],invalidOverlap:CeilingDesigner.valid(r,{...a,id:'other'}),areaOffset:CeilingDesigner.offsetAt(r,r.x+a.x+10,r.y+a.y+10)};});assert.deepEqual(data.rays,[true,true]);assert.equal(data.cleanup,true);assert.equal(data.saved.offset,-250);assert.ok(data.invalidOverlap);assert.equal(data.areaOffset,-250);
 await p.setViewportSize({width:390,height:844});await p.locator('.ceiling-designer [data-plan]').click();await p.screenshot({path:`${dir}/mobile.png`});await p.locator('.ceiling-designer [data-close]').click();const normal=await p.evaluate(()=>{setView('3d-ext');const count=()=>sc3.children.filter(o=>o.userData.ceiling&&o.userData.roomId===testRoom.id).length;const before=count();build3D();return{before,after:count()};});assert.ok(normal.before>0);assert.equal(normal.before,normal.after);await p.evaluate(()=>{setView('3d-int');CeilingDesigner.open();});await p.locator('.ceiling-designer [data-3d]').click();await p.waitForTimeout(400);assert.deepEqual(errors,[]);fs.writeFileSync(`${dir}/checks.json`,JSON.stringify(data,null,2));console.log('Ceiling editor creation, fixture attachment, height edit, Undo/Redo, save and 2D/3D/mobile passed.');
}finally{await b.close();}
