import assert from 'node:assert/strict';import fs from 'node:fs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const browser=await chromium.launch({args:['--use-angle=metal']});
const dir='docs/quality-review/detail-loop';
try{const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(/Shader Error|VALIDATE_STATUS|WebGLProgram/.test(m.text()))errors.push(m.text());});
 await page.goto(process.env.APP_URL||'http://localhost:8932/');await page.waitForSelector('#fmp-exterior-search',{state:'attached'});await page.locator('#bnav-tools').click();await page.evaluate(()=>document.getElementById('fmp-exterior').closest('.cat-body').classList.add('open'));
 await page.locator('#fmp-exterior-search').fill('独立ポスト');assert.equal(await page.locator('#fmp-exterior .asset-tile:not([hidden])').count(),1);await page.locator('#fmp-exterior .asset-tile:not([hidden])').click();
 await page.evaluate(()=>{ST.floor=1;placeItem(ST.tool,2000,2000);document.getElementById('props').classList.add('show','prop-expanded');});assert.equal(await page.evaluate(()=>ST.selected.type),'original-mailbox');assert.equal(await page.evaluate(()=>item3DBaseY(ST.selected)),0);
 await page.locator('#finish-body').fill('#485962');await page.locator('#finish-roughness-body').selectOption('0.22');assert.equal(await page.evaluate(()=>ST.selected.finishRoughness.body),.22);assert.equal(await page.evaluate(()=>ST.selected.finishColors.body),'#485962');await page.locator('#finish-body').scrollIntoViewIfNeeded();await page.screenshot({path:`${dir}/mobile-exterior-finishes.png`});
 const data=await page.evaluate(()=>JSON.parse(serializeDataSnapshot()));assert.ok(data.items.some(i=>i.type==='original-mailbox'&&i.finishColors.body==='#485962'&&i.finishRoughness.body===.22));
 await page.setViewportSize({width:1440,height:1000});await page.evaluate(async()=>{await new Promise(resolve=>{init3D();resolve();});const id='im0261-Sofa-MEGA_PACK_Sofa-BOLIA_sofa_Ivory';placeItem(id,5500,2000);updateSelectedModelFinish('fabric','#537e91');updateSelectedModelFinish('wood','#71503a');updateSelectedModelRoughness('wood','0.48');setView('3d-ext');applyLightPreset('day');camExt.position.set(10,7,11);orbit.target.set(4,0,2);orbit.update();invalidate3D();});await page.waitForFunction(()=>!hasPendingGltfModels());
 const profile=await page.evaluate(()=>{const item=DATA.items.find(i=>i.type.endsWith('BOLIA_sofa_Ivory'));const m=getFmpItem(item.type);const out=[];_modelCache[m.model].traverse(o=>{if(o.isMesh)out.push({channel:o.material.userData.finishChannel,custom:!!o.material.userData.customFinish});});return {item,out};});assert.equal(profile.item.finishColors.fabric,'#537e91');assert.ok(profile.out.some(m=>m.channel==='fabric'));
 await page.screenshot({path:`${dir}/external-and-original-in-app.png`});assert.deepEqual(errors,[]);fs.writeFileSync(`${dir}/integration.json`,JSON.stringify({groundDatum:true,mobileColorAndRoughness:true,saved:true,externalProfile:profile.out,errors},null,2));console.log('PASS mobile exterior search/placement, ground datum, per-surface color/gloss persistence, external model integration, no JS/shader errors.');
}finally{await browser.close();}
