/* Browser contract regression with a synthetic source and a metadata-only callback; no AI candidate render/ledger. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/tmp/webcad-browser-check/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const Fixture=require('./internal-api-catalogue-fixture.cjs');
const origin=process.env.APP_URL||'http://127.0.0.1:65353',out=process.env.OUTPUT_DIR||'/tmp/webcad-catalogue-contract';
assert.ok(/^http:\/\/127\.0\.0\.1:\d+$/.test(origin)&&!/:63239$|:65236$|:65352$/.test(origin));fs.mkdirSync(out,{recursive:true});
(async()=>{const profile=fs.mkdtempSync(path.join(os.tmpdir(),'webcad-catalogue-contract-')),context=await chromium.launchPersistentContext(profile,{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,viewport:{width:1400,height:1000},args:['--use-angle=metal']}),page=await context.newPage(),errors=[],blocked=[];
 try{
  await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===origin&&!u.pathname.startsWith('/api/'))return r.continue();blocked.push(u.origin+u.pathname);return r.abort();});page.on('pageerror',e=>errors.push(e.message));
  await page.goto(origin+'/?internalAPI=1');await page.waitForSelector('#app-loading',{state:'hidden',timeout:60000});await page.waitForFunction(()=>window.EditorInternalAPI&&window.SceneCatalogue&&window.PlanImport);
  const report=await page.evaluate(async({envelope,ids,invalid})=>{
   async function integrity(){const dbs={};for(const info of await indexedDB.databases()){const db=await new Promise((res,rej)=>{const q=indexedDB.open(info.name);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error);}),stores={};for(const name of db.objectStoreNames)stores[name]=await new Promise((res,rej)=>{const tx=db.transaction(name,'readonly'),s=tx.objectStore(name),k=s.getAllKeys(),v=s.getAll();tx.oncomplete=()=>res({keys:k.result,values:v.result});tx.onerror=()=>rej(tx.error);});dbs[info.name]={version:db.version,stores};db.close();}return {data:serializeDataSnapshot(),history:HISTORY.slice(),redo:REDO_HISTORY.slice(),dirty:DIRTY,local:Object.fromEntries(Object.entries(localStorage)),session:Object.fromEntries(Object.entries(sessionStorage)),indexedDB:dbs};}
   const before=await integrity(),sourceBefore=JSON.stringify(envelope);let callbacks=0;
   const api=EditorInternalAPI.create({catalogue:()=>PlanImport.sceneCatalogue(),readScene:id=>id==='contract-draft'?envelope:null,renderPreview:async input=>{input.assertFresh();++callbacks;return {backend:'browser-contract-metadata-only',nativeRenderingPerformed:false};}});
   const all=api.read_catalog({}),subset=api.read_catalog({ids}),scene=api.get_scene({planId:'contract-draft'}),results=[];
   const patch=catalogId=>({planId:'contract-draft',baseRevision:scene.revision,selectedObjectIds:['contract-object'],displayBindings:[{sourceEntityId:'contract-object',catalogId,sizingPolicy:'fit-source',appearanceMode:'unspecified'}],incompleteConfirmed:true});
   for(const id of [...ids,'fmp-Chair07']){try{const response=await api.preview_patch(patch(id));results.push({id,accepted:true,nativeRenderingPerformed:false,response});}catch(e){results.push({id,accepted:false,error:{code:e.code,message:e.message}});}}
   const invalidResults=[];for(const id of invalid){let queryError,bindingError;try{api.read_catalog({ids:[id]});}catch(e){queryError=e.code;}try{await api.preview_patch(patch(id));}catch(e){bindingError=e.code;}invalidResults.push({id,queryError,bindingError});}
   const missing={};try{api.read_catalog({ids:['missing.valid']});}catch(e){missing.query=e.code;}try{await api.preview_patch(patch('missing.valid'));}catch(e){missing.binding=e.code;}
   const narrow={};try{api.get_scene({planId:'contract.draft'});}catch(e){narrow.plan=e.code;}
   envelope.source.objects[0].id='contract.object';const dottedScene=api.get_scene({planId:'contract-draft'}),dottedPatch=patch('fmp-Chair07');dottedPatch.baseRevision=dottedScene.revision;dottedPatch.selectedObjectIds=['contract.object'];dottedPatch.displayBindings[0].sourceEntityId='contract.object';try{await api.preview_patch(dottedPatch);}catch(e){narrow.source=e.code;}envelope.source.objects[0].id='contract-object';
   return {before,after:await integrity(),sourceUnchanged:JSON.stringify(envelope)===sourceBefore,query:subset,allCatalogueCount:all.entries.length,allCatalogueHash:all.hash,results,invalidResults,missing,narrow,metadataOnlyCallbacks:callbacks,aiCandidatePreviewCalls:0,nativeRenderingPerformed:false,applyCalls:0,paidCalls:0,parallelPlanCount:ParallelEditors.plans.size,parallelPaneCount:ParallelEditors.panes.size};
  },{envelope:Fixture.envelope(),ids:Fixture.PERIOD_IDS,invalid:Fixture.INVALID_IDS});
  assert.deepEqual(report.query.entries.map(e=>e.id),Fixture.PERIOD_IDS);assert.deepEqual(report.after,report.before);assert.equal(report.sourceUnchanged,true);assert.equal(report.parallelPlanCount,0);assert.equal(report.parallelPaneCount,0);
  for(const result of report.results){const opening=report.query.entries.find(e=>e.id===result.id)?.openingOnly;if(opening){assert.equal(result.accepted,false);assert.equal(result.error.code,'unknown_catalogue');}else{assert.equal(result.accepted,true);assert.equal(result.response.diff[0].after.binding.catalogId.value,result.id);}}
  for(const item of report.invalidResults){assert.equal(item.queryError,'invalid_request');assert.equal(item.bindingError,'invalid_request');}
  assert.deepEqual(report.missing,{query:'unknown_catalogue',binding:'unknown_catalogue'});assert.deepEqual(report.narrow,{plan:'invalid_request',source:'invalid_request'});assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);
  fs.writeFileSync(path.join(out,'browser-contract-results.json'),JSON.stringify({origin,profile,...report,errors,blocked},null,2)+'\n');console.log(JSON.stringify({fiveQueriesPassed:true,threeNonOpeningBindingsPassed:true,twoOpeningGuardsPreserved:true,normalBindingPassed:true,invalidInputsPassed:report.invalidResults.length,planSourceConstraintsPreserved:true,actualBrowser:true,metadataOnlyCallbacks:report.metadataOnlyCallbacks,nativeRenderingPerformed:false,aiCandidatePreviewCalls:0,hostAndStorageUnchanged:true,errors,blocked}));
 }finally{await context.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
