const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const API=require('../../assets/js/editor-internal-api.js'),Catalogue=require('../../assets/js/scene-catalogue.js');
const {runtime}=require('./scene-fixtures.cjs'),Fixture=require('./internal-api-catalogue-fixture.cjs');
const schemaDir=path.resolve(__dirname,'../../docs/internal-api');
const schema=name=>JSON.parse(fs.readFileSync(path.join(schemaDir,name),'utf8'));
function session(){const rt=runtime(),state=Fixture.envelope();let renders=0,lookups=0;const cap={catalogue:()=>{const c=rt.PlanImport.sceneCatalogue();return {...c,get(id){lookups++;return c.get(id);}};},readScene:id=>id==='contract-draft'?state:null,renderPreview:async()=>{++renders;return {backend:'node-contract-fixture',nativeRenderingPerformed:false};}};return {rt,state,api:API.create(cap),renders:()=>renders,lookups:()=>lookups};}
test('all five exact period IDs can be queried with detached metadata and unchanged scene',()=>{const {api,state}=session(),before=JSON.stringify(state),all=api.read_catalog({}),subset=api.read_catalog({ids:Fixture.PERIOD_IDS});assert.deepEqual(subset.entries.map(e=>e.id),Fixture.PERIOD_IDS);for(const entry of subset.entries){assert.equal(Catalogue.cleanId(entry.id),true);assert.deepEqual(entry,all.entries.find(e=>e.id===entry.id));}subset.entries[0].w=0;assert.ok(api.read_catalog({ids:[Fixture.PERIOD_IDS[0]]}).entries[0].w>0);assert.equal(JSON.stringify(state),before);});
test('three non-opening period bindings reach the existing compiler; two windows retain opening-only rejection',async()=>{const {api,state,renders}=session(),before=JSON.stringify(state),scene=api.get_scene({planId:'contract-draft'});for(const catalogId of Fixture.PERIOD_IDS){const model=api.read_catalog({ids:[catalogId]}).entries[0],request=Fixture.patch(scene,catalogId);if(model.openingOnly){await assert.rejects(api.preview_patch(request),e=>e.code==='unknown_catalogue');continue;}const result=await api.preview_patch(request);assert.equal(result.diff[0].after.binding.catalogId.value,catalogId);if(result.rendered)assert.equal(result.preview.nativeRenderingPerformed,false);else assert.ok(result.diagnostics.some(d=>d.severity==='error'));assert.equal(result.sourceHash,scene.sourceHash);assert.equal(result.applyAvailable,false);}assert.ok(renders()<=3);assert.equal(JSON.stringify(state),before);});
test('normal catalogue query/binding behavior and membership checks remain enforced',async()=>{const {api}=session(),scene=api.get_scene({planId:'contract-draft'});assert.equal(api.read_catalog({ids:['fmp-Chair07']}).entries[0].id,'fmp-Chair07');assert.equal((await api.preview_patch(Fixture.patch(scene,'fmp-Chair07'))).diff[0].after.binding.catalogId.value,'fmp-Chair07');for(const id of ['nonexistent.model','a'.repeat(120)]){assert.equal(Catalogue.cleanId(id),true);assert.throws(()=>api.read_catalog({ids:[id]}),e=>e.code==='unknown_catalogue');await assert.rejects(api.preview_patch(Fixture.patch(scene,id)),e=>e.code==='unknown_catalogue');}});
test('invalid catalogue IDs and prototype-key requests reject before catalogue get',async()=>{const {api,lookups}=session(),scene=api.get_scene({planId:'contract-draft'});for(const catalogId of Fixture.INVALID_IDS){assert.equal(Catalogue.cleanId(catalogId),false);const count=lookups();assert.throws(()=>api.read_catalog({ids:[catalogId]}),e=>e.code==='invalid_request');await assert.rejects(api.preview_patch(Fixture.patch(scene,catalogId)),e=>e.code==='invalid_request');assert.equal(lookups(),count);}for(const key of ['__proto__','constructor','prototype']){const request=JSON.parse('{"'+key+'":{},"ids":["fmp-Chair07"]}');assert.throws(()=>api.read_catalog(request),e=>e.code==='invalid_request');const binding=Fixture.patch(scene,'fmp-Chair07');Object.defineProperty(binding.displayBindings[0],key,{value:{},enumerable:true});await assert.rejects(api.preview_patch(binding),e=>e.code==='invalid_request');}assert.equal(Object.prototype.polluted,undefined);});
test('plan/source binding ID grammar does not inherit catalogue periods or longer lengths',async()=>{const {api,state}=session();for(const planId of ['contract.draft','a'.repeat(101),'../draft'])assert.throws(()=>api.get_scene({planId}),e=>e.code==='invalid_request');state.source.objects[0].id='contract.object';const scene=api.get_scene({planId:'contract-draft'}),p=Fixture.patch(scene,'fmp-Chair07');p.selectedObjectIds=['contract.object'];p.displayBindings[0].sourceEntityId='contract.object';await assert.rejects(api.preview_patch(p),e=>e.code==='invalid_request');});
function accepts(id,s){return typeof id==='string'&&new RegExp(s.pattern).test(id)&&!s.not.enum.includes(id);}
test('new request schemas share the catalogue allowlist and leave plan/source fields narrow',()=>{const read=schema('read_catalog.request.schema.json'),patch=schema('preview_patch.request.schema.json'),cat=read.properties.ids.items,binding=patch.properties.displayBindings.items.properties.catalogId.oneOf[0];assert.deepEqual(cat,binding);for(const id of [...Fixture.PERIOD_IDS,...Fixture.INVALID_IDS,'fmp-Chair07','a'.repeat(120),'missing.valid'])assert.equal(accepts(id,cat),Catalogue.cleanId(id));assert.equal(new RegExp(patch.properties.planId.pattern).test('contract.draft'),false);assert.equal(new RegExp(patch.properties.displayBindings.items.properties.sourceEntityId.pattern).test('contract.object'),false);});
test('catalogue response schema includes actual unreviewed, audited and audit-mismatch runtime statuses',()=>{const {api,rt}=session(),id='im0261-Cabinet-MEGA_PACK_CABINET-cabinet-354290_frame_walnut_brown',known=api.read_catalog({ids:[id,'fmp-Chair07']}).entries;assert.equal(known[0].materialCapability.status,'asset-and-code-audited');assert.equal(known[1].materialCapability.status,'unreviewed');rt.CATALOGUE_FINISHES.models[rt.FMP_ITEMS[id].model]['cabinet-354290_frame_walnut_brown']='wood';const changed=api.read_catalog({ids:[id]}).entries[0];assert.equal(changed.materialCapability.status,'audit-mismatch');assert.equal(changed.materialCapability.verifiedChannels.length,0);const values=schema('read_catalog.response.schema.json').properties.entries.items.properties.materialCapability.properties.status.enum;assert.deepEqual([...values].sort(),[...known.map(e=>e.materialCapability.status),changed.materialCapability.status].sort());});
