// Real native editor, only synthetic explicit test numbers; independent of both frozen Astra ledgers.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/tmp/webcad-browser-check/node_modules/playwright'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const F=require('./internal-api-wall-height-fixture.cjs'),origin=process.env.APP_URL||'http://127.0.0.1:65354',out=process.env.OUTPUT_DIR||'/tmp/webcad-wall-height-native';
assert.ok(/^http:\/\/127\.0\.0\.1:\d+$/.test(origin)&&!/:63239$|:65236$|:65348$|:65349$|:65352$/.test(origin));fs.mkdirSync(out,{recursive:true});
(async()=>{const profile=fs.mkdtempSync(path.join(os.tmpdir(),'webcad-wall-height-native-')),context=await chromium.launchPersistentContext(profile,{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,viewport:{width:1500,height:1000},args:['--use-angle=metal']}),page=await context.newPage(),errors=[],blocked=[],responses=[],states=[];
 try{
  await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===origin&&!u.pathname.startsWith('/api/'))return r.continue();blocked.push(u.origin+u.pathname);return r.abort();});page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/?internalAPI=1');await page.waitForSelector('#app-loading',{state:'hidden',timeout:60000});await page.waitForFunction(()=>window.WebCADInternalAPI&&window.threeModulesReady);
  await page.evaluate(envelope=>{closePresetChoice();DATA=envelope.snapshot;HISTORY.length=0;REDO_HISTORY.length=0;HISTORY.push('synthetic keep history');REDO_HISTORY.push('synthetic keep redo');DIRTY=true;setView('3d-ext');PlanImport.stageSceneIR(envelope.source,{...envelope.options,extraction:{kind:'synthetic-wall-height',paidCalls:0}});},F.envelope());await page.waitForFunction(()=>ren&&!hasPendingGltfModels()&&!_gltfRebuildTimer,null,{timeout:60000});await page.evaluate(()=>{orbit.enableDamping=false;orbit.autoRotate=false;camExt.position.set(8,7,8);orbit.target.set(2,1,1.5);orbit.update();invalidate3D();});
  // As in the existing capture pose hook, disable damping during synthetic fixture setup.
  await page.waitForTimeout(300);
  async function integrity(){return page.evaluate(async()=>{const stores={};for(const info of await indexedDB.databases()){const db=await new Promise((res,rej)=>{const q=indexedDB.open(info.name);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error);});for(const name of db.objectStoreNames)stores[info.name+':'+name]=await new Promise((res,rej)=>{const tx=db.transaction(name,'readonly'),s=tx.objectStore(name),k=s.getAllKeys(),v=s.getAll();tx.oncomplete=()=>res({keys:k.result,values:v.result});tx.onerror=()=>rej(tx.error);});db.close();}return {data:serializeDataSnapshot(),history:HISTORY.slice(),redo:REDO_HISTORY.slice(),dirty:DIRTY,source:JSON.stringify(PlanImport.state.result.sceneIR),options:JSON.stringify(PlanImport.state.result.sceneOptions),camera:WebCADInternalAPI.get_scene({planId:'host-draft'}).camera,local:Object.fromEntries(Object.entries(localStorage)),session:Object.fromEntries(Object.entries(sessionStorage)),indexedDB:stores};});}
  const before=await integrity();states.push({checkpoint:'before',value:before});const scene=await page.evaluate(()=>WebCADInternalAPI.get_scene({planId:'host-draft'}));assert.deepEqual(scene.source,F.source());
  async function call(value){const request=F.patch(scene,value);const response=await page.evaluate(p=>WebCADInternalAPI.preview_patch(p),request);assert.equal(response.rendered,true,JSON.stringify(response.diagnostics));assert.equal(response.preview.memoryOnly,true);assert.equal(response.applyAvailable,false);assert.equal(response.fullReconstructionReady,false);assert.deepEqual(response.preview.camera,scene.camera);
   const frame=page.frames().find(f=>new URL(f.url()).searchParams.get('editorPane')===response.preview.paneId);await frame.waitForTimeout(300);
   const native=await frame.evaluate(async()=>{const w=DATA.walls.find(w=>w.id==='wall-free'),roots=getSelectableRoots3D(w),box=new THREE.Box3();roots.forEach(r=>{r.updateMatrixWorld(true);box.union(new THREE.Box3().setFromObject(r));});return {storedWall:JSON.parse(JSON.stringify(w)),wallHeightMm:wallHeightMm(w),wallDisplayHeightMm:wallDisplayHeightM(w)*1000,wallLiftMm:wallLiftMm(w),baseSupportWorldMm:wallBaseSupportY(w)*1000,floorSlabHeightMm:floorSlabHeightMForFloor(w.floor)*1000,bbox:{min:box.min.toArray().map(v=>v*1000),max:box.max.toArray().map(v=>v*1000),geometryHeightMm:(box.max.y-box.min.y)*1000},camera:EditorPane.view(),saveDisabled:document.getElementById('save-btn').disabled,source:DATA.sceneReconstructionReports[0].originalIR,retainedOverrides:DATA.sceneReconstructionReports[0].reviewDecisions.displayOverrides};});
   const display=response.wallDisplays.find(w=>w.sourceEntityId==='wall-free');assert.equal(native.wallHeightMm,value);assert.equal(native.storedWall.wallHeight,value);assert.deepEqual(native.camera,scene.camera);assert.deepEqual(native.source,F.source());assert.deepEqual(display.bbox.min,native.bbox.min);assert.deepEqual(display.bbox.max,native.bbox.max);assert.ok(Math.abs(display.effectiveHeight.valueMm-native.bbox.geometryHeightMm)<.001);assert.ok(Math.abs(native.bbox.geometryHeightMm-(value+180))<1,JSON.stringify(native));assert.equal(native.saveDisabled,true);assert.equal(await page.evaluate(id=>ParallelEditors.readSavedPane(id),response.preview.planId),null);assert.equal(await page.evaluate(async p=>{try{await ParallelEditors.persistPane(p.paneId,p.planId,{});return false;}catch(e){return e.message==='Memory-only preview cannot be saved';}},response.preview),true);assert.equal(display.sourceMeasured,false);assert.equal(display.approvalState,'unreviewed');
   await frame.locator('#c3d-wrap').screenshot({path:path.join(out,'native-height-'+value+'.png')});responses.push({request,response,native});const state=await integrity();assert.deepEqual(state,before);states.push({checkpoint:'success-'+value,value:state});return response;
  }
  await call(300);await call(6000);const first=await call(1100);
  const rejections=[];for(const value of [299,6001,'1100',null,'low']){const p=F.patch(scene,value);const e=await page.evaluate(async p=>{try{await WebCADInternalAPI.preview_patch(p);return null;}catch(e){return {code:e.code,message:e.message};}},p);assert.ok(e);rejections.push({kind:'invalid-value',value,error:e});}
  const host=F.patch(scene);host.selectedEntityIds=['wall-host','room-fixture'];host.displayOverrides[0].sourceEntityId='wall-host';const hostError=await page.evaluate(async p=>{try{await WebCADInternalAPI.preview_patch(p);return null;}catch(e){return {code:e.code,message:e.message};}},host);assert.equal(hostError.code,'invalid_display_override');rejections.push({kind:'opening-host',error:hostError});
  const stale=await page.evaluate(async p=>{const old=PlanImport.state.result.sceneOptions.pageScope.slice();PlanImport.state.result.sceneOptions.pageScope.push('synthetic stale edit');try{await WebCADInternalAPI.preview_patch(p);return null;}catch(e){return {code:e.code,message:e.message};}finally{PlanImport.state.result.sceneOptions.pageScope=old;}},F.patch(scene,1700));assert.equal(stale.code,'stale_revision');rejections.push({kind:'stale',error:stale});
  const cancelled=await page.evaluate(async p=>{const pending=WebCADInternalAPI.preview_patch(p).then(()=>null,e=>({code:e.code,message:e.message}));setTimeout(()=>ParallelEditors.close(),0);return await pending;},F.patch(scene,1700));assert.equal(cancelled.code,'preview_cancelled');await page.waitForFunction(()=>ParallelEditors.plans.size===0&&ParallelEditors.panes.size===0);const cancelledState=await integrity();assert.deepEqual(cancelledState,before);states.push({checkpoint:'reject-stale-cancel',value:cancelledState});
  const next=await call(1500),diff=next.diff.find(d=>d.kind==='wall-height-display-override');assert.equal(diff.display.before.requestedHeight.valueMm,1100);assert.equal(diff.display.materializedHeightDeltaMm,400);assert.ok(Math.abs(diff.display.effectiveHeightDeltaMm-400)<1);
  const cleared=await page.evaluate(p=>WebCADInternalAPI.preview_patch(p),{...F.patch(scene),displayOverrides:[]});assert.equal(cleared.rendered,true);assert.equal(cleared.previewPlan.walls[0].wallHeight,2400);const clear=cleared.diff.find(d=>d.kind==='wall-height-display-override');assert.equal(clear.before.valueMm,1500);assert.equal(clear.after,null);assert.equal(clear.display.after.rendererContext.ceilingLinked,true);assert.equal(clear.display.after.requestedHeight,null);
  const clearFrame=page.frames().find(f=>new URL(f.url()).searchParams.get('editorPane')===cleared.preview.paneId);await clearFrame.locator('#c3d-wrap').screenshot({path:path.join(out,'native-height-default-cleared.png')});responses.push({request:{displayOverrides:[]},response:cleared});states.push({checkpoint:'override-cleared',value:await integrity()});assert.deepEqual(states.at(-1).value,before);
  await page.evaluate(()=>ParallelEditors.close());const after=await integrity();assert.deepEqual(after,before);assert.equal(await page.evaluate(()=>ParallelEditors.plans.size+ParallelEditors.panes.size),0);assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);
  const report={origin,profile,actualBrowser:true,nativeEditor:true,syntheticExplicitNumbersOnly:true,aiCandidatePreviewCalls:0,paidCalls:0,applyCalls:0,responses,rejections,cancelled,states,before,after,errors,blocked,hostAndStorageUnchanged:true};fs.writeFileSync(path.join(out,'browser-wall-height-results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({actualBrowser:true,nativeEditor:true,boundary300and6000:true,hostRejected:true,cancelled,previousSuccessBaseline:1100,requestedEffectiveBBoxSeparated:true,overrideCleared:true,sameCamera:true,saveDisabled:true,hostAndStorageUnchanged:true,nativeSyntheticSuccesses:responses.length,aiCandidatePreviewCalls:0,errors,blocked}));
 }catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:false}).catch(()=>{});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:String(e),stack:e.stack,errors,blocked,responses,states},null,2));throw e;}finally{await context.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
