/* Real Chrome regression: own profile/origin, external capture, no paid calls. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/tmp/webcad-browser-check/node_modules/playwright');
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict');
const origin=process.env.APP_URL||'http://127.0.0.1:65348',out=process.env.OUTPUT_DIR||require('node:path').join(require('node:os').tmpdir(), 'webcad-api-lifecycle-evidence');
assert.ok(/^http:\/\/127\.0\.0\.1:\d+$/.test(origin)&&!/:63239$|:65236$/.test(origin));fs.mkdirSync(out,{recursive:true});
(async()=>{const profile=fs.mkdtempSync(path.join(os.tmpdir(),'webcad-api-lifecycle-')),context=await chromium.launchPersistentContext(profile,{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,viewport:{width:1500,height:1000},args:['--use-angle=metal']}),page=await context.newPage(),errors=[],blocked=[],cases=[];try{
 await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===origin&&!u.pathname.startsWith('/api/'))return r.continue();blocked.push(u.origin+u.pathname);return r.abort();});page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin+'/?internalAPI=1');await page.waitForSelector('#app-loading',{state:'hidden',timeout:60000});await page.waitForFunction(()=>window.WebCADInternalAPI&&window.threeModulesReady);await page.evaluate(()=>{closePresetChoice();document.getElementById('floor-sel').value='2';onFloorChange(2);setView('3d-ext');});await page.waitForFunction(()=>ren&&!hasPendingGltfModels()&&!_gltfRebuildTimer,null,{timeout:90000});await page.getByRole('button',{name:'固定raw 2Fの部分プレビュー（AIなし・未完成）'}).click();await page.waitForSelector('#scene-ir-review');
 // Development regression fixture only; excluded from the clean AI packet.
 const request=await page.evaluate(()=>({planId:'host-draft',baseRevision:WebCADInternalAPI.get_scene({planId:'host-draft'}).revision,selectedObjectIds:['obj-chair-nw'],incompleteConfirmed:true,displayBindings:[{sourceEntityId:'obj-chair-nw',catalogId:'fmp-Chair07',sizingPolicy:'fit-source',appearanceMode:'match-diagram-appearance'},{sourceEntityId:'room-ldk',catalogId:null,sizingPolicy:'native',appearanceMode:'match-diagram-appearance'}]}));
 async function rootState(){return page.evaluate(()=>({data:serializeDataSnapshot(),history:JSON.stringify(HISTORY),redo:JSON.stringify(REDO_HISTORY),dirty:DIRTY,source:JSON.stringify(PlanImport.state.result.sceneIR),options:JSON.stringify(PlanImport.state.result.sceneOptions),camera:WebCADInternalAPI.get_scene({planId:'host-draft'}).camera,local:Object.fromEntries(Object.entries(localStorage)),session:Object.fromEntries(Object.entries(sessionStorage))}));}
 async function databaseState(){return page.evaluate(async()=>{const result={};for(const info of await indexedDB.databases()){const db=await new Promise((res,rej)=>{const r=indexedDB.open(info.name);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});const stores={};for(const name of db.objectStoreNames)stores[name]=await new Promise((res,rej)=>{const tx=db.transaction(name,'readonly'),st=tx.objectStore(name),keys=st.getAllKeys(),rows=st.getAll();tx.oncomplete=()=>res({keys:keys.result,rows:rows.result});tx.onerror=()=>rej(tx.error);});result[info.name]={version:db.version,stores};db.close();}return result;});}
 const before=await rootState(),databaseBefore=await databaseState();
 for(const mode of ['stale-install','dispose-final-raf','stop-final-raf','close-inflight']){
  const result=await page.evaluate(async({request,mode})=>{const pe=ParallelEditors,open=pe.openPlan;let entered=false;
   pe.openPlan=async function(){const id=await open.apply(this,arguments),pane=[...pe.panes.values()].find(p=>p.planId===id),w=pane.frame.contentWindow;
    if(mode==='stale-install'){const install=w.EditorPane.install;w.EditorPane.install=async function(){const result=await install.apply(this,arguments);DIRTY=!DIRTY;return result;};}
    if(mode==='close-inflight'){w.EditorPane.install=()=>{entered=true;return new Promise(()=>{});};}
    if(mode==='dispose-final-raf'||mode==='stop-final-raf'){const apply=w.EditorPane.applyView;w.EditorPane.applyView=function(){apply.apply(this,arguments);const raf=w.requestAnimationFrame.bind(w);let n=0;w.requestAnimationFrame=cb=>mode==='stop-final-raf'?0:raf(t=>{if(++n>=2)w.EditorPane.dispose();cb(t);});};}
    return id;
   };
   const start=performance.now(),pending=WebCADInternalAPI.preview_patch(request).then(value=>({ok:true,value}),e=>({ok:false,code:e.code,message:e.message}));
   if(mode==='close-inflight'){while(!entered&&performance.now()-start<30000)await new Promise(r=>setTimeout(r,20));if(!entered)throw Error('close hook did not run');pe.close();}
   const result=await pending;pe.openPlan=open;if(mode==='stale-install')DIRTY=!DIRTY;return {...result,elapsedMs:performance.now()-start,plans:pe.plans.size,panes:pe.panes.size};
  },{request,mode});assert.equal(result.ok,false,mode);assert.equal(result.plans,0,mode);assert.equal(result.panes,0,mode);assert.equal(result.code,mode==='stale-install'?'stale_revision':mode==='stop-final-raf'?'preview_timeout':'preview_cancelled',mode);if(mode==='stop-final-raf')assert.ok(result.elapsedMs<15000);assert.deepEqual(await rootState(),before);assert.deepEqual(await databaseState(),databaseBefore);cases.push({mode,...result});
 }
 const first=await page.evaluate(p=>WebCADInternalAPI.preview_patch(p),request);assert.equal(first.rendered,true);await page.evaluate(()=>ParallelEditors.close());assert.equal(await page.evaluate(()=>ParallelEditors.plans.size),0);
 const recreated=await page.evaluate(p=>WebCADInternalAPI.preview_patch(p),request);assert.equal(recreated.rendered,true);assert.notEqual(recreated.preview.planId,first.preview.planId);assert.equal(recreated.image,null);assert.equal(recreated.imageCaptureStatus,'external-not-captured');assert.deepEqual(await rootState(),before);assert.deepEqual(await databaseState(),databaseBefore);await page.screenshot({path:path.join(out,'native-recreated.png')});cases.push({mode:'close-and-recreate',oldId:first.preview.planId,newId:recreated.preview.planId,rendered:true});
 const persistence=await page.evaluate(async candidateId=>{const pe=ParallelEditors,previewIds=[...pe.plans.keys()],sourceCopy=previewIds.find(id=>id!==candidateId);pe.discardMemoryPlan(sourceCopy);
  const ordinary=await pe.addPlan({walls:[],rooms:[],items:[],startMode:'blank'},'Ordinary save regression'),pane=[...pe.panes.values()].find(p=>p.planId===ordinary),saved=await pane.frame.contentWindow.EditorPane.save();
  async function rows(){const db=await new Promise((res,rej)=>{const r=indexedDB.open('webcad-parallel-workspace',1);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});try{return await new Promise((res,rej)=>{const tx=db.transaction('workspaces','readonly'),r=tx.objectStore('workspaces').get('local');tx.oncomplete=()=>res(r.result);tx.onerror=()=>rej(tx.error);});}finally{db.close();}}
  const siblingRows=await rows();await pe.saveWorkspace();const workspaceRows=await rows();const memoryPane=[...pe.panes.values()].find(p=>pe.plans.get(p.planId).memoryOnly);let memorySave;try{await memoryPane.frame.contentWindow.EditorPane.save();memorySave=true;}catch(e){memorySave=e.message;}
  pe.close();return {ordinary,previewIds,saved,siblingRows,workspaceRows,memorySave,remaining:[...pe.plans.keys()],remainingPanes:pe.panes.size};
 },recreated.preview.planId);
 for(const rows of [persistence.siblingRows,persistence.workspaceRows]){assert.equal(rows.length,1);assert.equal(rows[0].id,persistence.ordinary);assert.equal(rows[0].memoryOnly,false);assert.ok(!JSON.stringify(rows).includes('internal-preview-source'));assert.ok(!rows[0].plan.sceneReconstructionReports);for(const id of persistence.previewIds)assert.ok(!JSON.stringify(rows).includes(id));}assert.match(persistence.memorySave,/Memory-only/);assert.deepEqual(persistence.remaining,[persistence.ordinary]);assert.equal(persistence.remainingPanes,0);assert.deepEqual(await rootState(),before);assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);
 const report={origin,profile,cases,persistence,rootUnchanged:true,databaseUnchangedBeforeExplicitOrdinarySave:true,databaseBefore,persistencePathCoverage:['preview pane save','ordinary sibling pane save','comparison workspace save'],errors,blocked,imageJudgmentPerformed:false,paidCalls:0,applyCalls:0};fs.writeFileSync(path.join(out,'lifecycle-browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({cases:cases.map(c=>({mode:c.mode,code:c.code,rendered:c.rendered})),centralSaveExcludedMemoryPlans:true,rootUnchanged:true,errors,blocked}));
 }finally{await context.close();}})().catch(e=>{console.error(e);process.exitCode=1});
