/* Own Chrome process/profile and loopback origin only. Never attaches existing tabs. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/tmp/webcad-browser-check/node_modules/playwright');
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),crypto=require('crypto');
const origin=process.env.APP_URL||'http://127.0.0.1:65347',out=process.env.OUTPUT_DIR||require('node:path').join(require('node:os').tmpdir(), 'webcad-internal-api-evidence');
assert.ok(/^http:\/\/127\.0\.0\.1:\d+$/.test(origin)&&!/:63239$|:65236$/.test(origin));fs.mkdirSync(out,{recursive:true});
(async()=>{const profile=fs.mkdtempSync(path.join(os.tmpdir(),'webcad-internal-api-chrome-')),context=await chromium.launchPersistentContext(profile,{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,viewport:{width:1600,height:1000},args:['--use-angle=metal']});let page;const errors=[],blocked=[];try{
 await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===origin&&!u.pathname.startsWith('/api/'))return r.continue();blocked.push(u.origin+u.pathname);return r.abort();});
 const defaultPage=await context.newPage();await defaultPage.goto(origin);await defaultPage.waitForSelector('#app-loading',{state:'hidden',timeout:60000});assert.equal(await defaultPage.evaluate(()=>typeof WebCADInternalAPI),'undefined');await defaultPage.close();
 page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/?internalAPI=1');await page.waitForSelector('#app-loading',{state:'hidden',timeout:60000});await page.waitForFunction(()=>window.WebCADInternalAPI&&window.threeModulesReady);await page.evaluate(()=>{closePresetChoice();document.getElementById('floor-sel').value='2';onFloorChange(2);setView('3d-ext');});await page.waitForFunction(()=>ren&&!hasPendingGltfModels()&&!_gltfRebuildTimer,null,{timeout:90000});
 await page.evaluate(()=>{camExt.position.set(10,11,12);orbit.target.set(3.64,3.2,2.05);orbit.update();invalidate3D();});
 await page.getByRole('button',{name:'固定raw 2Fの部分プレビュー（AIなし・未完成）'}).click();await page.waitForSelector('#scene-ir-review');await page.screenshot({path:path.join(out,'01-source-review.png')});
 const calls=await page.evaluate(()=>({catalog:WebCADInternalAPI.read_catalog({ids:['fmp-Chair07','fmp-Bed01']}),scene:WebCADInternalAPI.get_scene({planId:'host-draft'})}));fs.writeFileSync(path.join(out,'read-catalog.json'),JSON.stringify(calls.catalog,null,2));fs.writeFileSync(path.join(out,'get-scene.json'),JSON.stringify(calls.scene,null,2));
 assert.equal(calls.scene.rawSha256,'c98e9213665b0527fae907a19d145d8a038db8f82bd049c57b74607add05485c');
 async function integrity(){return page.evaluate(async()=>{const stores={};for(const info of await indexedDB.databases()){const db=await new Promise((res,rej)=>{const r=indexedDB.open(info.name);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});stores[info.name]={version:db.version,stores:{}};for(const name of db.objectStoreNames){stores[info.name].stores[name]=await new Promise((res,rej)=>{const tx=db.transaction(name,'readonly'),st=tx.objectStore(name),k=st.getAllKeys(),v=st.getAll();tx.oncomplete=()=>res({keys:k.result,values:v.result});tx.onerror=()=>rej(tx.error);});}db.close();}return {data:serializeDataSnapshot(),history:JSON.stringify(HISTORY),redo:JSON.stringify(REDO_HISTORY),dirty:DIRTY,source:JSON.stringify(PlanImport.state.result.sceneIR),options:JSON.stringify(PlanImport.state.result.sceneOptions),camera:WebCADInternalAPI.get_scene({planId:'host-draft'}).camera,storage:{local:Object.fromEntries(Object.entries(localStorage)),session:Object.fromEntries(Object.entries(sessionStorage)),indexedDB:stores}};});}
 const before=await integrity();const first={planId:'host-draft',baseRevision:calls.scene.revision,selectedObjectIds:['obj-chair-nw'],incompleteConfirmed:true,displayBindings:[{sourceEntityId:'obj-chair-nw',catalogId:'fmp-Chair07',sizingPolicy:'fit-source',appearanceMode:'match-diagram-appearance'}]};
 const r1=await page.evaluate(p=>WebCADInternalAPI.preview_patch(p),first);assert.equal(r1.rendered,false);assert.ok(r1.diagnostics.some(d=>d.code==='appearance_mapping_required'));fs.writeFileSync(path.join(out,'patch-1-request.json'),JSON.stringify(first,null,2));fs.writeFileSync(path.join(out,'patch-1-response.json'),JSON.stringify(r1,null,2));
 const second=structuredClone(first);second.displayBindings.push({sourceEntityId:'room-ldk',catalogId:null,sizingPolicy:'native',appearanceMode:'match-diagram-appearance'});
 const r2=await page.evaluate(p=>WebCADInternalAPI.preview_patch(p),second);fs.writeFileSync(path.join(out,'patch-2-request.json'),JSON.stringify(second,null,2));fs.writeFileSync(path.join(out,'patch-2-response.json'),JSON.stringify(r2,null,2));assert.equal(r2.rendered,true,JSON.stringify(r2.diagnostics));
 const frame=page.frames().find(f=>f.url().includes('editorPane='+r2.preview.paneId));assert.ok(frame);await frame.waitForFunction(()=>ren&&!hasPendingGltfModels()&&!_gltfRebuildTimer,null,{timeout:90000});await page.waitForTimeout(1000);
 const native=await frame.evaluate(()=>({plan:EditorPane.snapshot(),state:{history:HISTORY,redo:REDO_HISTORY,dirty:DIRTY},view:EditorPane.view(),metrics:EditorPane.metrics(),pending:hasPendingGltfModels(),models:Object.keys(_modelCache),rendererSize:ren.getSize(new THREE.Vector2()).toArray(),geometryCount:sc3.children.length,canvas:!!document.querySelector('#c3d-wrap canvas[data-engine]')}));
 assert.equal(native.plan.items.length,1);assert.equal(native.plan.items[0].type,'fmp-Chair07');assert.equal(native.plan.rooms.length,1);assert.deepEqual(native.plan.sceneReconstructionReports[0].originalIR,calls.scene.source);assert.deepEqual(native.view.camera,calls.scene.camera.camera);assert.equal(native.view.view,'3d-ext');assert.equal(native.canvas,true);assert.equal(native.state.dirty,false);assert.ok(native.models.some(m=>m.includes('Chair07')));assert.ok(native.geometryCount>0);await page.screenshot({path:path.join(out,'02-isolated-native-3d.png')});
 const after=await integrity();assert.deepEqual(after,before,'Original DATA/history/dirty/raw/options/camera/storage must match exactly');
 const stale=await page.evaluate(async p=>{p.baseRevision='sha256:'+'0'.repeat(64);try{await WebCADInternalAPI.preview_patch(p);return null;}catch(e){return {code:e.code,message:e.message};}},second);assert.equal(stale.code,'stale_revision');
 const guards=await frame.evaluate(async()=>{try{await EditorPane.save();return {saved:true};}catch(e){return {saved:false,message:e.message};}});assert.equal(guards.saved,false);
 const report={origin,profile,rawByteSha256:calls.scene.rawSha256,sourceHash:calls.scene.sourceHash,catalogueHash:calls.catalog.hash,manualPatchReplays:2,paidCalls:0,applyCalls:0,firstRendered:r1.rendered,secondRendered:r2.rendered,sourcePlanId:'host-draft',previewPlanId:r2.preview.planId,sameCamera:true,originalUnchanged:true,storageUnchanged:true,native,stale,guards,errors,blocked};assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(report,null,2));fs.writeFileSync(path.join(out,'integrity-before.json'),JSON.stringify(before,null,2));fs.writeFileSync(path.join(out,'integrity-after.json'),JSON.stringify(after,null,2));console.log(JSON.stringify({native3D:true,sameCamera:true,originalUnchanged:true,storageUnchanged:true,manualPatchReplays:2,errors,blocked}));
 }finally{await context.close();}})().catch(e=>{console.error(e);process.exitCode=1});
