const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {runtime}=require('./scene-fixtures.cjs'),API=require('../../assets/js/editor-internal-api.js');
const frozen=()=>JSON.parse(fs.readFileSync('local-preview/frozen-page-2.json','utf8'));
function session(){const rt=runtime(),s={source:frozen(),snapshot:{walls:[],rooms:[],items:[],heightDefaults:{modelVersion:2,floorThickness:180,floorRaiseSet:true,floorRaise:27},privateToken:'do-not-export'},options:{materialization:'bounded-v3',pageScope:['frozen-page-2']},camera:{view:'2d',floor:2,twoD:{zoom:.1,panX:50,panY:40},camera:null},state:{history:['unchanged-history'],redo:[],dirty:true},rawSha256:'c98e9213665b0527fae907a19d145d8a038db8f82bd049c57b74607add05485c',diagnostics:[]};let renders=0;const cap={catalogue:()=>rt.PlanImport.sceneCatalogue(),readScene:id=>id==='draft-1'?s:null,renderPreview:async input=>{renders++;input.assertFresh();return {planId:'isolated',camera:input.camera};}};return {rt,s,cap,api:API.create(cap),renders:()=>renders};}
function patch(scene){return {planId:'draft-1',baseRevision:scene.revision,selectedObjectIds:['obj-chair-nw'],incompleteConfirmed:true,displayBindings:[{sourceEntityId:'obj-chair-nw',catalogId:'fmp-Chair07',sizingPolicy:'fit-source',appearanceMode:'match-diagram-appearance'},{sourceEntityId:'room-ldk',catalogId:null,sizingPolicy:'native',appearanceMode:'match-diagram-appearance'}]};}
test('catalogue uses real exact metadata; scene copies and projection cannot mutate host or leak unknown metadata',()=>{const {api,s}=session();s.snapshot.rooms.push({id:'room-metadata',shape:{kind:'orthogonalPolygon',outer:[{x:0,y:0,secret:'nested-secret'}],token:'shape-token'},secret:'room-secret'});const before=JSON.stringify(s),cat=api.read_catalog({ids:['fmp-Chair07','fmp-Bed01']}),scene=api.get_scene({planId:'draft-1'});assert.equal(cat.entries[0].front,'+Z');assert.ok(cat.entries[0].parameters.includes('rot'));assert.ok(cat.entries[1].head);assert.match(cat.hash,/^sha256:[0-9a-f]{64}$/);assert.equal(scene.snapshot.privateToken,undefined);assert.equal(JSON.stringify(scene.snapshot).includes('secret'),false);assert.equal(scene.snapshot.rooms[0].shape.token,undefined);scene.source.objects.length=0;scene.snapshot.items.push({});cat.entries[0].w=0;assert.equal(JSON.stringify(s),before);assert.equal(api.read_catalog({ids:['fmp-Chair07']}).entries[0].w>0,true);});
test('two hand-authored display patches diagnose a missing room mapping, then render native isolation with source preserved',async()=>{const {api,s,renders}=session(),before=JSON.stringify(s),scene=api.get_scene({planId:'draft-1'}),p=patch(scene);p.displayBindings.pop();const first=await api.preview_patch(p);assert.equal(first.rendered,false);assert.ok(first.diagnostics.some(d=>d.code==='appearance_mapping_required'));p.displayBindings.push({sourceEntityId:'room-ldk',catalogId:null,sizingPolicy:'native',appearanceMode:'match-diagram-appearance'});const second=await api.preview_patch(p);assert.equal(second.rendered,true,JSON.stringify(second.diagnostics));assert.equal(renders(),1);assert.equal(second.applyAvailable,false);assert.equal(second.fullReconstructionReady,false);assert.equal(second.previewPlan.items[0].type,'fmp-Chair07');assert.equal(second.previewPlan.rooms[0].floorRaiseMm,27);assert.ok(second.deferred.some(d=>d.id==='obj-stair'));assert.ok(second.fullDiagnostics.some(d=>d.code==='unsupported_stair_reconstruction'));assert.equal(JSON.stringify(s),before);assert.equal(api.get_scene({planId:'draft-1'}).revision,scene.revision);});
test('stale target, source, options, history and camera reject before render',async()=>{for(const mutate of [s=>s.snapshot.items.push({id:'edited'}),s=>s.source.objects[0].sourceFootprint.value.center.x++,s=>s.options.pageScope.push('new-page'),s=>s.state.history.push('new-edit'),s=>s.camera.twoD.zoom++]){const {api,s,renders}=session(),p=patch(api.get_scene({planId:'draft-1'}));mutate(s);await assert.rejects(api.preview_patch(p),e=>e.code==='stale_revision');assert.equal(renders(),0);}});
test('limited operations reject source edits, arbitrary file/code, forged scope, unknown catalogues and approval bypass',async()=>{const {api}=session(),scene=api.get_scene({planId:'draft-1'});assert.deepEqual(Object.keys(api),['read_catalog','get_scene','preview_patch']);assert.throws(()=>api.get_scene({planId:'draft-1',file:'/etc/passwd'}));assert.throws(()=>api.get_scene({planId:'../draft'}));for(const edit of [p=>p.source=[],p=>p.apply=true,p=>p.acceptedReviewGroups=['rooms:room-ldk'],p=>p.incompleteConfirmed=false,p=>p.selectedObjectIds=['missing'],p=>p.displayBindings[0].catalogId='invented',p=>p.displayBindings[0].rotationDeg=180,p=>p.displayBindings[0].sizingPolicy='proxy',p=>p.displayBindings.push(p.displayBindings[0])]){const p=patch(scene);edit(p);await assert.rejects(api.preview_patch(p));}await assert.rejects(api.preview_patch(JSON.parse('{"__proto__":{},"planId":"draft-1"}')));});
test('unsupported selected source stays unresolved; no unknownification or omission can create success',async()=>{const {api,s}=session(),before=JSON.stringify(s),p=patch(api.get_scene({planId:'draft-1'}));const stair=s.source.objects.find(e=>e.objectType.value==='stair');p.selectedObjectIds=[stair.id];p.displayBindings=[];const out=await api.preview_patch(p);assert.equal(out.rendered,false);assert.ok(out.diagnostics.some(d=>d.code==='unsupported_stair_reconstruction'));assert.equal(JSON.stringify(s),before);});
test('race after an asynchronous render does not return success for a stale source',async()=>{const {cap,s}=session();cap.renderPreview=async()=>{s.source.objects[0].sourceFootprint.value.center.x++;return {};};const api=API.create(cap);await assert.rejects(api.preview_patch(patch(api.get_scene({planId:'draft-1'}))),e=>e.code==='stale_revision');});

test('catalogue changes invalidate the revision; data prototypes and function values are rejected',async()=>{const {api,cap}=session(),p=patch(api.get_scene({planId:'draft-1'})),original=cap.catalogue;cap.catalogue=()=>{const c=original();return {get:c.get,list:()=>c.list().map(e=>({...e,w:e.w+1}))};};await assert.rejects(api.preview_patch(p),e=>e.code==='stale_revision');assert.throws(()=>api.read_catalog({ids:[()=>{}]}));assert.throws(()=>api.get_scene(Object.assign(Object.create({inherited:'unexpected'}),{planId:'draft-1'})));});

test('hung render has a bounded deadline, releases busy and fences its late continuation',async()=>{const {cap}=session();cap.previewTimeoutMs=20;let release,attempt=0,cancelled=0;cap.cancelPreview=()=>cancelled++;cap.renderPreview=async input=>{if(++attempt===1)await new Promise(r=>release=r);input.assertFresh();return {};};const api=API.create(cap);await assert.rejects(api.preview_patch(patch(api.get_scene({planId:'draft-1'}))),e=>e.code==='preview_timeout');assert.equal(cancelled,1);assert.equal((await api.preview_patch(patch(api.get_scene({planId:'draft-1'})))).rendered,true);release();await new Promise(setImmediate);assert.equal(cancelled,1,'late cancelled job must not release another preview');});
test('explicit lifecycle cancellation rejects and allows a new preview',async()=>{const {cap}=session();let attempt=0;cap.renderPreview=async input=>{if(++attempt===1)input.cancel('preview_cancelled','editor closed');input.assertFresh();return {};};const api=API.create(cap);await assert.rejects(api.preview_patch(patch(api.get_scene({planId:'draft-1'}))),e=>e.code==='preview_cancelled');assert.equal((await api.preview_patch(patch(api.get_scene({planId:'draft-1'})))).rendered,true);});
