// Regression of the independent f825886 harness probe. Lifecycle is mocked;
// physical geometry/storage/rendering is verified separately in Chrome.
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const code=fs.readFileSync('local-preview/internal-api.js','utf8');
function fixture(){let cap,stale=false,sequence=0;const raf=[];let current;
 const PE={plans:new Map(),panes:new Map(),readSavedPane(){},close(){for(const p of PE.panes.values())p.frame.contentWindow.EditorPane.dispose();PE.panes.clear();},setSync(){},async openPlan(plan,name,opts){const id='preview-'+(++sequence),editor={DATA:{walls:[]},EditorPane:{install:async()=>true,applyView(){},view:()=>({view:'2d'}),dispose(){editor._editorPaneDisposed=true;}},document:{querySelectorAll:()=>[]},requestAnimationFrame:f=>raf.push(f)},pane={id:'pane-'+sequence,planId:id,ready:true,frame:{contentWindow:editor,isConnected:true}};current={editor,pane};PE.plans.set(id,{plan,memoryOnly:opts.memoryOnly});opts.onCreated(id);PE.panes.set(pane.id,pane);return id;},discardMemoryPlan(id){assert.equal(PE.plans.get(id)?.memoryOnly,true);for(const p of [...PE.panes.values()])if(p.planId===id){p.frame.contentWindow.EditorPane.dispose();PE.panes.delete(p.id);}PE.plans.delete(id);}};
 const root={document:{querySelector:()=>null},EditorInternalAPI:{create:c=>(cap=c,{})}};root.parent=root;
 vm.runInNewContext(code,{window:root,location:{hostname:'127.0.0.1',search:'?internalAPI=1'},URLSearchParams,ParallelEditors:PE,performance,setTimeout,clearTimeout});
 function input(){const controller=new AbortController();return {plan:{items:[]},targetSnapshot:{},source:{},camera:{view:'2d'},displayBindings:[],diagnostics:[],signal:controller.signal,cancel(code,message){const e=Error(message);e.code=code;controller.abort(e);},assertFresh(){if(controller.signal.aborted)throw controller.signal.reason;if(stale)throw Error('STALE');}};}
 return {cap,PE,raf,input,current:()=>current,makeStale:()=>stale=true,async flush(){await new Promise(setImmediate);while(raf.length)raf.shift()();await new Promise(setImmediate);}};
}
test('stale source after install rejects and removes every provisional memory record/pane',async()=>{const f=fixture(),pending=f.cap.renderPreview(f.input()),rejected=assert.rejects(pending,/STALE/);await new Promise(setImmediate);f.makeStale();await f.flush();await rejected;assert.equal(f.PE.plans.size,0);assert.equal(f.PE.panes.size,0);});
test('disposed pane during final animation wait rejects even if callbacks are delivered',async()=>{const f=fixture(),pending=f.cap.renderPreview(f.input()),rejected=assert.rejects(pending,e=>e.code==='preview_cancelled');await new Promise(setImmediate);f.current().editor.EditorPane.dispose();await f.flush();await rejected;assert.equal(f.PE.plans.size,0);assert.equal(f.PE.panes.size,0);});
test('stopped animation callbacks time out and remove the provisional scene',async()=>{const f=fixture(),start=performance.now();await assert.rejects(f.cap.renderPreview(f.input()),e=>e.code==='preview_timeout');assert.ok(performance.now()-start<3500);assert.equal(f.PE.plans.size,0);assert.equal(f.PE.panes.size,0);});
test('close cancels an in-flight preview and successful close permits recreation',async()=>{const f=fixture(),pending=f.cap.renderPreview(f.input());await new Promise(setImmediate);f.PE.close();await assert.rejects(pending,e=>e.code==='preview_cancelled');assert.equal(f.PE.plans.size,0);let next=f.cap.renderPreview(f.input());await f.flush();const a=await next;assert.equal(a.imageCaptureStatus,'external-not-captured');f.PE.close();assert.equal(f.PE.plans.size,0);next=f.cap.renderPreview(f.input());await f.flush();const b=await next;assert.notEqual(a.planId,b.planId);});
