'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {libraryContext,makePaneWindow,fixture,ROOT}=require('./plan-library-test-support.cjs');
const tick=()=>new Promise(resolve=>setImmediate(resolve)),plain=v=>JSON.parse(JSON.stringify(v));
function legacy(){return {walls:[{id:7,floor:1,x1:0,y1:0,x2:1000,y2:0,thick:120},{id:7,floor:2,x1:0,y1:0,x2:1000,y2:0,thick:120},{id:9,floor:2,x1:20,y1:30,x2:20,y2:30,thick:120,unknownInert:{retained:true}}],rooms:[{id:11,floor:1,x:0,y:0,w:1000,d:1000}],items:[],exteriorWallSettings:{walls:{7:{color:'#123456'},99:{opaque:'dormant'}},faces:{'7_future_face':{opaque:true}}},unknownOptional:{nested:[7]}};}
function harness(options={}){let h;const admissions=[];h=libraryContext({...options,beforeLibrary(c,sandbox){for(const file of ['room-geometry','plan-schema','legacy-plan-copy-dryrun','legacy-plan-compatibility','legacy-plan-lineage','plan-repository-lab'])vm.runInContext(fs.readFileSync(path.join(ROOT,'assets/js/'+file+'.js'),'utf8'),sandbox);c.__cloneInTestRealm=value=>{c.__testValue=JSON.stringify(value);const result=vm.runInContext('JSON.parse(__testValue)',sandbox);delete c.__testValue;return result;};const install=c.EditorPane.install;c.EditorPane.install=async(plan,saved,cap)=>{const repo=c.PlanLibrary.repo,checked=repo.validateAdmission(plan,cap);if(!checked.ok)throw Error('pane validation rejected');admissions.push(cap);return install(plan,saved);};},iframeFactory(){const child=makePaneWindow().window,install=child.EditorPane.install;child.EditorPane.install=async(plan,saved,cap)=>{const checked=h.api.repo.validateAdmission(plan,cap);if(!checked.ok)throw Error('pane validation rejected');admissions.push(cap);return install(plan,saved);};return child;}});const get=h.api.repo.get;h.api.repo.get=async(...args)=>{const value=await get(...args);return value===undefined?value:h.context.__cloneInTestRealm(value);};h.admissions=admissions;return h;}
async function converted(h){const raw=JSON.stringify(legacy()),source=await h.api.repo.importSource({sourceId:'anonymous',kind:'plan',raw}),originalId=source.plans[0].planId,review=await h.api.repo.prepareLegacyCopy(originalId);await h.api.repo.createLegacyCopy(review,'converted','Converted copy','create');return {raw,originalId};}
async function save(h){const p=[...h.api.panes.values()][0];return h.api.persistPane(p.id,p.planId,h.plan);}
test('inventory keeps originals inspectable and conversion requires a deliberate review/commit then separate selection',async()=>{const h=harness();await h.api.ready;const source=await h.api.repo.importSource({sourceId:'anonymous',kind:'plan',raw:JSON.stringify(legacy())}),originalId=source.plans[0].planId,before=h.context.__editorPlanId;await h.api.list();assert.ok(h.document.querySelector('[data-library-convert-review]'));await h.api.inspectOriginal(originalId);assert.equal(h.document.querySelector('textarea').readOnly,true);await h.api.reviewLegacyCopy(originalId);const commit=h.document.querySelector('[data-library-convert-commit]');assert.ok(commit);assert.equal(h.context.__editorPlanId,before);let pending;const run=h.api.run;h.api.run=fn=>(pending=run(fn));commit.onclick();await pending;const heads=await h.api.repo.list();assert.equal(heads.length,2);assert.equal(h.context.__editorPlanId,before);const converted=heads.find(head=>head.origin?.legacyCopy);assert.ok(converted);assert.notEqual(converted.id,originalId);});
test('native open/save/reload preserves converted ID, original archive, exact inert records and unknown data',async()=>{const h=harness();await h.api.ready;const source=await converted(h);await h.api.openPlan('converted');assert.ok(h.admissions.at(-1));assert.equal(h.context.__editorPlanId,'converted');h.edit({...h.plan,rooms:[{...h.plan.rooms[0],x:500}]});await save(h);h.context.clearDirty();await h.api.reloadPlan('native-editor');assert.equal(h.plan.rooms[0].x,500);assert.deepEqual(h.plan.walls[2],legacy().walls[2]);assert.deepEqual(h.plan.unknownOptional,legacy().unknownOptional);assert.equal((await h.api.repo.read(source.originalId)).revision.kind,'legacy-copy');assert.equal((await h.api.repo.list('rawSources'))[0].raw,source.raw);});
test('native to comparison and fresh native reload carry repository admission with the same plan ID',async()=>{
 const h=harness();await h.api.ready;const original=await converted(h);await h.api.openPlan('converted');h.edit({...h.plan,rooms:[{...h.plan.rooms[0],x:555}]});
 await h.api.repo.save({planId:'strict-comparison',name:'Synthetic comparison',operationId:'seed-strict-comparison',baseRevisionId:null,baseGeneration:0,payload:fixture(222)});
 assert.equal(await h.api.openComparison(),true);assert.equal(h.popups.length,0,'entry waits for a deliberate second-plan choice');
 assert.equal(h.document.querySelector('[data-library-open-plan="converted"]').disabled,true,'current plan cannot compare against itself');
 const choice=h.document.querySelector('[data-library-open-plan="strict-comparison"]');assert.ok(choice);assert.equal(await choice.onclick(),true);assert.equal(h.popups.length,1);
 const url=new URL(h.popups[0].url),cmp=harness({mem:h.mem,native:false,search:url.search});await cmp.api.ready;const panes=[...cmp.api.panes.values()],p=panes[0];
 assert.deepEqual(panes.map(pane=>pane.planId),['converted','strict-comparison']);assert.equal(p.planId,'converted');assert.ok(cmp.admissions[0],'converted pane receives its repository admission');
 const snapshot=p.frame.contentWindow.EditorPane.snapshot();assert.equal(snapshot.rooms[0].x,555);assert.deepEqual(snapshot.walls[2],legacy().walls[2]);assert.deepEqual(snapshot.unknownOptional,legacy().unknownOptional);
 await cmp.api.persistPane(p.id,p.planId,snapshot);const fresh=harness({mem:h.mem,sessionStorage:h.sessionStorage});await fresh.api.ready;
 assert.equal(fresh.context.__editorPlanId,'converted');assert.ok(fresh.admissions.at(-1));assert.equal(fresh.plan.rooms[0].x,555);assert.deepEqual(fresh.plan.walls[2],legacy().walls[2]);assert.deepEqual(fresh.plan.unknownOptional,legacy().unknownOptional);
 assert.equal((await fresh.api.repo.list('rawSources'))[0].raw,original.raw);assert.equal((await fresh.api.repo.read(original.originalId)).revision.kind,'legacy-copy');
});
test('derived/RPG copy retains source entities and zeros but newly added invalid source content fails',async()=>{const h=harness();await h.api.ready;await converted(h);await h.api.openPlan('converted');const source=plain(h.plan),sourceText=JSON.stringify(h.plan),options={sourcePaneId:'native-editor',sourcePlanId:'converted',sourceSnapshot:sourceText,isCurrent:()=>true};const derived=await h.api.createIndependentPlan({...source,unknownDerived:true},'RPG anonymous',options);assert.ok((await h.api.repo.read(derived)).head.origin.legacyCopy);assert.deepEqual(h.plan,source);const invalid=plain(source);invalid.walls.push({...source.walls[2],id:30});await assert.rejects(h.api.createIndependentPlan(invalid,'Invalid AI addition',options),/形式/);assert.equal(h.context.__editorPlanId,'converted');assert.deepEqual(h.plan,source);});
test('recovery creates a lineage-bearing independent copy and invalid recoveries preserve current edits',async()=>{const h=harness();await h.api.ready;await converted(h);await h.api.openPlan('converted');const saved=await h.api.repo.read('converted'),draft={plan:h.plan,payload:h.plan,dirty:true,generation:2,baseRevisionId:saved.revision.id,baseGeneration:saved.head.headGeneration};const written=await h.api.repo.saveDraft('other-session','converted',draft);const recovered=await h.api.recoverDraft(written.id);assert.ok((await h.api.repo.read(recovered)).head.origin.legacyCopy);assert.equal(h.context.__editorPlanId,recovered);const before=h.plan,bad=plain(before);bad.walls.push({...bad.walls[2],id:77});const invalid=await h.api.repo.saveDraft('bad-session','converted',{...draft,plan:bad,payload:bad});await assert.rejects(h.api.recoverDraft(invalid.id),/validation/);assert.deepEqual(h.plan,before);assert.equal(h.context.__editorPlanId,recovered);});
test('bad repository lineage or cancelled install never changes current identity, data or dirty state',async()=>{const h=harness();await h.api.ready;await converted(h);const before=h.plan,id=h.context.__editorPlanId;h.cancelInstall();await assert.rejects(h.api.openPlan('converted'),/取消|取り消/);assert.equal(h.context.__editorPlanId,id);assert.deepEqual(h.plan,before);h.cancelInstall(false);const db=h.mem.dbs.get('webcad-plan-library-lab-ui-v1');db.stores.get('plans').get('converted').origin.legacyCopy.rawDigest='0'.repeat(64);await assert.rejects(h.api.openPlan('converted'),/lineage/);assert.equal(h.context.__editorPlanId,id);assert.deepEqual(h.plan,before);});
test('shared creation and sync reject zero-wall copies before requests or dirty/identity changes',async()=>{const h=harness();await h.api.ready;await converted(h);await h.api.openPlan('converted');const c=h.context,source=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),statuses=[];c.sharedSetStatus=(text,error)=>statuses.push({text,error});c.fetch=()=>{throw Error('network must not be used');};function section(start,end){return source.slice(source.indexOf(start),source.indexOf(end,source.indexOf(start)));}vm.runInContext(section('async function sharedSyncNow(){','async function flushSharedChanges(){')+'\n'+section('async function createSharedRoom(){','function leaveSharedRoom(){'),vm.createContext(c));c.DIRTY=true;const before=h.plan;await c.createSharedRoom();await c.sharedSyncNow();assert.equal(c.DIRTY,true);assert.equal(c.__editorPlanId,'converted');assert.deepEqual(h.plan,before);assert.equal(statuses.length,2);assert.ok(statuses.every(s=>s.error));});
test('ordinary selected legacy JSON opens the same explicit copy review without replacing dirty current work',async()=>{const h=harness();await h.api.ready;h.edit(fixture(888));const before=h.plan,id=h.context.__editorPlanId,c=h.context,source=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),readers=[];c.FileReader=class{constructor(){readers.push(this);}readAsText(){}};c.console={warn(){},error(){}};c._jsonImportRequest=0;c.stageJsonImport=text=>{const p=JSON.parse(text),v=c.PlanSchema.validatePlan(p);if(!v.ok)throw Error('strict invalid');return {data:p};};vm.runInContext(source.slice(source.indexOf('function doImport(inp){'),source.indexOf('// 天井に固定する器具',source.indexOf('function doImport(inp){'))),vm.createContext(c));const input={files:['anonymous.json'],value:'anonymous.json'};let pending;const run=h.api.run;h.api.run=fn=>(pending=run(fn));c.doImport(input);readers[0].onload({target:{result:JSON.stringify(legacy())}});await pending;assert.ok(h.document.querySelector('[data-library-convert-commit]'));assert.equal(c.__editorPlanId,id);assert.equal(c.DIRTY,true);assert.deepEqual(h.plan,before);assert.equal((await h.api.repo.list('rawSources')).length,1);});
test('stale legacy import review and ambiguous references cannot create a converted head',async()=>{const h=harness();await h.api.ready;assert.equal(await h.api.reviewLegacyImport(JSON.stringify(legacy()),{isCurrent:()=>false}),false);assert.equal((await h.api.repo.list()).length,0);const ambiguous=legacy();ambiguous.items=[{id:30,type:'chair',floor:2,x:0,y:0,wallId:7}];await assert.rejects(h.api.reviewLegacyImport(JSON.stringify(ambiguous)),/unhandled_identity_references/);assert.equal((await h.api.repo.list()).length,0);assert.equal((await h.api.repo.list('rawSources')).length,0);});
test('real RPG conversion helper and retained-source composition both derive independently with the copy contract',async()=>{const h=harness();await h.api.ready;const original=legacy();original.items=[{id:40,type:'chair',floor:1,x:100,y:200,w:500,d:500,rot:0,opaqueFinish:{retained:true}}];const source=await h.api.repo.importSource({sourceId:'anonymous-rpg-source',kind:'plan',raw:JSON.stringify(original)}),review=await h.api.repo.prepareLegacyCopy(source.plans[0].planId);await h.api.repo.createLegacyCopy(review,'converted','Converted','create');await h.api.openPlan('converted');const base=plain(h.plan),options={sourcePaneId:'native-editor',sourcePlanId:'converted',sourceSnapshot:JSON.stringify(base),isCurrent:()=>true};const converter=require('../../assets/js/asset-pack-conversion.js').createConverter({version:1,revision:'anonymous-v1',mappings:[{sourceId:'chair',targetId:'rpg-mansion-chair-01',native:true}]},[{id:'chair',w:500,d:500,h:900},{id:'rpg-mansion-chair-01',w:500,d:500,h:900}]),preview=converter.preview(base);assert.equal(preview.changed,1);const rpg=await h.api.createIndependentPlan(preview.plan,'RPG actual helper',{...options,cataloguePack:'rpg-mansion'}),rpgSaved=await h.api.repo.read(rpg);assert.equal(rpgSaved.payload.items[0].type,'rpg-mansion-chair-01');assert.deepEqual(plain(rpgSaved.payload.walls),base.walls);assert.deepEqual(plain(rpgSaved.payload.items[0].opaqueFinish),base.items[0].opaqueFinish);assert.ok(rpgSaved.head.origin.legacyCopy);const generated={walls:[{id:50,floor:1,x1:3000,y1:0,x2:4000,y2:0,thick:120}],rooms:[],items:[]};assert.equal(h.context.PlanSchema.validatePlan(generated).ok,true);const combined={...base,walls:base.walls.concat(generated.walls)},composition=await h.api.createIndependentPlan(combined,'Retained source composition',options);assert.ok((await h.api.repo.read(composition)).head.origin.legacyCopy);assert.deepEqual(h.plan,base);});
test('incoming unsupported shared plan cannot clear the current admission or mutate current edits',async()=>{const h=harness();await h.api.ready;await converted(h);await h.api.openPlan('converted');const c=h.context,cap=h.admissions.at(-1),before=h.plan,source=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');c.__legacyPlanAdmission=cap;c.DIRTY=true;vm.runInContext(source.slice(source.indexOf('function installSharedPlan('),source.indexOf('async function withSharedPlanIdentity(',source.indexOf('function installSharedPlan('))),vm.createContext(c));assert.throws(()=>c.installSharedPlan({plan:legacy(),version:2},'unsupported-room',false),/形式/);assert.equal(c.__legacyPlanAdmission,cap);assert.equal(c.DIRTY,true);assert.equal(c.__editorPlanId,'converted');assert.deepEqual(h.plan,before);});
test('manual shared save cannot transmit an unsupported zero copy or clear its dirty state',async()=>{const h=harness();await h.api.ready;await converted(h);await h.api.openPlan('converted');const c=h.context,source=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),before=h.plan,statuses=[];c.DIRTY=true;c.SHARED.roomId='unsupported-room';c.sharedSetStatus=(...args)=>statuses.push(args);c.fetch=()=>{throw Error('no transmission allowed');};vm.runInContext(source.slice(source.indexOf('async function savePlanToStorage(){'),source.indexOf('async function loadPlanFromStorage(){',source.indexOf('async function savePlanToStorage(){'))),vm.createContext(c));assert.equal(await c.savePlanToStorage(),false);assert.equal(c.DIRTY,true);assert.equal(c.__editorPlanId,'converted');assert.deepEqual(h.plan,before);assert.equal(statuses.length,1);assert.equal(statuses[0][1],true);});
