'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto').webcrypto;
const Repository=require('../../assets/js/plan-repository-lab.js'),Schema=require('../../assets/js/plan-schema.js');
const {memoryIDB}=require('./plan-library-test-support.cjs');
function plan(){return {walls:[{id:7,floor:1,x1:0,y1:0,x2:1000,y2:0,thick:120},{id:7,floor:2,x1:0,y1:0,x2:1000,y2:0,thick:120},{id:9,floor:2,x1:20,y1:30,x2:20,y2:30,thick:120,inertExtension:{retained:true}}],rooms:[{id:11,floor:1,x:0,y:0,w:1000,d:1000}],items:[],exteriorWallSettings:{walls:{7:{texture:'data:image/png;base64,YQ==',textureFlipX:true},99:{custom:'dormant'}},faces:{'7_future_suffix':{texture:'data:image/png;base64,Yg=='}}},unknown:{numericMap:{7:'leave'}}};}
async function setup(){const mem=memoryIDB();global.IDBKeyRange=mem.keyRange;const repo=Repository.create({indexedDB:mem.idb,crypto,name:'webcad-plan-library-lab-legacy-tests'});const raw=JSON.stringify(plan()),imported=await repo.importSource({sourceId:'anonymous',kind:'plan',raw});const originalId=imported.plans[0].planId,review=await repo.prepareLegacyCopy(originalId);const copy=await repo.createLegacyCopy(review,'converted','conversion-copy','create');return {repo,mem,raw,originalId,copy};}
function table(h,store){return h.mem.dbs.get('webcad-plan-library-lab-legacy-tests').stores.get(store);}
test('explicit converted copy archives original unchanged and issues non-JSON admission',async()=>{const h=await setup(),saved=await h.repo.read('converted');assert.equal(Schema.validatePlan(saved.payload).ok,false);assert.equal(saved.payload.walls.length,3);assert.deepEqual(saved.payload.unknown,plan().unknown);assert.notEqual(saved.payload.walls[0].id,saved.payload.walls[1].id);assert.equal((await h.repo.read(h.originalId)).revision.kind,'legacy-copy');assert.equal([...table(h,'rawSources').values()][0].raw,h.raw);const cap=await h.repo.admission('converted',saved.payload);assert.equal(h.repo.validateAdmission(saved.payload,cap).ok,true);assert.throws(()=>h.repo.validateAdmission(saved.payload,JSON.parse(JSON.stringify(cap))),/untrusted/);});
test('payload flags and forged origins cannot create permission',async()=>{const h=await setup(),saved=await h.repo.read('converted');await assert.rejects(h.repo.save({planId:'forged',operationId:'new',payload:{...saved.payload,allowLegacyZeroWalls:true},origin:saved.head.origin,baseRevisionId:null,baseGeneration:0}),/untrusted/);table(h,'plans').set('forged',{id:'forged',...saved.head,headRevisionId:saved.revision.id});await assert.rejects(h.repo.admission('forged',saved.payload),/lineage/);});
test('changed invalid inert record, added zero wall, dropped IDs, duplicate IDs and unrelated errors fail before head advances',async()=>{const h=await setup(),saved=await h.repo.read('converted');const cases=[p=>p.walls[2].inertExtension.retained=false,p=>p.walls.push({...p.walls[2],id:99}),p=>delete p.walls[2].id,p=>delete p.rooms[0].id,p=>p.rooms.push({...p.rooms[0]}),p=>p.walls[0].thick=1,p=>p.items.push({id:30,type:'chair',floor:8,x:0,y:0}),p=>p.walls[2].baseRoom=11];for(const alter of cases){const payload=structuredClone(saved.payload);alter(payload);await assert.rejects(h.repo.save({planId:'converted',operationId:crypto.randomUUID(),payload,baseRevisionId:saved.revision.id,baseGeneration:saved.head.headGeneration}),/validation/);assert.equal((await h.repo.read('converted')).revision.id,saved.revision.id);}});
test('raw hash, import revision, source payload, candidate revision and contract mismatches fail closed',async()=>{for(const mutate of [h=>[...table(h,'rawSources').values()][0].raw+=' ',h=>[...table(h,'migrations').values()].find(r=>r.importRevisionId).importRevisionId='converted:create',h=>{const r=table(h,'revisions').get(h.originalId+':import');r.payload='{}';},h=>{const r=table(h,'revisions').get('converted:create');r.payloadDigest='0'.repeat(64);},h=>table(h,'plans').get('converted').origin.legacyCopy.candidateDigest='0'.repeat(64),h=>{[...table(h,'rawSources').values()][0].rawStructured={walls:[],rooms:[],items:[]};}]){const h=await setup();mutate(h);await assert.rejects(h.repo.read('converted'));}});
test('duplicate, valid edits, derive and restore carry verified lineage while source-only invalid content fails',async()=>{const h=await setup(),before=await h.repo.read('converted');await h.repo.duplicate('converted','duplicate','duplicate','dup');assert.equal((await h.repo.read('duplicate')).payload.walls.length,3);const edited=structuredClone(before.payload);edited.rooms[0].x=500;const saved=await h.repo.save({planId:'converted',operationId:'edit',payload:edited,baseRevisionId:before.revision.id,baseGeneration:before.head.headGeneration});await h.repo.derive({planId:'derived',operationId:'derive',payload:edited,kind:'derived-plan',baseRevisionId:null,baseGeneration:0},'converted',saved.revisionId);assert.equal((await h.repo.read('derived')).payload.rooms[0].x,500);await h.repo.restore('converted',before.revision.id,saved.revisionId,saved.head.headGeneration,'restore');assert.equal((await h.repo.read('converted')).payload.rooms[0].x,0);const invalid=structuredClone(edited);invalid.walls.push({...edited.walls[2],id:55});await assert.rejects(h.repo.derive({planId:'invalid-derived',operationId:'derive',payload:invalid,kind:'derived-plan',baseRevisionId:null,baseGeneration:0},'converted',saved.revisionId),/validation/);});
test('stale or serialized review cannot commit and storage failure leaves originals readable',async()=>{const h=await setup(),review=await h.repo.prepareLegacyCopy(h.originalId);await assert.rejects(h.repo.createLegacyCopy(JSON.parse(JSON.stringify(review)),'bad','bad','bad'),/review/);h.mem.failNext(new DOMException('Disk full','QuotaExceededError'));await assert.rejects(h.repo.createLegacyCopy(review,'failed','failed','failed'),{name:'QuotaExceededError'});assert.equal(await h.repo.read('failed'),null);assert.equal((await h.repo.read(h.originalId)).payload.walls.length,3);assert.equal(await h.repo.get('migrations','legacy-copy-contract:failed'),undefined);});
test('numeric zero wall ID remapping is blocked rather than activating dormant renderer settings',async()=>{const mem=memoryIDB();global.IDBKeyRange=mem.keyRange;const repo=Repository.create({indexedDB:mem.idb,crypto,name:'webcad-plan-library-lab-zero-id'}),source=plan();source.walls=source.walls.slice(0,2).map(w=>({...w,id:0}));source.exteriorWallSettings={walls:{0:{color:'#123456'}}};source.items=[];const raw=JSON.stringify(source),imported=await repo.importSource({sourceId:'anonymous-zero-id',kind:'plan',raw});await assert.rejects(repo.prepareLegacyCopy(imported.plans[0].planId),/unsupported_numeric_zero_wall_identity/);assert.equal((await repo.list()).length,1);assert.equal((await repo.list('rawSources'))[0].raw,raw);});
test('a derivation cannot revive a zero record removed from its actual source snapshot',async()=>{const h=await setup(),source=await h.repo.read('converted'),without={...source.payload,walls:source.payload.walls.filter(w=>w.id!==9)};await assert.rejects(h.repo.derive({planId:'revived',operationId:'derive',payload:source.payload,kind:'derived-plan',baseRevisionId:null,baseGeneration:0},'converted',source.revision.id,without),/validation/);assert.equal(await h.repo.read('revived'),null);});
test('all ordinary new save payloads remain strict despite a permissive-looking JSON flag',async()=>{const h=await setup(),invalid={...plan(),allowLegacyZeroWalls:true};await assert.rejects(h.repo.save({planId:'new-ai-output',operationId:'new',payload:invalid,baseRevisionId:null,baseGeneration:0}),/new_plan_validation_failed/);assert.equal(await h.repo.read('new-ai-output'),null);});
