const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const {runtime,read}=require('./scene-fixtures.cjs'),Schema=require('../../assets/js/plan-schema.js');
const copy=x=>JSON.parse(JSON.stringify(x));
const input=()=>({walls:[],rooms:[],items:[{type:'bath',x:2000,y:2000,w:1600,d:1600,rot:0,floor:1}]});
function setup(){const c=runtime();vm.runInContext(read('assets/js/plan-finish.js'),c);c.PlanFinish.mount=()=>{};c.structureItems=()=>[];c.isDerivedStructure=()=>false;c.draw2d=()=>{};c.resetView=()=>{};return c;}
test('opt-in keeps pre-pick reader dimensions separately from catalogue display and survives ordinary save/load',()=>{
 const c=setup();c.LEGACY_READER_DIMENSION_RETENTION=true;const p=input();c.PlanImport.state.result={plan:p,finish:{picks:[{slot:'s0',model:'fmp-BathTub02'}]}};c.applyPlanImport();assert.equal(c.DATA.items.length,1);const item=copy(c.DATA.items[0]),e=item.legacyReaderDimensions;assert.equal(item.type,'fmp-BathTub02');assert.equal(item.w,1160);assert.equal(item.d,517);assert.equal(e.input.type,'bath');assert.deepEqual(e.input.w,{provided:true,value:1600,status:'reader-reported-unverified'});assert.equal(e.sourceMeasurementStatus,'unverified');assert.equal(e.extentRole,'unspecified');assert.deepEqual(e.displayAtImport,{type:item.type,w:1160,d:517,basis:'legacy-catalogue-and-renderer-assumptions'});assert.equal(c.HISTORY.length,1);assert.equal(JSON.parse(c.HISTORY[0]).items.length,0);
 const plain=setup();plain.PlanImport.state.result={plan:input(),finish:{picks:[{slot:'s0',model:'fmp-BathTub02'}]}};plain.applyPlanImport();const geometry=copy(item);delete geometry.legacyReaderDimensions;assert.deepEqual(geometry,copy(plain.DATA.items[0]));
 const saved=copy(c.DATA);assert.equal(Schema.validatePlan(saved).ok,true);assert.deepEqual(Schema.normalizePlan(saved).items[0].legacyReaderDimensions,e);saved.items[0].w=999;assert.equal(saved.items[0].legacyReaderDimensions.input.w.value,1600);assert.equal(saved.items[0].legacyReaderDimensions.displayAtImport.w,1160);
});
test('missing and explicit null dimensions stay independently unknown while renderer uses existing defaults',()=>{
 const c=setup(),p={walls:[],rooms:[],items:[{type:'door-single',x:2000,y:2000,d:null,rot:0,floor:1}]},raw=JSON.stringify(p),snapshot=c.PlanImport.legacyReaderDimensionSnapshot(p),out=c.PlanImport.toAppObjects(p,snapshot),e=copy(out.items[0].legacyReaderDimensions);assert.equal(JSON.stringify(p),raw);assert.deepEqual(e.input.w,{provided:false,value:null,status:'unknown'});assert.deepEqual(e.input.d,{provided:true,value:null,status:'unknown'});assert.equal(e.extentRole,'unspecified');assert.equal(out.items[0].w,c.getItemDefaultSize('door-single').w);assert.equal(e.displayAtImport.w,out.items[0].w);assert.equal(e.input.w.value,null);
});
test('default-off import and old saved plans keep the old fields and rendering geometry',()=>{
 const c=setup(),p=input();const expected=copy(c.PlanImport.toAppObjects(p)).items[0];c.PlanImport.state.result={plan:p};c.applyPlanImport();const item=copy(c.DATA.items[0]);assert.equal(item.legacyReaderDimensions,undefined);for(const key of ['type','x','y','w','d','rot','floor'])assert.equal(item[key],expected[key]);const old=copy(c.DATA);assert.equal(Schema.validatePlan(old).ok,true);assert.equal(Schema.normalizePlan(old).items[0].legacyReaderDimensions,undefined);
});
test('cancelled apply does not mutate DATA/history; retained snapshot does not change on a later pick',()=>{
 const c=setup();c.LEGACY_READER_DIMENSION_RETENTION=true;c.DATA.rooms=[{id:'old',type:'room',x:0,y:0,w:1000,d:1000,floor:1}];c.confirm=()=>false;const p=input();c.PlanImport.state.result={plan:p,finish:{picks:[{slot:'s0',model:'fmp-BathTub02'}]}};const before=JSON.stringify(c.DATA);c.applyPlanImport();assert.equal(JSON.stringify(c.DATA),before);assert.equal(c.HISTORY.length,0);assert.equal(c.PlanImport.state.legacyReaderDimensionSnapshot,undefined);assert.equal(c.PlanImport.state.result.legacyReaderDimensionSnapshot[0].w.value,1600);c.applyPlanImport();assert.equal(c.PlanImport.state.result.legacyReaderDimensionSnapshot[0].w.value,1600);assert.equal(JSON.stringify(c.DATA),before);
});

test('invalid dimensions never retain nested payloads through save, export or whole-item shared patch',()=>{
 const {topLevelFunction}=require('./height-runtime.cjs');
 for(const value of [{arbitrary:'not-a-dimension',payload:{sourceText:'unrelated marker'}},['unrelated marker'],NaN,Infinity,-1,0,200001,true,'unrelated marker']){
  const c=setup();c.LEGACY_READER_DIMENSION_RETENTION=true;const p=input();p.items[0].w=value;c.PlanImport.state.result={plan:p,finish:{picks:[{slot:'s0',model:'fmp-BathTub02'}]}};c.applyPlanImport();const e=copy(c.DATA.items[0].legacyReaderDimensions);assert.deepEqual(e.input.w,{provided:true,value:null,status:'invalid',diagnostic:{code:'invalid_reader_dimension',field:'w'}});
  c.SHARED={dirtyIds:{walls:{},items:{},rooms:{}},forceScan:true};c.SHARED_FIELDS=[];['sharedClone','sharedFastSignature','buildSharedPatch'].forEach(name=>vm.runInContext(topLevelFunction(name),c));const patch=c.buildSharedPatch(c.DATA,null);for(const output of [JSON.stringify(c.DATA),JSON.stringify(patch),JSON.stringify(Schema.normalizePlan(copy(c.DATA)))]){assert.equal(output.includes('unrelated marker'),false);assert.equal(output.includes('arbitrary'),false);assert.equal(output.includes('sourceText'),false);}
 }
});
test('public converter narrows forged sidecar fields and accepts bounded numeric primitives only',()=>{
 const c=setup(),p=input(),forged=[{type:{payload:'unrelated marker'},w:{provided:true,value:{payload:'unrelated marker'}},d:{provided:true,value:'840'},extra:{payload:'unrelated marker'}}];const out=c.PlanImport.toAppObjects(p,forged),e=copy(out.items[0].legacyReaderDimensions);assert.equal(JSON.stringify(e).includes('unrelated marker'),false);assert.equal(e.input.type,null);assert.equal(e.input.w.status,'invalid');assert.deepEqual(e.input.d,{provided:true,value:'840',status:'reader-reported-unverified'});assert.equal(e.input.extra,undefined);
});

test('no-pick display baseline is bounded even when existing mkItem preserves an invalid width',()=>{
 for(const type of ['bath','chair','door-single']){const c=setup(),p=input();p.items[0].type=type;p.items[0].w={payload:'nested baseline marker'};const before=JSON.stringify(p),out=c.PlanImport.toAppObjects(p,c.PlanImport.legacyReaderDimensionSnapshot(p)),item=out.items[0],e=copy(item.legacyReaderDimensions);assert.equal(JSON.stringify(p),before);assert.deepEqual(copy(item.w),{payload:'nested baseline marker'});assert.equal(e.input.w.status,'invalid');assert.equal(e.displayAtImport.w,null);assert.deepEqual(e.displayAtImport.wDiagnostic,{code:'invalid_display_dimension',field:'w'});assert.equal(JSON.stringify(e).includes('nested baseline marker'),false);const saved=copy(out);assert.equal(JSON.stringify(saved.items[0].legacyReaderDimensions).includes('nested baseline marker'),false);}
});
