'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto').webcrypto;
const Repository=require('../../assets/js/plan-repository-lab.js'),Schema=require('../../assets/js/plan-schema.js'),{memoryIDB}=require('./plan-library-test-support.cjs');
let serial=0;
function fixture(){return {walls:[{id:10,floor:1,x1:0,y1:0,x2:1000,y2:0,thick:120},{id:10,floor:2,x1:0,y1:0,x2:1000,y2:0,thick:120},{id:30,floor:2,x1:20,y1:30,x2:20,y2:30,thick:120,anonymousMarker:'retained'}],rooms:[{id:40,floor:1,x:0,y:0,w:1000,d:1000}],items:[]};}
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
async function setup({structured=false,customCrypto=crypto,converted=true,workspace=false}={}){const mem=memoryIDB();global.IDBKeyRange=mem.keyRange;const name='webcad-plan-library-lab-review-'+(++serial),repo=Repository.create({indexedDB:mem.idb,crypto:customCrypto,name});const plan=fixture(),raw=structured?workspace?{plans:[{id:'anonymous-entry',plan}],attachment:new Blob(['anonymous-bytes'],{type:'text/plain'})}:plan:JSON.stringify(plan),imported=await repo.importSource({sourceId:'anonymous-review-'+serial,kind:workspace?'workspace':'plan',raw}),originalId=imported.plans[0].planId;const h={repo,mem,name,plan,raw,imported,originalId};if(converted){const review=await repo.prepareLegacyCopy(originalId);await repo.createLegacyCopy(review,'converted','Converted anonymous','create');h.saved=await repo.read('converted');}return h;}
function store(h,name){return h.mem.dbs.get(h.name).stores.get(name);}
async function save(h,payload,operationId){return h.repo.save({planId:'converted',operationId,payload,baseRevisionId:h.saved.revision.id,baseGeneration:h.saved.head.headGeneration});}

test('save snapshots caller data and metadata before any asynchronous validation or serialization',async()=>{
 const h=await setup(),payload=structuredClone(h.saved.payload),request={planId:'converted',operationId:'immutable-save',payload,baseRevisionId:h.saved.revision.id,baseGeneration:h.saved.head.headGeneration};const pending=h.repo.save(request);
 payload.walls.push({id:777,floor:1,x1:90,y1:90,x2:90,y2:90,thick:120});request.planId='wrong-target';request.operationId='wrong-operation';request.baseRevisionId=null;
 assert.equal((await pending).status,'saved');const loaded=await h.repo.read('converted');assert.equal(loaded.revision.id,'converted:immutable-save');assert.equal(loaded.payload.walls.length,3);assert.equal(await h.repo.read('wrong-target'),null);
});
test('a validator microtask cannot change the private immutable serialized snapshot',async()=>{
 const h=await setup(),payload=structuredClone(h.saved.payload),validate=Schema.validatePlan;let validatedFrozen=false;
 Schema.validatePlan=function(plan,...args){const result=validate.call(this,plan,...args);if(Object.isFrozen(plan)){validatedFrozen=true;queueMicrotask(()=>payload.walls.push({id:778,floor:1,x1:1,y1:1,x2:1,y2:1,thick:120}));}return result;};
 try{assert.equal((await save(h,payload,'microtask-save')).status,'saved');}finally{Schema.validatePlan=validate;}
 assert.equal(validatedFrozen,true);assert.equal((await h.repo.read('converted')).payload.walls.length,3);
});
test('hidden toJSON and accessor save hooks are rejected without execution or head advancement for legacy and strict data',async()=>{
 const h=await setup(),before=h.saved.revision.id;let calls=0;for(const legacy of [true,false])for(const hook of ['toJSON','accessor']){const payload=legacy?structuredClone(h.saved.payload):{walls:[],rooms:[],items:[]};if(hook==='toJSON')Object.defineProperty(payload,'toJSON',{value(){calls++;return {walls:[{id:99,floor:1,x1:0,y1:0,x2:0,y2:0,thick:120}],rooms:[],items:[]};}});else Object.defineProperty(payload,'unknownField',{enumerable:true,get(){calls++;return 'side effect';}});
 const request={planId:legacy?'converted':'strict-hook',operationId:'hook-'+hook,payload,baseRevisionId:legacy?before:null,baseGeneration:legacy?h.saved.head.headGeneration:0};await assert.rejects(h.repo.save(request),/non_json/);assert.equal((await h.repo.read('converted')).revision.id,before);assert.equal(await h.repo.read('strict-hook'),null);}
 assert.equal(calls,0);
});
test('raw structured projections must match the original archived codec bytes, even if an import payload is replaced and rehashed',async()=>{
 for(const structured of [false,true]){const h=await setup({structured,converted:false}),raw=store(h,'rawSources').get(h.imported.snapshotId),beforeRaw=raw.raw,beforeDigest=raw.rawDigest,replaced=fixture();replaced.walls[2].anonymousMarker='not-in-archived-bytes';replaced.walls[2].x1=replaced.walls[2].x2=800;raw.rawStructured=structuredClone(replaced);const revision=store(h,'revisions').get(h.originalId+':import');revision.payload=JSON.stringify(replaced);revision.payloadDigest=await h.repo.digest(revision.payload);await assert.rejects(h.repo.prepareLegacyCopy(h.originalId),/raw_source|lineage/);assert.equal(raw.raw,beforeRaw);assert.equal(raw.rawDigest,beforeDigest);assert.equal(await h.repo.read('forged-copy'),null);}
});
test('the unchanged structured codec still verifies workspace originals containing opaque Blob metadata',async()=>{
 const h=await setup({structured:true,workspace:true}),loaded=await h.repo.read('converted');assert.equal(loaded.payload.walls.length,3);assert.equal((await h.repo.admission('converted',loaded.payload)).retainedZeroWalls,1);const raw=await h.repo.get('rawSources',h.imported.snapshotId);assert.equal(raw.rawStructured.attachment.size,15);
});
test('an arbitrary caller parent payload cannot revive a zero absent from its named saved parent revision',async()=>{
 const h=await setup(),removed=structuredClone(h.saved.payload);removed.walls=removed.walls.filter(w=>w.id!==30);const edited=await save(h,removed,'removed-zero');const request={planId:'unproven-child',operationId:'derive',payload:h.saved.payload,kind:'derived-plan',baseRevisionId:null,baseGeneration:0};await assert.rejects(h.repo.derive(request,'converted',edited.revisionId,h.saved.payload),/untrusted_derivation_source/);assert.equal(await h.repo.read('unproven-child'),null);assert.equal((await h.repo.read('converted')).payload.walls.some(w=>w.id===30),false);
});
test('a verified dirty draft may legitimately differ from saved parent, with its exact source snapshot durably bound to derivation',async()=>{
 const h=await setup(),removed=structuredClone(h.saved.payload);removed.walls=removed.walls.filter(w=>w.id!==30);const edited=await save(h,removed,'removed-zero');const draft=await h.repo.saveDraft('anonymous-session','converted',{plan:h.saved.payload,payload:h.saved.payload,dirty:true,generation:3,baseRevisionId:edited.revisionId,baseGeneration:edited.head.headGeneration});const ticket=await h.repo.prepareDerivationSource('converted',edited.revisionId,draft.id,3);await h.repo.derive({planId:'proven-dirty-child',operationId:'derive',payload:h.saved.payload,kind:'derived-plan',baseRevisionId:null,baseGeneration:0},'converted',edited.revisionId,ticket);const child=await h.repo.read('proven-dirty-child');assert.equal(child.payload.walls.some(w=>w.id===30),true);assert.equal((await h.repo.read('converted')).payload.walls.some(w=>w.id===30),false);assert.equal(child.head.origin.copiedFromRevisionId,edited.revisionId);const registered=await h.repo.get('migrations','legacy-copy-contract:proven-dirty-child'),source=await h.repo.get('rawSources',registered.sourceSnapshot.id);assert.equal(await h.repo.digest(source.raw),registered.sourceSnapshot.digest);assert.equal(JSON.parse(source.raw).walls.some(w=>w.id===30),true);assert.equal(source.sourceOwner.generation,3);assert.equal(source.sourceOwner.parentRevisionId,edited.revisionId);
});
test('stale/serialized source tickets and tampered source snapshot lineage fail closed',async()=>{
 const h=await setup(),draft=await h.repo.saveDraft('anonymous-session','converted',{plan:h.saved.payload,payload:h.saved.payload,dirty:true,generation:3,baseRevisionId:h.saved.revision.id,baseGeneration:h.saved.head.headGeneration}),ticket=await h.repo.prepareDerivationSource('converted',h.saved.revision.id,draft.id,3),request={planId:'child',operationId:'derive',payload:h.saved.payload,kind:'derived-plan',baseRevisionId:null,baseGeneration:0};await assert.rejects(h.repo.derive(request,'converted',h.saved.revision.id,JSON.parse(JSON.stringify(ticket))),/untrusted_derivation_source/);
 await h.repo.saveDraft('anonymous-session','converted',{...draft,plan:h.saved.payload,payload:h.saved.payload,dirty:true,generation:4});await assert.rejects(h.repo.derive(request,'converted',h.saved.revision.id,ticket),/stale_derivation_source/);assert.equal(await h.repo.read('child'),null);
 const fresh=await h.repo.prepareDerivationSource('converted',h.saved.revision.id,draft.id,4);await h.repo.derive(request,'converted',h.saved.revision.id,fresh);const registration=await h.repo.get('migrations','legacy-copy-contract:child');store(h,'rawSources').get(registration.sourceSnapshot.id).raw+=' ';await assert.rejects(h.repo.read('child'),/raw_source|lineage/);
});
test('newly invalid source data cannot receive a derivation source ticket',async()=>{
 const h=await setup(),invalid=structuredClone(h.saved.payload);invalid.walls.push({id:99,floor:1,x1:0,y1:0,x2:0,y2:0,thick:120});const draft=await h.repo.saveDraft('anonymous-invalid','converted',{plan:invalid,payload:invalid,dirty:true,generation:1,baseRevisionId:h.saved.revision.id,baseGeneration:h.saved.head.headGeneration});await assert.rejects(h.repo.prepareDerivationSource('converted',h.saved.revision.id,draft.id,1),/validation/);assert.equal((await h.repo.read('converted')).revision.id,h.saved.revision.id);
});
test('review invalidation during proof and at the CAS write boundary creates neither a converted head nor registration',async()=>{
 let hold=false,target='',entered=deferred(),gate=deferred();const customCrypto={randomUUID:()=>crypto.randomUUID(),subtle:{async digest(algorithm,bytes){if(hold&&new TextDecoder().decode(bytes)===target){hold=false;entered.resolve();await gate.promise;}return crypto.subtle.digest(algorithm,bytes);}}};const h=await setup({customCrypto}),review=await h.repo.prepareLegacyCopy(h.originalId);let current=true;target=String(h.raw);hold=true;const pending=h.repo.createLegacyCopy(review,'cancelled-proof','Cancelled proof','create',{isCurrent:()=>current});await entered.promise;current=false;gate.resolve();await assert.rejects(pending,/stale/);assert.equal(await h.repo.read('cancelled-proof'),null);assert.equal(await h.repo.get('migrations','legacy-copy-contract:cancelled-proof'),undefined);
 const again=await h.repo.prepareLegacyCopy(h.originalId);let calls=0;await assert.rejects(h.repo.createLegacyCopy(again,'cancelled-write','Cancelled write','create',{isCurrent:()=>++calls<5}),/stale/);assert.equal(await h.repo.read('cancelled-write'),null);assert.equal(await h.repo.get('migrations','legacy-copy-contract:cancelled-write'),undefined);
});
