/* Own Chrome process/profile and loopback origin only. Never attaches existing tabs. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/tmp/webcad-browser-check/node_modules/playwright');
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),crypto=require('crypto');
const origin=process.env.APP_URL||'http://127.0.0.1:65360',out=process.env.OUTPUT_DIR||path.join(os.tmpdir(),'webcad-native-profile-replay');
assert.ok(/^http:\/\/127\.0\.0\.1:\d+$/.test(origin)&&!/:63239$|:65236$|:65352$/.test(origin));fs.mkdirSync(out,{recursive:true});
(async()=>{const profile=fs.mkdtempSync(path.join(os.tmpdir(),'webcad-sofa-profile-chrome-')),context=await chromium.launchPersistentContext(profile,{executablePath:process.env.CHROMIUM_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,viewport:{width:1600,height:1000},args:['--use-angle=metal']});let page;const errors=[],blocked=[];try{
 await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===origin&&!u.pathname.startsWith('/api/'))return r.continue();blocked.push(u.origin+u.pathname);return r.abort();});
 const defaultPage=await context.newPage();await defaultPage.goto(origin);await defaultPage.waitForSelector('#app-loading',{state:'hidden',timeout:60000});assert.equal(await defaultPage.evaluate(()=>typeof WebCADInternalAPI),'undefined');await defaultPage.close();
 page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/?internalAPI=1');await page.waitForSelector('#app-loading',{state:'hidden',timeout:60000});await page.waitForFunction(()=>window.WebCADInternalAPI&&window.threeModulesReady);await page.evaluate(()=>{closePresetChoice();document.getElementById('floor-sel').value='2';onFloorChange(2);setView('3d-ext');});await page.waitForFunction(()=>ren&&!hasPendingGltfModels()&&!_gltfRebuildTimer,null,{timeout:90000});
 await page.evaluate(()=>{DATA.walls=[];DATA.rooms=[];DATA.items=[];HISTORY.length=0;REDO_HISTORY.length=0;DIRTY=false;DATA.heightDefaults={modelVersion:2,floorThickness:180,floorRaise:27,floorRaiseSet:true};DATA.floors={};rebuild3D();});
 await page.evaluate(()=>ensureGltfModel(TailoredSofaFinish.url));await page.waitForFunction(()=>_modelCache[TailoredSofaFinish.url]&&!hasPendingGltfModels(),null,{timeout:60000});
 const asset=await page.evaluate(()=>({capability:TailoredSofaFinish.capability(),yaw:ModelQuality.sourceYaw(TailoredSofaFinish.url),assetStatus:TailoredSofaFinish.status(_modelCache[TailoredSofaFinish.url]),nativeRoot:{rotation:_modelCache[TailoredSofaFinish.url].rotation.toArray(),facingNormalized:_modelCache[TailoredSofaFinish.url].userData.facingNormalized}}));fs.writeFileSync(path.join(out,'native-front-audit.json'),JSON.stringify(asset,null,2));assert.equal(asset.capability.frontAudit?.axis,'+Z');assert.equal(asset.yaw,0);
 for(const side of [1,-1]){const data=await page.evaluate(side=>{const scene=new THREE.Scene();scene.background=new THREE.Color('#dfe4e8');const sofa=makeGltfBoxFitClone(TailoredSofaFinish.url,2,1.02,.94,null);sofa.rotation.set(0,0,0);scene.add(sofa);scene.add(new THREE.HemisphereLight(0xffffff,0x667788,2.2));const key=new THREE.DirectionalLight(0xffffff,2);key.position.set(3,5,4);scene.add(key);const camera=new THREE.PerspectiveCamera(35,ren.domElement.width/ren.domElement.height,.01,100);camera.position.set(.6,1.6,side*3.5);camera.lookAt(0,.52,0);camera.updateMatrixWorld();ren.render(scene,camera);const box=new THREE.Box3().setFromObject(sofa);return {png:ren.domElement.toDataURL('image/png'),box:{min:box.min.toArray(),max:box.max.toArray()},rotation:sofa.rotation.toArray()};},side);fs.writeFileSync(path.join(out,side>0?'native-0deg-plus-Z.png':'native-0deg-minus-Z.png'),Buffer.from(data.png.split(',')[1],'base64'));delete data.png;fs.writeFileSync(path.join(out,side>0?'native-0deg-plus-Z.json':'native-0deg-minus-Z.json'),JSON.stringify(data,null,2));}
 await page.evaluate(()=>{camExt.position.set(10,11,12);orbit.target.set(3.64,3.2,2.05);orbit.update();invalidate3D();});
 await page.getByRole('button',{name:'固定raw 2Fの部分プレビュー（AIなし・未完成）'}).click();await page.waitForSelector('#scene-ir-review');await page.screenshot({path:path.join(out,'01-source-review.png')});
 const calls=await page.evaluate(()=>({catalog:WebCADInternalAPI.read_catalog({ids:['custom-sofa-tailored','fmp-Sofa01']}),scene:WebCADInternalAPI.get_scene({planId:'host-draft'})}));fs.writeFileSync(path.join(out,'read-catalog.json'),JSON.stringify(calls.catalog,null,2));fs.writeFileSync(path.join(out,'get-scene.json'),JSON.stringify(calls.scene,null,2));
 assert.equal(calls.scene.rawSha256,'c98e9213665b0527fae907a19d145d8a038db8f82bd049c57b74607add05485c');
 async function integrity(){return page.evaluate(async()=>{const stores={};for(const info of await indexedDB.databases()){const db=await new Promise((res,rej)=>{const r=indexedDB.open(info.name);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});stores[info.name]={version:db.version,stores:{}};for(const name of db.objectStoreNames){stores[info.name].stores[name]=await new Promise((res,rej)=>{const tx=db.transaction(name,'readonly'),st=tx.objectStore(name),k=st.getAllKeys(),v=st.getAll();tx.oncomplete=()=>res({keys:k.result,values:v.result});tx.onerror=()=>rej(tx.error);});}db.close();}return {data:serializeDataSnapshot(),history:JSON.stringify(HISTORY),redo:JSON.stringify(REDO_HISTORY),dirty:DIRTY,source:JSON.stringify(PlanImport.state.result.sceneIR),options:JSON.stringify(PlanImport.state.result.sceneOptions),camera:WebCADInternalAPI.get_scene({planId:'host-draft'}).camera,storage:{local:Object.fromEntries(Object.entries(localStorage)),session:Object.fromEntries(Object.entries(sessionStorage)),indexedDB:stores}};});}
 const before=await integrity();const first={planId:'host-draft',baseRevision:calls.scene.revision,selectedObjectIds:['obj-sofa'],incompleteConfirmed:true,displayBindings:[{sourceEntityId:'obj-sofa',catalogId:'custom-sofa-tailored',sizingPolicy:'fit-source',appearanceMode:'match-diagram-appearance',appearanceProfile:{id:'tailored-sofa-regional-colors',version:1,assetSha256:'d05b95294ee7f2d763b2ede6f2391548a96f3021ad897ab81ec712d79c9d5667',colors:{body:'#E5E4DB',seat:'#EEEEE5'}}}]};
 const r1=await page.evaluate(p=>WebCADInternalAPI.preview_patch(p),first);assert.equal(r1.rendered,false);assert.ok(r1.diagnostics.some(d=>d.code==='appearance_mapping_required'));fs.writeFileSync(path.join(out,'patch-1-request.json'),JSON.stringify(first,null,2));fs.writeFileSync(path.join(out,'patch-1-response.json'),JSON.stringify(r1,null,2));
 const second=structuredClone(first);second.displayBindings.push({sourceEntityId:'room-ldk',catalogId:null,sizingPolicy:'native',appearanceMode:'match-diagram-appearance'});
 const r2=await page.evaluate(p=>WebCADInternalAPI.preview_patch(p),second);fs.writeFileSync(path.join(out,'patch-2-request.json'),JSON.stringify(second,null,2));fs.writeFileSync(path.join(out,'patch-2-response.json'),JSON.stringify(r2,null,2));assert.equal(r2.rendered,true,JSON.stringify(r2.diagnostics));
 const frame=page.frames().find(f=>f.url().includes('editorPane='+r2.preview.paneId));assert.ok(frame);await frame.waitForFunction(()=>ren&&!hasPendingGltfModels()&&!_gltfRebuildTimer,null,{timeout:90000});await page.waitForTimeout(1000);
 const native=await frame.evaluate(()=>({plan:EditorPane.snapshot(),state:{history:HISTORY,redo:REDO_HISTORY,dirty:DIRTY},view:EditorPane.view(),metrics:EditorPane.metrics(),pending:hasPendingGltfModels(),models:Object.keys(_modelCache),rendererSize:ren.getSize(new THREE.Vector2()).toArray(),geometryCount:sc3.children.length,canvas:!!document.querySelector('#c3d-wrap canvas[data-engine]')}));
 assert.equal(native.plan.items.length,1);assert.equal(native.plan.items[0].type,'custom-sofa-tailored');assert.deepEqual(native.plan.items[0].tailoredSofaColors,{version:1,colors:{body:'#E5E4DB',seat:'#EEEEE5'}});assert.equal(native.plan.items[0].finishColors,undefined);assert.equal(native.plan.items[0].h,undefined);assert.equal(r2.preview.appearanceProfileDisplays[0].ok,true);assert.equal(native.plan.rooms.length,1);assert.deepEqual(native.plan.sceneReconstructionReports[0].originalIR,calls.scene.source);assert.deepEqual(native.view.camera,calls.scene.camera.camera);assert.equal(native.view.view,'3d-ext');assert.equal(native.canvas,true);assert.equal(native.state.dirty,false);assert.ok(native.models.some(m=>m.includes('sofa_tailored')));assert.ok(native.geometryCount>0);await page.screenshot({path:path.join(out,'02-isolated-native-3d.png')});
 const rendered=await frame.evaluate(()=>{const item=DATA.items[0],roots=getSelectableRoots3D(item),box=new THREE.Box3();roots.forEach(r=>box.union(new THREE.Box3().setFromObject(r)));const meshes=[];roots.forEach(root=>root.traverse(n=>{if(n.isMesh&&n.name)meshes.push({name:n.name,color:n.material.color.getHexString(),position:n.position.toArray(),roughness:n.material.roughness,metalness:n.material.metalness,normalScale:n.material.normalScale.toArray(),normalMap:!!n.material.normalMap,channel:n.material.userData.finishChannel||null});}));ren.render(sc3,camExt);return {bbox:{min:box.min.toArray(),max:box.max.toArray(),heightMm:(box.max.y-box.min.y)*1000},feetMm:box.min.y*1000,planHeightMm:getItemHeightValue(item),expectedFeetMm:(item3DBaseY(item)+(item.elev||0)*U)*1000,meshes,png:ren.domElement.toDataURL('image/png')};});fs.writeFileSync(path.join(out,'03-native-sofa-canvas.png'),Buffer.from(rendered.png.split(',')[1],'base64'));delete rendered.png;const userPNG=await frame.evaluate(()=>{const camera=new THREE.PerspectiveCamera(40,ren.domElement.width/ren.domElement.height,.01,200);camera.position.set(7.1,4.65,3.3);camera.lookAt(5.58,3.25,.56);camera.updateMatrixWorld();ren.render(sc3,camera);const png=ren.domElement.toDataURL('image/png');ren.render(sc3,camExt);return png;});fs.writeFileSync(path.join(out,'native-sofa-raw-two-colors-manual-display-only.png'),Buffer.from(userPNG.split(',')[1],'base64'));assert.ok(Math.abs(rendered.bbox.heightMm-1020)<.01);assert.ok(Math.abs(rendered.feetMm-rendered.expectedFeetMm)<.01);assert.equal(rendered.planHeightMm,1020);assert.equal(rendered.meshes.length,14);for(const n of rendered.meshes){if(n.channel?.endsWith('body'))assert.equal(n.color,'e5e4db');if(n.channel?.endsWith('seat'))assert.equal(n.color,'eeeee5');if(n.name.includes('Oak_leg'))assert.equal(n.color,'866142');if(n.name.includes('Seat_seam'))assert.equal(n.color,'89938b');}fs.writeFileSync(path.join(out,'native-sofa-materials-bbox.json'),JSON.stringify(rendered,null,2));
 const after=await integrity();assert.deepEqual(after,before,'Original DATA/history/dirty/raw/options/camera/storage must match exactly');
 const stale=await page.evaluate(async p=>{p.baseRevision='sha256:'+'0'.repeat(64);try{await WebCADInternalAPI.preview_patch(p);return null;}catch(e){return {code:e.code,message:e.message};}},second);assert.equal(stale.code,'stale_revision');
 const guards=await frame.evaluate(async()=>{try{await EditorPane.save();return {saved:true};}catch(e){return {saved:false,message:e.message};}});assert.equal(guards.saved,false);
 // Two pane-owned editor instances; changes remain in this process and memory comparison.
 const paneIds=await page.evaluate(()=>[...ParallelEditors.panes.values()].map(p=>({id:p.id,planId:p.planId}))),other=page.frames().find(f=>f.url().includes('editorPane='+paneIds.find(p=>p.id!==r2.preview.paneId).id));
 const secondPlan=structuredClone(native.plan);secondPlan.items[0].tailoredSofaColors={version:1,colors:{body:'#112233',seat:'#445566'}};
 await other.evaluate(async ({plan,view})=>{await EditorPane.install(plan,{history:[],redo:[],dirty:false,view});},{plan:secondPlan,view:calls.scene.camera});await other.waitForFunction(()=>ren&&!hasPendingGltfModels()&&!_gltfRebuildTimer,null,{timeout:90000});
 const paneIsolation=await Promise.all([frame,other].map(f=>f.evaluate(()=>{const it=DATA.items[0],p=parent.TailoredSofaFinish.verifyRendered(it,getSelectableRoots3D(it));delete p.proof;return {item:it,proof:p,state:{history:HISTORY,redo:REDO_HISTORY,dirty:DIRTY},colors:getSelectableRoots3D(it).flatMap(r=>{const out=[];r.traverse(n=>{if(n.isMesh&&n.material.userData.finishChannel)out.push([n.name,n.material.color.getHexString()]);});return out;})};})));
 assert.equal(paneIsolation[0].proof.ok,true);assert.equal(paneIsolation[1].proof.ok,true);assert.deepEqual(paneIsolation[0].item.tailoredSofaColors,second.displayBindings[0].appearanceProfile?{version:1,colors:second.displayBindings[0].appearanceProfile.colors}:null);assert.deepEqual(paneIsolation[1].item.tailoredSofaColors,secondPlan.items[0].tailoredSofaColors);assert.deepEqual(await integrity(),before);fs.writeFileSync(path.join(out,'two-pane-isolation.json'),JSON.stringify(paneIsolation,null,2));
 await page.addScriptTag({url:origin+'/assets/js/plan-repository-lab.js'});const namespace='webcad-plan-library-lab-appearance-'+crypto.randomUUID();
 const saved=await page.evaluate(async({namespace,plan})=>{const repo=PlanRepositoryLab.create({name:namespace});const record=await repo.save({planId:'manual-source-profile',operationId:'v1-save',baseRevisionId:null,baseGeneration:0,payload:plan,name:'Manual isolated sofa profile'});await repo.close();const fresh=PlanRepositoryLab.create({name:namespace});const loaded=await fresh.read('manual-source-profile');await fresh.close();return {record,loaded};},{namespace,plan:native.plan});assert.deepEqual(saved.loaded.payload,native.plan);const decision=saved.loaded.payload.sceneReconstructionReports[0].reviewDecisions.bindingDecisions.find(d=>d.binding.sourceEntityId==='obj-sofa');assert.deepEqual(decision.binding.appearanceProfile,second.displayBindings[0].appearanceProfile);assert.equal(decision.appearanceProvenance.sourceSnapshot,JSON.stringify(calls.scene.source.objects.find(o=>o.id==='obj-sofa')));
 await page.evaluate(namespace=>new Promise((res,rej)=>{const q=indexedDB.deleteDatabase(namespace);q.onsuccess=()=>res(true);q.onerror=()=>rej(q.error);q.onblocked=()=>rej(Error('own namespace blocked'));}),namespace);assert.deepEqual(await integrity(),before);fs.writeFileSync(path.join(out,'isolated-save-fresh-read.json'),JSON.stringify({namespace,...saved},null,2));
 // Exact UI control in the existing review fieldset; no new global finish channels.
 await page.evaluate(()=>ParallelEditors.close());assert.deepEqual(await integrity(),before);
 await page.locator('[data-scene-mapping="obj-sofa"]').evaluate(el=>{const detail=el.closest('details');if(detail)detail.open=true;el.click();});await page.locator('[data-scene-catalogue]').selectOption('custom-sofa-tailored');const ui=page.locator('[data-scene-appearance-profile]');await ui.waitFor();await page.locator('[data-scene-sizing]').selectOption('fit-source');await page.locator('[data-scene-appearance]').selectOption('match-diagram-appearance');await ui.selectOption('tailored-sofa-regional-colors');await page.screenshot({path:path.join(out,'04-profile-review-ui.png')});await page.locator('[data-scene-mapping-confirm]').click();
 const uiSaved=await page.evaluate(()=>({source:PlanImport.state.result.sceneIR,options:PlanImport.state.result.sceneOptions,canApply:PlanImport.state.result.sceneCompilation.canApply,buttonDisabled:document.getElementById('plan-import-apply').disabled}));assert.deepEqual(uiSaved.source,calls.scene.source);assert.equal(uiSaved.canApply,false);assert.equal(uiSaved.buttonDisabled,true);const uiDecision=uiSaved.options.bindingDecisions.find(d=>d.binding.sourceEntityId==='obj-sofa');assert.deepEqual(uiDecision.binding.appearanceProfile,second.displayBindings[0].appearanceProfile);assert.deepEqual(uiSaved.options.acceptedReviewGroups,[]);assert.deepEqual(uiSaved.options.reviewedEntities,{});fs.writeFileSync(path.join(out,'profile-review-saved.json'),JSON.stringify(uiSaved,null,2));
 // A new isolated tab receives changed GLB padding: real loader hash failure cannot become API profile success.
 const bad=fs.readFileSync('assets/models/refined/sofa_tailored_v1.glb');bad[20+bad.readUInt32LE(12)-1]=10;const badPage=await context.newPage();await badPage.route('**/sofa_tailored_v1.glb?*',r=>r.fulfill({status:200,contentType:'model/gltf-binary',body:bad}));await badPage.goto(origin+'/?internalAPI=1');await badPage.waitForSelector('#app-loading',{state:'hidden',timeout:60000});await badPage.waitForFunction(()=>window.threeModulesReady&&getFmpItem('custom-sofa-tailored'));await badPage.evaluate(()=>ensureGltfModel(TailoredSofaFinish.url));await badPage.waitForFunction(()=>_modelCache[TailoredSofaFinish.url]&&!hasPendingGltfModels(),null,{timeout:60000});await badPage.getByRole('button',{name:'固定raw 2Fの部分プレビュー（AIなし・未完成）'}).click();await badPage.waitForFunction(()=>PlanImport.state.result?.sceneIR?.sceneVersion===3);
 const badResult=await badPage.evaluate(async template=>{const scene=WebCADInternalAPI.get_scene({planId:'host-draft'}),catalog=WebCADInternalAPI.read_catalog({ids:['custom-sofa-tailored']});try{await WebCADInternalAPI.preview_patch({...template,baseRevision:scene.revision});return {unexpectedSuccess:true};}catch(e){return {code:e.code,catalog,assetStatus:TailoredSofaFinish.status(_modelCache[TailoredSofaFinish.url]),sourceUnchanged:JSON.stringify(scene.source)===JSON.stringify(PlanImport.state.result.sceneIR)};}},second);assert.equal(badResult.code,'invalid_appearance_profile');assert.equal(badResult.catalog.entries[0].appearanceProfiles[0].available,false);assert.equal(badResult.assetStatus.reason,'asset-hash');assert.equal(badResult.sourceUnchanged,true);await badPage.close();fs.writeFileSync(path.join(out,'api-native-hash-failure.json'),JSON.stringify({changedByteSha256:crypto.createHash('sha256').update(bad).digest('hex'),...badResult},null,2));
 const report={origin,profile,paneIsolation,nativeHashFailureRejected:true,isolatedNamespace:namespace,saveReloadPreserved:true,uiSavedProfile:true,uiApplyDisabled:true,asset,rendered,profiles:r2.appearanceProfiles,rawByteSha256:calls.scene.rawSha256,sourceHash:calls.scene.sourceHash,catalogueHash:calls.catalog.hash,manualPatchReplays:2,paidCalls:0,applyCalls:0,firstRendered:r1.rendered,secondRendered:r2.rendered,sourcePlanId:'host-draft',previewPlanId:r2.preview.planId,sameCamera:true,originalUnchanged:true,storageUnchanged:true,native,stale,guards,errors,blocked};assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(report,null,2));fs.writeFileSync(path.join(out,'integrity-before.json'),JSON.stringify(before,null,2));fs.writeFileSync(path.join(out,'integrity-after.json'),JSON.stringify(after,null,2));console.log(JSON.stringify({native3D:true,sameCamera:true,originalUnchanged:true,storageUnchanged:true,manualPatchReplays:2,errors,blocked}));
 }finally{await context.close();}})().catch(e=>{console.error(e);process.exitCode=1});
