const {chromium}=require('/tmp/webcad-browser-check/node_modules/playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
const origin='http://127.0.0.1:65236',out='docs/quality-review/native-door-direction';
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal']}),ctx=await browser.newContext({viewport:{width:1700,height:1100}}),page=await ctx.newPage(),result={checks:[],errors:[],apiRequests:[],syntheticDataOnly:true,userTabObserved:false};ctx.setDefaultTimeout(30000);page.on('pageerror',e=>result.errors.push(e.stack));page.on('dialog',d=>d.accept());await ctx.route('**/*',r=>{const u=new URL(r.request().url());if(u.pathname.startsWith('/api/'))result.apiRequests.push(u.href);return u.origin===origin&&!u.pathname.startsWith('/api/')||['data:','blob:'].includes(u.protocol)?r.continue():r.abort();});
try{
 await page.goto(origin+'/?planLibrary=1');await page.waitForFunction(()=>!!PlanLibrary);
 await page.evaluate(async()=>{await PlanLibrary.repo.save({planId:'doors-review',name:'建具・原本保持の確認',operationId:'seed-doors',baseRevisionId:null,baseGeneration:0,payload:{walls:[],rooms:[],items:[],startMode:'blank'}});});
 await page.locator('[data-library-open]').click();await page.locator('[data-library-open-plan="doors-review"]').click();await page.waitForFunction(()=>[...PlanLibrary.panes.values()].some(p=>p.planId==='doors-review'&&p.ready));const f=await (await page.locator('.library-pane iframe').elementHandle()).contentFrame();
 await f.evaluate(async()=>{const body=await(await fetch('/local-preview/sample.json')).json();window.__doorBody=body;window.__doorSource=JSON.stringify(body.sourceLocal);openPlanImport();PlanImport.stageBuildingReview(body);});
 for(const floor of [1,2,3]){const g=f.locator('details[data-building-floor="'+floor+'"]');await g.evaluate(e=>e.open=true);await g.locator('[data-building-identity]').check();await g.locator('[data-building-identity-evidence]').fill('Public PDF floor title and correspondence inspected; no new AI');await g.locator('[data-building-confirm]').click();}
 await f.locator('[data-building-partial]').check();await f.locator('#plan-import-apply').click();await f.waitForFunction(()=>DATA.sceneReconstructionReports?.some(r=>r.kind==='building-registration'));await f.evaluate(()=>closePlanImport());
 result.source=await f.evaluate(()=>({unchanged:JSON.stringify(__doorBody.sourceLocal)===__doorSource,reports:DATA.items.filter(i=>i.sourceOpeningMapping).map(i=>({id:i.id,type:i.type,floor:i.floor,flipX:i.flipX,flipY:i.flipY,mapping:i.sourceOpeningMapping,current:SourceOpeningReview.currentStatus(i,DATA.walls,DATA.items,getOpeningWallInfo(i))})),notice:document.getElementById('building-registration-notice-detail').textContent}));
 assert.equal(result.source.unchanged,true);assert.ok(result.source.reports.every(r=>Number.isInteger(r.mapping.sourceReference.sourceItemIndex)));const originals=await f.evaluate(()=>__doorBody.sourceLocal.items);for(const r of result.source.reports)assert.equal(r.mapping.sourceReading,JSON.stringify(originals[r.mapping.sourceReference.sourceItemIndex]));assert.equal(result.source.reports.length,11);assert.ok(result.source.reports.every(r=>r.mapping.status==='unresolved'));assert.ok(result.source.reports.filter(r=>r.type==='door-slide-s').every(r=>r.flipX===false));assert.match(result.source.notice,/自動反転しません/);result.checks.push('native import preserves unknown source direction and does not auto-reverse');
 await f.locator('#btn-3di').click();await f.waitForFunction(()=>ren&&!hasPendingGltfModels(),null,{timeout:90000});
 await f.evaluate(()=>{ST.floor=1;onFloorChange(1);document.getElementById('floor-sel').value='1';const it=DATA.items.find(i=>i.sourceOpeningMapping&&i.type==='door-slide-s');ST.selected=it;window.__sourceDoorId=it.id;window.__sourceDoorOriginal=it.sourceOpeningMapping.sourceReading;updateProps();camExt.up.set(0,0,-1);camExt.position.set(3.64,floorTopY(1)+12,2.0475);orbit.target.set(3.64,floorTopY(1),2.0475);orbit.update();invalidate3D();});await page.waitForTimeout(400);await page.screenshot({path:out+'/01-source-unknown-native-settings.png'});
 // Use the existing property buttons, not a duplicate direction form.
 const xButton=f.locator('#props button').filter({hasText:'左右反転'}),yButton=f.locator('#props button').filter({hasText:'上下反転'});await xButton.click();await yButton.click();
 result.editor=await f.evaluate(()=>({status:SourceOpeningReview.currentStatus(ST.selected,DATA.walls,DATA.items,getOpeningWallInfo(ST.selected)),rawRetained:ST.selected.sourceOpeningMapping.sourceReading===__sourceDoorOriginal,settings:ST.selected.sourceOpeningMapping.editorSettings}));assert.equal(result.editor.status.status,'editor-direction-set');assert.equal(result.editor.rawRetained,true);assert.match(result.editor.status.message,/図面との一致は利用者による確認/);await page.screenshot({path:out+'/02-native-direction-settings-and-diagnostics.png'});
 const edit=await f.evaluate(()=>serializeDataSnapshot());await f.evaluate(()=>undoAction());assert.notEqual(await f.evaluate(()=>serializeDataSnapshot()),edit);await f.evaluate(()=>redoAction());assert.equal(await f.evaluate(()=>serializeDataSnapshot()),edit);result.checks.push('existing native settings retain source, Undo/Redo and truthful current diagnostics');
 fs.writeFileSync(out+'/source-applied-plan.json',await f.evaluate(()=>serializeDataSnapshot()));
 // Independent source-axis oracle across handedness, reversed walls and reflection.
 result.matrix=await f.evaluate(async()=>{
  const readings=[],walls=[],cases=[];let index=0;
  for(const type of ['door-swing','door-slide-s'])for(const angle of [0,90])for(const hand of [false,true])for(const side of [false,true])for(const reversed of [false,true])for(const mirror of [false,true]){
   const rot=mirror?(180-angle):angle,a=rot*Math.PI/180,u={x:Math.cos(a),y:Math.sin(a)},center={x:(index%8)*8000+3000,y:Math.floor(index/8)*8000+3000},flipY=mirror?!side:side;
   const reading={type,floor:1,x:center.x,y:center.y,w:780,d:type==='door-swing'?780:150,rot,flipX:hand,flipY};
   const w={id:'matrix-wall-'+index,floor:1,x1:center.x-u.x*2000,y1:center.y-u.y*2000,x2:center.x+u.x*2000,y2:center.y+u.y*2000,thick:120};if(reversed){[w.x1,w.x2]=[w.x2,w.x1];[w.y1,w.y2]=[w.y2,w.y1];}
   readings.push(reading);walls.push(w);cases.push({index,type,angle,hand,side,reversed,mirror,source:reading});index++;
  }
  const sourceSnapshot=JSON.stringify({readings,walls}),native=PlanImport.toAppObjects({walls,rooms:readings.map((r,i)=>({floor:1,x:r.x-2500,y:r.y-2500,w:5000,d:5000,n:'direction case '+i})),items:readings,sourceOpeningReviewRequested:true});await EditorPane.install(native);setView('3d-int');build3D();await new Promise(resolve=>setTimeout(resolve,200));
  const before=serializeDataSnapshot(),norm=poly=>poly.map(p=>[Math.round(p.x*1e5),Math.round(p.y*1e5)]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]),results=[];
  for(const c of cases){const it=DATA.items[c.index],anim=_doorAnims.find(d=>d.it===it);if(!anim)throw Error('Missing actual native door '+c.index);const owner=anim.pivot||anim.slideMesh,mesh=owner.children.find(o=>o.isMesh&&o.geometry.type==='BoxGeometry');if(!mesh)throw Error('Missing panel mesh');const src=c.source,a=src.rot*Math.PI/180,u={x:Math.cos(a),y:Math.sin(a)},n={x:-u.y,y:u.x};
   for(const fraction of [0,.5,1]){if(anim.pivot)anim.pivot.rotation.y=anim.openY*fraction;else anim.slideMesh.position.x=anim.closedX+(anim.openX-anim.closedX)*fraction;anim.grp.updateMatrixWorld(true);const w=mesh.geometry.parameters.width/2,d=mesh.geometry.parameters.depth/2,actual=[[-w,-d],[w,-d],[w,d],[-w,d]].map(q=>{const v=mesh.localToWorld(new THREE.Vector3(q[0],0,q[1]));return {x:v.x/U,y:v.z/U};});
    let cx,cy,ux,uy,nx,ny,width;if(src.type==='door-swing'){const sign=src.flipX?-1:1,t=(src.flipY?-1:1)*Math.PI/2*fraction,hx=src.x-u.x*sign*390,hy=src.y-u.y*sign*390;ux=u.x*Math.cos(t)+n.x*Math.sin(t);uy=u.y*Math.cos(t)+n.y*Math.sin(t);nx=-u.x*Math.sin(t)+n.x*Math.cos(t);ny=-u.y*Math.sin(t)+n.y*Math.cos(t);cx=hx+ux*sign*390;cy=hy+uy*sign*390;width=780;}else{const travel=src.flipX?-810:810,face=src.flipY?86:-86;cx=src.x+u.x*travel*fraction+n.x*face;cy=src.y+u.y*travel*fraction+n.y*face;ux=u.x;uy=u.y;nx=n.x;ny=n.y;width=840;}
    const expected=[[-width/2,-18],[width/2,-18],[width/2,18],[-width/2,18]].map(q=>({x:cx+ux*q[0]+nx*q[1],y:cy+uy*q[0]+ny*q[1]}));if(JSON.stringify(norm(actual))!==JSON.stringify(norm(expected)))throw Error('Source oracle disagrees with actual 3D '+JSON.stringify({c,fraction,actual,expected}));
    const info=getOpeningWallInfo(it),shape=SceneOpeningGeometry.planGeometry(it,info.wall.thick,fraction),rad=info.rot*Math.PI/180,shared=shape.leaf.map(p=>({x:info.x+p.x*Math.cos(rad)-p.y*Math.sin(rad),y:info.y+p.x*Math.sin(rad)+p.y*Math.cos(rad)}));if(JSON.stringify(norm(shared))!==JSON.stringify(norm(actual)))throw Error('2D/3D disagreement');results.push({case:c.index,type:c.type,reversed:c.reversed,mirror:c.mirror,hand:c.hand,side:c.side,fraction,actual,expected});
   }
  }
  return {cases:cases.length,states:results.length,sourceUnchanged:JSON.stringify({readings,walls})===sourceSnapshot,planUnchanged:serializeDataSnapshot()===before,results};
 });assert.equal(result.matrix.cases,64);assert.equal(result.matrix.states,192);assert.equal(result.matrix.sourceUnchanged,true);assert.equal(result.matrix.planUnchanged,true);result.checks.push('64 actual native mesh cases / 192 closed-half-open states match independent source oracle and shared 2D geometry');
 for(const [index,label] of [[0,'swing'],[32,'slide']])for(const fraction of [0,.5,1]){await f.evaluate(({index,fraction})=>{const it=DATA.items[index],anim=_doorAnims.find(d=>d.it===it);if(anim.pivot)anim.pivot.rotation.y=anim.openY*fraction;else anim.slideMesh.position.x=anim.closedX+(anim.openX-anim.closedX)*fraction;ST.selected=it;updateProps();camExt.up.set(0,0,-1);const info=getOpeningWallInfo(it);camExt.position.set(info.x*U,floorTopY(1)+4.5,info.y*U+4);orbit.target.set(info.x*U,floorTopY(1)+.8,info.y*U);orbit.update();invalidate3D();render3DNow();},{index,fraction});await page.waitForTimeout(120);await page.screenshot({path:out+'/03-matrix-'+label+'-'+fraction+'.png'});}
 result.pockets=await f.evaluate(async()=>{
  const walls=[],items=[],rooms=[],specs=[];let index=0;
  for(const dir of [-1,1])for(const reversed of [false,true]){
   const center={x:index*8000+3000,y:3000},host={id:'pocket-host-'+index,floor:1,x1:center.x-2000,y1:center.y,x2:center.x+2000,y2:center.y,thick:120};if(reversed)[host.x1,host.x2]=[host.x2,host.x1];
   const a=center.x+dir*450,b=center.x+dir*1350,lo=Math.min(a,b),hi=Math.max(a,b),spec={id:'pocket-'+index,floor:1,kind:'door-pocket',hostWallId:host.id,center,widthMm:900,travelDirection:{x:dir,y:0},sourceLeaf:{mechanism:'pocket',closedCenter:center,leafWidthMm:900,thicknessMm:36,travelDistanceMm:900,pocketPolygon:[{x:lo,y:center.y-30},{x:hi,y:center.y-30},{x:hi,y:center.y+30},{x:lo,y:center.y+30}]}};
   const compiled=SceneOpeningGeometry.compileOpening(spec,[host],[]);if(!compiled.ok)throw Error(JSON.stringify(compiled.diagnostics));walls.push(host);items.push(compiled.item);rooms.push({id:'pocket-room-'+index,type:'room',floor:1,x:center.x-2500,y:center.y-2500,w:5000,d:5000,n:'synthetic exact cavity',floorRaiseMm:0});specs.push({spec,dir,reversed});index++;
  }
  await EditorPane.install({walls,rooms,items});setView('3d-ext');build3D();const baseline=serializeDataSnapshot(),checks=[];
  for(let i=0;i<items.length;i++){const it=DATA.items[i],anim=_doorAnims.find(d=>d.it===it),mesh=anim.slideMesh.children.find(o=>o.isMesh&&o.geometry.type==='BoxGeometry'),source=specs[i];
   for(const fraction of [0,.5,1]){anim.slideMesh.position.x=anim.closedX+(anim.openX-anim.closedX)*fraction;sc3.updateMatrixWorld(true);const actual=[[-.45,-.018],[.45,-.018],[.45,.018],[-.45,.018]].map(q=>{const v=mesh.localToWorld(new THREE.Vector3(q[0],0,q[1]));return [v.x/U,v.z/U];}),cx=source.spec.center.x+source.dir*900*fraction,cy=source.spec.center.y,expected=[[cx-450,cy-18],[cx+450,cy-18],[cx+450,cy+18],[cx-450,cy+18]],norm=p=>p.map(q=>q.map(n=>Math.round(n*1e5))).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);if(JSON.stringify(norm(actual))!==JSON.stringify(norm(expected)))throw Error('Actual pocket panel mismatch');
    const wallMeshes=[];sc3.traverse(o=>{if(o.isMesh&&o.userData.selectKind==='wall'&&o.userData.selectRef.id===source.spec.hostWallId)wallMeshes.push(o);});
    const point=new THREE.Vector3((source.spec.center.x+source.dir*900)*U,item3DBaseY(it)+.7,cy*U);const distances=[-1,1].map(sign=>{const ray=new THREE.Raycaster(point,new THREE.Vector3(0,0,sign),0,.2),hit=ray.intersectObjects(wallMeshes,false)[0];return hit?hit.distance/U:null;});if(!distances.every(d=>d!==null&&Math.abs(d-30)<.05))throw Error('Actual pocket interior not hollow '+JSON.stringify({source,distances}));checks.push({dir:source.dir,reversed:source.reversed,fraction,actual,expected,innerSkinDistancesMm:distances});
   }
  }
  return {checks,states:checks.length,planUnchanged:serializeDataSnapshot()===baseline,syntheticExactCavity:true};
 });assert.equal(result.pockets.states,12);assert.equal(result.pockets.planUnchanged,true);result.checks.push('actual pocket wall has 60mm internal cavity and both directions fit at 0/0.5/1, including reversed hosts');
 for(const fraction of [0,.5,1]){await f.evaluate(fraction=>{const it=DATA.items[0],anim=_doorAnims.find(d=>d.it===it);anim.slideMesh.position.x=anim.closedX+(anim.openX-anim.closedX)*fraction;ST.selected=it;updateProps();camExt.up.set(0,1,0);camExt.position.set(2.5,3.8,7);orbit.target.set(2.5,.8,3);orbit.update();invalidate3D();render3DNow();},fraction);await page.waitForTimeout(150);await page.screenshot({path:out+'/04-exact-pocket-'+fraction+'.png'});}
 assert.deepEqual(result.errors,[]);assert.deepEqual(result.apiRequests,[]);result.status='pass';
}catch(e){result.failure=e.stack;throw e;}finally{fs.writeFileSync(out+'/results.json',JSON.stringify(result,null,2));await ctx.close();await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
