/* Real-browser acceptance. Run only in a permitted browser environment.
   Requires the app on its own static, non-production localhost origin.
   No browser-security switches, backend requests, AI calls, user data or deployment. */
'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const origin=process.env.WEBCAD_UI_ORIGIN,out=process.env.WEBCAD_UI_QA_OUTPUT||'/tmp/webcad-native-header-qa';
if(!origin||!/^http:\/\/127\.0\.0\.1:\d+$/.test(origin))throw Error('Set WEBCAD_UI_ORIGIN to the permitted dedicated localhost origin');
const handleDialog=d=>d.type()==='confirm'&&d.message()==='現在の未保存の編集を、選んだ間取りJSONへ置き換えますか？'?d.accept():d.dismiss();
async function importAnonymousRoom(frame,id){
 const plan=await frame.evaluate(id=>{const p=JSON.parse(serializeDataSnapshot());p.startMode='blank';p.items=[];p.rooms=[{id,floor:1,x:0,y:0,w:4000,d:3000,n:'Anonymous QA room',use:'living'}];p.walls=[[0,0,4000,0],[4000,0,4000,3000],[4000,3000,0,3000],[0,3000,0,0]].map(([x1,y1,x2,y2],i)=>({id:id+'-wall-'+i,floor:1,x1,y1,x2,y2,thick:120}));return p;},id);
 await frame.locator('#import-file').setInputFiles({name:id+'.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(plan))});await frame.waitForFunction(id=>DATA.rooms.some(r=>r.id===id),id);
}
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.WEBCAD_BROWSER_EXECUTABLE||'/usr/bin/chromium',headless:true,chromiumSandbox:true}),results=[];fs.mkdirSync(out,{recursive:true});
 try{for(const width of [320,390,768,1440]){
  const context=await browser.newContext({viewport:{width,height:960},acceptDownloads:true});await context.route('**/*',r=>{const u=new URL(r.request().url());return u.origin===origin&&!u.pathname.startsWith('/api/')||['data:','blob:'].includes(u.protocol)?r.continue():r.abort();});const page=await context.newPage();page.on('dialog',handleDialog);await page.goto(origin+'/index.html?preset=blank');await page.waitForFunction(()=>window.PlanLibrary&&PlanLibrary.panes.size&&[...PlanLibrary.panes.values()].every(p=>p.ready));await page.evaluate(()=>PlanLibrary.ready);await page.locator('#app-loading').waitFor({state:'hidden'});await page.locator('#preset-choice-modal').waitFor({state:'hidden'});await page.evaluate(()=>history.replaceState(null,'','/index.html'));await importAnonymousRoom(page,'anonymous-ui-room-a');
  const structure=await page.evaluate(()=>({first:document.querySelector('#toolbar').firstElementChild.className,entries:document.querySelectorAll('#compare-launch').length,position:getComputedStyle(document.querySelector('#compare-launch')).position,group:document.querySelector('[data-library-current]').closest('.library-current').parentNode.id==='toolbar',identityOrder:document.querySelector('#toolbar>.brand-mark').nextElementSibling.classList.contains('library-current'),compareOrder:document.querySelector('#toolbar>.library-current').nextElementSibling.id==='compare-launch',prototype:/改善試作|TPS試作|案を比較\s*試作/.test(document.body.innerText),visibleViews:['btn-2d','btn-3de','btn-3di'].map(id=>{const b=document.getElementById(id).getBoundingClientRect(),a=document.querySelector('.toolbar-actions').getBoundingClientRect();return b.x>=a.x&&b.right<=a.right&&b.height>=40;})}));assert.match(structure.first,/brand-mark/);assert.equal(structure.entries,1);assert.equal(structure.position,'static');assert.equal(structure.group,true);assert.equal(structure.identityOrder,true);assert.equal(structure.compareOrder,true);assert.equal(structure.prototype,false);if(width<=768)assert.deepEqual(structure.visibleViews,[true,true,true]);
  // Native view controls retain their real onclick paths. No AI/outputs are run.
  for(const [id,view] of [['btn-2d','2d'],['btn-3de','3d-ext'],['btn-3di','3d-int'],['btn-3dw','3d-walk']]){await page.locator('#'+id).click();await page.waitForFunction(v=>ST.view===v,view);await page.locator('#app-loading').waitFor({state:'hidden'});}
  for(const mode of ['fps','tps']){
   if(mode==='tps')await page.locator('#walk-tps-mode').click();await page.locator('#compare-launch').scrollIntoViewIfNeeded();const geometry=await page.evaluate(()=>{const a=document.getElementById('compare-launch').getBoundingClientRect(),b=document.getElementById('walk-dpad').getBoundingClientRect();return {overlap:a.x<b.right&&a.right>b.x&&a.y<b.bottom&&a.bottom>b.y,text:document.getElementById('walk-tps-mode').textContent};});assert.equal(geometry.overlap,false);assert.doesNotMatch(geometry.text,/試作/);await page.screenshot({path:path.join(out,width+'-'+mode+'.png')});
  }
  await page.locator('#btn-2d').click();await page.locator('#save-btn').click();await page.waitForFunction(()=>!DIRTY&&!SHARED.saveBusy);const savedId=await page.evaluate(()=>__editorPlanId);await page.reload();await page.waitForFunction(id=>window.PlanLibrary&&__editorPlanId===id&&[...PlanLibrary.panes.values()].every(p=>p.ready),savedId);assert.equal(await page.locator('#toolbar>.brand-mark').count(),1);assert.equal(await page.locator('.offline-preview-banner').count(),0);
  // Existing dialog entry/cancel cycles; no generation, print, share or network submit.
  for(const [entry,modal,close] of [['plan-import-toolbar-btn','plan-import-modal','closePlanImport()'],['unity-render-toolbar-btn','unity-render-modal','closeUnityRenderModal()'],['video-render-toolbar-btn','video-render-modal','closeVideoRenderModal()'],['jis-drawing-toolbar-btn','jis-drawing-overlay','closeJisDrawingDialog()']]){
   const control=page.locator('#'+entry);if(!await control.isVisible())continue;for(let i=0;i<2;i++){await control.click();await page.locator('#'+modal).waitFor({state:'visible'});await page.locator('#'+modal+' [onclick="'+close+'"]').first().click();await page.locator('#'+modal).waitFor({state:'hidden'});}
  }
  if(width===1440){
   for(const action of ['history','duplicate']){await page.locator('[data-library-action="'+action+'"]').click();await page.locator('.library-dialog').waitFor({state:'visible'});await page.keyboard.press('Escape');await page.locator('.library-dialog').waitFor({state:'hidden'});}
   const download=page.waitForEvent('download');await page.locator('#toolbar button[onclick="exportPlan()"] ').click();const json=JSON.parse(await fs.promises.readFile(await(await download).path(),'utf8'));assert.ok(Array.isArray(json.walls)&&Array.isArray(json.items));
   const peer=await page.evaluate(async()=>{const id='anonymous-header-peer';await PlanLibrary.repo.duplicate(__editorPlanId,id,'Anonymous header comparison peer','anonymous-header-peer-copy');return id;});await page.locator('#compare-launch').click();await page.locator('.library-dialog').waitFor({state:'visible'});const popup=context.waitForEvent('page');await page.locator('[data-library-open-plan="'+peer+'"]').click();const compare=await popup;compare.on('dialog',handleDialog);await compare.waitForLoadState();await compare.waitForFunction(()=>window.PlanLibrary&&[...PlanLibrary.panes.values()].every(p=>p.ready)&&PlanLibrary.panes.size===2);
   assert.equal(await compare.locator('.parallel-heading .brand-mark').count(),1);assert.equal(await compare.locator('.parallel-controls [data-library-action]').count(),0);assert.equal(await compare.locator('.library-pane iframe').count(),2);
   await compare.locator('[data-parallel-sync]').uncheck();await compare.locator('[data-parallel-align]').click();
   for(const iframe of await compare.locator('.library-pane iframe').elementHandles()){
    const frame=await iframe.contentFrame();await importAnonymousRoom(frame,'anonymous-pane-room-'+(await frame.evaluate(()=>__editorPlanId)));assert.equal(await frame.locator('#toolbar>.brand-mark').isVisible(),false);assert.equal(await frame.locator('#compare-launch').isVisible(),false);assert.equal(await frame.locator('[data-library-current]').count(),1);await frame.locator('#btn-3dw').click();await frame.waitForFunction(()=>ST.view==='3d-walk');assert.doesNotMatch(await frame.locator('#walk-tps-mode').innerText(),/試作/);await frame.locator('#btn-2d').click();await frame.locator('#save-btn').click();await frame.waitForFunction(()=>!DIRTY&&!SHARED.saveBusy);
   }
   await compare.screenshot({path:path.join(out,'comparison-two-native-panes.png')});await compare.locator('[data-library-layout="1"]').click();await compare.waitForFunction(()=>PlanLibrary.panes.size===1);await compare.locator('[data-library-layout="2"]').click();await compare.waitForFunction(()=>PlanLibrary.panes.size===2&&[...PlanLibrary.panes.values()].every(p=>p.ready));await compare.close();
  }
  results.push({width,structure,viewCycles:true,walkModes:true,saveReload:true,comparisonPaneMatrix:width===1440});await context.close();
 }
 }finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({results,realBrowser:true,syntheticDataOnly:true},null,2));await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
