const {chromium}=require('/tmp/webcad-browser-check/node_modules/playwright'),fs=require('node:fs'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const origin='http://127.0.0.1:65236',out='docs/quality-review/native-source-cabinet',asset='im0261-Cabinet-MEGA_PACK_CABINET-cabinet-354290_frame_walnut_brown';
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal']}),ctx=await b.newContext({viewport:{width:1700,height:1100}}),page=await ctx.newPage(),result={errors:[],apiRequests:[],userTabObserved:false,checks:[]};page.on('pageerror',e=>result.errors.push(e.stack));page.on('dialog',d=>d.accept());await ctx.route('**/*',r=>{const u=new URL(r.request().url());if(u.pathname.startsWith('/api/'))result.apiRequests.push(u.href);return u.origin===origin&&!u.pathname.startsWith('/api/')||['data:','blob:'].includes(u.protocol)?r.continue():r.abort();});try{
await page.goto(origin+'/?planLibrary=1');await page.waitForFunction(()=>!!window.PlanLibrary);await page.locator('[data-library-new]').click();await page.locator('[data-library-sample]').click();await page.waitForFunction(()=>[...PlanLibrary.panes.values()].some(p=>p.ready));const f=await(await page.locator('.library-pane iframe').elementHandle()).contentFrame();await f.waitForFunction(()=>document.querySelector('[data-source-object="marks:23"]'));
result.before=await f.evaluate(()=>({source:JSON.stringify(PlanImport.state?.result?.sourceLocal),count:DATA.items.length}));
for(const floor of [1,2,3]){const g=f.locator('details[data-building-floor="'+floor+'"]');await g.evaluate(e=>e.open=true);await g.locator('[data-building-identity]').check();await g.locator('[data-building-identity-evidence]').fill('Public PDF floor title inspected; no new AI');await g.locator('[data-building-confirm]').click();}
await f.locator('[data-building-partial]').check();await f.locator('[data-source-object-rotation="marks:23"]').fill('180');await f.locator('[data-source-object="marks:23"]').selectOption(asset);await page.screenshot({path:out+'/01-existing-import-review.png'});await f.locator('#plan-import-apply').click();await f.waitForFunction(asset=>DATA.items.some(i=>i.type===asset),asset);await f.evaluate(()=>closePlanImport());
result.sourceUnchanged=await f.evaluate(()=>JSON.stringify(DATA.sceneReconstructionReports.find(r=>r.kind==='building-registration').sourceLocal))===result.before.source;assert.equal(result.sourceUnchanged,true);result.applied=await f.evaluate(asset=>{const it=DATA.items.find(i=>i.type===asset);window.__cabId=it.id;window.__cabSource=it.sourceObjectMapping.sourceSnapshot;window.__cabApplied=serializeDataSnapshot();return {item:it,sourceOriginal:DATA.sceneReconstructionReports.find(r=>r.kind==='building-registration').sourceLocal.marks[23],count:DATA.items.filter(i=>i.type===asset).length,sourceStatus:SourceObjectMapping.currentStatus(it)};},asset);assert.equal(result.applied.count,1);assert.deepEqual([result.applied.item.floor,result.applied.item.x+740,result.applied.item.y+235,result.applied.item.w,result.applied.item.d,result.applied.item.rot],[2,3850,2910,1480,470,180]);assert.equal(result.applied.sourceStatus.edited,false);assert.equal(result.applied.item.sourceObjectMapping.sourceSnapshot,JSON.stringify(result.applied.sourceOriginal));
await f.evaluate(()=>undoAction());assert.equal(await f.evaluate(()=>DATA.items.length),0);await f.evaluate(()=>redoAction());assert.equal(await f.evaluate(()=>serializeDataSnapshot()),await f.evaluate(()=>__cabApplied));result.checks.push('real native partial import / exactly one cabinet / original source / Undo and Redo');
await f.evaluate(()=>{ST.floor=2;onFloorChange(2);document.getElementById('floor-sel').value='2';ST.selected=DATA.items.find(i=>i.id===__cabId);updateProps();setView('3d-int');});await f.waitForFunction(()=>ren&&!hasPendingGltfModels(),null,{timeout:90000});await f.evaluate(()=>build3D());
result.geometry=await f.evaluate(()=>{const it=DATA.items.find(i=>i.id===__cabId),owner=sc3.children.find(o=>{let found=false;o.traverse(n=>{if(n.userData.selectRef===it||n.userData.selectRef?.id===it.id)found=true;});return found;});if(!owner)throw Error('No native selected model '+JSON.stringify({it,selected:ST.selected?.id,view:ST.view,floor:ST.floor,cache:Object.keys(_modelCache),children:sc3.children.map(o=>({type:o.type,refs:(()=>{const refs=[];o.traverse(n=>{if(n.userData.selectRef)refs.push(n.userData.selectRef.id);if(n.userData.instanceRefs)refs.push(n.userData.instanceRefs.map(i=>i.id));});return refs;})()}))}));const box=new THREE.Box3().setFromObject(owner),size=box.getSize(new THREE.Vector3()),model=FMP_ITEMS[it.type];return {mm:[size.x/U,size.y/U,size.z/U],bottom:box.min.y/U,base:item3DBaseY(it)/U,model:model.model,materialColors:(()=>{const colors=[];owner.traverse(o=>{if(o.isMesh){const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>colors.push({name:m.name,color:m.color?.getHexString(),map:!!m.map}));}});return colors;})()};});assert.ok(Math.abs(result.geometry.mm[0]-1480)<.1);assert.ok(Math.abs(result.geometry.mm[1]-600)<.1);assert.ok(Math.abs(result.geometry.mm[2]-470)<.1);assert.ok(Math.abs(result.geometry.bottom-result.geometry.base)<.1);result.assetSha256=crypto.createHash('sha256').update(fs.readFileSync(result.geometry.model)).digest('hex');
for(const side of [1,-1]){await f.evaluate(side=>{const it=DATA.items.find(i=>i.id===__cabId),x=(it.x+it.w/2)*U,z=(it.y+it.d/2)*U,y=item3DBaseY(it);orbit.maxDistance=100;orbit.minDistance=.01;orbit.minPolarAngle=0;orbit.maxPolarAngle=Math.PI;camExt.up.set(0,1,0);camExt.position.set(x+1.6,y+1.5,z+side*2);orbit.target.set(x,y+.3,z);orbit.update();invalidate3D();render3DNow();},side);await page.waitForTimeout(250);await page.screenshot({path:out+'/02-native-cabinet-side-'+side+'.png'});}result.checks.push('actual selected GLB is 1480 x 470 x 600mm with catalogue materials and floor placement');
await f.evaluate(()=>{ST.selected=DATA.items.find(i=>i.id===__cabId);updateSelectedProp('rot',90);});assert.equal(await f.evaluate(()=>SourceObjectMapping.currentStatus(DATA.items.find(i=>i.id===__cabId)).edited),true);assert.equal(await f.locator('[data-source-object-status]').getAttribute('data-source-object-status'),'edited-or-unverified');await f.evaluate(()=>undoAction());assert.equal(await f.evaluate(()=>SourceObjectMapping.currentStatus(DATA.items.find(i=>i.id===__cabId)).edited),false);
await f.locator('#save-btn').click();await page.waitForFunction(()=>[...PlanLibrary.plans.values()].some(r=>!r.state.dirty));result.saved=await page.evaluate(async()=>{const p=[...PlanLibrary.panes.values()][0],r=await PlanLibrary.repo.read(p.planId);return r;});assert.equal(result.saved.payload.items.filter(i=>i.type===asset).length,1);assert.equal(result.saved.payload.items.find(i=>i.type===asset).sourceObjectMapping.sourceSnapshot,result.applied.item.sourceObjectMapping.sourceSnapshot);result.checks.push('native geometry edit invalidates source display status; Undo restores it; native Save returns');assert.deepEqual(result.errors,[]);assert.deepEqual(result.apiRequests,[]);result.status='pass';
}finally{fs.writeFileSync(out+'/results.json',JSON.stringify(result,null,2));await ctx.close();await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
