'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/tmp/webcad-browser-check/node_modules/playwright');
const url=process.env.APP_URL;if(!/^http:\/\/(127\.0\.0\.1|localhost):\d+\/$/.test(url||''))throw Error('offline localhost APP_URL required');
const dir=path.resolve('docs/quality-review/parallel-heavy'),plan=JSON.parse(fs.readFileSync('tools/tests/fixtures/public-native/parallel-heavy.json'));
const result={fixture:{walls:plan.walls.length,rooms:plan.rooms.length,items:plan.items.length,floors:[...new Set(plan.rooms.map(r=>r.floor))],syntheticStressFurniture:0},samples:[],errors:[],blocked:[]};
const pct=(v,p)=>[...v].sort((a,b)=>a-b)[Math.floor((v.length-1)*p)];
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal']});const ctx=await browser.newContext({viewport:{width:1800,height:1100}});await ctx.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===new URL(url).origin&&!u.pathname.startsWith('/api/'))return r.continue();if(['data:','blob:'].includes(u.protocol))return r.continue();result.blocked.push(u.href);return r.abort();});const page=await ctx.newPage();page.on('pageerror',e=>result.errors.push(e.message));page.on('dialog',d=>d.accept());
const ids=()=>page.evaluate(()=>[...ParallelEditors.panes.keys()]);
async function ready(id){await page.waitForFunction(id=>!!ParallelEditors.panes.get(id)?.frame.contentWindow?.EditorPane,id);await page.evaluate(async id=>{await ParallelEditors.panes.get(id).frame.contentWindow.EditorPane.ready;},id);}
async function measure(label){await page.evaluate(()=>{const p=ParallelEditors.panes.values().next().value,v=p.frame.contentWindow.EditorPane.view();v.camera={pos:[20,18,24],target:[3.6,4,3.6],fov:50};p.frame.contentWindow.EditorPane.applyView(v);ParallelEditors.changed(p.id);});await page.waitForTimeout(500);const ps=await ids(),times=[];for(let i=0;i<40;i++)times.push(await page.evaluate(async ({id,i})=>{const api=ParallelEditors.panes.get(id).frame.contentWindow.EditorPane,v=api.view();if(v.camera)v.camera.pos[0]+=i%2?.04:-.04;const start=performance.now();api.applyView(v);ParallelEditors.changed(id);await new Promise(requestAnimationFrame);return performance.now()-start;},{id:ps[0],i}));const before=await page.evaluate(()=>[...ParallelEditors.panes.values()].map(p=>p.frame.contentWindow.EditorPane.metrics()));await page.waitForTimeout(2200);const after=await page.evaluate(()=>[...ParallelEditors.panes.values()].map(p=>p.frame.contentWindow.EditorPane.metrics()));result.samples.push({label,retained:await page.evaluate(()=>ParallelEditors.plans.size),active:ps.length,responseToNextRAFMs:{p50:pct(times,.5),p95:pct(times,.95),samples:times.length},idleRenderDelta:after.map((m,i)=>m.renderCalls-before[i].renderCalls),metrics:after,views:await page.evaluate(()=>[...ParallelEditors.panes.values()].map(p=>p.frame.contentWindow.EditorPane.view())),memory:await page.evaluate(()=>performance.memory?{used:performance.memory.usedJSHeapSize,total:performance.memory.totalJSHeapSize}:null)});assert.ok(after.every(m=>m.quality.ao&&m.quality.shadows));assert.ok(after.every((m,i)=>m.renderCalls===before[i].renderCalls),'idle panes should stop rendering');}
try{await page.goto(url+'?preset=blank');await page.waitForSelector('#app-loading',{state:'hidden',timeout:90000});const original=await page.evaluate(()=>serializeDataSnapshot());await page.evaluate(()=>{ParallelEditors.open();ParallelEditors.changed([...ParallelEditors.panes.keys()][0]);ParallelEditors.align();ParallelEditors.close();});await page.waitForTimeout(500);assert.equal(await page.locator('iframe').count(),0,'close during initial load cancels later mounts');result.loadingCloseSafe=true;await page.evaluate(async p=>{ParallelEditors.open();if(ParallelEditors.plans.size===1)await ParallelEditors.addPlan(p,'Startup readiness');},plan);await page.waitForFunction(()=>ParallelEditors.panes.size===2&&[...ParallelEditors.panes.values()].every(p=>p.frame.contentWindow?.EditorPane));for(const id of await ids())await ready(id);for(const id of await page.evaluate(()=>[...ParallelEditors.plans.keys()]))await page.evaluate(id=>ParallelEditors.remove(id),id);
const aPlan=await page.evaluate(p=>ParallelEditors.addPlan(p,'Native three-floor A'),plan);const a=(await ids())[0];await ready(a);await page.evaluate(id=>{const w=ParallelEditors.panes.get(id).frame.contentWindow;w.setView('3d-ext');const v=w.EditorPane.view();v.camera={pos:[17,16,20],target:[3,2,3],fov:50};w.EditorPane.applyView(v);},a);await page.waitForFunction(id=>{const w=ParallelEditors.panes.get(id).frame.contentWindow;return w.ren&&!w.hasPendingGltfModels();},a,{timeout:90000});await page.waitForTimeout(2000);await measure('one active / one retained native three-floor');
await page.evaluate(p=>ParallelEditors.addPlan(p,'Native B'),plan);for(const id of await ids())await ready(id);await page.evaluate(()=>{for(const p of ParallelEditors.panes.values())p.frame.contentWindow.setView('3d-ext');ParallelEditors.align();});await page.waitForFunction(()=>[...ParallelEditors.panes.values()].every(p=>!p.frame.contentWindow.hasPendingGltfModels()),null,{timeout:90000});await page.waitForTimeout(2000);await measure('two active / two retained native three-floor');
await page.evaluate(async p=>{await ParallelEditors.addPlan(p,'Native C');await ParallelEditors.addPlan(p,'Native D');},plan);await measure('two active / four retained native three-floor');assert.equal(await page.locator('iframe').count(),2);await page.screenshot({path:path.join(dir,'native-two-editors-3d.png')});
const stateBefore=await page.evaluate(id=>ParallelEditors.panes.get(id).frame.contentWindow.serializeDataSnapshot(),a);const c=await page.evaluate(()=>[...ParallelEditors.plans.values()].find(p=>p.name==='Native C').id);const started=Date.now();await page.evaluate(({a,c})=>ParallelEditors.select(a,c),{a,c});await page.evaluate(({a,aPlan})=>ParallelEditors.select(a,aPlan),{a,aPlan});result.switchRoundTripMs=Date.now()-started;assert.equal(await page.evaluate(id=>ParallelEditors.panes.get(id).frame.contentWindow.serializeDataSnapshot(),a),stateBefore);assert.equal(await page.evaluate(()=>serializeDataSnapshot()),original);await page.evaluate(()=>ParallelEditors.close());await page.waitForFunction(()=>ParallelEditors.modelPool.cache.size===0&&ParallelEditors.modelPool.resources.size===0);assert.equal(await page.locator('iframe').count(),0);result.released=true;assert.deepEqual(result.errors,[]);result.status='pass';console.log(JSON.stringify(result));}catch(e){result.status='fail';result.failure=e.stack;throw e;}finally{fs.writeFileSync(path.join(dir,'results.json'),JSON.stringify(result,null,2));await ctx.close();await browser.close();}})();
