const {chromium}=require('/tmp/webcad-browser-check/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal']});const ctx=await browser.newContext(),p=await ctx.newPage();const errors=[],checks=[];let accept=false,confirms=0;p.on('pageerror',e=>errors.push(e.message));p.on('dialog',async d=>{if(d.type()==='confirm')confirms++;accept?await d.accept():await d.dismiss();});await ctx.route('**/*',r=>{const u=new URL(r.request().url());return u.origin==='http://127.0.0.1:65235'||['data:','blob:'].includes(u.protocol)?r.continue():r.abort();});try{await p.goto('http://127.0.0.1:65235/?preset=blank');await p.waitForSelector('#app-loading',{state:'hidden',timeout:90000});if(await p.locator('#preset-choice-modal').isVisible())await p.locator('[onclick="chooseBlankPlan()"]').click();await p.locator('#compare-launch').click();await p.waitForFunction(()=>ParallelEditors.panes.size===2&&[...ParallelEditors.panes.values()].every(p=>p.ready));
const snap=()=>p.evaluate(async()=>({plans:[...ParallelEditors.plans.values()],panes:[...ParallelEditors.panes.values()].map(p=>({id:p.id,planId:p.planId,state:p.frame.contentWindow.EditorPane.state()})),active:ParallelEditors.activeId,saved:await new Promise((resolve,reject)=>{const q=indexedDB.open('webcad-parallel-workspace');q.onsuccess=()=>{const db=q.result,t=db.transaction('workspaces'),r=t.objectStore('workspaces').get('local');r.onsuccess=()=>{resolve(r.result);db.close();};r.onerror=()=>reject(r.error);};q.onerror=()=>reject(q.error);})}));
await p.evaluate(()=>ParallelEditors.saveWorkspace());
const paneId=await p.evaluate(()=>[...ParallelEditors.panes.keys()][0]);const frame=await(await p.locator('.parallel-pane iframe').first().elementHandle()).contentFrame();
await frame.evaluate(()=>{window._qaReads=[];window.FileReader=class{readAsText(file){file.text().then(text=>window._qaReads.push(()=>this.onload({target:{result:text}})));}};});
for(const operation of ['switch','close']){const before=await frame.evaluate(()=>serializeDataSnapshot());const chooser=p.waitForEvent('filechooser');await frame.locator('#toolbar button[onclick="document.getElementById(\'import-file\').click()"] ').click();await(await chooser).setFiles([{name:'delayed.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({walls:[],rooms:[],items:[{id:'late',type:'original-sofa',floor:1,x:9999,y:0,w:1000,d:800}]}))}]);await frame.waitForFunction(()=>_qaReads.length>0);
if(operation==='switch'){const target=await p.evaluate(()=>ParallelEditors.addPlan({walls:[],rooms:[],items:[]},'switch target'));await p.locator('.parallel-pane header select').first().selectOption(target);await p.waitForFunction(()=>[...ParallelEditors.panes.values()].every(p=>p.ready));const switched=await frame.evaluate(()=>serializeDataSnapshot());await frame.evaluate(()=>_qaReads.shift()());assert.equal(await frame.evaluate(()=>serializeDataSnapshot()),switched);checks.push('real JSON picker delayed read cannot overwrite switched plan');}
else{await frame.evaluate(()=>{parent._qaClosedWindow=window;parent._qaFinishRead=_qaReads.shift();});await p.locator('[data-parallel-close]').click();await p.evaluate(()=>_qaFinishRead());assert.equal(await p.evaluate(()=>_qaClosedWindow.serializeDataSnapshot()),before);await p.locator('#compare-launch').click();await p.waitForFunction(()=>ParallelEditors.panes.size===2&&[...ParallelEditors.panes.values()].every(p=>p.ready));checks.push('real JSON picker delayed read cannot apply after close');}}
for(const hidden of [true,false]){const id=await p.evaluate(async hidden=>{const api=ParallelEditors,pane=[...api.panes.values()][0],id=pane.planId,editor=pane.frame.contentWindow;editor.HISTORY.push(editor.serializeDataSnapshot());editor.DATA.items.push({id:'remove-qa-'+hidden,type:'original-sofa',floor:1,x:123,y:456,w:1800,d:800,rot:0});editor.DIRTY=true;if(hidden){const other=await api.addPlan({walls:[],rooms:[],items:[]},'hidden replacement');await api.select(pane.id,other);}return id;},hidden);const before=await snap(),n=confirms;accept=false;if(hidden)await p.evaluate(id=>ParallelEditors.remove(id),id);else await p.locator('.parallel-pane [data-parallel-pane-remove]').first().click();if(!hidden)await p.locator('[data-parallel-status]').filter({hasText:'取り消しました'}).waitFor();assert.equal(confirms,n+1);assert.deepEqual(await snap(),before);checks.push((hidden?'hidden':'mounted')+' dirty cancel preserves plans, histories, active pane and checkpoint');accept=true;if(hidden)await p.evaluate(id=>ParallelEditors.remove(id),id);else await p.locator('.parallel-pane [data-parallel-pane-remove]').first().click();await p.waitForFunction(id=>!ParallelEditors.plans.has(id)&&[...ParallelEditors.panes.values()].every(p=>p.ready),id);assert.equal(confirms,n+2);assert.deepEqual((await snap()).saved,before.saved);checks.push((hidden?'hidden':'mounted')+' confirmed removal leaves saved checkpoint intact');}
assert.deepEqual(errors,[]);fs.mkdirSync('docs/quality-review/parallel-remove',{recursive:true});fs.writeFileSync('docs/quality-review/parallel-remove/results.json',JSON.stringify({status:'pass',checks,confirms,errors,userTabObserved:false},null,2));console.log(JSON.stringify({checks,confirms,errors}));}finally{await ctx.close();await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
