'use strict';
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const origin=process.env.APP_URL||'http://127.0.0.1:65331',out=process.env.TEST_OUTPUT||'/tmp/parallel-view-preferences';fs.mkdirSync(out,{recursive:true});
const fixture=(id,north)=>({walls:[{id:id+'-wall',floor:1,x1:0,y1:0,x2:4000,y2:0,thick:120}],rooms:[{id:id+'-room',floor:1,x:0,y:0,w:4000,d:3000,n:id}],items:[],northDeg:north,autoRoomLights:false,startMode:'blank'});
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']}),context=await browser.newContext({viewport:{width:1700,height:1100}}),page=await context.newPage(),result={checks:[],errors:[],apiRequests:[],syntheticOnly:true};context.setDefaultTimeout(30000);page.on('pageerror',e=>result.errors.push(e.message));await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.pathname.startsWith('/api/'))result.apiRequests.push(u.href);return u.origin===origin&&!u.pathname.startsWith('/api/')||['data:','blob:'].includes(u.protocol)?route.continue():route.abort();});
try{
 await page.goto(origin+'/index.html?planLibrary=1');await page.waitForFunction(()=>window.PlanLibrary);await page.evaluate(async plans=>{for(const [id,payload]of plans)await PlanLibrary.repo.save({planId:id,name:id,operationId:'seed-'+id,baseRevisionId:null,baseGeneration:0,payload});await PlanLibrary.openPlan('view-A');await PlanLibrary.openPlan('view-C');PlanLibrary.setSync(false);PlanLibrary.changed([...PlanLibrary.panes.values()][0].id);await PlanLibrary.layout(1);await PlanLibrary.openPlan('view-B');},[['view-A',fixture('A',45)],['view-B',fixture('B',180)],['view-C',fixture('C',270)]]);
 const paneIds=await page.evaluate(()=>[...PlanLibrary.panes.values()].map(p=>p.id));let frames=await Promise.all((await page.locator('.library-pane iframe').elementHandles()).map(h=>h.contentFrame()));let a=frames[0],b=frames[1];
 for(const f of frames){await f.locator('#btn-3di').click();await f.waitForFunction(()=>ren&&orbit&&ST.view==='3d-int'&&threeModulesReady);await f.locator('#app-loading').waitFor({state:'hidden'});}
 await a.evaluate(()=>{window.expectedFloor={pos:camExt.position.toArray(),target:orbit.target.toArray(),min:orbit.minPolarAngle,max:orbit.maxPolarAngle};});
 await a.locator('#surface-sel').selectOption('ceiling');await a.locator('button[onclick="toggleGrid()"]').click();await a.locator('button[onclick="toggleDim()"]').click();await a.locator('#snap-sel').selectOption('455');
 await a.evaluate(()=>{queueSunHour(7);flushSunHour();updateSunSim('season','winter');updateAtmosphere('haze',.8);flushSunHour();updateLightSetting('room',.9);document.getElementById('sun-hour').dispatchEvent(new Event('input',{bubbles:true}));});
 await page.waitForTimeout(400);const initialA=await a.evaluate(()=>EditorPane.state()),initialB=await b.evaluate(()=>EditorPane.state());assert.equal(initialA.dirty,false);assert.equal(initialB.dirty,false);
 assert.equal(initialA.view.surface.ceilingView,true);assert.equal(initialA.view.preferences.lighting.hour,7);assert.equal(initialB.view.preferences.lighting.hour,13);assert.equal(initialA.plan.northDeg,45);assert.equal(initialB.plan.northDeg,180);
 const persisted=await page.evaluate(()=>PlanLibrary.repo.get('views',PlanLibrary.session));assert.equal(persisted.cameras['view-A'].preferences.snap,455);assert.equal(persisted.cameras['view-A'].preferences.lighting.hour,7);result.checks.push('Option-only native controls persist A view without dirty/history changes or affecting B');
 await page.evaluate(id=>PlanLibrary.switchPlan(id,'view-C'),paneIds[0]);assert.equal(await a.evaluate(()=>ST.ceilingView),false);assert.equal(await a.evaluate(()=>ST.snap),10);assert.equal(await a.evaluate(()=>LIGHT_SETTINGS.hour),13);assert.equal(await a.evaluate(()=>DATA.northDeg),270);
 await page.evaluate(id=>PlanLibrary.switchPlan(id,'view-A'),paneIds[0]);const restoredA=await a.evaluate(()=>EditorPane.state());assert.deepEqual(restoredA.view,initialA.view);assert.deepEqual(await b.evaluate(()=>EditorPane.state()),initialB);result.checks.push('A→C→A restores ceiling, upward camera, grid/dim/snap/lighting; B stays unchanged');
 await a.locator('#surface-sel').selectOption('floor');const floor=await a.evaluate(()=>({pos:camExt.position.toArray(),target:orbit.target.toArray(),min:orbit.minPolarAngle,max:orbit.maxPolarAngle}));assert.deepEqual(floor,initialA.view.surface.floorCamera);await a.locator('#surface-sel').selectOption('ceiling');
 const failed=await a.evaluate(async()=>{const before=EditorPane.state(),data=DATA,privateBefore=CeilingDesigner.captureViewContext(),old=rebuild3D;let fail=true;rebuild3D=function(){if(fail){fail=false;throw Error('synthetic renderer failure');}return old.apply(this,arguments);};let message;try{await EditorPane.install({walls:[],rooms:[],items:[],startMode:'blank'},{view:{view:'3d-int',floor:1}});}catch(error){message=error.message;}finally{rebuild3D=old;}return {before,after:EditorPane.state(),sameData:DATA===data,privateBefore,privateAfter:CeilingDesigner.captureViewContext(),message};});assert.equal(failed.sameData,true);assert.match(failed.message,/synthetic renderer/);assert.deepEqual(failed.after,failed.before);assert.deepEqual(failed.privateAfter,failed.privateBefore);result.checks.push('Failed native rebuild restores DATA, history, preferences, public surface and controller private floor camera/limits');
 // One-shot alignment and continuous synchronization retain target conditions.
 await page.evaluate(ids=>{const a=PlanLibrary.panes.get(ids[0]),w=a.frame.contentWindow;w.ST.panX+=23;PlanLibrary.changed(a.id);PlanLibrary.align();},paneIds);const beforeSyncB=await b.evaluate(()=>EditorPane.state());await page.locator('[data-parallel-align]').click();assert.equal(await page.locator('[data-parallel-sync]').isChecked(),false);const afterAlignB=await b.evaluate(()=>EditorPane.state());assert.deepEqual(afterAlignB.view.preferences,initialB.view.preferences);assert.deepEqual(afterAlignB.view.surface,initialB.view.surface);assert.equal(afterAlignB.plan.northDeg,180);assert.equal(afterAlignB.plan.autoRoomLights,false);
 await page.locator('[data-parallel-sync]').check();const dataB=await b.evaluate(()=>JSON.stringify(DATA));await a.evaluate(()=>{ST.panX+=41;document.dispatchEvent(new Event('wheel'));});await page.waitForTimeout(400);assert.equal(await b.evaluate(()=>ST.panX),await a.evaluate(()=>ST.panX));assert.equal(await b.evaluate(()=>JSON.stringify(DATA)),dataB);assert.equal(await b.evaluate(()=>LIGHT_SETTINGS.hour),13);const panB=await b.evaluate(()=>ST.panX);await a.evaluate(()=>{queueSunHour(17);flushSunHour();document.getElementById('sun-hour').dispatchEvent(new Event('input',{bubbles:true}));});await page.waitForTimeout(400);assert.equal(await b.evaluate(()=>ST.panX),panB);assert.equal(await b.evaluate(()=>LIGHT_SETTINGS.hour),13);result.checks.push('One-shot leaves sync OFF; continuous camera changes copy only camera/2D; lighting changes never propagate');await page.locator('[data-parallel-sync]').uncheck();
 const beforeHide=await a.evaluate(()=>EditorPane.view());await page.evaluate(id=>PlanLibrary.changed(id),paneIds[0]);await page.locator('[data-library-layout="1"]').click();await page.waitForFunction(()=>PlanLibrary.panes.size===1);await page.locator('[data-library-layout="2"]').click();await page.waitForFunction(()=>PlanLibrary.panes.size===2&&[...PlanLibrary.panes.values()].every(p=>p.ready));assert.deepEqual(await a.evaluate(()=>EditorPane.view()),beforeHide);await page.evaluate(async()=>{const c=[...PlanLibrary.panes.values()].find(p=>p.planId==='view-C');if(c)await PlanLibrary.closePlan(c.id);if(![...PlanLibrary.panes.values()].some(p=>p.planId==='view-B'))await PlanLibrary.openPlan('view-B');});let reopenedB=await page.evaluate(()=>[...PlanLibrary.panes.values()].find(p=>p.planId==='view-B').frame.contentWindow.EditorPane.view());assert.deepEqual(reopenedB.preferences,initialB.view.preferences);result.checks.push('1→2 layout remount preserves hidden plan runtime view');
 await page.evaluate(id=>PlanLibrary.closePlan(id),paneIds[0]);await page.evaluate(()=>PlanLibrary.openPlan('view-A'));await page.waitForFunction(()=>[...PlanLibrary.panes.values()].find(p=>p.planId==='view-A')?.ready);const reopenedA=await page.evaluate(()=>[...PlanLibrary.panes.values()].find(p=>p.planId==='view-A').frame.contentWindow.EditorPane.view());assert.deepEqual(reopenedA,beforeHide);result.checks.push('Close→reopen restores all A view conditions');
 await page.reload();await page.waitForFunction(()=>PlanLibrary&&PlanLibrary.panes.size===2&&[...PlanLibrary.panes.values()].every(p=>p.ready));const reloadA=await page.evaluate(()=>[...PlanLibrary.panes.values()].find(p=>p.planId==='view-A').frame.contentWindow.EditorPane.view());assert.deepEqual(reloadA,beforeHide);result.checks.push('Browser reload restores serialized view contract');
 await page.evaluate(()=>{const w=[...PlanLibrary.panes.values()].find(p=>p.planId==='view-A').frame.contentWindow;w.setView('2d');w.setView('3d-int');w.CeilingDesigner.setSurface('floor');w.setView('3d-ext');w.setView('3d-int');});assert.equal(await page.evaluate(()=>[...PlanLibrary.panes.values()].find(p=>p.planId==='view-A').frame.contentWindow.ST.ceilingView),false);result.checks.push('Native 2D/interior/ceiling/floor/exterior transitions remain usable after remount');
 assert.deepEqual(result.errors,[]);assert.deepEqual(result.apiRequests,[]);await page.screenshot({path:out+'/two-native-panes.png'});result.status='pass';console.log(JSON.stringify(result,null,2));
}catch(error){result.status='fail';result.failure=error.stack;await page.screenshot({path:out+'/failure.png'});console.error(JSON.stringify(result,null,2));process.exitCode=1;}finally{fs.writeFileSync(out+'/results.json',JSON.stringify(result,null,2));await context.close();await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
