// Native controls are clicked in isolated Chrome. Setup/readback does not replace the editor.
const {chromium}=require('/tmp/webcad-browser-check/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
const url=process.env.APP_URL;if(!/^http:\/\/127\.0\.0\.1:\d+\/$/.test(url||''))throw Error('offline APP_URL required');
const out='docs/quality-review/parallel-native-header';
const fixture={walls:[{id:'qa-wall',floor:1,x1:0,y1:0,x2:4000,y2:0,thick:120}],rooms:[{id:'qa-room',floor:1,x:0,y:0,w:4000,d:3000,n:'QA room',use:'living'}],items:[{id:'qa-sofa',type:'original-sofa',floor:1,x:1400,y:1000,w:1800,d:800,rot:0}]};
(async()=>{
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal'],timeout:30000});
 const ctx=await browser.newContext({viewport:{width:1700,height:1100},acceptDownloads:true}),p=await ctx.newPage();
 const result={checks:[],errors:[],dialogs:[],blocked:[],userTabObserved:false};let accept=true;
 await ctx.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===new URL(url).origin&&!u.pathname.startsWith('/api/')||['data:','blob:'].includes(u.protocol))return r.continue();result.blocked.push(u.href);return r.abort();});
 p.on('pageerror',e=>result.errors.push(e.message));p.on('dialog',async d=>{result.dialogs.push({type:d.type(),message:d.message(),accepted:accept});if(accept)await d.accept();else await d.dismiss();});
 const cards=()=>p.locator('.parallel-pane');const frame=async(i=0)=>(await cards().nth(i).locator('iframe').elementHandle()).contentFrame();
 const native=async(handler,i=0)=>(await frame(i)).locator('#toolbar button[onclick="'+handler+'"]');
 const geometry=async(i=0)=>(await frame(i)).evaluate(()=>JSON.stringify({walls:DATA.walls,rooms:DATA.rooms,items:DATA.items}));
 async function check(label,run){await run();result.checks.push({action:label,status:'pass'});console.log('PASS '+label);}
 async function pick(locator,name,plan){const chooser=p.waitForEvent('filechooser');await locator.click();await(await chooser).setFiles(name?[{name,mimeType:'application/json',buffer:Buffer.from(typeof plan==='string'?plan:JSON.stringify(plan))}]:[]);}
 async function save(i=0){const f=await frame(i);await f.locator('#save-btn').click();await f.waitForFunction(()=>!DIRTY&&!SHARED.saveBusy);}
 async function edit(i=0){await p.waitForTimeout(80);const f=await frame(i),b=await cards().nth(i).locator('iframe').boundingBox(),point=await f.evaluate(()=>{const it=DATA.items[0];return{x:ST.panX+(it.x+it.w*.9)*ST.zoom*.05,y:ST.panY+(it.y+it.d/2)*ST.zoom*.05,before:it.x};});await p.mouse.click(b.x+b.width*.6,b.y+b.height*.85);await p.mouse.click(b.x+point.x,b.y+point.y);result.clicks=(result.clicks||[]).concat([{point,box:b,state:await f.evaluate(({x,y})=>({selected:ST.selected?.id,hit:document.elementFromPoint(x,y)?.id,view:EditorPane.view()}),point)}]);await f.waitForFunction(()=>ST.selected?.id===DATA.items[0].id);await p.keyboard.press('ArrowRight');await f.waitForFunction(x=>DATA.items[0].x>x,point.before);return point.before;}
 try{
  await p.goto(url+'?preset=blank');await p.waitForSelector('#app-loading',{state:'hidden',timeout:90000});if(await p.locator('#preset-choice-modal').isVisible())await p.locator('[onclick="chooseBlankPlan()"]').click();
  const importHandler="document.getElementById('import-file').click()";
  await pick(p.locator('#toolbar button[onclick="'+importHandler+'"]'),'A.json',fixture);await p.waitForFunction(()=>DATA.items[0]?.id==='qa-sofa');
  const host=await p.evaluate(()=>serializeDataSnapshot());result.originalHeader=await p.locator('#toolbar button').evaluateAll(es=>es.map(e=>({id:e.id,handler:e.getAttribute('onclick'),text:e.textContent.trim()})));
  await check('比較開始・既存ヘッダー・重複メニューなし・ロゴ1つ',async()=>{await p.locator('#compare-launch').click();await p.waitForFunction(()=>ParallelEditors.panes.size===2&&[...ParallelEditors.panes.values()].every(p=>p.ready));assert.equal(await p.locator('.parallel-plan-menu,.parallel-import,.parallel-controls input[type=file]').count(),0);assert.equal(await p.locator('.parallel-brand').count(),1);assert.equal(await(await frame()).locator('#collab-indicator').isVisible(),false);for(let i=0;i<2;i++){const f=await frame(i);assert.equal(await f.locator('#toolbar>.brand-mark').isVisible(),false);const handlers=await f.locator('#toolbar button').evaluateAll(es=>es.map(e=>e.getAttribute('onclick')));for(const b of result.originalHeader)assert.ok(handlers.includes(b.handler),'missing native handler '+b.handler);}});
  await check('比較上部は空案の追加・最大4案、JSONは各案へ',async()=>{await p.locator('[data-parallel-add]').click();await p.waitForFunction(()=>ParallelEditors.plans.size===3);await p.locator('[data-parallel-add]').click();await p.waitForFunction(()=>ParallelEditors.plans.size===4);assert.equal(await p.locator('[data-parallel-add]').isDisabled(),true);assert.equal(await cards().count(),2);const select=cards().nth(1).locator('header select'),original=await select.inputValue(),c=await p.evaluate(()=>[...ParallelEditors.plans.values()][2].id);await select.selectOption(c);await p.waitForFunction(()=>[...ParallelEditors.panes.values()].every(p=>p.ready));await pick(await native(importHandler,1),'C.json',fixture);await(await frame(1)).waitForFunction(()=>DATA.items[0]?.id==='qa-sofa');await select.selectOption(original);await p.waitForFunction(()=>[...ParallelEditors.panes.values()].every(p=>p.ready));});
  await check('Aの通常canvas編集とUndo/RedoはBに漏れない',async()=>{const b=await geometry(1),x=await edit(),f=await frame();await f.locator('.stool[title="Undo"]').click();assert.equal(await f.evaluate(()=>DATA.items[0].x),x);await f.locator('.stool[title="Redo"]').click();assert.ok(await f.evaluate(()=>DATA.items[0].x)>x);assert.equal(await geometry(1),b);});
  await check('コピー/貼付とUndoはAだけ',async()=>{const f=await frame(),b=await geometry(1);await edit();await f.locator('.stool[title="コピー"]').click();await f.locator('.stool[title="ペースト"]').click();assert.equal(await f.evaluate(()=>DATA.items.length),2);assert.equal(await geometry(1),b);await f.locator('.stool[title="Undo"]').click();assert.equal(await f.evaluate(()=>DATA.items.length),1);});
  await check('既存Aヘッダー保存と既存保存読込・B保存からAを保護',async()=>{await save();const f=await frame(),saved=await f.evaluate(()=>DATA.items[0].x);await edit();await save(1);assert.equal(await f.evaluate(async()=>(await StorageAdapter.load()).items[0].x),saved);accept=false;await(await native('loadPlanFromStorageButton()')).click();accept=true;assert.equal(await f.evaluate(()=>DIRTY),true);await(await native('loadPlanFromStorageButton()')).click();await f.waitForFunction(x=>DATA.items[0].x===x&&!DIRTY,saved);});
  await check('既存保存ボタン失敗・未保存保持・再試行・繰り返し',async()=>{const f=await frame();await edit();await p.evaluate(()=>{window.__qaTx=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(...args){const tx=__qaTx.apply(this,args);if(this.name==='webcad-parallel-workspace'&&args[1]==='readwrite')queueMicrotask(()=>tx.abort());return tx;};});try{const dialog=p.waitForEvent('dialog',{predicate:d=>d.message().includes('保存に失敗')});await f.locator('#save-btn').click();await dialog;await f.waitForFunction(()=>!SHARED.saveBusy);assert.equal(await f.evaluate(()=>DIRTY),true);}finally{await p.evaluate(()=>{IDBDatabase.prototype.transaction=__qaTx;delete window.__qaTx;});}await save();await save();});
  await check('BヘッダーJSON読込はBだけ・A保持',async()=>{const a=await geometry();await pick(await native(importHandler,1),'B.json',{...fixture,items:[{...fixture.items[0],x:1800}]});await(await frame(1)).waitForFunction(()=>DATA.items[0].x===1800);assert.equal(await geometry(),a);});
  await check('BのJSON書出しは実ダウンロード・Bの内容',async()=>{const download=p.waitForEvent('download');await(await native('exportPlan()',1)).click();const file='/tmp/webcad-native-B-export.json';await(await download).saveAs(file);assert.equal(JSON.parse(fs.readFileSync(file)).items[0].x,1800);});
  await check('Bの未保存JSON置換取消とファイル選択取消',async()=>{const before=await geometry(1);accept=false;await pick(await native(importHandler,1),'Replace.json',fixture);await p.waitForTimeout(100);accept=true;assert.equal(await geometry(1),before);await pick(await native(importHandler,1));assert.equal(await geometry(1),before);});
  await check('B不正JSONを繰り返し拒否し履歴保持',async()=>{const f=await frame(1),before=await f.evaluate(()=>({plan:serializeDataSnapshot(),history:HISTORY.slice(),dirty:DIRTY}));for(let i=0;i<2;i++){const dialog=p.waitForEvent('dialog',{predicate:d=>d.message().includes('読み込めません')});await pick(await native(importHandler,1),'Invalid.json','{"walls":[],"items":"bad"}');await dialog;assert.deepEqual(await f.evaluate(()=>({plan:serializeDataSnapshot(),history:HISTORY.slice(),dirty:DIRTY})),before);}});
  await check('画角同期ONでもAの階数はBを変更しない',async()=>{await(await frame()).locator('#floor-sel').selectOption('2');await p.waitForTimeout(100);assert.equal(await(await frame()).evaluate(()=>ST.floor),2);assert.equal(await(await frame(1)).evaluate(()=>ST.floor),1);await(await frame()).locator('#floor-sel').selectOption('1');});
  await check('グリッド・寸法の既存ボタンはAだけ',async()=>{const b=await(await frame(1)).evaluate(()=>({grid:ST.showGrid,dim:ST.showDim}));for(const [handler,key] of [['toggleGrid()','showGrid'],['toggleDim()','showDim']]){const f=await frame(),before=await f.evaluate(k=>ST[k],key);await(await native(handler)).click();assert.equal(await f.evaluate(k=>ST[k],key),!before);await(await native(handler)).click();}assert.deepEqual(await(await frame(1)).evaluate(()=>({grid:ST.showGrid,dim:ST.showDim})),b);});
  await check('2D/外観/内観/ウォークはAの既存ヘッダーだけに作用',async()=>{for(const [id,view] of [['#btn-3de','3d-ext'],['#btn-3di','3d-int'],['#btn-3dw','3d-walk'],['#btn-2d','2d']]){const f=await frame();await f.locator(id).click();await f.waitForFunction(v=>ST.view===v,view,{timeout:90000});await p.waitForTimeout(100);assert.equal(await(await frame(1)).evaluate(()=>ST.view),'2d');}});
  await check('Aの3D更新・全体表示の既存ボタン',async()=>{const b=await geometry(1);await(await native('refresh3DPreviewWithLoading()')).click();await(await frame()).waitForFunction(()=>!hasPendingGltfModels(),null,{timeout:90000});await(await native('resetView()')).click();assert.equal(await geometry(1),b);});
  await check('階クリアの取消・Aだけ削除・Undo復元',async()=>{const a=await geometry(),b=await geometry(1);accept=false;await(await native('clearFloor()')).click();accept=true;assert.equal(await geometry(),a);await(await native('clearFloor()')).click();assert.equal(await(await frame()).evaluate(()=>DATA.items.length+DATA.walls.length+DATA.rooms.length),0);assert.equal(await geometry(1),b);await(await frame()).locator('.stool[title="Undo"]').click();assert.equal(await geometry(),a);});
  await check('既存下書き・JIS・共有・画像/動画ダイアログはA内に開く',async()=>{for(const [id,overlay,close,disabled] of [['#plan-import-toolbar-btn','#plan-import-modal','closePlanImport()','#plan-import-run'],['#jis-drawing-toolbar-btn','#jis-drawing-overlay','closeJisDrawingDialog()',null],['#share-btn','#share-overlay','closeShareDialog()','#share-create-btn'],['#unity-render-toolbar-btn','#unity-render-modal','closeUnityRenderModal()','#ai-render-run'],['#video-render-toolbar-btn','#video-render-modal','closeVideoRenderModal()','#video-render-run']]){const f=await frame();await f.locator(id).click();await f.locator(overlay).waitFor({state:'visible'});assert.equal(await(await frame(1)).locator(overlay).isVisible(),false);if(disabled)assert.equal(await f.locator(disabled).isDisabled(),true);await f.locator(overlay+' [onclick="'+close+'"]').click();await f.locator(overlay).waitFor({state:'hidden'});}});
  await check('同期OFFのwheelは独立・一度だけ整列・同期ON',async()=>{await(await frame()).locator('#btn-2d').click();await(await frame()).locator('#c2d').waitFor({state:'visible'});await p.locator('[data-parallel-sync]').uncheck();const a=await frame(),b=await frame(1),before=await b.evaluate(()=>EditorPane.view().twoD),box=await a.locator('#c2d').boundingBox();await p.mouse.move(box.x+box.width*.8,box.y+box.height*.4);await p.mouse.wheel(0,180);await p.waitForTimeout(150);assert.deepEqual(await b.evaluate(()=>EditorPane.view().twoD),before);await p.locator('[data-parallel-align]').click();assert.deepEqual(await a.evaluate(()=>EditorPane.view().twoD),await b.evaluate(()=>EditorPane.view().twoD));assert.equal(await p.locator('[data-parallel-sync]').isChecked(),false);await p.locator('[data-parallel-sync]').check();});
  await check('同期ONの2D実wheelで画角だけ一致',async()=>{const a=await frame(),b=await frame(1),box=await a.locator('#c2d').boundingBox();await p.mouse.move(box.x+box.width*.8,box.y+box.height*.4);await p.mouse.wheel(0,100);await p.waitForTimeout(150);assert.deepEqual(await a.evaluate(()=>EditorPane.view().twoD),await b.evaluate(()=>EditorPane.view().twoD));});
  await check('外観3Dの実wheelと画角同期ON/OFF',async()=>{const a=await frame(),b=await frame(1);await a.locator('#btn-3de').click();await b.locator('#btn-3de').click();await p.waitForFunction(()=>[...ParallelEditors.panes.values()].every(p=>p.frame.contentWindow.ren&&!p.frame.contentWindow.hasPendingGltfModels()));await p.waitForTimeout(500);await p.locator('[data-parallel-align]').click();await p.locator('[data-parallel-sync]').uncheck();const before=await b.evaluate(()=>EditorPane.view().camera),box=await a.locator('#c3d-wrap canvas[data-engine]').boundingBox();await p.mouse.move(box.x+box.width*.8,box.y+box.height*.55);await p.mouse.wheel(0,160);await p.waitForTimeout(700);assert.deepEqual(await b.evaluate(()=>EditorPane.view().camera),before);await p.locator('[data-parallel-sync]').check();await p.mouse.move(box.x+box.width*.8,box.y+box.height*.55);await p.mouse.wheel(0,100);await p.waitForTimeout(900);const cams=await Promise.all([a,b].map(f=>f.evaluate(()=>EditorPane.view().camera)));for(let i=0;i<3;i++)assert.ok(Math.abs(cams[0].pos[i]-cams[1].pos[i])<.001);assert.equal(await a.evaluate(()=>ST.view),'3d-ext');assert.equal(await b.evaluate(()=>ST.view),'3d-ext');await a.locator('#btn-2d').click();await b.locator('#btn-2d').click();});
  await check('比較セット保存・取消・再読込・非表示案保存',async()=>{await p.locator('[data-parallel-save]').click();await p.locator('[data-parallel-status]').filter({hasText:'表示中・非表示の案'}).waitFor();assert.equal(await p.evaluate(()=>ParallelEditors.hasUnsaved()),false);await edit();accept=false;await p.locator('[data-parallel-load]').click();await p.locator('[data-parallel-status]').filter({hasText:'取り消しました'}).waitFor();accept=true;assert.equal(await p.evaluate(()=>ParallelEditors.hasUnsaved()),true);await p.locator('[data-parallel-load]').click();await p.locator('[data-parallel-status]').filter({hasText:'保存した比較セットを開きました'}).waitFor();assert.equal(await p.evaluate(()=>ParallelEditors.hasUnsaved()),false);});
  await check('案パネルの×・未保存取消と確認',async()=>{await edit();const id=await cards().nth(0).locator('header select').inputValue();accept=false;await cards().nth(0).locator('[data-parallel-pane-remove]').click();accept=true;assert.equal(await p.evaluate(()=>ParallelEditors.plans.size),4);await cards().nth(0).locator('[data-parallel-pane-remove]').click();await p.waitForFunction(()=>ParallelEditors.plans.size===3&&[...ParallelEditors.panes.values()].every(p=>p.ready));});
  await check('比較から戻る・元の編集データ保持・単独ロゴ復帰',async()=>{await p.locator('[data-parallel-close]').click();await p.locator('.parallel-editors').waitFor({state:'hidden'});assert.equal(await p.evaluate(()=>serializeDataSnapshot()),host);assert.equal(await p.locator('#toolbar>.brand-mark').isVisible(),true);await p.locator('#compare-launch').click();await p.waitForFunction(()=>[...ParallelEditors.panes.values()].every(p=>p.ready));});
  await check('比較上部の以前保存した案・空状態の診断',async()=>{await p.locator('.parallel-recovery summary').click();await p.locator('[data-parallel-legacy-add]').click();await p.locator('[data-parallel-status]').filter({hasText:'以前に保存した案はありません'}).waitFor();});
  await check('タブレット幅でも既存JSON/保存をパネル内で操作',async()=>{await p.setViewportSize({width:1280,height:1000});await p.waitForTimeout(200);const f=await frame(1);for(const handler of ['savePlanToStorage()',importHandler,'exportPlan()'])assert.equal(await(await native(handler,1)).isVisible(),true);result.tablet=await f.evaluate(()=>({innerHeight,canvasHeight:canvas.height,bodyHeight:document.body.getBoundingClientRect().height,bottomNav:document.getElementById('bottom-nav').getBoundingClientRect().toJSON()}));const x=await f.evaluate(()=>DATA.items[0].x),download=p.waitForEvent('download');await(await native('exportPlan()',1)).click();const file='/tmp/webcad-native-tablet-export.json';await(await download).saveAs(file);assert.equal(JSON.parse(fs.readFileSync(file)).items[0].x,x);await p.screenshot({path:out+'/native-two-headers-tablet.png'});await p.setViewportSize({width:1700,height:1100});});
  result.paneHeader=await(await frame()).locator('#toolbar button').evaluateAll(es=>es.map(e=>({id:e.id,handler:e.getAttribute('onclick'),text:e.textContent.trim(),display:getComputedStyle(e).display,disabled:e.disabled})));
  await p.screenshot({path:out+'/native-two-headers.png'});assert.deepEqual(result.errors,[]);result.status='pass';
 }catch(e){result.status='fail';result.failure=e.stack;await p.screenshot({path:out+'/failure.png'});throw e;}
 finally{fs.writeFileSync(out+'/results.json',JSON.stringify(result,null,2));await ctx.close();await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
