/* Independent browser profile only. No user's tabs or persisted data are read.
 * APP_URL must point to the offline loopback preview. Measurements report this
 * machine/fixture, not a universal speed or GPU-memory guarantee. */
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/tmp/webcad-browser-check/node_modules/playwright');
const appURL=process.env.APP_URL;
if(!appURL||!/^http:\/\/(127\.0\.0\.1|localhost):\d+\/$/.test(appURL))throw Error('Set APP_URL to offline loopback preview, ending in /');
const output=process.env.PARALLEL_REPORT_DIR||path.resolve('docs/quality-review/parallel-editors');
const plan={walls:[{id:'wall-1',x1:0,y1:0,x2:5000,y2:0,thick:120,floor:1}],rooms:[{id:'room-1',x:0,y:0,w:5000,d:4000,n:'Fixture room',use:'living',floor:1}],items:[{id:'item-1',type:'original-sofa',x:2000,y:2000,w:2100,d:820,h:900,rot:0,floor:1,modelFacingVersion:1,finishColors:{fabric:'#a75842'}}],floorCount:1,northDeg:0};
const pct=(xs,p)=>{const sorted=[...xs].sort((a,b)=>a-b);return sorted[Math.min(sorted.length-1,Math.floor((sorted.length-1)*p))];};
(async()=>{
 fs.mkdirSync(output,{recursive:true});
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal']});
 const context=await browser.newContext({viewport:{width:1800,height:1100},acceptDownloads:false});
 const page=await context.newPage(),errors=[],requests=[],external=[],results={fixture:'one room, wall, existing original-sofa; no AI',viewport:{width:1800,height:1100},samples:[],checks:[],errors};
 page.on('pageerror',e=>errors.push({message:e.message.slice(0,1000),stack:e.stack?.split('\n').slice(0,5).join('\n')}));
 context.on('request',r=>requests.push({url:r.url(),method:r.method()}));
 await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.protocol==='http:'&&u.origin===new URL(appURL).origin&&!u.pathname.startsWith('/api/'))return route.continue();if(['data:','blob:'].includes(u.protocol))return route.continue();external.push(route.request().url());return route.abort('blockedbyclient');});
 page.on('dialog',d=>d.accept()); // Only this brand-new test profile has dialogs.
 const panes=()=>page.evaluate(()=>[...ParallelEditors.panes.keys()]);
  async function frame(id){await page.waitForFunction(id=>ParallelEditors.panes.get(id)?.frame?.contentWindow?.EditorPane,id);const locator=await page.evaluate(id=>ParallelEditors.panes.get(id).frame.getAttribute('name'),id);let f=page.frames().find(f=>f.name()===locator);if(!f){const handles=await page.locator('iframe').elementHandles();for(const h of handles){const fr=await h.contentFrame();if(await h.evaluate((el,id)=>el===ParallelEditors.panes.get(id).frame,id)){f=fr;break;}}}assert.ok(f,'pane iframe exists');await f.evaluate(()=>EditorPane.ready);return f;}
 async function snapshot(id){return (await frame(id)).evaluate(()=>EditorPane.snapshot());}
 async function view(id){return (await frame(id)).evaluate(()=>EditorPane.view());}
 async function measure(label){const ids=await panes(),frames=await Promise.all(ids.map(frame)),latency=[];for(let i=0;i<24;i++){latency.push(await page.evaluate(async({id,i})=>{const started=performance.now(),api=ParallelEditors.panes.get(id).frame.contentWindow.EditorPane,v=api.view();v.twoD.panX+=i%2?8:-8;api.applyView(v);ParallelEditors.changed(id);await new Promise(requestAnimationFrame);return performance.now()-started;},{id:ids[0],i}));}const metrics=await Promise.all(frames.map(f=>f.evaluate(()=>EditorPane.metrics()))),memory=await page.evaluate(()=>performance.memory?{usedJSHeapSize:performance.memory.usedJSHeapSize,totalJSHeapSize:performance.memory.totalJSHeapSize}:null);results.samples.push({label,active:ids.length,retained:await page.evaluate(()=>ParallelEditors.plans.size),latencyMs:{p50:pct(latency,.5),p95:pct(latency,.95),samples:latency.length},memory,metrics});}
 try{
  await page.goto(appURL+'?preset=blank');await page.waitForFunction(()=>window.ParallelEditors);await page.waitForSelector('#app-loading',{state:'hidden',timeout:90000});
  const hostBefore=await page.evaluate(()=>serializeDataSnapshot());
  await page.evaluate(()=>ParallelEditors.open());await page.waitForFunction(()=>ParallelEditors.panes.size===2&&[...ParallelEditors.panes.values()].every(p=>p.frame.contentWindow?.EditorPane));for(const id of await panes())await frame(id);for(const id of await page.evaluate(()=>[...ParallelEditors.plans.keys()]))await page.evaluate(id=>ParallelEditors.remove(id),id);
  const first=await page.evaluate(p=>ParallelEditors.addPlan(p,'Fixture A'),plan);let ids=await panes();assert.equal(ids.length,1);const a=ids[0];await frame(a);await measure('one active / one retained 2D');await (await frame(a)).evaluate(()=>setView('3d-ext'));await (await frame(a)).waitForFunction(()=>!!ren&&!hasPendingGltfModels(),null,{timeout:90000});await measure('one active / one retained 3D');await (await frame(a)).evaluate(()=>setView('2d'));
  const second=await page.evaluate(p=>ParallelEditors.addPlan(p,'Fixture B'),{...plan,items:[{...plan.items[0],x:3000,finishColors:{fabric:'#52768a'}}]});ids=await panes();assert.equal(ids.length,2);const b=ids.find(x=>x!==a);await frame(b);
  const bInitial=await snapshot(b);await (await frame(a)).evaluate(()=>{saveState();DATA.items[0].x+=250;ST.selected=DATA.items[0];draw2d();});assert.equal((await snapshot(a)).items[0].x,2250);assert.deepEqual(await snapshot(b),bInitial,'editing A changes no B mutable data');await (await frame(a)).evaluate(()=>EditorPane.undo());assert.equal((await snapshot(a)).items[0].x,2000);await (await frame(a)).evaluate(()=>EditorPane.redo());assert.equal((await snapshot(a)).items[0].x,2250);results.checks.push('real DATA edit + native Undo/Redo isolate A from B');
  await page.evaluate(()=>ParallelEditors.setSync(false));const vb=await view(b);await (await frame(a)).evaluate(()=>{const v=EditorPane.view();v.twoD.panX+=123;EditorPane.applyView(v);});await page.evaluate(id=>ParallelEditors.changed(id),a);assert.deepEqual(await view(b),vb,'sync off keeps B view');await page.evaluate(()=>ParallelEditors.setSync(true));await page.evaluate(id=>ParallelEditors.changed(id),a);assert.deepEqual((await view(a)).twoD,(await view(b)).twoD,'sync on propagates 2D view');const wheelBefore=(await view(a)).twoD.panY;const box=await (await frame(a)).locator('#c2d').boundingBox();assert.ok(box);await page.mouse.move(box.x+box.width*.8,box.y+box.height*.45);await page.mouse.wheel(0,180);await (await frame(a)).waitForFunction(z=>EditorPane.view().twoD.panY!==z,wheelBefore);await page.waitForTimeout(120);assert.deepEqual((await view(a)).twoD,(await view(b)).twoD,'actual simulator wheel event synchronizes panes');await page.evaluate(()=>ParallelEditors.setSync(false));await (await frame(a)).evaluate(()=>{const v=EditorPane.view();v.twoD.panY+=87;EditorPane.applyView(v);});await page.evaluate(id=>{ParallelEditors.changed(id);ParallelEditors.align();},a);assert.deepEqual((await view(a)).twoD,(await view(b)).twoD,'one-time align works with sync off');assert.deepEqual((await snapshot(b)).items,bInitial.items,'camera synchronization changes no plan objects');results.checks.push('toggle and one-time align synchronize view only');
  await measure('two active / two retained 2D');for(const id of await panes())await (await frame(id)).evaluate(()=>setView('3d-ext'));for(const id of await panes())await (await frame(id)).waitForFunction(()=>!!ren&&!hasPendingGltfModels(),null,{timeout:90000});await measure('two active / two retained 3D');for(const id of await panes())await (await frame(id)).evaluate(()=>setView('2d'));
  await page.evaluate(async p=>{await ParallelEditors.addPlan({...p,items:[{...p.items[0],x:4000}]},'Fixture C.json');await ParallelEditors.addPlan({...p,items:[{...p.items[0],x:4500}]},'Fixture D.json');},plan);await page.waitForFunction(()=>ParallelEditors.plans.size===4);const third=await page.evaluate(()=>[...ParallelEditors.plans.values()].find(p=>p.name==='Fixture C.json').id),fourth=await page.evaluate(()=>[...ParallelEditors.plans.values()].find(p=>p.name==='Fixture D.json').id);assert.equal((await panes()).length,2,'four plans retain only two real editors');assert.equal(await page.evaluate(()=>ParallelEditors.plans.size),4);const rejected=await page.evaluate(async p=>{try{await ParallelEditors.addPlan(p,'Fifth');return false;}catch{return true;}},plan);assert.equal(rejected,true,'fifth retained plan rejected');
  await page.evaluate(({a,third})=>ParallelEditors.select(a,third),{a,third});assert.equal((await snapshot(a)).items[0].x,4000);await page.evaluate(({a,first})=>ParallelEditors.select(a,first),{a,first});assert.equal((await snapshot(a)).items[0].x,2250,'return restores plan edits');await (await frame(a)).evaluate(()=>EditorPane.undo());assert.equal((await snapshot(a)).items[0].x,2000,'switch restores independent Undo');await (await frame(a)).evaluate(()=>EditorPane.redo());await (await frame(a)).evaluate(()=>EditorPane.save());const savedA=await (await frame(a)).evaluate(()=>StorageAdapter.load());assert.equal(savedA.items[0].x,2250);assert.equal((await (await frame(b)).evaluate(()=>StorageAdapter.load())),null,'saving A must not create a saved B');results.checks.push('four retained plans, two active panes, switching restores edits and Undo');
  await measure('two active / four retained');
  for(const id of await panes())await (await frame(id)).evaluate(()=>{setView('3d-ext');});for(const id of await panes())await (await frame(id)).waitForFunction(()=>!!ren&&!hasPendingGltfModels(),null,{timeout:90000});await page.waitForTimeout(1800);
  const rendered=await Promise.all((await panes()).map(async id=>(await frame(id)).evaluate(()=>({view:ST.view,modelReady:!hasPendingGltfModels(),renderer:!!ren,calls:ren?.info.render.calls,pixelRatio:ren?.getPixelRatio(),shadows:ren?.shadowMap.enabled,colors:DATA.items[0].finishColors}))));assert.ok(rendered.every(x=>x.renderer&&x.modelReady),'both real 3D model scenes ready');results.rendered=rendered;
  await (await frame(a)).evaluate(()=>{const v=EditorPane.view();v.camera={pos:[8,7,10],target:[2.5,.5,2],fov:50};EditorPane.applyView(v);});await page.evaluate(id=>{ParallelEditors.changed(id);ParallelEditors.align();},a);await page.waitForTimeout(500);await measure('two active / four retained 3D');await page.screenshot({path:path.join(output,'two-editors-3d.png'),fullPage:false});
  await page.waitForTimeout(600);results.sceneFinishes=await Promise.all((await panes()).map(async id=>(await frame(id)).evaluate(()=>{const colors=[];sc3.traverse(o=>{if(o.isMesh)for(const m of [].concat(o.material||[]))if(m.userData?.finishChannel==='fabric')colors.push(m.color.getHexString());});return colors;})));assert.ok(results.sceneFinishes[0].includes('a75842'),'A actual scene has red fabric');assert.ok(results.sceneFinishes[1].includes('52768a'),'B actual scene has blue fabric');const bStable=await (await frame(b)).evaluate(()=>EditorPane.metrics());await (await frame(a)).evaluate(()=>{saveState();DATA.items[0].x+=25;rebuild3D();});await page.waitForTimeout(700);const bAfter=await (await frame(b)).evaluate(()=>EditorPane.metrics());results.unchangedPane={before:bStable,after:bAfter};results.sharedObjectOwnership=await page.evaluate(()=>{const windows=[...ParallelEditors.panes.values()].map(p=>p.frame.contentWindow);function refs(w){let geom,mat;Object.values(w._modelCache)[0].traverse(o=>{if(!geom&&o.isMesh){geom=o.geometry;mat=Array.isArray(o.material)?o.material[0]:o.material;}});return {geom,mat};}const [a,b]=windows.map(refs);return {sharedArrayBuffer:a.geom.attributes.position.array.buffer===b.geom.attributes.position.array.buffer,separateGeometry:a.geom!==b.geom,separateMaterial:a.mat!==b.mat};});assert.deepEqual(results.sharedObjectOwnership,{sharedArrayBuffer:true,separateGeometry:true,separateMaterial:true});results.sharedModelPool=await page.evaluate(()=>({entries:ParallelEditors.modelPool.cache.size,resources:ParallelEditors.modelPool.resources.size}));assert.equal(results.sharedModelPool.entries,1,'two panes use one loaded sofa model template');
  assert.equal(bAfter.renderCalls,bStable.renderCalls,'unchanged B should not render when A edits');
  assert.equal(await page.evaluate(()=>serializeDataSnapshot()),hostBefore,'host original plan remains unchanged');
  await page.evaluate(()=>ParallelEditors.saveWorkspace());await page.evaluate(()=>ParallelEditors.close());await page.waitForFunction(()=>ParallelEditors.modelPool.cache.size===0);assert.equal(await page.evaluate(()=>ParallelEditors.panes.size),0);assert.equal(await page.locator('iframe').count(),0,'close removes owned editor frames');results.checks.push('host original DATA preserved; close releases child frames and model pool');const restored=await context.newPage();restored.on('pageerror',e=>errors.push({message:e.message.slice(0,1000)}));restored.on('dialog',d=>d.accept());await restored.goto(appURL+'?preset=blank');await restored.waitForFunction(()=>window.ParallelEditors);await restored.waitForSelector('#app-loading',{state:'hidden',timeout:90000});await restored.evaluate(()=>ParallelEditors.open());await restored.waitForFunction(()=>ParallelEditors.panes.size===2&&[...ParallelEditors.panes.values()].every(p=>p.frame.contentWindow?.EditorPane));for(const f of restored.frames().slice(1))await f.evaluate(()=>EditorPane.ready);await restored.evaluate(()=>ParallelEditors.loadWorkspace());await restored.waitForFunction(()=>ParallelEditors.plans.size===4&&ParallelEditors.panes.size===2);const restoredData=await restored.evaluate(()=>[...ParallelEditors.panes.values()].map(p=>p.frame.contentWindow.EditorPane.state()));assert.equal(restoredData[0].plan.items[0].x,2275);assert.equal(restoredData[1].plan.items[0].x,3000);assert.equal(restoredData[0].plan.items[0].finishColors.fabric,'#a75842');assert.equal(restoredData[1].plan.items[0].finishColors.fabric,'#52768a');assert.ok(restoredData[0].history.length,'workspace persists native Undo snapshots');await restored.evaluate(()=>[...ParallelEditors.panes.values()][0].frame.contentWindow.EditorPane.undo());assert.equal(await restored.evaluate(()=>[...ParallelEditors.panes.values()][0].frame.contentWindow.EditorPane.snapshot().items[0].x),2250);results.checks.push('saved workspace reload in fresh page restores four plans, separate finishes and native Undo');await restored.evaluate(()=>ParallelEditors.close());await restored.close();
  results.externalBlocked=external;assert.deepEqual(external,[],'all requests remain loopback, no API');assert.deepEqual(errors,[],'no uncaught browser errors');results.assetRequests=requests.filter(r=>/\.glb(?:\?|$)/.test(r.url));results.status='pass';
 }catch(e){results.status='fail';results.failure=e.stack;throw e;}finally{fs.writeFileSync(path.join(output,'browser-results.json'),JSON.stringify(results,null,2));await context.close();await browser.close();}
 console.log('PASS: isolated actual editors, retained plans, view-only synchronization, native Undo, release; measurement report '+output);
})().catch(e=>{console.error(e);process.exitCode=1;});
