'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {libraryContext,fixture,Storage,ROOT}=require('./plan-library-test-support.cjs');
const plain=v=>JSON.parse(JSON.stringify(v)),tick=()=>new Promise(resolve=>setImmediate(resolve));
async function until(check){for(let i=0;i<600;i++){if(check())return;await tick();}throw Error('condition did not settle');}
function status(h){return h.document.querySelector('[data-library-status]')?.textContent||h.document.querySelector('[data-library-dirty]')?.title||'';}
async function comparison({unsaved=false}={}){
 const h=libraryContext({native:false,search:'?planLibrary=1'});await h.api.ready;
 for(let i=1;i<=2;i++)await h.api.repo.save({planId:'plan-fixture-'+i,name:'Plan '+i,operationId:'seed-'+i,baseRevisionId:null,baseGeneration:0,payload:fixture(i*100)});
 await h.api.repo.setView('comparison-fixture',{retainedPlanIds:['plan-fixture-1','plan-fixture-2'],panelPlanIds:['plan-fixture-1','plan-fixture-2'],sync:false});
 const events=new Map(),c=libraryContext({mem:h.mem,native:false,search:'?planLibrary=1&librarySession=comparison-fixture',beforeLibrary:ctx=>{ctx.addEventListener=(name,fn)=>events.set(name,fn);}});c.events=events;await c.api.ready;
 const [a,b]=[...c.api.panes.values()];await a.frame.contentWindow.EditorPane.install(fixture(321),{dirty:true,history:['undo-a'],redo:['redo-a'],cataloguePack:'native-pack',view:{view:'2d',floor:1,twoD:{zoom:7,panX:8,panY:9}}});c.api.edited(a.id);await tick();
 if(unsaved){await c.api.repo.get('drafts',JSON.stringify([c.api.session,a.planId]));const r=c.api.plans.get(a.planId);r.baseRevisionId=null;r.baseGeneration=0;const stores=c.mem.dbs.get('webcad-plan-library-lab-ui-v1').stores;stores.get('plans').delete(a.planId);const d=stores.get('drafts').get(JSON.stringify([c.api.session,a.planId]));d.baseRevisionId=null;d.baseGeneration=0;}
 c.localStorage.setItem('webcad-plan-v1','  anonymous original bytes\n');return {c,a,b};
}
async function launch(c,a){assert.equal(await c.api.openNativeAction(a.id,'share',a.frame.contentWindow),true,status(c));const target=c.popups.at(-1),url=new URL(target.url),token=url.searchParams.get('nativeAction');return {target,url,token,ticket:await c.api.repo.get('views',token)};}
function native(c,url,extra={}){
 const calls={share:0,join:0,rooms:0};const n=libraryContext({mem:c.mem,search:url.search,localStorage:c.localStorage,beforeLibrary:ctx=>{ctx.openShareDialog=()=>calls.share++;ctx.sharedSetStatus=m=>calls.message=m;ctx.initSharedRoomFromUrl=async()=>{calls.join++;throw Error('No automatic join');};ctx.fetch=()=>{calls.rooms++;throw Error('No backend requests');};extra.before?.(ctx);},...extra});return {n,calls};
}
test('existing share entry delegates only to genuine library host; native dialog and network guards remain',()=>{
 const html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),code=html.slice(html.indexOf('function openShareDialog(){'),html.indexOf('function closeShareDialog(){'));
 let calls=0,overlay=0;const pane={EDITOR_PANE:'pane',window:{parent:{PlanLibrary:{openNativeAction(id,action,w){assert.equal(id,'pane');assert.equal(action,'share');assert.equal(w,pane.window);calls++;return 'handoff';}}}},document:{getElementById(){throw Error('No duplicate pane dialog');}}};vm.runInNewContext(code,pane);assert.equal(pane.openShareDialog(),'handoff');assert.equal(calls,1);
 const normal={EDITOR_PANE:null,window:{},document:{getElementById:id=>id==='share-overlay'?{classList:{add(){overlay++;}}}:null},renderSharedUi(){},sharedDisplayName:()=>'',setTimeout};vm.runInNewContext(code,normal);normal.openShareDialog();assert.equal(overlay,1);
 assert.match(html,/if\(COMPARISON_PREVIEW \|\| EDITOR_PANE\)/);assert.match(html,/Comparison preview cannot access application APIs/);assert.match(html,/Comparison preview cannot join collaboration/);
});
test('same-ID dirty A ticket preserves peer, layout, original bytes, history/redo/view; native installs before share without network',async()=>{
 const {c,a,b}=await comparison(),before=plain(a.frame.contentWindow.EditorPane.state()),peer=plain(b.frame.contentWindow.EditorPane.state()),layout=plain(await c.api.repo.get('views',c.api.session));
 const {url,token,ticket}=await launch(c,a);assert.deepEqual([...url.searchParams.keys()],['nativeAction']);assert.equal(url.hash,'');assert.notEqual(token,c.api.session);assert.deepEqual(plain(ticket.panelPlanIds),[a.planId]);assert.equal(ticket.nativeAction.status,'prepared');assert.deepEqual(plain(a.frame.contentWindow.EditorPane.state()),before);assert.deepEqual(plain(b.frame.contentWindow.EditorPane.state()),peer);assert.deepEqual(plain(await c.api.repo.get('views',c.api.session)),layout);assert.equal(c.localStorage.getItem('webcad-plan-v1'),'  anonymous original bytes\n');
 const inherited=new Storage();inherited.setItem('webcad-collab-client','source-client');inherited.setItem('webcad-plan-library-native-session','inherited-wrong-session');const {n,calls}=native(c,url,{sessionStorage:inherited});await n.api.ready;
 assert.equal(n.context.__editorPlanId,a.planId);assert.deepEqual(plain(n.context.EditorPane.state()),before);assert.equal(n.context.presetLoads,undefined);assert.equal(calls.share,1);assert.equal(calls.join+calls.rooms,0);assert.notEqual(n.api.session,token);assert.notEqual(n.api.session,'inherited-wrong-session');assert.notEqual(n.context.SHARED.clientId,'source-client');assert.equal(inherited.getItem('webcad-collab-client'),n.context.SHARED.clientId);assert.equal((await c.api.repo.get('views',token)).nativeAction.status,'consumed');assert.equal(n.api.nativeActionStatus,'ready');assert.equal(n.context.DIRTY,true);
});
test('never-saved and blank drafts checkpoint same ID without explicit-save cleaning',async()=>{
 for(const blank of [false,true]){const {c,a}=await comparison({unsaved:true});if(blank){await a.frame.contentWindow.EditorPane.install({walls:[],rooms:[],items:[],startMode:'blank'},{dirty:true,history:['blank-undo'],redo:['blank-redo'],cataloguePack:'native-pack'});c.api.edited(a.id);await tick();}
 const {url}=await launch(c,a),{n,calls}=native(c,url);await n.api.ready;assert.equal(calls.share,1);assert.equal(n.context.__editorPlanId,a.planId);assert.equal((await c.api.repo.read(a.planId)).revision.kind,'unsaved-checkpoint');assert.equal(a.frame.contentWindow.DIRTY,true);assert.equal(n.context.DIRTY,true);assert.deepEqual(n.plan,a.frame.contentWindow.EditorPane.snapshot());}
});
test('popup denial, forged pane, preview, pending source work cause no persistence or replacement',async()=>{
 const {c,a,b}=await comparison(),head=plain(await c.api.repo.read(a.planId)),source=plain(a.frame.contentWindow.EditorPane.state()),peer=plain(b.frame.contentWindow.EditorPane.state());c.context.open=()=>null;assert.equal(await c.api.openNativeAction(a.id,'share',a.frame.contentWindow),false);assert.match(status(c),/ポップアップ/);assert.equal(await c.api.openNativeAction(a.id,'share',{}),false);a.frame.contentWindow.COMPARISON_PREVIEW=true;assert.equal(await c.api.openNativeAction(a.id,'share',a.frame.contentWindow),false);a.frame.contentWindow.COMPARISON_PREVIEW=false;a.installing=true;assert.equal(await c.api.openNativeAction(a.id,'share',a.frame.contentWindow),false);a.installing=false;assert.deepEqual(plain(await c.api.repo.read(a.planId)),head);assert.deepEqual(plain(a.frame.contentWindow.EditorPane.state()),source);assert.deepEqual(plain(b.frame.contentWindow.EditorPane.state()),peer);assert.equal(c.popups.length,0);
});
test('repeat clicks coalesce blank and acknowledged owner; closing share is not a second room creation',async()=>{
 const {c,a}=await comparison();let release,entered=false;const original=c.api.repo.saveDraft;c.api.repo.saveDraft=async(...args)=>{if(!entered){entered=true;await new Promise(resolve=>release=resolve);}return original(...args);};
 const one=c.api.openNativeAction(a.id,'share',a.frame.contentWindow);await until(()=>entered);const two=c.api.openNativeAction(a.id,'share',a.frame.contentWindow);assert.equal(one,two);assert.equal(c.popups.length,1);release();assert.equal(await one,true);const target=c.popups[0],url=new URL(target.url),{n,calls}=native(c,url);await n.api.ready;target.PlanLibrary=n.api;target.SHARED=n.context.SHARED;target.__editorPlanId=n.context.__editorPlanId;let focuses=0;target.focus=()=>focuses++;assert.equal(await c.api.openNativeAction(a.id,'share',a.frame.contentWindow),true);assert.equal(c.popups.length,1);assert.equal(focuses,1);assert.equal(calls.share,1);assert.equal(calls.join+calls.rooms,0);
});
test('source change, installer epoch, popup close or pagehide during await abort ticket without touching peer',async()=>{
 for(const change of ['edit','epoch','close','pagehide']){const {c,a,b}=await comparison(),peer=plain(b.frame.contentWindow.EditorPane.state()),original=c.api.repo.saveDraft;let release,entered=false;c.api.repo.saveDraft=async(...args)=>{if(!entered){entered=true;await new Promise(resolve=>release=resolve);}return original(...args);};
 const pending=c.api.openNativeAction(a.id,'share',a.frame.contentWindow);await until(()=>entered);if(change==='edit'){await a.frame.contentWindow.EditorPane.install(fixture(999),{dirty:true,cataloguePack:'native-pack'});c.api.edited(a.id);}else if(change==='epoch')a.installEpoch=(a.installEpoch||0)+1;else if(change==='pagehide')c.events.get('pagehide')();else c.popups[0].close();release();assert.equal(await pending,false);assert.equal(c.popups[0].closed,true);assert.equal(c.popups[0].url,undefined);assert.deepEqual(plain(b.frame.contentWindow.EditorPane.state()),peer);assert.equal(a.frame.contentWindow.DIRTY,true);assert.equal(c.api.panes.size,2);}
});
test('draft write conflict, quota abort and view CAS conflict keep source edits and head',async()=>{
 for(const fault of ['conflict','quota','view']){const {c,a}=await comparison(),before=plain(a.frame.contentWindow.EditorPane.state()),head=plain(await c.api.repo.read(a.planId));if(fault==='conflict')c.api.repo.saveDraft=async()=>({status:'conflict'});else if(fault==='quota')c.mem.failNext(new DOMException('Disk full','QuotaExceededError'),'webcad-plan-library-lab-ui-v1');else c.api.repo.setView=async()=>{throw Error('view_generation_conflict');};assert.equal(await c.api.openNativeAction(a.id,'share',a.frame.contentWindow),false);assert.deepEqual(plain(a.frame.contentWindow.EditorPane.state()),before);assert.deepEqual(plain(await c.api.repo.read(a.planId)),head);assert.equal(c.popups[0].closed,true);assert.equal(c.popups[0].url,undefined);}
});
test('expired, replayed, conflicting preset/room or tampered draft ticket never reaches preset/share/join',async()=>{
 for(const fault of ['expired','replay','preset','room','draft','role']){const {c,a}=await comparison(),{url,token}=await launch(c,a),store=c.mem.dbs.get('webcad-plan-library-lab-ui-v1').stores;
 if(fault==='expired')store.get('views').get(token).nativeAction.expiresAt=Date.now()-1;if(fault==='replay')store.get('views').get(token).nativeAction.status='consumed';if(fault==='role')store.get('views').get(token).nativeAction.role='comparison';if(fault==='draft')store.get('drafts').get(JSON.stringify([token,a.planId])).payload=fixture(999);if(fault==='preset')url.searchParams.set('preset','blank');if(fault==='room')url.searchParams.set('room','abcdefghijklmnopqrstuv');const {n,calls}=native(c,url);await n.api.ready;assert.equal(calls.share+calls.join+calls.rooms,0);assert.equal(n.context.presetLoads,undefined);assert.equal(n.api.nativeActionStatus,'failed');assert.notEqual(n.context.__editorPlanId,a.planId);assert.equal(a.frame.contentWindow.DIRTY,true);assert.match(status(n),/保持/);}
});
test('duplicate native startup claims only once; copied consumed ticket remains a failed replay',async()=>{
 const {c,a}=await comparison(),{url,token}=await launch(c,a),left=native(c,url),right=native(c,url);await Promise.all([left.n.api.ready,right.n.api.ready]);assert.equal(left.calls.share+right.calls.share,1);assert.equal([left.n.api.nativeActionStatus,right.n.api.nativeActionStatus].filter(v=>v==='failed').length,1);assert.equal((await c.api.repo.get('views',token)).nativeAction.status,'consumed');const refresh=native(c,url);await refresh.n.api.ready;assert.equal(refresh.calls.share+refresh.calls.join,0);assert.equal(refresh.n.api.nativeActionStatus,'failed');assert.ok(await c.api.repo.get('drafts',JSON.stringify([token,a.planId])));
});
test('native install cancellation/fault and runtime view failure restore identity, history and view; failed owner can be reopened',async()=>{
 for(const fault of ['install','cancel','view','corrupt']){const {c,a}=await comparison(),{url,token,target}=await launch(c,a);const {n,calls}=native(c,url,{before:ctx=>{if(fault==='install')ctx.EditorPane.install=async()=>{throw Error('Synthetic native draw failure');};if(fault==='cancel')ctx.EditorPane.install=async()=>false;}});if(fault==='view'){const original=n.api.repo.setView;n.api.repo.setView=async(...args)=>{if(args[0]!==token)throw Error('Synthetic runtime view failure');return original(...args);};}if(fault==='corrupt')c.mem.dbs.get('webcad-plan-library-lab-ui-v1').stores.get('revisions').get(c.api.plans.get(a.planId).baseRevisionId).payload='{}';await n.api.ready;assert.equal(calls.share+calls.join,0);assert.notEqual(n.context.__editorPlanId,a.planId);assert.deepEqual(n.plan,fixture());assert.equal(n.api.nativeActionStatus,'failed');assert.equal((await c.api.repo.get('views',token)).nativeAction.status,'failed');assert.ok(!n.document.body.inert);assert.equal(a.frame.contentWindow.DIRTY,true);if(fault!=='corrupt'){target.PlanLibrary=n.api;assert.equal(await c.api.openNativeAction(a.id,'share',a.frame.contentWindow),true);assert.equal(c.popups.length,2);}}
});
test('native later same-ID save conflicts preserve old comparison draft and do not overwrite new head',async()=>{
 const {c,a}=await comparison(),{url}=await launch(c,a),{n}=native(c,url);await n.api.ready;n.edit(fixture(777));await tick();await n.api.persistPane('native-editor',a.planId,n.plan);assert.equal(a.frame.contentWindow.EditorPane.snapshot().rooms[0].x,321);assert.equal(a.frame.contentWindow.DIRTY,true);await assert.rejects(c.api.persistPane(a.id,a.planId,a.frame.contentWindow.EditorPane.snapshot()),/競合/);assert.equal((await c.api.repo.read(a.planId)).payload.rooms[0].x,777);assert.equal(a.frame.contentWindow.DIRTY,true);
});
test('active native room provenance reaches disconnected comparison; native action prepares existing retry only',async()=>{
 const room='abcdefghijklmnopqrstuv',h=libraryContext();await h.api.ready;await h.api.withSharedIdentity(room,()=>{h.context.SHARED.roomId=room;h.context.SHARED.roomGeneration=3;});assert.equal(await h.api.openComparison(),true);const c=libraryContext({mem:h.mem,native:false,search:new URL(h.popups[0].url).search});await c.api.ready;const a=[...c.api.panes.values()][0];await a.frame.contentWindow.EditorPane.install(fixture(432),{dirty:true,cataloguePack:'native-pack'});c.api.edited(a.id);await tick();const {url}=await launch(c,a),{n,calls}=native(c,url);await n.api.ready;assert.equal(n.context.__editorPlanId,'shared-room-'+room);assert.equal(n.context.SHARED.roomId,null);assert.equal(n.api.nativeActionRoomId,room);assert.equal(calls.share,1);assert.equal(calls.join+calls.rooms,0);assert.match(calls.message,/再接続/);assert.equal(a.frame.contentWindow.EditorPane.snapshot().rooms[0].x,432);assert.equal(a.frame.contentWindow.DIRTY,true);
 const html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),code=html.slice(html.indexOf('function sharedRoomFromLocation(){'),html.indexOf('function sharedUrl(){')),ctx={NATIVE_PLAN_EDITOR:true,window:{PlanLibrary:n.api},location:{search:url.search,hash:''},URLSearchParams};vm.runInNewContext(code,ctx);assert.equal(ctx.sharedRoomFromLocation(),room);
});
test('shared-room ID without verified provenance is blocked instead of silently creating another room',async()=>{
 const {c,a}=await comparison(),id='shared-room-abcdefghijklmnopqrstuv',r=c.api.plans.get(a.planId);c.api.plans.delete(a.planId);r.id=id;a.planId=id;a.frame.contentWindow.__editorPlanId=id;c.api.plans.set(id,r);assert.equal(await c.api.openNativeAction(a.id,'share',a.frame.contentWindow),false);assert.equal(c.popups.length,0);assert.match(status(c),/元の共同編集ルーム/);
});

test('real detached pane clone field order is normalized for ticket and native state verification',async()=>{
 const clone=require(path.join(ROOT,'assets/js/parallel-editors.js')).cloneState,{c,a}=await comparison();c.context.cloneEditorPaneState=clone;const before=plain(a.frame.contentWindow.EditorPane.state()),{url}=await launch(c,a),{n,calls}=native(c,url,{before:ctx=>ctx.cloneEditorPaneState=clone});await n.api.ready;assert.equal(calls.share,1);assert.deepEqual(plain(n.context.EditorPane.state()),before);assert.equal(n.api.nativeActionStatus,'ready');
});

test('copied original-room reconnect URL excludes consumed handoff and remains a normal share URL',()=>{
 const html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),code=html.slice(html.indexOf('function sharedUrl(){'),html.indexOf('function sharedSetStatus(')),room='abcdefghijklmnopqrstuv',ctx={URL,location:{href:'https://example.test/index.html?nativeAction=consumed-token'},SHARED:{roomId:room}};vm.runInNewContext(code,ctx);const url=new URL(ctx.sharedUrl());assert.equal(url.searchParams.has('nativeAction'),false);assert.equal(url.searchParams.has('room'),false);assert.equal(url.hash,'#room='+room);
});
test('unacknowledged destination stays coalesced until ticket expiry, then retries from retained draft',async()=>{
 const {c,a}=await comparison();let now=Date.now();c.context.Date=class extends Date{static now(){return now;}};const before=plain(a.frame.contentWindow.EditorPane.state()),{token,target}=await launch(c,a);assert.equal(await c.api.openNativeAction(a.id,'share',a.frame.contentWindow),false);assert.equal(c.popups.length,1);assert.match(status(c),/まだ準備を確認できません/);now+=300001;assert.equal(await c.api.openNativeAction(a.id,'share',a.frame.contentWindow),true);assert.equal(c.popups.length,2);assert.equal(target.closed,false);await tick();assert.equal((await c.api.repo.get('views',token)).nativeAction.status,'cancelled');assert.deepEqual(plain(a.frame.contentWindow.EditorPane.state()),before);
});
test('native startup is inert throughout ticket verification and expiry during final persistence rolls back',async()=>{
 const {c,a}=await comparison(),{url,token}=await launch(c,a);let now=Date.now(),release,entered=false;const {n,calls}=native(c,url,{before:ctx=>{ctx.Date=class extends Date{static now(){return now;}};}}),original=n.api.repo.get;
 n.api.repo.get=async(...args)=>{if(!entered){entered=true;await new Promise(resolve=>release=resolve);}return original(...args);};await until(()=>entered);assert.equal(n.document.body.inert,true);const update=n.api.repo.updateView;n.api.repo.updateView=async(...args)=>{const result=await update(...args);if(result.nativeAction?.status==='consumed')now=result.nativeAction.expiresAt+1;return result;};release();await n.api.ready;assert.equal(n.api.nativeActionStatus,'failed');assert.equal(calls.share+calls.join+calls.rooms,0);assert.ok(!n.document.body.inert);assert.notEqual(n.context.__editorPlanId,a.planId);assert.equal((await c.api.repo.get('views',token)).nativeAction.status,'failed');assert.equal(a.frame.contentWindow.DIRTY,true);
});
test('actual installer restores retained 3D camera in a 2D native handoff after delayed engine readiness',async()=>{
 const {runtime}=require('./parallel-view-preferences-support.cjs'),{c,a}=await comparison(),source=runtime();source.ctx.ST.view='2d';source.ctx.ST.showGrid=false;source.ctx.ST.snap=455;source.ctx.ST.panX=123;source.ctx.DIRTY=true;source.ctx.camExt.position.set(9,8,7);a.frame.contentWindow.EditorPane=source.editor;Object.defineProperty(a.frame.contentWindow,'DIRTY',{get:()=>source.ctx.DIRTY});c.api.edited(a.id);await tick();const before=plain(source.editor.state()),{url}=await launch(c,a),target=runtime(),listeners=new Map(),camera=target.ctx.camExt,orbit=target.ctx.orbit;
 target.ctx.ST.view='2d';target.ctx.camExt=null;target.ctx.orbit=null;target.ctx.ren=null;target.ctx.threeModulesReady=false;target.ctx.addEventListener=(name,fn)=>listeners.set(name,fn);target.ctx.removeEventListener=(name,fn)=>{if(listeners.get(name)===fn)listeners.delete(name);};let initialized=0;target.ctx.init3D=()=>{initialized++;target.ctx.camExt=camera;target.ctx.orbit=orbit;target.ctx.ren={};};
 const {n,calls}=native(c,url,{before:ctx=>{ctx.EditorPane=target.editor;Object.defineProperty(ctx,'DIRTY',{get:()=>target.ctx.DIRTY,set:v=>target.ctx.DIRTY=v});}});await until(()=>listeners.has('three-ready'));assert.equal(n.document.body.inert,true);assert.equal(calls.share,0);assert.equal(target.ctx.DATA.rooms[0].id,'A');target.ctx.threeModulesReady=true;listeners.get('three-ready')();await n.api.ready;assert.equal(n.api.nativeActionStatus,'ready',status(n));assert.equal(initialized,1);assert.equal(calls.share,1);assert.equal(calls.join+calls.rooms,0);assert.deepEqual(plain(target.editor.state()),before);assert.deepEqual(plain(source.editor.state()),before);assert.ok(!n.document.body.inert);assert.equal(target.ctx.ST.view,'2d');
});
test('actual pending room creation keeps its native owner and repeat/close cannot start a second room',async()=>{
 const {c,a,b}=await comparison(),peer=plain(b.frame.contentWindow.EditorPane.state()),{url,target}=await launch(c,a),{n}=native(c,url);await n.api.ready;const ctx=n.context,html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');ctx.serializeDataSnapshot=()=>JSON.stringify(ctx.DATA);ctx.sharedRoomFromLocation=()=>null;ctx.sceneV3LocalOnlyPlan=()=>false;ctx.sharedSetStatus=()=>{};ctx.closeSharedSocket=()=>{};ctx.copySharedUrl=async()=>{};for(const name of ['normalizeLegacyFurnitureItems','ensureObjectIds','ensureExteriorWallSettings','ensureInteriorWallSettings','ensureRoofAppearance','syncExteriorWallSettings','captureViewState'])ctx[name]=()=>{};
 vm.runInContext(html.slice(html.indexOf('async function createSharedRoom(){'),html.indexOf('function leaveSharedRoom(){')),vm.createContext(ctx));vm.runInContext(html.slice(html.indexOf('function closeShareDialog(){'),html.indexOf('function closeShareDialogOnBackdrop(')),ctx);await n.api.repo.save({planId:'other-native-plan',name:'Other',operationId:'seed-native-other',baseRevisionId:null,baseGeneration:0,payload:fixture(888)});let release,requests=0;ctx.fetch=async()=>{requests++;return new Promise(resolve=>release=()=>resolve({ok:false,status:500}));};const pending=ctx.createSharedRoom();await until(()=>!!release);assert.equal(ctx.SHARED.createPending.planId,a.planId);await assert.rejects(n.api.openPlan('other-native-plan'),/作成中/);await assert.rejects(n.api.newPlan(),/作成中/);ctx.closeShareDialog();await ctx.createSharedRoom();assert.equal(requests,1);target.PlanLibrary=n.api;target.__editorPlanId=ctx.__editorPlanId;assert.equal(await c.api.openNativeAction(a.id,'share',a.frame.contentWindow),true);assert.equal(c.popups.length,1);release();await pending;assert.equal(ctx.SHARED.createPending,null);assert.equal(ctx.__editorPlanId,a.planId);ctx.clearDirty();await n.api.openPlan('other-native-plan');assert.equal(ctx.__editorPlanId,'other-native-plan');assert.equal(a.frame.contentWindow.DIRTY,true);assert.deepEqual(plain(b.frame.contentWindow.EditorPane.state()),peer);
});

test('successful native action cleans only its ticket URL; ordinary repeated refresh restores the same dirty ID without repeating share',async()=>{
 const {c,a}=await comparison(),{url,token}=await launch(c,a),{n,calls}=native(c,url);await n.api.ready;assert.equal(n.context.location.search,'');assert.equal(n.context.location.hash,'');assert.equal(calls.share,1);assert.equal((await c.api.repo.get('views',token)).nativeAction.status,'consumed');let fresh=n;
 for(let i=0;i<2;i++){fresh=libraryContext({mem:c.mem,sessionStorage:n.sessionStorage,search:fresh.context.location.search});await fresh.api.ready;assert.equal(fresh.context.__editorPlanId,a.planId);assert.deepEqual(plain(fresh.plan),plain(n.plan));assert.equal(fresh.context.DIRTY,true);assert.equal(fresh.context.presetLoads,undefined);assert.deepEqual(fresh.popups,[]);}
 const replay=native(c,url);await replay.n.api.ready;assert.equal(replay.n.api.nativeActionStatus,'failed');assert.equal(replay.n.context.location.search,url.search);
});
test('ordinary refresh after an existing-room native action retains disconnected original-room provenance',async()=>{
 const room='abcdefghijklmnopqrstuv',h=libraryContext();await h.api.ready;await h.api.withSharedIdentity(room,()=>{h.context.SHARED.roomId=room;h.context.SHARED.roomGeneration=3;});await h.api.openComparison();const c=libraryContext({mem:h.mem,native:false,search:new URL(h.popups[0].url).search});await c.api.ready;const a=[...c.api.panes.values()][0],{url}=await launch(c,a),{n}=native(c,url);await n.api.ready;assert.equal(n.context.location.search,'');const fresh=libraryContext({mem:h.mem,sessionStorage:n.sessionStorage,search:n.context.location.search});await fresh.api.ready;assert.equal(fresh.context.__editorPlanId,'shared-room-'+room);assert.equal(fresh.api.nativeActionRoomId,room);assert.equal(fresh.context.SHARED.roomId,null);
});

test('native action sessionStorage failure keeps the ticket URL and rejects readiness instead of cleaning an unadopted session',async()=>{
 const {c,a}=await comparison(),{url,token}=await launch(c,a),storage=new Storage();storage.setItem=()=>{throw new DOMException('Anonymous session store denied','QuotaExceededError');};const {n,calls}=native(c,url,{sessionStorage:storage});await n.api.ready;assert.equal(n.api.nativeActionStatus,'failed');assert.equal(n.context.location.search,url.search);assert.equal(calls.share,0);assert.equal((await c.api.repo.get('views',token)).nativeAction.status,'failed');assert.equal(a.frame.contentWindow.DIRTY,true);assert.equal(n.document.body.inert,undefined);
});
