'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {libraryContext,memoryIDB,fixture,Storage,ROOT}=require('./plan-library-test-support.cjs');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const plain=v=>JSON.parse(JSON.stringify(v));
async function settle(){for(let i=0;i<30;i++)await tick();}
function current(h){return h.api.panes.get('native-editor');}
async function save(h){const p=current(h);return h.api.persistPane(p.id,p.planId,h.plan);}
async function seed(h,id='other',x=200){return h.api.repo.save({planId:id,name:id,operationId:'seed',payload:fixture(x),baseRevisionId:null,baseGeneration:0});}
async function decide(h,task,choice){let b;for(let i=0;i<600&&!b;i++){await new Promise(resolve=>setTimeout(resolve,5));b=h.document.querySelector('[data-library-decision="'+choice+'"]');}assert.ok(b,'dirty choice shown');b.onclick();return task;}
test('ordinary bootstrap uses native single pane; no legacy copy or plan save on startup',async()=>{
 const h=libraryContext();await h.api.ready;assert.equal(h.api.panes.size,1);assert.equal(h.context.presetLoads,1);assert.match(h.context.__editorPlanId,/^plan-/);assert.equal(current(h).frame.contentWindow.document,h.document);assert.equal((await h.api.repo.list()).length,0);assert.equal((await h.api.repo.list('rawSources')).length,0);assert.equal(h.document.querySelector('[data-library-current]').value,h.context.__editorPlanId);
});
test('ordinary save and reload keep ID, unknown fields and native history/view state through new lifecycle',async()=>{
 const h=libraryContext();await h.api.ready;const id=h.context.__editorPlanId;h.edit(fixture(123));await tick();const result=await save(h);assert.equal(result.status,'saved');h.context.clearDirty();assert.deepEqual(plain((await h.api.repo.read(id)).payload),fixture(123));const fresh=libraryContext({mem:h.mem,sessionStorage:h.sessionStorage,plan:fixture(999)});await fresh.api.ready;assert.equal(fresh.context.__editorPlanId,id);assert.deepEqual(fresh.plan,fixture(123));assert.deepEqual(fresh.context.EditorPane.state().history,['undo-fixture']);assert.deepEqual(fresh.context.EditorPane.state().redo,['redo-fixture']);assert.equal(fresh.context.EditorPane.state().view.twoD.zoom,2);assert.equal(fresh.context.EditorPane.state().cataloguePack,'native-pack');assert.equal(fresh.context.presetLoads,undefined);assert.notEqual(fresh.api.session,h.api.session);
});
test('transaction quota/abort rejects save, leaves current dirty and previous head intact',async()=>{
 const h=libraryContext();await h.api.ready;h.edit(fixture(111));await tick();await save(h);const id=h.context.__editorPlanId,previous=(await h.api.repo.read(id)).revision.id;h.edit(fixture(222));await settle();h.mem.failNext(new DOMException('Disk full','QuotaExceededError'),'webcad-plan-library-lab-ui-v1');await assert.rejects(save(h),{name:'QuotaExceededError'});assert.equal(h.context.DIRTY,true);assert.equal((await h.api.repo.read(id)).revision.id,previous);assert.deepEqual(h.plan,fixture(222));
});
test('failed/cancelled native install never changes current identity or scene',async()=>{
 const h=libraryContext();await h.api.ready;await save(h);await seed(h);const id=h.context.__editorPlanId,before=h.plan;h.failInstall(Error('normalization failed'));await assert.rejects(h.api.openPlan('other'),/normalization failed/);assert.equal(h.context.__editorPlanId,id);assert.deepEqual(h.plan,before);h.failInstall(null);h.cancelInstall();await assert.rejects(h.api.openPlan('other'),/取り消/);assert.equal(h.context.__editorPlanId,id);assert.deepEqual(h.plan,before);
});
test('dirty cancel does not switch or write new revision; discard preserves original draft',async()=>{
 const h=libraryContext();await h.api.ready;await save(h);await seed(h);const id=h.context.__editorPlanId;h.edit(fixture(777));await tick();const head=(await h.api.repo.read(id)).revision.id;assert.equal(await decide(h,h.api.openPlan('other'),'cancel'),false);assert.equal(h.context.__editorPlanId,id);assert.equal((await h.api.repo.read(id)).revision.id,head);assert.equal(await decide(h,h.api.openPlan('other'),'discard'),true);assert.equal(h.context.__editorPlanId,'other');assert.equal((await h.api.repo.read(id)).revision.id,head);assert.ok((await h.api.repo.list('drafts')).some(d=>d.sessionId.startsWith('discard:')&&d.payload.rooms[0].x===777));
});
test('stale native tab saves conflict without advancing head or losing edit',async()=>{
 const h=libraryContext();await h.api.ready;await save(h);const other=libraryContext({mem:h.mem,sessionStorage:h.sessionStorage});await other.api.ready;const id=h.context.__editorPlanId;other.edit(fixture(444));await tick();await save(other);h.edit(fixture(333));await tick();await assert.rejects(save(h),/競合/);assert.equal((await h.api.repo.read(id)).payload.rooms[0].x,444);assert.equal(h.context.DIRTY,true);assert.equal(h.plan.rooms[0].x,333);assert.ok((await h.api.repo.list('revisions')).some(r=>r.kind==='conflict'&&JSON.parse(r.payload).rooms[0].x===333));
});
test('legacy malformed/raw originals are untouched; explicit copy preserves exact bytes and repeated identity',async()=>{
 const mem=memoryIDB(),local=new Storage();const raw='  '+JSON.stringify(fixture(444))+'\n',bad='{malformed';local.setItem('webcad-plan-v1',raw);mem.seed('webcad','plans','webcad-plan-v1',bad);const h=libraryContext({mem,localStorage:local});await h.api.ready;assert.equal((await h.api.repo.list()).length,0);const sources=await h.api.repo.readLegacySources();assert.equal(sources.length,2);const malformed=await h.api.repo.importSource(sources.find(s=>s.raw===bad));assert.equal(malformed.plans.length,0);assert.equal((await h.api.repo.get('rawSources',malformed.snapshotId)).raw,bad);const first=await h.api.repo.importSource(sources.find(s=>s.raw===raw));const repeat=await h.api.repo.importSource(sources.find(s=>s.raw===raw));assert.equal(first.plans[0].planId,repeat.plans[0].planId);await h.api.openPlan(first.plans[0].planId);assert.equal(h.plan.rooms[0].x,444);assert.equal(local.getItem('webcad-plan-v1'),raw);assert.equal(mem.dbs.get('webcad').stores.get('plans').get('webcad-plan-v1'),bad);
});
test('native comparison handoff checkpoints same plan ID, separate session, dirty source and original legacy bytes',async()=>{
 const local=new Storage();local.setItem('webcad-plan-v1','old bytes');const h=libraryContext({localStorage:local});await h.api.ready;h.edit(fixture(543));await tick();const id=h.context.__editorPlanId;await seed(h,'comparison-other');assert.equal(await h.api.openComparison('comparison-other'),true);const url=new URL(h.popups[0].url),session=url.searchParams.get('librarySession');assert.equal(url.searchParams.get('planLibrary'),'1');assert.notEqual(session,h.api.session);assert.deepEqual((await h.api.repo.get('views',session)).panelPlanIds,[id,'comparison-other']);const d=await h.api.repo.get('drafts',JSON.stringify([session,id]));assert.deepEqual(d.payload,fixture(543));assert.equal(d.dirty,true);assert.equal(h.context.DIRTY,true);assert.equal((await h.api.repo.read(id)).revision.kind,'unsaved-checkpoint');assert.equal(local.getItem('webcad-plan-v1'),'old bytes');
});
test('shared room uses ordinary protected save while independent navigation is blocked',async()=>{
 const h=libraryContext({joined:true});await h.api.ready;assert.equal(h.context.presetLoads,undefined);assert.equal(h.api.plans.get(h.context.__editorPlanId).name,'共同編集のプラン');await save(h);await seed(h);await assert.rejects(h.api.openPlan('other'),/共同編集中/);assert.equal(h.context.SHARED.roomId,'room-fixture');
});
test('missing library dependencies fail closed; never use legacy storage adapter',async()=>{
 for(const missing of ['PlanRepositoryLab','createEditorModelPool','EditorPane']){const h=libraryContext({missing});await h.api.ready;await assert.rejects(h.api.persistPane('native-editor','old',fixture()),/初期化/);assert.equal(h.mem.calls.length,0);assert.equal(h.context.presetLoads,undefined);}
 const source=fs.readFileSync(path.join(ROOT,'assets/js/app-state.js'),'utf8'),part=source.slice(source.indexOf('var StorageAdapter ='),source.indexOf('\nfunction markDirty()',source.indexOf('var StorageAdapter =')));let count=0;const sandbox={NATIVE_PLAN_EDITOR:true,NATIVE_EDITOR_PANE:'native-editor',window:{__editorPlanId:'stable-id',PlanLibrary:{ready:Promise.resolve(),persistPane:(p,id,data)=>{assert.equal(p,'native-editor');assert.equal(id,'stable-id');assert.deepEqual(JSON.parse(JSON.stringify(data)),fixture());count++;return Promise.resolve({status:'saved'});},readSavedPane:id=>{assert.equal(id,'stable-id');count++;return Promise.resolve(fixture());}}},localStorage:{getItem(){throw Error('legacy touched');},removeItem(){throw Error('legacy deleted');}},indexedDB:{open(){throw Error('legacy db touched');}}};vm.runInNewContext(part,sandbox);await sandbox.StorageAdapter.save(fixture());await sandbox.StorageAdapter.load();assert.equal(await sandbox.StorageAdapter.hasData(),true);assert.equal(count,3);
});
test('explicit blank/default start has a fresh identity and cannot replace prior saved plan',async()=>{
 const h=libraryContext();await h.api.ready;await save(h);const id=h.context.__editorPlanId,head=(await h.api.repo.read(id)).revision.id;const fresh=libraryContext({mem:h.mem,sessionStorage:h.sessionStorage,search:'?preset=blank',plan:{walls:[],rooms:[],items:[],startMode:'blank'}});await fresh.api.ready;assert.notEqual(fresh.context.__editorPlanId,id);await save(fresh);assert.equal((await h.api.repo.read(id)).revision.id,head);assert.equal((await h.api.repo.list()).length,2);
});
test('comparison loads native handoff draft, child save uses same identity, native reopen reads newest clean head',async()=>{
 const h=libraryContext();await h.api.ready;await save(h);h.context.clearDirty();const id=h.context.__editorPlanId;await seed(h,'comparison-other');await h.api.openComparison('comparison-other');const url=new URL(h.popups[0].url),comparison=libraryContext({mem:h.mem,native:false,search:url.search});await comparison.api.ready;assert.equal(comparison.api.panes.size,2);const p=[...comparison.api.panes.values()][0];assert.equal(p.planId,id);const changed=fixture(989);await p.frame.contentWindow.EditorPane.install(changed,{dirty:true});comparison.api.edited(p.id);await settle();const result=await comparison.api.persistPane(p.id,id,changed);assert.equal(result.status,'saved');p.frame.contentWindow.clearDirty();assert.deepEqual(plain(await comparison.api.readSavedPane(id)),changed);const fresh=libraryContext({mem:h.mem,sessionStorage:h.sessionStorage});await fresh.api.ready;assert.equal(fresh.context.__editorPlanId,id);assert.deepEqual(fresh.plan,changed);assert.equal(fresh.context.DIRTY,false);
});
test('comparison keeps four retained IDs and only two live panes; collapse/reopen preserves drafts',async()=>{
 const h=libraryContext();await h.api.ready;for(let i=1;i<=4;i++)await seed(h,'p'+i,i*100);const session='comparison-layout-fixture';await h.api.repo.setView(session,{retainedPlanIds:['p1','p2','p3','p4'],panelPlanIds:['p1','p2'],sync:false});const c=libraryContext({mem:h.mem,native:false,search:'?planLibrary=1&librarySession='+session});await c.api.ready;assert.equal(c.api.panes.size,2);assert.equal(c.api.retained.length,4);const p=[...c.api.panes.values()][1];await p.frame.contentWindow.EditorPane.install(fixture(654),{dirty:true,history:['kept'],redo:['redo'],cataloguePack:'rpg-mansion'});c.api.edited(p.id);await settle();await c.api.layout(1);assert.equal(c.api.panes.size,1);assert.equal(c.api.retained.length,4);await c.api.layout(2);assert.equal(c.api.panes.size,2);const reopened=[...c.api.panes.values()].find(p=>p.planId==='p2');assert.equal(reopened.frame.contentWindow.EditorPane.snapshot().rooms[0].x,654);assert.deepEqual(reopened.frame.contentWindow.EditorPane.state().history,['kept']);assert.equal(reopened.frame.contentWindow.DIRTY,true);
});
test('existing ordinary and child storage adapters dispatch to same controller; preview saves stay forbidden',async()=>{
 const source=fs.readFileSync(path.join(ROOT,'assets/js/app-state.js'),'utf8'),part=source.slice(source.indexOf('var StorageAdapter ='),source.indexOf('\nfunction markDirty()',source.indexOf('var StorageAdapter =')));const calls=[];const api={persistPane:(pane,id,data)=>{calls.push(['save',pane,id]);return Promise.resolve({status:'saved'});},readSavedPane:id=>{calls.push(['load',id]);return Promise.resolve(fixture());}};const child={EDITOR_PANE:'test-child',COMPARISON_PREVIEW:false,window:{__editorPlanId:'stable-id',parent:{ParallelEditors:api}}};vm.runInNewContext(part,child);await child.StorageAdapter.save(fixture());await child.StorageAdapter.load();assert.equal(await child.StorageAdapter.hasData(),true);assert.deepEqual(calls,[['save','test-child','stable-id'],['load','stable-id'],['load','stable-id']]);const preview={EDITOR_PANE:'test-child',COMPARISON_PREVIEW:true};vm.runInNewContext(part,preview);await assert.rejects(preview.StorageAdapter.save(fixture()),/Read-only/);assert.equal(await preview.StorageAdapter.load(),null);assert.equal(await preview.StorageAdapter.hasData(),false);
});
test('native derived plans reuse repository and retain source ID, payload and single live editor',async()=>{
 const h=libraryContext();await h.api.ready;const source=h.context.__editorPlanId,before=h.plan,derived=fixture(900);const id=await h.api.createIndependentPlan(derived,'RPG derived fixture',{sourcePaneId:'native-editor',sourcePlanId:source,sourceSnapshot:JSON.stringify(before),isCurrent:()=>true,cataloguePack:'rpg-mansion'});assert.notEqual(id,source);assert.equal(h.api.panes.size,1);assert.equal(h.context.__editorPlanId,source);assert.deepEqual(h.plan,before);assert.deepEqual(plain((await h.api.repo.read(source)).payload),before);assert.deepEqual(plain((await h.api.repo.read(id)).payload),derived);assert.equal((await h.api.repo.get('drafts',JSON.stringify([h.api.session,id]))).cataloguePack,'rpg-mansion');assert.equal(h.api.retained.length,2);const fresh=libraryContext({mem:h.mem,sessionStorage:h.sessionStorage});await fresh.api.ready;assert.equal(fresh.context.__editorPlanId,source);assert.equal(fresh.api.retained.length,2);assert.deepEqual(fresh.plan,before);
});
test('view transaction failure during native switch rolls back identity and visible state',async()=>{
 const h=libraryContext();await h.api.ready;await save(h);await seed(h);const id=h.context.__editorPlanId,before=h.plan,original=h.api.repo.setView;h.api.repo.setView=async()=>{throw Error('view storage abort');};await assert.rejects(h.api.openPlan('other'),/view storage abort/);h.api.repo.setView=original;assert.equal(h.context.__editorPlanId,id);assert.deepEqual(h.plan,before);assert.equal(current(h).planId,id);assert.deepEqual(plain((await h.api.repo.get('views',h.api.session)).panelPlanIds),[id]);
});
test('transaction completion owns save success; request-success followed by abort leaves no head or revision',async()=>{
 const h=libraryContext();await h.api.ready;h.mem.failNext(new DOMException('Commit aborted','AbortError'),'webcad-plan-library-lab-ui-v1');await assert.rejects(h.api.repo.save({planId:'abort-fixture',operationId:'aborted',payload:fixture(),baseRevisionId:null,baseGeneration:0}),{name:'AbortError'});assert.equal(await h.api.repo.read('abort-fixture'),null);assert.equal(await h.api.repo.get('revisions','abort-fixture:aborted'),undefined);
});
test('corrupt repository read rejects before native installation and leaves current plan visible',async()=>{
 const h=libraryContext();await h.api.ready;await save(h);const id=h.context.__editorPlanId,before=h.plan,saved=await h.api.repo.read(id),revs=h.mem.dbs.get('webcad-plan-library-lab-ui-v1').stores.get('revisions'),raw=revs.get(saved.revision.id);revs.set(raw.id,{...raw,payload:JSON.stringify(fixture(999))});await assert.rejects(h.api.reloadPlan('native-editor'),/revision_integrity_failed/);assert.equal(h.context.__editorPlanId,id);assert.deepEqual(h.plan,before);
});
test('native save respects repository canClean and concurrent editor changes; empty payload never dispatches save',async()=>{
 const source=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),part=source.slice(source.indexOf('async function savePlanToStorage(){'),source.indexOf('async function loadPlanFromStorage(){'));let calls=0,dirty=true,finish;const context={DATA:fixture(),SHARED:{roomId:null},StorageAdapter:{save:async()=>{calls++;return {canClean:false};}},serializeDataSnapshot(){return JSON.stringify(context.DATA);},setSaveButtonBusy(){},clearDirty(){dirty=false;},alert(){},normalizeLegacyFurnitureItems(){},ensureObjectIds(){},ensureExteriorWallSettings(){},ensureInteriorWallSettings(){},ensureRoofAppearance(){},ensureFloorMetadata(){},ensureHeightDefaults(){},syncExteriorWallSettings(){},captureViewState(){}};context.window=context;vm.runInNewContext(part,context);assert.equal(await context.savePlanToStorage(),true);assert.equal(dirty,true);context.StorageAdapter.save=()=>new Promise(resolve=>finish=resolve);const pending=context.savePlanToStorage();context.DATA=fixture(333);finish({canClean:true});assert.equal(await pending,true);assert.equal(dirty,true);context.DATA={walls:[],rooms:[],items:[],startMode:'blank'};const before=calls;await context.savePlanToStorage();assert.equal(calls,before);
});
test('direct ordinary load entry point dispatches protected installer and cannot reach default-on-failure legacy restore',async()=>{
 const source=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),part=source.slice(source.indexOf('async function loadPlanFromStorage(){'),source.indexOf('async function loadPlanFromStorageButton(){'));let calls=0;const context={NATIVE_PLAN_EDITOR:true,NATIVE_EDITOR_PANE:'native-editor',window:{PlanLibrary:{run:fn=>fn(),reloadPlan:id=>{assert.equal(id,'native-editor');calls++;return Promise.resolve(true);}}},StorageAdapter:{load(){throw Error('legacy restore reached');}},alert(){}};vm.runInNewContext(part,context);assert.equal(await context.loadPlanFromStorage(),true);assert.equal(calls,1);context.window.PlanLibrary={};assert.equal(await context.loadPlanFromStorage(),false);
});
test('anonymous legacy cross-floor reuse remains preserved and distinctly diagnosed from same-floor collision',()=>{
 const schema=require(path.join(ROOT,'assets/js/plan-schema.js')),wall={id:7,floor:1,x1:0,y1:0,x2:1000,y2:0,thick:120},cross={walls:[wall,{...wall,floor:2}],rooms:[],items:[]},same={...cross,walls:[wall,{...wall,x2:2000}]},before=JSON.stringify(cross);const across=schema.validatePlan(cross),collision=schema.validatePlan(same);assert.equal(across.ok,false);assert.equal(collision.ok,false);assert.equal(across.errors.filter(x=>/重複/.test(x)).length,1);assert.equal(collision.errors.filter(x=>/重複/.test(x)).length,1);assert.equal(JSON.stringify(cross),before);const normalized=schema.normalizePlan(cross);assert.deepEqual(normalized.walls.map(x=>x.id),[7,7]);assert.deepEqual(normalized.walls.map(x=>x.floor),[1,2]);
});
test('anonymous zero-length legacy wall is preserved by normalization; strict gate cannot silently repair it',()=>{
 const schema=require(path.join(ROOT,'assets/js/plan-schema.js')),legacy={walls:[{id:9,floor:2,x1:10,y1:20,x2:10,y2:20,thick:120}],rooms:[],items:[],interiorWallSettings:{faces:{'9:synthetic-face':{texture:'data:image/png;base64,c3ludGhldGlj'}}}},before=JSON.stringify(legacy),checked=schema.validatePlan(legacy);assert.equal(checked.ok,false);assert.equal(checked.errors.filter(x=>/始点と終点/.test(x)).length,1);const normalized=schema.normalizePlan(legacy);assert.equal(normalized.walls.length,1);assert.equal(normalized.walls[0].id,9);assert.deepEqual(normalized.interiorWallSettings,legacy.interiorWallSettings);assert.equal(JSON.stringify(legacy),before);
});
