'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {libraryContext,fixture,ROOT}=require('./plan-library-test-support.cjs');
const plain=value=>JSON.parse(JSON.stringify(value)),tick=()=>new Promise(resolve=>setImmediate(resolve));
async function until(check){for(let i=0;i<800;i++){if(check())return;await tick();}throw Error('condition did not settle');}
async function seed(h,id='second',x=200){return h.api.repo.save({planId:id,name:'Plan '+id,operationId:'seed-'+id,baseRevisionId:null,baseGeneration:0,payload:fixture(x)});}
async function save(h){const p=[...h.api.panes.values()][0];await h.api.persistPane(p.id,p.planId,h.plan);h.context.clearDirty();}
function button(h,id){return h.document.querySelector('[data-library-open-plan="'+id+'"]');}
function named(h,label){return h.document.querySelectorAll('button').find(b=>b.textContent===label);}
function header(c){const d=c.document,t=d.querySelector('#toolbar'),brand=d.createElement('b'),floor=d.createElement('select'),actions=d.createElement('div'),compare=d.createElement('button');brand.className='brand-mark';floor.id='floor-sel';actions.className='toolbar-actions';compare.id='compare-launch';actions.append(d.querySelector('#save-btn'),compare);t.append(brand,floor,actions);return {t,brand,floor,actions,compare};}
async function compareFixture(){const h=libraryContext();await h.api.ready;await save(h);for(let i=2;i<=5;i++)await seed(h,'p'+i,i*100);await h.api.openComparison('p2');const c=libraryContext({mem:h.mem,native:false,search:new URL(h.popups[0].url).search});await c.api.ready;return {h,c};}

test('actual attachment code places identity and existing comparison node directly after brand; actions retain their owners',async()=>{
 let nodes;const h=libraryContext({beforeLibrary:c=>nodes=header(c)});await h.api.ready;const identity=h.document.querySelector('.library-current');assert.deepEqual(nodes.t.children,[nodes.brand,identity,nodes.compare,nodes.floor,nodes.actions]);assert.equal(h.document.querySelector('#save-btn').parentNode,nodes.actions);assert.deepEqual(nodes.actions.children.filter(e=>e.dataset.libraryAction).map(e=>e.dataset.libraryAction),['duplicate','history']);assert.equal(identity.querySelector('[data-library-current]').attrs['aria-label'],'編集中のプラン');
});
test('mobile order and overflow contracts place identity before action row, while comparison pane branding remains hidden',()=>{
 const css=fs.readFileSync(path.join(ROOT,'assets/ui-refinement.css'),'utf8');assert.match(css,/#toolbar>\.brand-mark\{grid-row:1;grid-column:1\}/);assert.match(css,/#toolbar>\.library-current\{grid-row:2;grid-column:1;min-width:0/);assert.match(css,/#toolbar>#compare-launch\{grid-row:2;grid-column:2/);assert.match(css,/\.toolbar-actions\{display:flex;grid-column:1\/-1;grid-row:3;[^}]*overflow-x:auto/);assert.match(css,/\.editor-pane #toolbar>\.library-current\{grid-row:1;grid-column:1\}/);assert.match(css,/\.editor-pane #toolbar>\.toolbar-actions\{grid-row:2\}/);assert.match(css,/\.editor-pane #compare-launch,\.editor-pane #toolbar>\.brand-mark[^}]*display:none!important/);
});
test('comparison entry opens the existing list first; cancel and reopen do not make a popup or checkpoint',async()=>{
 const h=libraryContext();await h.api.ready;const before=h.plan,id=h.context.__editorPlanId;await h.api.openComparison();assert.equal(h.popups.length,0);assert.equal(h.document.querySelector('h2').textContent,'比較する案を選ぶ');assert.match(h.document.querySelector('[data-library-list-status]').textContent,/別の案が必要/);named(h,'閉じる').onclick();await h.api.openComparison();assert.equal(h.popups.length,0);assert.deepEqual(h.plan,before);assert.equal(h.context.__editorPlanId,id);assert.equal(await h.api.repo.read(id),null);
});
test('current saved plan is visibly marked and disabled; same-ID comparison is rejected without opening a tab',async()=>{
 const h=libraryContext();await h.api.ready;await save(h);await seed(h);await h.api.openComparison();const id=h.context.__editorPlanId,current=button(h,id);assert.equal(current.disabled,true);assert.match(current.parentNode.children[0].textContent,/編集中/);assert.equal(await h.api.openComparison(id),false);assert.equal(h.popups.length,0);assert.ok(h.document.querySelector('.library-dialog'));
});
test('async list selection opens synchronously in its direct row click, then hands off two specific plan IDs',async()=>{
 const h=libraryContext();await h.api.ready;await seed(h);h.edit(fixture(333));await h.api.openComparison();const before=h.plan,id=h.context.__editorPlanId;const pending=button(h,'second').onclick();assert.equal(h.popups.length,1,'window.open occurs before promise continuation');await pending;const session=new URL(h.popups[0].url).searchParams.get('librarySession'),view=await h.api.repo.get('views',session);assert.deepEqual(plain(view.panelPlanIds),[id,'second']);assert.deepEqual(plain((await h.api.repo.get('drafts',JSON.stringify([session,id]))).payload),before);assert.deepEqual(h.plan,before);assert.equal(h.context.DIRTY,true);assert.equal(h.document.querySelector('.library-dialog'),null);
 const c=libraryContext({mem:h.mem,native:false,search:new URL(h.popups[0].url).search});await c.api.ready;assert.deepEqual([...c.api.panes.values()].map(p=>p.planId),[id,'second']);
});
test('popup denial preserves list and edits; a second direct choice retries the existing action',async()=>{
 const h=libraryContext();await h.api.ready;await seed(h);h.edit(fixture(444));await h.api.openComparison();const before=h.plan,open=h.context.open;h.context.open=()=>null;const row=button(h,'second');assert.equal(await row.onclick(),false);assert.equal(h.popups.length,0);assert.equal(button(h,'second'),row);assert.match(h.document.querySelector('[data-library-list-status]').textContent,/ポップアップ/);assert.deepEqual(h.plan,before);assert.equal(h.context.DIRTY,true);h.context.open=open;assert.equal(await row.onclick(),true);assert.equal(h.popups.length,1);
});
test('first-plan explicit copy selects its new ID before offering existing JSON import, without auto-opening comparison',async()=>{
 const h=libraryContext();await h.api.ready;await save(h);await h.api.openComparison();const id=h.context.__editorPlanId,before=h.plan;await named(h,'現在の案を複製して編集').onclick();const heads=await h.api.repo.list(),copy=heads.find(p=>p.id!==id);assert.equal(heads.length,2);assert.ok(copy);assert.deepEqual(plain((await h.api.repo.read(copy.id)).payload),before);assert.equal(h.popups.length,0);assert.equal(h.document.querySelector('h2').textContent,'比較する案を選ぶ');assert.equal(h.context.__editorPlanId,copy.id);assert.equal(h.api.panes.get('native-editor').planId,copy.id);assert.match(h.document.querySelector('[data-library-list-status]').textContent,/複製した案を編集中/);assert.equal(button(h,copy.id).disabled,true);assert.equal(button(h,id).disabled,false);assert.equal(h.document.querySelector('[data-library-import-route]'),null);
});
test('first-copy dirty cancellation returns to the existing list and keeps the source ID and edits',async()=>{
 const h=libraryContext();await h.api.ready;h.edit(fixture(456));await h.api.openComparison();const id=h.context.__editorPlanId,before=h.plan,pending=named(h,'現在の案を複製して編集').onclick();await until(()=>h.document.querySelector('[data-library-decision="cancel"]'));h.document.querySelector('[data-library-decision="cancel"]').onclick();assert.equal(await pending,false);assert.equal(h.context.__editorPlanId,id);assert.deepEqual(h.plan,before);assert.equal((await h.api.repo.list()).length,0);assert.ok(named(h,'現在の案を複製して編集'));assert.doesNotMatch(h.document.querySelector('[data-library-list-status]').textContent,/JSON/);
});
test('new unsaved first-copy selection cancellation preserves source and committed copy, with no hint that import is safe yet',async()=>{
 const h=libraryContext();await h.api.ready;await h.api.openComparison();const id=h.context.__editorPlanId,before=h.plan,pending=named(h,'現在の案を複製して編集').onclick();await until(()=>h.document.querySelector('[data-library-decision="cancel"]'));h.document.querySelector('[data-library-decision="cancel"]').onclick();assert.equal(await pending,false);assert.equal(h.context.__editorPlanId,id);assert.deepEqual(h.plan,before);assert.equal((await h.api.repo.list()).length,2);assert.ok(h.document.querySelector('.library-dialog'));assert.doesNotMatch(h.document.querySelector('[data-library-list-status]').textContent,/複製した案を編集中/);
});
test('first-copy can complete a never-saved source through existing Save confirmation before selecting the independent copy',async()=>{
 const h=libraryContext();await h.api.ready;await h.api.openComparison();const original=h.context.__editorPlanId,before=h.plan;h.context.savePlanToStorage=async()=>{await save(h);return true;};const pending=named(h,'現在の案を複製して編集').onclick();await until(()=>h.document.querySelector('[data-library-decision="save"]'));h.document.querySelector('[data-library-decision="save"]').onclick();const copied=await pending;assert.notEqual(copied,original);assert.equal(h.context.__editorPlanId,copied);assert.deepEqual(plain((await h.api.repo.read(original)).payload),before);assert.deepEqual(plain((await h.api.repo.read(copied)).payload),before);assert.match(h.document.querySelector('[data-library-list-status]').textContent,/複製した案を編集中/);assert.equal(h.popups.length,0);
});
test('copy failure never selects another ID or claims that JSON import is safe on a copy',async()=>{
 const h=libraryContext();await h.api.ready;await save(h);await h.api.openComparison();const original=h.context.__editorPlanId,before=h.plan;h.api.repo.duplicate=async()=>{throw Error('copy storage failed');};assert.equal(await named(h,'現在の案を複製して編集').onclick(),false);assert.equal(h.context.__editorPlanId,original);assert.deepEqual(h.plan,before);assert.equal(h.context.DIRTY,false);assert.equal((await h.api.repo.list()).length,1);assert.equal(h.popups.length,0);assert.ok(h.document.querySelector('.library-dialog'));assert.match(h.document.querySelector('[data-library-list-status]').textContent,/copy storage failed/);
});
test('existing original and legacy-list Back routes preserve the comparison picker purpose',async()=>{
 const h=libraryContext();await h.api.ready;await save(h);const archived=await h.api.repo.importSource({sourceId:'anonymous-preserved',kind:'plan',raw:JSON.stringify(fixture(234))});await h.api.openComparison();await named(h,'原本を確認').onclick();assert.equal(h.document.querySelector('h2').textContent,'保存原本（読み取り専用）');await named(h,'戻る').onclick();assert.equal(h.document.querySelector('h2').textContent,'比較する案を選ぶ');await named(h,'旧保存を読み取り専用で一覧').onclick();assert.match(h.document.querySelector('h2').textContent,/旧保存/);await named(h,'戻る').onclick();assert.equal(h.document.querySelector('h2').textContent,'比較する案を選ぶ');assert.equal(h.popups.length,0);assert.equal(archived.plans.length,1);
});
test('two-pane list has explicit destination, and dirty cancel restores that list and both pane identities',async()=>{
 const {c}=await compareFixture(),[left,right]=[...c.api.panes.values()];await left.frame.contentWindow.EditorPane.install(fixture(555),{dirty:true,history:['keep-undo'],redo:['keep-redo']});await c.api.list({paneId:left.id});const destination=c.document.querySelector('[data-library-destination]');assert.equal(destination.value,left.id);const before=left.frame.contentWindow.EditorPane.state(),pending=button(c,'p3').onclick();await until(()=>c.document.querySelector('[data-library-decision="cancel"]'));c.document.querySelector('[data-library-decision="cancel"]').onclick();assert.equal(await pending,false);assert.deepEqual(left.frame.contentWindow.EditorPane.state(),before);assert.equal(right.planId,'p2');assert.equal(c.document.querySelector('[data-library-destination]').value,left.id);assert.ok(button(c,'p3'));assert.equal(c.api.retained.length,2);
});
test('third and fourth saved plans use existing pane switching, preserve drafts/history, and reload without making a third pane',async()=>{
 const {c}=await compareFixture(),[left,right]=[...c.api.panes.values()],leftId=left.planId;await right.frame.contentWindow.EditorPane.install(fixture(666),{dirty:true,history:['kept-undo'],redo:['kept-redo']});
 right.frame.contentWindow.savePlanToStorage=async()=>{await c.api.persistPane(right.id,right.planId,right.frame.contentWindow.EditorPane.snapshot());right.frame.contentWindow.clearDirty();return true;};
 const switchThird=c.api.openPlan('p3',right.id);await until(()=>c.document.querySelector('[data-library-decision="save"]'));c.document.querySelector('[data-library-decision="save"]').onclick();assert.equal(await switchThird,true);assert.equal(c.api.panes.size,2);assert.equal(right.planId,'p3');assert.equal(left.planId,leftId);assert.equal(await c.api.openPlan('p4',right.id),true);assert.equal(c.api.retained.length,4);assert.equal(c.api.panes.size,2);
 const draft=await c.api.repo.get('drafts',JSON.stringify([c.api.session,'p2']));assert.equal(draft.payload.rooms[0].x,666);assert.deepEqual(plain(draft.history),['kept-undo']);assert.deepEqual(plain(draft.redo),['kept-redo']);
 await assert.rejects(c.api.openPlan('p5',right.id),/4案/);assert.equal(c.api.retained.length,4);const restored=libraryContext({mem:c.mem,native:false,search:'?planLibrary=1&librarySession='+c.api.session});await restored.api.ready;assert.equal(restored.api.panes.size,2);assert.equal(restored.api.retained.length,4);const target=[...restored.api.panes.values()][1];await restored.api.switchPlan(target.id,'p2');assert.equal(target.frame.contentWindow.EditorPane.snapshot().rooms[0].x,666);assert.deepEqual(plain(target.frame.contentWindow.EditorPane.state().history),['kept-undo']);
});
test('both pane saves keep their own IDs and payloads; attempting to choose the other visible ID rejects',async()=>{
 const {c}=await compareFixture(),[left,right]=[...c.api.panes.values()];await assert.rejects(c.api.openPlan(right.planId,left.id),/もう一方/);await left.frame.contentWindow.EditorPane.install(fixture(777),{dirty:true});await right.frame.contentWindow.EditorPane.install(fixture(888),{dirty:true});await c.api.persistPane(left.id,left.planId,fixture(777));await c.api.persistPane(right.id,right.planId,fixture(888));assert.equal((await c.api.repo.read(left.planId)).payload.rooms[0].x,777);assert.equal((await c.api.repo.read(right.planId)).payload.rooms[0].x,888);assert.equal(c.api.panes.size,2);
});
test('failed tab navigation closes only the new tab and leaves original selection available for retry',async()=>{
 const h=libraryContext();await h.api.ready;await seed(h);h.edit(fixture(999));await h.api.openComparison();const before=h.plan,open=h.context.open;h.context.open=()=>{const p=open();p.location.replace=()=>{throw Error('navigation blocked');};return p;};assert.equal(await button(h,'second').onclick(),false);assert.equal(h.popups[0].closed,true);assert.ok(button(h,'second'));assert.deepEqual(h.plan,before);assert.equal(h.context.DIRTY,true);assert.match(h.document.querySelector('[data-library-list-status]').textContent,/navigation blocked/);
});
