'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {libraryContext,fixture,ROOT}=require('./plan-library-test-support.cjs');
const {runtime}=require('./parallel-view-preferences-support.cjs');
const plain=v=>JSON.parse(JSON.stringify(v));
const tick=()=>new Promise(resolve=>setImmediate(resolve)),key=(session,id)=>JSON.stringify([session,id]);
async function until(fn){for(let i=0;i<600;i++){if(fn())return;await new Promise(resolve=>setTimeout(resolve,1));}throw Error('Anonymous transition did not reach delayed work');}
async function simple(){const h=libraryContext();await h.api.ready;const source=h.context.__editorPlanId;await h.api.persistPane('native-editor',source,h.plan);h.context.clearDirty();await h.api.repo.save({planId:'anonymous-target',name:'Anonymous target',operationId:'seed',baseRevisionId:null,baseGeneration:0,payload:fixture(222)});return {h,source};}
for(const change of ['clear-floor','clear-floor-undo'])test('actual native '+change+' during engine wait aborts target commit and persists latest source',async()=>{
 const r=runtime(),listeners=new Map(),h=libraryContext({beforeLibrary:ctx=>{ctx.EditorPane=r.editor;Object.defineProperty(ctx,'DIRTY',{get:()=>r.ctx.DIRTY,set:v=>r.ctx.DIRTY=v});}});r.ctx.document.body=h.document.body;await h.api.ready;const source=h.context.__editorPlanId;await h.api.persistPane('native-editor',source,r.editor.snapshot());
 await h.api.repo.save({planId:'anonymous-target',name:'Anonymous target',operationId:'seed',baseRevisionId:null,baseGeneration:0,payload:fixture(222)});const head=await h.api.repo.read('anonymous-target');await h.api.repo.saveDraft(h.api.session,'anonymous-target',{plan:head.payload,payload:head.payload,dirty:false,history:[],redo:[],view:{view:'3d-int',floor:1,twoD:{zoom:2,panX:3,panY:4}},generation:0,baseRevisionId:head.revision.id,baseGeneration:head.head.headGeneration});
 const c=r.ctx,html=fs.readFileSync(ROOT+'/index.html','utf8'),app=fs.readFileSync(ROOT+'/assets/js/app-state.js','utf8');Object.assign(c,{WALKTHROUGH:null,isObjectLocked:()=>false,sharedRememberEditTargets(){},pushHistorySnapshot:(history,s)=>history.push(s),markDirty(){c.DIRTY=true;h.api.edited('native-editor');},syncExteriorWallSettings(){},syncLockBatchUi(){},ren:null,confirm:()=>true,sharedForceFullSync(){},syncNorthFromPlan(){},ensureFloorMetadata(){},clearMultiSelection(){},threeModulesReady:false});c.document.getElementById('props').classList.remove=()=>{};c.addEventListener=(name,fn)=>listeners.set(name,fn);c.removeEventListener=(name,fn)=>{if(listeners.get(name)===fn)listeners.delete(name);};
 vm.runInContext(app.slice(app.indexOf('function saveState(){'),app.indexOf('\nfunction ensureObjectIds(){')),c);vm.runInContext(html.slice(html.indexOf('function clearFloor(){'),html.indexOf('// ─── ビュー/カメラ状態の保存・復元')),c);vm.runInContext(html.slice(html.indexOf('function undoAction(){'),html.indexOf('// 読み取り画面のページ選択')),c);
 const pending=h.api.openPlan('anonymous-target');await until(()=>listeners.has('three-ready'));assert.equal(h.document.body.inert,true);assert.equal(h.api.panes.get('native-editor').ready,false);c.clearFloor();assert.equal(c.DATA.rooms.length,0);if(change==='clear-floor-undo')c.undoAction();const latest=r.editor.state();c.threeModulesReady=true;listeners.get('three-ready')();await assert.rejects(pending,/元の編集/);
 assert.equal(h.context.__editorPlanId,source);assert.deepEqual(r.editor.state(),latest);const draft=await h.api.repo.get('drafts',key(h.api.session,source));assert.deepEqual(plain(draft.payload),plain(r.editor.snapshot()));assert.equal(draft.dirty,true);assert.deepEqual(plain(draft.history),plain(latest.history));assert.deepEqual(plain(draft.redo),plain(latest.redo));assert.equal((await h.api.repo.read('anonymous-target')).revision.id,head.revision.id);assert.equal(h.document.body.inert,undefined);assert.equal(h.api.panes.get('native-editor').ready,true);assert.equal(h.api.retained.includes('anonymous-target'),false);
});
test('source edits during admission or source-draft await never get replaced by stale rollback state',async()=>{
 for(const phase of ['admission','draft']){const {h,source}=await simple();let entered=false,release;if(phase==='admission'){const original=h.api.repo.admission;h.api.repo.admission=async(...args)=>{if(args[0]==='anonymous-target'){entered=true;await new Promise(resolve=>release=resolve);}return original(...args);};}else{const original=h.api.repo.saveDraft;h.api.repo.saveDraft=async(...args)=>{if(args[1]===source&&!entered){entered=true;await new Promise(resolve=>release=resolve);}return original(...args);};}const pending=h.api.openPlan('anonymous-target');await until(()=>entered);assert.equal(h.document.body.inert,true);h.edit(fixture(777));release();await assert.rejects(pending,/元の編集/);assert.equal(h.context.__editorPlanId,source);assert.equal(h.plan.rooms[0].x,777);assert.equal((await h.api.repo.get('drafts',key(h.api.session,source))).payload.rooms[0].x,777);assert.equal(h.context.DIRTY,true);assert.equal(h.document.body.inert,undefined);}
});
for(const fault of ['success','view-failure','view-and-protection-failure'])test('a target API edit during view await is preserved on '+fault,async()=>{
 const {h,source}=await simple();let entered=false,release;const original=h.api.repo.setView;h.api.repo.setView=async(...args)=>{entered=true;await new Promise(resolve=>release=resolve);if(fault!=='success')throw Error('Anonymous view abort');return original(...args);};const pending=h.api.openPlan('anonymous-target');await until(()=>entered);assert.equal(h.document.body.inert,true);h.edit(fixture(999));if(fault==='view-and-protection-failure')h.api.repo.saveDraft=async()=>{throw Error('Anonymous target protection abort');};release();
 if(fault==='success'){assert.equal(await pending,true);assert.equal(h.context.__editorPlanId,'anonymous-target');assert.equal((await h.api.repo.get('drafts',key(h.api.session,'anonymous-target'))).payload.rooms[0].x,999);}else{await assert.rejects(pending,/Anonymous view abort/);if(fault==='view-failure'){assert.equal(h.context.__editorPlanId,source);assert.equal((await h.api.repo.get('drafts',key(h.api.session,'anonymous-target'))).payload.rooms[0].x,999);}else{assert.equal(h.context.__editorPlanId,'anonymous-target');assert.equal(h.plan.rooms[0].x,999);assert.equal(h.context.DIRTY,true);assert.equal(h.api.retained.includes('anonymous-target'),true);}}
 assert.equal(h.document.body.inert,undefined);assert.equal(h.api.panes.get('native-editor').ready,true);
});
test('window-level keydown is capture-suppressed while installing; keyup cleanup and original inert state survive cancellation',async()=>{
 const listeners=new Map(),noop=()=>{},document={body:{inert:true},addEventListener:noop,querySelector:()=>null,documentElement:{classList:{add:noop}}},root={document,comparisonCatalogueReady:Promise.resolve(),parent:{ParallelEditors:{activeId:null,modelPool:{resources:new Set()}}},addEventListener:(name,fn,capture)=>listeners.set(name,{fn,capture}),removeEventListener:name=>listeners.delete(name)};
 const ctx={window:root,document,EDITOR_PANE:'anonymous-pane',render3DNow:noop,_jsonImportRequest:0,DATA:fixture(),sc3:null,ren:null,orbit:null,composer:null,_pmremGen:null,_envRT:null,_modelCache:{},_texCache:{},setTimeout,clearTimeout};vm.createContext(ctx);vm.runInContext(fs.readFileSync(ROOT+'/assets/js/parallel-editors.js','utf8'),ctx);const first=root.EditorPane.install(fixture(2),{view:{view:'3d-int'}});await tick();const second=root.EditorPane.install(fixture(3),{view:{view:'3d-int'}});await tick();assert.equal(await first,false);assert.equal(root._editorInputLocked,true);let prevented=0,stopped=0;const shortcut=listeners.get('keydown');assert.equal(shortcut.capture,true);shortcut.fn({preventDefault(){prevented++;},stopImmediatePropagation(){stopped++;}});assert.equal(prevented,1);assert.equal(stopped,1);assert.equal(listeners.has('keyup'),false);root.EditorPane.dispose();assert.equal(await second,false);assert.equal(root._editorInputLocked,undefined);assert.equal(document.body.inert,true);
});
function installActualClear(h){const c=h.context,html=fs.readFileSync(ROOT+'/index.html','utf8'),app=fs.readFileSync(ROOT+'/assets/js/app-state.js','utf8');Object.assign(c,{ST:{floor:1,selected:null},WALKTHROUGH:null,isObjectLocked:()=>false,sharedRememberEditTargets(){},HISTORY:[],REDO_HISTORY:[],pushHistorySnapshot:(history,s)=>history.push(s),serializeDataSnapshot:()=>JSON.stringify(c.DATA),syncExteriorWallSettings(){},syncLockBatchUi(){},draw2d(){},ren:null,confirm:()=>true});const props=c.document.createElement('div');props.id='props';c.document.body.append(props);const sandbox=vm.createContext(c);vm.runInContext(app.slice(app.indexOf('function saveState(){'),app.indexOf('\nfunction ensureObjectIds(){')),sandbox);vm.runInContext(html.slice(html.indexOf('function clearFloor(){'),html.indexOf('// ─── ビュー/カメラ状態の保存・復元')),sandbox);}
for(const phase of ['reload-read','history-restore','history-read'])test('actual native clearFloor/saveState during '+phase+' remains dirty and recoverable without installing over it',async()=>{
 const {h,source}=await simple();installActualClear(h);const head=(await h.api.repo.read(source)).revision.id,revisions=(await h.api.repo.list('revisions')).length;let entered=false,release,pending;
 if(phase==='history-restore'){const original=h.api.repo.restore;h.api.repo.restore=async(...args)=>{entered=true;await new Promise(resolve=>release=resolve);return original(...args);};}else{const original=h.api.repo.read;h.api.repo.read=async(...args)=>{if(args[0]===source&&!entered){entered=true;await new Promise(resolve=>release=resolve);}return original(...args);};}
 if(phase==='reload-read')pending=h.api.reloadPlan('native-editor');else{await h.api.history('native-editor');const restore=h.document.querySelector('[data-library-restore]');assert.ok(restore);const original=h.api.run;h.api.run=fn=>pending=original(fn);restore.onclick();}
 await until(()=>entered);assert.equal(h.document.body.inert,true);assert.equal(h.context._editorInputLocked,true);assert.equal(h.api.panes.get('native-editor').ready,true);h.context.clearFloor();assert.equal(h.plan.rooms.length,0);assert.equal(h.context.DIRTY,true);await tick();release();
 if(phase==='reload-read')await assert.rejects(pending,/元の編集/);else assert.equal(await pending,false);
 assert.equal(h.context.__editorPlanId,source);assert.equal(h.plan.rooms.length,0);assert.equal(h.context.DIRTY,true);const draft=await h.api.repo.get('drafts',key(h.api.session,source));assert.equal(draft.payload.rooms.length,0);assert.equal(draft.dirty,true);assert.equal(h.document.body.inert,undefined);assert.equal(h.context._editorInputLocked,undefined);assert.equal(h.api.panes.get('native-editor').ready,true);if(phase==='history-read'){assert.notEqual((await h.api.repo.read(source)).revision.id,head);assert.equal((await h.api.repo.list('revisions')).length,revisions+1);}else{assert.equal((await h.api.repo.read(source)).revision.id,head);assert.equal((await h.api.repo.list('revisions')).length,revisions);}
});
test('reload and history success/failure return the prior inert/input state and keep dirty choice cancellation usable',async()=>{
 for(const action of ['reload','history']){const {h,source}=await simple();h.document.body.inert=true;h.context._editorInputLocked='prior-lock';if(action==='reload'){assert.equal(await h.api.reloadPlan('native-editor'),true);assert.equal(h.document.body.inert,true);assert.equal(h.context._editorInputLocked,'prior-lock');h.document.body.inert=false;h.context._editorInputLocked=false;h.edit(fixture(777));await tick();const pending=h.api.reloadPlan('native-editor');await until(()=>h.document.querySelector('[data-library-decision="cancel"]'));assert.equal(h.document.body.inert,false);h.document.querySelector('[data-library-decision="cancel"]').onclick();assert.equal(await pending,false);assert.equal(h.plan.rooms[0].x,777);}else{await h.api.history('native-editor');let pending;const original=h.api.run;h.api.run=fn=>pending=original(fn);h.document.querySelector('[data-library-restore]').onclick();assert.equal(await pending,undefined);assert.equal(h.document.body.inert,true);assert.equal(h.context._editorInputLocked,'prior-lock');}
 assert.equal(h.context.__editorPlanId,source);}
});

test('reload/history repository failure releases their full-operation lock without changing source state',async()=>{
 for(const action of ['reload','history']){const {h}=await simple(),before=plain(h.context.EditorPane.state());if(action==='reload'){h.api.repo.read=async()=>{throw Error('Anonymous reload read abort');};await assert.rejects(h.api.reloadPlan('native-editor'),/Anonymous reload read abort/);}else{await h.api.history('native-editor');h.api.repo.restore=async()=>{throw Error('Anonymous history restore abort');};let pending;const original=h.api.run;h.api.run=fn=>pending=original(fn);h.document.querySelector('[data-library-restore]').onclick();assert.equal(await pending,false);}assert.deepEqual(plain(h.context.EditorPane.state()),before);assert.equal(h.document.body.inert,undefined);assert.equal(h.context._editorInputLocked,undefined);assert.equal(h.api.panes.get('native-editor').ready,true);}
});
