'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {libraryContext,makePaneWindow}=require('./plan-library-test-support.cjs');
const {runtime,fixture,clone}=require('./parallel-view-preferences-support.cjs');
async function host(){
 const children=[];const h=libraryContext({native:false,search:'?planLibrary=1',iframeFactory(){const r=runtime(),ui=makePaneWindow().window;r.ctx.document.querySelector=ui.document.querySelector.bind(ui.document);r.ctx.document.querySelectorAll=ui.document.querySelectorAll.bind(ui.document);r.ctx.SHARED={saveBusy:false};r.ctx.COMPARISON_PREVIEW=false;r.ctx.markDirty=()=>{r.ctx.DIRTY=true;};r.editor.dispose=()=>{};children.push(r);return r.ctx;}});await h.api.ready;
 for(const [id,north]of [['A',45],['B',180],['C',270]])await h.api.repo.save({planId:id,name:id,operationId:'seed-'+id,baseRevisionId:null,baseGeneration:0,payload:fixture(id,north)});
 await h.api.openPlan('A');await h.api.openPlan('C');h.api.setSync(false);h.api.changed([...h.api.panes.values()][0].id,{cameraChanged:false});await h.api.layout(1);await h.api.openPlan('B');const [a,b]=[...h.api.panes.values()];return {h,children,a,b,ar:children.find(r=>r.ctx===a.frame.contentWindow),br:children.find(r=>r.ctx===b.frame.contentWindow)};
}
async function settle(){await new Promise(resolve=>setTimeout(resolve,230));await new Promise(setImmediate);}
function options(r){r.ctx.ST.showGrid=false;r.ctx.ST.showDim=false;r.ctx.ST.snap=455;Object.assign(r.ctx.LIGHT_SETTINGS,{hour:7,season:'winter',haze:.7});r.ctx.CeilingDesigner.setSurface('ceiling');}
test('actual repository option-only view commit preserves plan head/generation/history/dirty and B',async()=>{
 const {h,a,b,ar,br}=await host();const beforeA=await h.api.repo.read('A'),beforeB=clone(br.editor.state()),generation=h.api.plans.get('A').generation;options(ar);h.api.changed(a.id,{cameraChanged:false});await settle();const view=await h.api.repo.get('views',h.api.session);assert.deepEqual(clone(view.cameras.A),clone(ar.editor.view()));assert.deepEqual(await h.api.repo.read('A'),beforeA);assert.equal(h.api.plans.get('A').generation,generation);assert.equal(ar.ctx.DIRTY,false);assert.deepEqual(clone(br.editor.state()),beforeB);
});
test('actual PlanLibrary A→C→A, hide→remount and close→open retain runtime/surface state',async()=>{
 const {h,a,b,ar,br,children}=await host();options(ar);options(br);br.ctx.LIGHT_SETTINGS.hour=22;br.ctx.ST.snap=910;const beforeA=clone(ar.editor.view()),beforeB=clone(br.editor.view());await h.api.switchPlan(a.id,'C');assert.equal(ar.ctx.LIGHT_SETTINGS.hour,13);assert.equal(ar.ctx.ST.snap,10);assert.equal(ar.ctx.ST.ceilingView,false);await h.api.switchPlan(a.id,'A');assert.deepEqual(clone(ar.editor.view()),beforeA);assert.deepEqual(clone(br.editor.view()),beforeB);
 h.api.changed(a.id,{cameraChanged:false});await h.api.layout(1);await h.api.layout(2);const restoredC=[...h.api.panes.values()].find(p=>p.planId==='C');assert.ok(restoredC);await h.api.closePlan(restoredC.id);await h.api.openPlan('B');const afterB=[...h.api.panes.values()].find(p=>p.planId==='B');assert.deepEqual(clone(afterB.frame.contentWindow.EditorPane.view()),beforeB);
 await h.api.closePlan(a.id);await h.api.openPlan('A');const afterA=[...h.api.panes.values()].find(p=>p.planId==='A');assert.notEqual(afterA.id,a.id);assert.deepEqual(clone(afterA.frame.contentWindow.EditorPane.view()),beforeA);assert.equal((await h.api.repo.list()).length,3);
});
test('dirty-discard switch discards only edits and retains runtime view through return and same-ID reload',async()=>{
 const {h,a,ar}=await host();options(ar);const before=clone(ar.editor.view());ar.ctx.DATA.rooms[0].n='unsaved geometry label';ar.ctx.DIRTY=true;
 const pending=h.api.switchPlan(a.id,'C');let decision;for(let i=0;i<100&&!decision;i++){await new Promise(setImmediate);decision=h.document.querySelector('[data-library-decision="discard"]');}assert.ok(decision);await decision.onclick();await pending;await h.api.switchPlan(a.id,'A');assert.equal(ar.ctx.DATA.rooms[0].n,'A');assert.equal(ar.ctx.DIRTY,false);assert.deepEqual(clone(ar.editor.view()),before);await h.api.reloadPlan(a.id);assert.deepEqual(clone(ar.editor.view()),before);
});
test('camera alignment and continuous sync copy only camera/2D, option-only events remain local',async()=>{
 const {h,a,b,ar,br}=await host();options(ar);br.ctx.LIGHT_SETTINGS.hour=22;br.ctx.ST.snap=100;const expected=clone(br.editor.view()),data=JSON.stringify(br.ctx.DATA);ar.ctx.ST.panX=333;assert.equal(h.api.align(),true);assert.equal(h.document.querySelector('[data-parallel-sync]').checked,false);assert.equal(br.ctx.ST.panX,333);assert.deepEqual(clone(br.editor.view().preferences),expected.preferences);assert.deepEqual(clone(br.editor.view().surface),expected.surface);assert.equal(JSON.stringify(br.ctx.DATA),data);
 h.api.setSync(true);ar.ctx.ST.panX=444;h.api.changed(a.id);assert.equal(br.ctx.ST.panX,444);ar.ctx.ST.panX=555;ar.ctx.LIGHT_SETTINGS.hour=17;h.api.changed(a.id,{cameraChanged:false});assert.equal(br.ctx.ST.panX,444);assert.equal(br.ctx.LIGHT_SETTINGS.hour,22);assert.equal(br.ctx.DATA.northDeg,180);assert.equal(br.ctx.DATA.autoRoomLights,false);assert.equal(JSON.stringify(br.ctx.DATA),data);
});
test('view storage fault retains runtime and plan revisions; normal retry uses existing session view generation',async()=>{
 const {h,a,ar}=await host();options(ar);const before=await h.api.repo.read('A'),state=clone(ar.editor.view());h.mem.failNext(new DOMException('synthetic view quota','QuotaExceededError'));h.api.changed(a.id,{cameraChanged:false});await settle();assert.deepEqual(clone(ar.editor.view()),state);assert.deepEqual(await h.api.repo.read('A'),before);h.api.changed(a.id,{cameraChanged:false});await settle();const saved=await h.api.repo.get('views',h.api.session);assert.deepEqual(clone(saved.cameras.A),state);assert.ok(saved.generation>0);
});
test('recreated PlanLibrary restores serialized runtime view in the same session without rewriting saved plan revisions',async()=>{
 const {h,a,b,ar,br}=await host();options(ar);br.ctx.LIGHT_SETTINGS.hour=22;br.ctx.ST.snap=910;const beforeA=clone(ar.editor.view()),beforeB=clone(br.editor.view()),heads=await Promise.all(['A','B'].map(id=>h.api.repo.read(id)));h.api.changed(a.id,{cameraChanged:false});await settle();
 const next=libraryContext({native:false,search:'?planLibrary=1',mem:h.mem,sessionStorage:h.sessionStorage,localStorage:h.localStorage,iframeFactory(){const r=runtime(),ui=makePaneWindow().window;r.ctx.document.querySelector=ui.document.querySelector.bind(ui.document);r.ctx.document.querySelectorAll=ui.document.querySelectorAll.bind(ui.document);r.ctx.SHARED={saveBusy:false};r.ctx.markDirty=()=>r.ctx.DIRTY=true;r.editor.dispose=()=>{};return r.ctx;}});await next.api.ready;assert.equal(next.api.panes.size,2);const views=Object.fromEntries([...next.api.panes.values()].map(p=>[p.planId,clone(p.frame.contentWindow.EditorPane.view())]));assert.deepEqual(views.A,beforeA);assert.deepEqual(views.B,beforeB);assert.deepEqual(clone(await Promise.all(['A','B'].map(id=>next.api.repo.read(id)))),clone(heads));
});
