'use strict';
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve('.'),dir='assets/models/packs/rpg-mansion-contract/v0.2.0/',out='tools/assets/rpg-pack-contract/tps-fixture';
const read=p=>JSON.parse(fs.readFileSync(p)),seats=read(dir+'sit-sockets.proposal.json').sockets,surfaces=read(dir+'placement-surfaces.proposal.json').surfaces,geometry=read(dir+'asset-geometry.json').items;
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--use-angle=swiftshader']});try{const context=await browser.newContext({viewport:{width:1100,height:850}});await context.route('**/*',r=>new URL(r.request().url()).origin===new URL(process.env.APP_URL||'http://127.0.0.1:8947/').origin?r.continue():r.abort());const page=await context.newPage();await page.goto((process.env.APP_URL||'http://127.0.0.1:8947/')+'?preset=blank');await page.waitForFunction(()=>AssetPackPicker?.getRegistry()?.listPacks().some(p=>p.count===50));await page.addScriptTag({path:path.join(root,out,'adapter.js')});
 const setup=await page.evaluate(async()=>{const contract=await(await fetch('assets/models/packs/rpg-mansion/conversion-map.json')).json(),types=['rpg-mansion-wing-chair-01','rpg-mansion-stool-01','sofa','dining-table','low_table','rpg-mansion-secretary-01'];const p={walls:[],rooms:[{id:'fixture-room',x:0,y:0,w:18000,d:6000,n:'TPS fixture',floor:2}],floorCount:2,startMode:'blank',items:types.map((type,i)=>{const a=getFmpItem(type)||getItemDefaultSize(type);return {id:'fixture-'+i,type,x:500+i*2600,y:1400,w:a.w*.9,d:a.d*1.1,h:123,rot:[37,90,-45,18,70,0][i],floor:2,elev:127,flipX:i===1};})};const resolved=p.items.map(i=>({h:getItemHeightValue(i)}));const converted=AssetPackConversion.createConverter(contract,Object.values(FMP_ITEMS)).preview(p,{approvedIndexes:[2,3,4],resolvedDimensions:resolved}).plan;applyJsonImport(stageJsonImport(JSON.stringify(converted)));onFloorChange(2);init3D();return {source:p,plan:JSON.parse(serializeDataSnapshot()),effectiveHeights:DATA.items.map(getItemHeightValue)};});
 fs.writeFileSync(path.join(out,'plan.json'),JSON.stringify(setup.plan,null,2)+'\n');
 const results=[];
 for(const record of [...seats,...surfaces]){
  const geo=geometry.find(g=>g.assetId===record.assetId),hash='sha256:'+crypto.createHash('sha256').update(fs.readFileSync(geo.modelPath)).digest('hex');assert.equal(hash,record.assetRevision);
  const result=await page.evaluate(async({record,revision})=>{const it=DATA.items.find(i=>i.type===record.assetId),f=getFmpItem(it.type);if(!_modelCache[f.model]){const g=await new Promise((r,j)=>getGltfLoader().load(f.model,r,undefined,j));ModelQuality.prepare(g.scene,f.model);_modelCache[f.model]=g.scene;}
   const oldScene=sc3,oldSelection=ST.selected;try{
    sc3=new THREE.Scene();ST.selected=it;buildItem3D(it);sc3.updateMatrixWorld(true);const group=sc3.children.find(o=>o.userData.selectRef===it);if(!group)throw Error('No real clone');const matrix=group.children[0].matrixWorld.clone();
    const floorY=floorTopY(it.floor),resolved=RpgTpsFixture.resolve(THREE,record,it,matrix,revision,()=>floorY),centre=resolved.worldSeatSurfaceCenter||resolved.worldSurfaceCenter;
    const ray=new THREE.Raycaster(new THREE.Vector3(centre[0],centre[1]+.01,centre[2]),new THREE.Vector3(0,-1,0)),hit=ray.intersectObject(group,true)[0];if(!hit)throw Error('No surface hit');
    const bbox=new THREE.Box3().setFromObject(group),height=getItemHeightValue(it),nominal=getFmpItem(it.type).h;const rayError=hit.point.distanceTo(new THREE.Vector3(...centre));
    const signatureChanged=RpgTpsFixture.resolve(THREE,record,{...it,assetPackConversion:{...it.assetPackConversion,renderHeightMm:height+1}},matrix,revision,()=>floorY).signature!==resolved.signature;
    let mismatchRejected=false;try{RpgTpsFixture.resolve(THREE,record,it,matrix,'sha256:wrong',()=>floorY);}catch(e){mismatchRejected=true;}
    const marker=(p,color)=>{const m=new THREE.Mesh(new THREE.SphereGeometry(.035,12,8),new THREE.MeshBasicMaterial({color,depthTest:false,depthWrite:false}));m.position.fromArray(p);m.renderOrder=10;sc3.add(m);};marker(centre,0xa000e0);if(record.kind==='sit'){marker(resolved.worldSeatFrameReference,0xffa000);marker(resolved.worldApproachFloorPoint,0x0088ff);}
    sc3.background=new THREE.Color('#eee9df');sc3.add(new THREE.HemisphereLight(0xffffff,0x777777,3));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(centre[0]-3,centre[1]+4,centre[2]+5);sc3.add(light);ren.setPixelRatio(1);ren.setSize(900,650,false);const camera=new THREE.PerspectiveCamera(38,ren.domElement.width/ren.domElement.height,.01,100);const mid=bbox.getCenter(new THREE.Vector3());camera.position.copy(mid).add(new THREE.Vector3(0,0,1).transformDirection(matrix).multiplyScalar(4.3)).add(new THREE.Vector3(1,0,0).transformDirection(matrix).multiplyScalar(.8)).add(new THREE.Vector3(0,2.2,0));camera.lookAt(mid);ren.render(sc3,camera);const image=ren.domElement.toDataURL('image/png');
    let instanced=null;if(!it.flipX){sc3=new THREE.Scene();ST.selected=null;_fmpInstancePools={};buildItem3D(it);finalizeFmpInstancePools();sc3.updateMatrixWorld(true);const inst=sc3.children.find(o=>o.isInstancedMesh&&o.userData.instanceRefs.includes(it));if(!inst)throw Error('No real instance');const mat=new THREE.Matrix4();inst.getMatrixAt(inst.userData.instanceRefs.indexOf(it),mat);mat.premultiply(inst.matrixWorld);const r=RpgTpsFixture.resolve(THREE,record,it,mat,revision,()=>floorY);instanced=r.worldSeatSurfaceCenter||r.worldSurfaceCenter;}
    return {assetId:it.type,height,storedH:it.h,nominalHeight:nominal,floorY,itemBaseY:item3DBaseY(it),elevationM:it.elev/1000,bboxTopY:bbox.max.y,resolved,rayError,instanced,signatureChanged,mismatchRejected,image};
   }finally{sc3=oldScene;ST.selected=oldSelection;_fmpInstancePools={};}
  },{record,revision:hash});
  assert.ok(result.rayError<1e-6,JSON.stringify(result));assert.ok(result.signatureChanged&&result.mismatchRejected);const centre=result.resolved.worldSeatSurfaceCenter||result.resolved.worldSurfaceCenter;
  if(result.instanced)assert.ok(Math.hypot(...result.instanced.map((v,i)=>v-centre[i]))<.00001);
  if(record.kind==='sit'){assert.equal(result.resolved.worldApproachFloorPoint[1],result.floorY);assert.ok(result.resolved.worldSeatFrameReference[1]<centre[1]);assert.ok(!('reachable' in result.resolved));}
  if(record.assetId.includes('secretary'))assert.ok(result.bboxTopY-centre[1]>.4);
  const pixels=Buffer.from(result.image.split(',')[1],'base64');assert.ok(pixels.length>10000,'Rendered screenshot missing');fs.writeFileSync(path.join(out,record.assetId+'.png'),pixels);delete result.image;results.push(result);
 }
 fs.writeFileSync(path.join(out,'world-results.json'),JSON.stringify({status:'renderer-contract-passed-TPS-host-pending',source:setup.source,plan:setup.plan,results,limitations:['No TPS runtime present in this checkout','No rig, reachability, path, collision, occupancy or exit validation']},null,2)+'\n');console.log('6 real GLB surfaces: clone raycasts, 5 instance transforms, floor/elevation, flip, height-v2, revisions and signatures passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
