const test=require('node:test'),assert=require('node:assert/strict'),Scene=require('../../assets/js/scene-ir-v3.js'),{runtime}=require('./scene-fixtures.cjs');
const f=value=>({value,status:'observed',source:'independent partial-preview source'}),u={value:null,status:'unknown'};
function fixture(){return {sceneVersion:3,units:'mm',coordinateSystem:'x-east-y-south-clockwise',annotations:[],walls:[],rooms:[{id:'room',floor:f(1),shape:f({kind:'rectUnion',rectangles:[{x:0,y:0,w:3000,d:3000}]}),boundaryBasis:f('clear-face')}],openings:[],objects:[{id:'chair',objectType:f('chair'),semanticExtent:f('asset'),placement:f({domain:'room',roomId:'room'}),sourceFootprint:f({center:{x:1000,y:1000},sizeMm:{w:435,d:475},axisX:{x:1,y:0}}),frontDirection:f({x:1,y:0}),heightMm:u,appearance:{diagramColor:f('#D6BA92')}},{id:'stairs',objectType:f('stair'),semanticExtent:f('asset'),placement:f({domain:'room',roomId:'room'}),sourceFootprint:f({center:{x:2300,y:2200},sizeMm:{w:500,d:700},axisX:{x:1,y:0}})}],siteRegions:[],buildingFootprints:[],bindings:[],connections:[]};}
const binding={id:'chair-binding',sourceEntityId:'chair',catalogId:f('fmp-Chair07'),sizingPolicy:'fit-source',appearanceMode:'match-diagram-appearance'};
function options(s){return {materialization:'bounded-v3',registry:runtime().PlanImport.sceneCatalogue(),targetPlan:{heightDefaults:{modelVersion:2,floorThickness:180}},defaultFloorOffset:()=>0,bindingDecisions:[{binding,sourceSnapshot:JSON.stringify(s.objects[0])}],partialSelection:Scene.createPartialSelection(s,['chair'],true)};}
function reviewed(s,opts){const first=Scene.compile(s,opts);return Scene.compile(s,{...opts,acceptedReviewGroups:first.reviewGroups.map(g=>g.id),reviewedEntities:Object.fromEntries(first.reviewGroups.map(g=>[g.entityId,g.reviewKey]))});}
test('selected object and dependent room can preview while unselected stairs remain unresolved source, full import still fails',()=>{const s=fixture(),before=JSON.stringify(s),opts=options(s),partial=reviewed(s,opts);assert.equal(partial.canApply,true,JSON.stringify(partial.diagnostics));assert.equal(partial.fullReconstructionReady,false);assert.equal(partial.reconstructionStatus,'incomplete-selected-preview');assert.deepEqual(partial.plan.items.map(i=>i.type),['fmp-Chair07']);assert.equal(partial.plan.rooms.length,1);assert.ok(partial.deferredEntities.some(e=>e.id==='stairs'&&e.status==='source-only-unresolved'));assert.equal(partial.acknowledgedOmissions.length,0,'No fabricated noncritical classification');assert.equal(JSON.stringify(s),before);const full=reviewed(s,{...opts,partialSelection:null});assert.equal(full.canApply,false);assert.ok(full.diagnostics.some(d=>d.code==='unsupported_stair_reconstruction'));});
test('selected unsupported symbol, unknown geometry, stale source and forged/empty scope cannot bypass reconstruction gates',()=>{const s=fixture(),opts=options(s);assert.equal(reviewed(s,{...opts,partialSelection:Scene.createPartialSelection(s,['stairs'],true)}).canApply,false);const changed=structuredClone(s);changed.objects[0].sourceFootprint.value.sizeMm.w++;assert.equal(reviewed(changed,opts).canApply,false);const forged=structuredClone(opts.partialSelection);forged.entityIds=['chair'];assert.equal(reviewed(s,{...opts,partialSelection:forged}).canApply,false);assert.equal(Scene.createPartialSelection(s,[],true),null);const unknown=fixture();unknown.objects[0].sourceFootprint=u;assert.equal(reviewed(unknown,{...options(unknown)}).canApply,false);const symbolic=fixture();symbolic.objects[0].objectType=f('unidentified-symbol');symbolic.objects[0].semanticExtent=f('symbol-only');assert.equal(reviewed(symbolic,options(symbolic)).canApply,false);});
test('scope changes require fresh approvals even for unchanged selected source entities',()=>{const s=fixture(),opts=options(s),first=Scene.compile(s,opts),second=structuredClone(s);second.objects.push({...structuredClone(second.objects[0]),id:'second-chair'});const secondOpts=options(second),one=Scene.compile(second,secondOpts),expanded=Scene.compile(second,{...secondOpts,partialSelection:Scene.createPartialSelection(second,['chair','second-chair'],true),acceptedReviewGroups:one.reviewGroups.map(g=>g.id),reviewedEntities:Object.fromEntries(one.reviewGroups.map(g=>[g.entityId,g.reviewKey]))});assert.equal(expanded.canApply,false);assert.equal(expanded.reviewGroups.find(g=>g.entityId==='chair').accepted,false);});
test('actual PlanImport partial action creates a distinct plan payload without editing root DATA or Undo history',async()=>{const c=runtime(),s=fixture(),opts={materialization:'bounded-v3',bindingDecisions:[{binding,sourceSnapshot:JSON.stringify(s.objects[0])}],partialSelection:c.SceneIR.createPartialSelection(s,['chair'],true)},first=c.PlanImport.previewSceneIR(s,opts);opts.acceptedReviewGroups=first.reviewGroups.map(g=>g.id);opts.reviewedEntities=Object.fromEntries(first.reviewGroups.map(g=>[g.entityId,g.reviewKey]));c.DATA.items.push({id:'existing',type:'memo',floor:1,x:5,y:8,w:300,d:200,rot:0});const before=JSON.stringify(c.DATA),history=JSON.stringify(c.HISTORY);let created;c.ParallelEditors={openPlan:async(plan,name)=>{created={plan,name};return 'new-partial-plan';}};c.PlanImport.stageSceneIR(s,opts);await c.applyPlanImport();assert.ok(created);assert.equal(created.plan.items.length,1);assert.equal(created.plan.sceneReconstructionReports[0].status,'incomplete-selected-preview');assert.deepEqual(JSON.parse(JSON.stringify(created.plan.sceneReconstructionReports[0].originalIR)),s);assert.equal(JSON.stringify(c.DATA),before);assert.equal(JSON.stringify(c.HISTORY),history);assert.equal(c.PlanImport.state.result.partialPlanId,'new-partial-plan');created=null;await c.applyPlanImport();assert.equal(created,null,'Consumed preview cannot create duplicate plans');});

const frozen=require('../../local-preview/frozen-page-2.json'),API=require('../../assets/js/editor-internal-api.js');
const safeWalls=['wall-west','wall-storage-east','wall-stair-north','wall-kitchen-screen','wall-kitchen-west-return'];
function structuralOptions(source,ids){return {materialization:'bounded-v3',registry:runtime().PlanImport.sceneCatalogue(),partialSelection:Scene.createPartialSelection(source,[],true,ids),bindingDecisions:['room-ldk','room-storage'].map(id=>({sourceSnapshot:JSON.stringify(source.rooms.find(e=>e.id===id)),binding:{id:'display-'+id,sourceEntityId:id,catalogId:u,sizingPolicy:'native',appearanceMode:'match-diagram-appearance'}}))};}
const target={heightDefaults:{modelVersion:2,wallHeight:2600,floorThickness:180,floorRaise:0,floorRaiseSet:true},floors:{}};
test('five non-hosting walls and storage floor use exact source horizontal geometry and reviewed display height',()=>{
 const source=structuredClone(frozen),before=JSON.stringify(source),opts=structuralOptions(source,[...safeWalls,'room-ldk','room-storage']),r=API.previewSceneIRSnapshot(source,target,opts);
 assert.equal(r.diagnostics.some(d=>d.severity==='error'),false,JSON.stringify(r.diagnostics));assert.deepEqual(r.plan.walls.map(w=>w.id),safeWalls);assert.deepEqual(r.plan.rooms.map(r=>r.id),['room-ldk','room-storage']);assert.equal(r.plan.rooms[1].floorColor,'#F1F0E8');
 for(const w of r.plan.walls){const raw=source.walls.find(e=>e.id===w.id);assert.deepEqual({id:w.id,floor:w.floor,start:{x:w.x1,y:w.y1},end:{x:w.x2,y:w.y2},thickness:w.thick},{id:raw.id,floor:raw.floor.value,start:raw.start.value,end:raw.end.value,thickness:raw.thicknessMm.value});assert.equal(w.wallHeight,2600);}
 assert.equal(r.defaults.filter(d=>d.path.endsWith('.wallHeight')&&d.provenance==='editor-default').length,5);assert.equal(r.fullReconstructionReady,false);assert.ok(r.deferredEntities.some(e=>e.id==='room-stair-space'));assert.equal(JSON.stringify(source),before);
});
test('structural dependency closure includes every hosted opening and adjoining room; forged missing aperture is rejected',()=>{
 const source=structuredClone(frozen),opts=structuralOptions(source,['wall-north']),scope=opts.partialSelection;
 assert.deepEqual(scope.entityIds,['room-ldk','wall-north','window-north-kitchen','window-north-sofa']);const forged=structuredClone(scope);forged.entityIds=forged.entityIds.filter(id=>id!=='window-north-sofa');const r=API.previewSceneIRSnapshot(source,target,{...opts,partialSelection:forged});assert.ok(r.diagnostics.some(d=>d.code==='stale_partial_selection'));assert.equal(r.canApply,false);
 const south=structuralOptions(source,['window-south-access']).partialSelection;assert.ok(south.entityIds.includes('window-south-stair'));assert.ok(south.entityIds.includes('room-stair-space'));const failed=API.previewSceneIRSnapshot(source,target,{...opts,partialSelection:south});assert.ok(failed.diagnostics.some(d=>d.code==='unsupported_stair_room_floor'));assert.equal(failed.canApply,false);assert.equal(failed.plan.rooms.some(r=>r.id==='room-stair-space'),false);
});
test('structural scope and source edits invalidate review keys, including unchanged walls',()=>{
 const source=structuredClone(frozen),opts=structuralOptions(source,['wall-west']),first=API.previewSceneIRSnapshot(source,target,opts),review={acceptedReviewGroups:first.reviewGroups.map(g=>g.id),reviewedEntities:Object.fromEntries(first.reviewGroups.map(g=>[g.entityId,g.reviewKey]))};
 assert.equal(API.previewSceneIRSnapshot(source,target,{...opts,...review}).canApply,true);const changed=API.previewSceneIRSnapshot(source,target,{...structuralOptions(source,['wall-west','wall-storage-east']),...review});assert.equal(changed.canApply,false);assert.equal(changed.reviewGroups.find(g=>g.entityId==='wall-west').accepted,false);
 const altered=structuredClone(source);altered.walls[1].thicknessMm.value++;const stale=API.previewSceneIRSnapshot(altered,target,{...opts,...review});assert.ok(stale.diagnostics.some(d=>d.code==='stale_partial_selection'));
});
test('API structural-only preview is bounded, isolated and still reports full unresolved source',async()=>{
 const state={snapshot:structuredClone(target),source:structuredClone(frozen),camera:{view:'3d-ext'},options:{},state:{history:[],redo:[],dirty:false}},before=JSON.stringify(state);let calls=0;
 const api=API.create({catalogue:()=>runtime().PlanImport.sceneCatalogue(),readScene:()=>state,renderPreview:async()=>{calls++;return {memoryOnly:true};}}),current=api.get_scene({planId:'draft'}),request={planId:'draft',baseRevision:current.revision,selectedObjectIds:[],selectedEntityIds:[...safeWalls,'room-ldk','room-storage'],displayBindings:['room-ldk','room-storage'].map(sourceEntityId=>({sourceEntityId,catalogId:null,sizingPolicy:'native',appearanceMode:'match-diagram-appearance'})),incompleteConfirmed:true};
 const r=await api.preview_patch(request);assert.equal(r.rendered,true);assert.equal(calls,1);assert.equal(r.previewPlan.walls.length,5);assert.equal(r.applyAvailable,false);assert.ok(r.fullDiagnostics.some(d=>d.code==='wrong_adjacent_room'));assert.ok(r.fullDiagnostics.some(d=>d.code==='unsupported_opening_mechanism'));assert.equal(JSON.stringify(state),before);
 await assert.rejects(api.preview_patch({...request,selectedEntityIds:['ann-title']}),e=>e.code==='invalid_patch');await assert.rejects(api.preview_patch({...request,selectedEntityIds:['wall-west','wall-west']}),e=>e.code==='invalid_patch');await assert.rejects(api.preview_patch({...request,selectionScope:r.selectionScope}),e=>e.code==='invalid_request');
});

test('selected nonphysical symbol failure belongs to review and unresolved ledger before Apply gating',()=>{
 const s=fixture();s.objects[0].objectType=f('unidentified-symbol');
 const opts=options(s);opts.bindingDecisions=[];
 const r=Scene.compile(s,opts);
 const d=r.diagnostics.find(d=>d.code==='selected_object_unmaterialized');assert.ok(d);
 assert.equal(r.canApply,false);
 assert.ok(r.reviewGroups.find(g=>g.entityId==='chair').diagnostics.some(x=>x.code===d.code));
 assert.ok(r.unresolvedEntities.find(e=>e.id==='chair').reasons.some(x=>x.code===d.code));
 assert.equal(r.reviewGroups.find(g=>g.entityId==='chair').canAcknowledgeOmission,false);
});
