const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const V3=require('../../assets/js/scene-ir-v3.js'),{runtime}=require('./scene-fixtures.cjs'),Geometry=require('../../assets/js/room-geometry.js'),{topLevelFunction}=require('./height-runtime.cjs');
const f=value=>({value,status:'observed',source:'independent synthetic 2F object survey'}),u=()=>({value:null,status:'unknown',unknownReason:'not-shown'});
const types={'sofa':'fmp-Sofa01','dining-table':'original-table','kitchen-sink':'fmp-CabinetA_Sink','refrigerator':'fmp-Refrigerator01'};
function fixture(c){let r=c.PlanImport.sceneCatalogue();return {sceneVersion:3,units:'mm',coordinateSystem:'x-east-y-south-clockwise',annotations:[],walls:[],rooms:[{id:'second-floor',floor:f(2),shape:f({kind:'rectUnion',rectangles:[{x:0,y:0,w:10000,d:6000}]}),boundaryBasis:f('clear-face')}],openings:[],objects:Object.entries(types).map(([type,id],i)=>{let m=r.get(id);return {id:'source-'+i,objectType:f(type),semanticExtent:f(m.semanticExtent),placement:f({domain:'room',roomId:'second-floor'}),sourceFootprint:f({center:{x:1500+i*2300,y:2500},sizeMm:{w:m.w,d:m.d},axisX:{x:1,y:0}}),frontDirection:u(),heightMm:u()};}),siteRegions:[],buildingFootprints:[],bindings:[],connections:[]};}
function decisions(scene,c){return scene.objects.map((o,i)=>({sourceSnapshot:JSON.stringify(o),binding:{id:'map-'+i,sourceEntityId:o.id,catalogId:f(types[o.objectType.value]),sizingPolicy:'native'}}));}
function reviewed(c,scene,extra={}){let opts={materialization:'bounded-v3',bindingDecisions:decisions(scene,c),...extra},first=c.PlanImport.previewSceneIR(scene,opts);return {...opts,acceptedReviewGroups:first.reviewGroups.map(g=>g.id),reviewedEntities:Object.fromEntries(first.reviewGroups.map(g=>[g.entityId,g.reviewKey]))};}
test('new source furniture types retain typed evidence and expose only exact catalogue semantic candidates',()=>{let c=runtime(),s=fixture(c),before=JSON.stringify(s);assert.equal(V3.compile(s).valid,true);for(let o of s.objects){let choices=c.PlanImport.sceneMappingCandidates(o,c.PlanImport.sceneCatalogue()).candidates;assert.ok(choices.some(m=>m.id===types[o.objectType.value]));assert.ok(choices.every(m=>(m.sourceObjectType||m.kind)===o.objectType.value));}assert.equal(JSON.stringify(s),before);});
test('four separately reviewed2F bindings Apply/save/Undo/Redo as ordinary real editable models preserving raw source',()=>{let c=runtime();c.RoomGeometry=Geometry;let s=fixture(c),raw=JSON.stringify(s);Object.assign(c,{REDO_HISTORY:[],HISTORY_LIMIT:100,DRAG:{active:false},ren:null,syncNorthFromPlan(){},ensureFloorMetadata(){},clearMultiSelection(){},sharedForceFullSync(){},markDirty(){},draw2d(){},sharedRememberEditTargets(){}});for(let name of ['serializeDataSnapshot','pushHistorySnapshot','saveState','restoreHistorySnapshot','undoAction','redoAction'])vm.runInContext(topLevelFunction(name),c);let before=c.serializeDataSnapshot(),opts=reviewed(c,s),staged=c.PlanImport.stageSceneIR(s,opts);assert.equal(staged.canApply,true,JSON.stringify(staged.diagnostics));c.applyPlanImport();let applied=c.serializeDataSnapshot();assert.equal(c.DATA.items.length,4);for(let it of c.DATA.items){assert.equal(it.floor,2);assert.ok(Object.values(types).includes(it.type));assert.equal(it.baseRoom,c.DATA.rooms[0].id);}assert.equal(JSON.stringify(s),raw);assert.equal(JSON.stringify(c.DATA.sceneReconstructionReports[0].originalIR),raw);assert.equal(c.DATA.sceneReconstructionReports[0].reviewDecisions.bindingDecisions.length,4);c.DATA=JSON.parse(applied);c.undoAction();assert.equal(c.serializeDataSnapshot(),before);c.redoAction();assert.equal(c.serializeDataSnapshot(),applied);});
test('known furniture front remains known and blocks models whose catalogue front is unaudited',()=>{let c=runtime(),s=fixture(c);s.objects[0].frontDirection=f({x:0,y:1});let raw=JSON.stringify(s),r=c.PlanImport.previewSceneIR(s,reviewed(c,s));assert.equal(r.canApply,false);assert.ok(r.diagnostics.some(d=>d.code==='mapping_unresolved'));assert.equal(JSON.stringify(s),raw);assert.equal(c.PlanImport.sceneCatalogue().get('fmp-Sofa01').front,null);});
test('semantic swap, stale source bindings and known incompatible heights cannot authorize Apply',()=>{for(let mutate of [(s,o)=>{o.bindingDecisions[0].binding.catalogId=f('fmp-Refrigerator01');},(s,o)=>{s.objects[0].sourceFootprint.value.center.x+=1;},(s,o)=>{s.objects[0].heightMm=f(2000);}]){let c=runtime(),s=fixture(c),opts=reviewed(c,s);mutate(s,opts);let r=c.PlanImport.previewSceneIR(s,opts);assert.equal(r.canApply,false);assert.equal(c.DATA.items.length,0);}});
