const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
const {runtime}=require('./scene-fixtures.cjs'),Audit=require('../../assets/js/scene-material-audit.js'),API=require('../../assets/js/editor-internal-api.js');
const TV='im0261-Cabinet-MEGA_PACK_CABINET-cabinet-354290_frame_walnut_brown';
function session(){const rt=runtime(),source=JSON.parse(fs.readFileSync('local-preview/frozen-page-2.json')),s={source,snapshot:{walls:[],rooms:[],items:[]},options:{materialization:'bounded-v3',pageScope:['frozen-page-2']},camera:{view:'2d',floor:2,twoD:{zoom:1,panX:0,panY:0},camera:null},state:{history:[],redo:[],dirty:false}};const cap={catalogue:()=>rt.PlanImport.sceneCatalogue(),readScene:()=>s,renderPreview:async input=>{input.assertFresh();return {memoryOnly:true};}};return {rt,s,cap,api:API.create(cap)};}
function patch(api,catalogId){return {planId:'host-draft',baseRevision:api.get_scene({planId:'host-draft'}).revision,selectedObjectIds:['obj-tv-console'],incompleteConfirmed:true,displayBindings:[{sourceEntityId:'room-ldk',catalogId:null,sizingPolicy:'native',appearanceMode:'match-diagram-appearance'},{sourceEntityId:'obj-tv-console',catalogId,sizingPolicy:'fit-source',appearanceMode:'match-diagram-appearance'}]};}
test('exact GLB audit pins actual material groups; unaudited catalogue controls remain unreviewed',()=>{const {api}=session(),audit=api.read_catalog({ids:[TV,'original-sideboard','fmp-Sofa01','fmp-Chair07']}).entries;assert.equal(audit[0].materialCapability.status,'asset-and-code-audited');assert.equal(audit[0].materialCapability.verifiedChannels[0].key,'body');assert.equal(audit[0].materialCapability.verifiedChannels[0].materials[0].textureColorEffect,'source-luminance-neutralized-tint');assert.equal(audit[1].materialCapability.verifiedChannels[0].key,'wood');assert.equal(audit[1].materialCapability.verifiedChannels[0].materials[0].textureColorEffect,'native-RGB-multiplies-tint');assert.equal(audit[1].materialCapability.fixedMaterials.length,2);assert.equal(audit[2].materialCapability.independentChannelCount,1);assert.equal(audit[2].materialCapability.sourceRegionSemanticsAudited,false);assert.equal(audit[3].materialCapability.status,'unreviewed');for(const a of Object.values(Audit.audits()))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(a.model)).digest('hex'),a.modelSHA256);});
test('asset/wiring mismatch fails audit; material descriptors are detached copies',()=>{const {rt,api}=session(),first=api.read_catalog({ids:[TV]}).entries[0];first.materialCapability.verifiedChannels.length=0;assert.equal(api.read_catalog({ids:[TV]}).entries[0].materialCapability.verifiedChannels.length,1);rt.CATALOGUE_FINISHES.models[rt.FMP_ITEMS[TV].model]['cabinet-354290_frame_walnut_brown']='wood';assert.equal(api.read_catalog({ids:[TV]}).entries[0].materialCapability.status,'audit-mismatch');});
test('previous successful preview diff detects 600 to 760 mm and geometry substitution without knowing raw height',async()=>{const {s,api}=session(),before=JSON.stringify(s);const first=await api.preview_patch(patch(api,TV));assert.equal(first.rendered,true);const f=first.diff.find(d=>d.sourceEntityId==='obj-tv-console').display;assert.equal(f.after.effectiveHeight.valueMm,600);assert.equal(f.after.sourceHeight.status,'unknown');const second=await api.preview_patch(patch(api,'original-sideboard')),d=second.diff.find(d=>d.sourceEntityId==='obj-tv-console').display;assert.equal(d.comparisonBasis,'previous-successful-isolated-preview');assert.equal(d.heightDeltaMm,160);assert.equal(d.heightChanged,true);assert.equal(d.geometryIdentityChanged,true);assert.equal(d.after.sourceHeight.value,null);assert.equal(d.after.effectiveHeight.sourceMeasured,false);assert.ok(second.diagnostics.some(d=>d.code==='display_height_changed'&&d.beforeMm===600&&d.afterMm===760));assert.ok(second.diagnostics.some(d=>d.code==='display_geometry_substitution'));assert.equal(JSON.stringify(s),before);});
test('failed preview never replaces comparison and stale baseline cannot be reused',async()=>{const {s,api,cap}=session();await api.preview_patch(patch(api,TV));cap.renderPreview=async()=>{throw Error('cancelled');};await assert.rejects(api.preview_patch(patch(api,'original-sideboard')));cap.renderPreview=async()=>({});const again=await api.preview_patch(patch(api,'original-sideboard'));assert.equal(again.diff.at(-1).display.heightDeltaMm,160);s.camera.twoD.zoom++;const next=await api.preview_patch(patch(api,TV));assert.equal(next.diff.at(-1).display.comparisonBasis,'unbound-source');});
test('known source height mismatch still blocks; channel transforms remain outside the bounded API',async()=>{const {s,api}=session();s.source.objects.find(o=>o.id==='obj-tv-console').heightMm={value:610,status:'observed',source:'synthetic:height measurement'};const p=patch(api,TV),out=await api.preview_patch(p);assert.equal(out.rendered,false);assert.ok(out.diagnostics.some(d=>d.code==='unsupported_asset_height'));p.displayBindings[1].channels=[{sourceRegion:'body',channel:'body',color:'#123456'}];await assert.rejects(api.preview_patch(p),e=>e.code==='invalid_request');});

test('sofa regional colours remain unresolved on the one-channel asset; source/front facts are retained',async()=>{const {api,s}=session(),before=JSON.stringify(s.source),request=patch(api,'fmp-Sofa01');request.selectedObjectIds=['obj-sofa'];request.displayBindings[1].sourceEntityId='obj-sofa';const out=await api.preview_patch(request);assert.equal(out.rendered,false);assert.ok(out.diagnostics.some(d=>d.code==='appearance_channels_unresolved'));assert.ok(out.diagnostics.some(d=>d.code==='mapping_unresolved'));assert.equal(JSON.stringify(s.source),before);assert.equal(s.source.objects.find(o=>o.id==='obj-sofa').appearance.diagramColor.value.length,2);});

test('returned rejected-preview descriptors cannot mutate the last successful comparison',async()=>{const {api}=session();await api.preview_patch(patch(api,TV));const rejected=patch(api,'original-sideboard');rejected.displayBindings[1].appearanceMode='unspecified';const out=await api.preview_patch(rejected);assert.equal(out.rendered,false);out.diff.at(-1).display.before.effectiveHeight.valueMm=0;const next=await api.preview_patch(patch(api,'original-sideboard'));assert.equal(next.diff.at(-1).display.heightDeltaMm,160);});
