const test=require('node:test'),assert=require('node:assert/strict');
const Scene=require('../../assets/js/scene-ir-v3.js'),Geometry=require('../../assets/js/room-geometry.js');
const f=value=>({value,status:'observed',source:'synthetic bounded materialization test'}),u={value:null,status:'unknown'};
function fixture(){return {sceneVersion:3,units:'mm',coordinateSystem:'x-east-y-south-clockwise',annotations:[],walls:[],rooms:[{id:'living',floor:f(1),shape:f({kind:'rectUnion',rectangles:[{x:0,y:0,w:4000,d:2000},{x:0,y:2000,w:2000,d:2000}]}),boundaryBasis:f('clear-face')}],openings:[],objects:[],siteRegions:[],buildingFootprints:[],bindings:[],connections:[]};}
const registry={get:id=>id==='desk'?{id,w:1200,d:600,h:730,front:'+Z',semanticExtent:'asset',finishChannels:[{key:'wood'}]}:null};
const base={materialization:'bounded-v3',registry,targetPlan:{heightDefaults:{modelVersion:2,floorThickness:180}},defaultFloorOffset:()=>0};
function approved(s,extra={}){const first=Scene.compile(s,{...base,...extra});return Scene.compile(s,{...base,...extra,acceptedReviewGroups:first.reviewGroups.map(g=>g.id),reviewedEntities:Object.fromEntries(first.reviewGroups.map(g=>[g.entityId,g.reviewKey]))});}
const codes=r=>r.diagnostics.map(d=>d.code);
function desk(){return {id:'desk-source',objectType:f('desk'),semanticExtent:f('asset'),placement:f({domain:'room',roomId:'living'}),sourceFootprint:f({center:{x:1000,y:1000},sizeMm:{w:1200,d:600},axisX:{x:1,y:0}}),frontDirection:f({x:0,y:1}),appearance:{diagramColor:f('#2255cc')},heightMm:u};}
function binding(){return {id:'desk-map',sourceEntityId:'desk-source',catalogId:f('desk'),sizingPolicy:'native',appearanceMode:'match-diagram-appearance'};}
test('bounded materialization keeps one editable L room after explicit fresh datum review',()=>{const s=fixture(),first=Scene.compile(s,base);assert.equal(first.canApply,false);const r=approved(s);assert.equal(r.canApply,true,JSON.stringify(r.diagnostics));assert.equal(r.plan.rooms.length,1);assert.equal(r.plan.rooms[0].shape.outer.length,6);assert.equal(Geometry.area(r.plan.rooms[0]),12000000);assert.equal(Geometry.contains(r.plan.rooms[0],{x:3000,y:3000}),false);assert.equal(r.plan.walls.length,0);assert.equal(Scene.compile(s).canApply,false);});
test('review decisions invalidate when source or mapped binding changes',()=>{const s=fixture(),r=Scene.compile(s,base),opts={...base,acceptedReviewGroups:r.reviewGroups.map(g=>g.id),reviewedEntities:Object.fromEntries(r.reviewGroups.map(g=>[g.entityId,g.reviewKey]))};assert.equal(Scene.compile(s,opts).canApply,true);s.rooms[0].shape.value.rectangles[0].w=4500;assert.equal(Scene.compile(s,opts).canApply,false);});
test('lowered entry uses explicit same-first-floor reference and known tile module',()=>{const s=fixture();s.rooms.push({id:'entry',floor:f(1),shape:f({kind:'rectUnion',rectangles:[{x:2100,y:2100,w:1740,d:1840}]}),boundaryBasis:f('clear-face'),relativeElevation:{offsetMm:f(-150),relativeToId:f('living')},appearance:{pattern:f('square-grid'),moduleMm:f(300),diagramColor:f('#888888')}});s.bindings.push({id:'entry-appearance',sourceEntityId:'entry',catalogId:u,sizingPolicy:'native',appearanceMode:'match-diagram-appearance'});const r=approved(s);assert.equal(r.canApply,true,JSON.stringify(r.diagnostics));const e=r.plan.rooms.find(r=>r.id==='entry');assert.equal(e.floorRaiseMm,-150);assert.equal(e.floorModuleMm,300);assert.equal(e.floorColor,'#888888');assert.equal(e.skipLevelMm,undefined);assert.equal(approved(s,{targetPlan:{heightDefaults:{}}}).canApply,false);});
test('known desk footprint/front/diagram color survives mapped native asset and height default is disclosed',()=>{const s=fixture();s.objects=[desk()];s.bindings=[binding()];const before=JSON.stringify(s),r=approved(s);assert.equal(r.canApply,true,JSON.stringify(r.diagnostics));const it=r.plan.items[0];assert.equal(it.rot,0);assert.equal(it.w,1200);assert.equal(it.d,600);assert.deepEqual(it.finishColors,{wood:'#2255cc'});assert.equal(it.baseRoom,'living');assert.ok(r.defaults.some(x=>x.path==='objects[0].heightMm'&&x.value===730));assert.equal(JSON.stringify(s),before);});
test('known catalog size mismatch cannot be fixed by native defaults and fit-source requires fresh review',()=>{const s=fixture();s.objects=[desk()];s.bindings=[binding()];s.objects[0].sourceFootprint.value.sizeMm.w=1400;assert.equal(approved(s).canApply,false);s.bindings[0].sizingPolicy='fit-source';const r=approved(s);assert.equal(r.canApply,true);assert.equal(r.plan.items[0].w,1400);assert.ok(codes(r).includes('asset_scaling_review'));});
test('unknown verified asset front and unmapped visible color block faithful materialization',()=>{const s=fixture();s.objects=[desk()];s.bindings=[binding()];assert.equal(approved(s,{registry:{get:()=>({...registry.get('desk'),front:null})}}).canApply,false);delete s.bindings[0].appearanceMode;assert.equal(approved(s).canApply,false);});
test('full footprint containment detects an object bridging a concave notch despite all four corners inside',()=>{const s=fixture();s.rooms[0].shape=f({kind:'orthogonalPolygon',outer:[{x:0,y:0},{x:4000,y:0},{x:4000,y:4000},{x:3000,y:4000},{x:3000,y:1000},{x:1000,y:1000},{x:1000,y:4000},{x:0,y:4000}]});const d=desk();d.sourceFootprint.value.center={x:2000,y:3000};d.sourceFootprint.value.sizeMm={w:3600,d:600};s.objects=[d];s.bindings=[{...binding(),sizingPolicy:'fit-source'}];const r=approved(s);assert.equal(r.canApply,false);assert.ok(codes(r).includes('asset_outside_room'));});
test('required openings and geometry cannot be omitted by source review acceptance',()=>{const s=fixture();s.walls=[{id:'wall',floor:f(1),start:f({x:0,y:0}),end:f({x:4000,y:0}),thicknessMm:f(120)}];s.openings=[{id:'door',floor:f(1),hostWallId:f('wall'),adjacentRoomIds:f(['living',null]),start:f({x:1000,y:0}),end:f({x:1900,y:0}),mechanism:f('fold')}];const r=approved(s,{unresolvedDecisions:[{entityId:'door',decision:'leave-unplaced',classification:'noncritical-decoration'}]});assert.equal(r.canApply,false);assert.ok(codes(r).includes('unsupported_opening_mechanism'));});
test('site region stays a source overlay with explicit incomplete status and no synthetic room/wall',()=>{const s=fixture();s.siteRegions=[{id:'parking',role:f('parking'),shape:f({kind:'rectUnion',rectangles:[{x:-3000,y:0,w:2500,d:5000}]})}];const r=approved(s);assert.equal(r.canApply,true);assert.equal(r.reconstructionStatus,'incomplete-source-overlays');assert.equal(r.plan.rooms.length,1);assert.equal(r.plan.walls.length,0);assert.equal(r.sourcePreview.polygons.find(p=>p.id==='parking').collection,'siteRegions');});
test('binding rotation cannot silently reverse known source front, and known bed head cannot disappear',()=>{const s=fixture();s.objects=[desk()];s.bindings=[{...binding(),rotationDeg:f(180)}];assert.equal(approved(s).canApply,false);assert.ok(codes(approved(s)).includes('asset_rotation_conflict'));s.bindings=[binding()];s.objects[0].objectType=f('bed');s.objects[0].headDirection=f({x:0,y:-1});assert.equal(approved(s).canApply,false);assert.ok(codes(approved(s)).includes('mapping_unresolved'));});
test('invalid catalog binding source is a diagnostic rather than exception',()=>{const s=fixture();s.bindings=[{...binding(),sourceEntityId:'missing'}];const r=Scene.compile(s,base);assert.equal(r.valid,false);assert.ok(codes(r).includes('invalid_reference'));});
test('required circulation cannot point to a door that adjoins different rooms',()=>{const s=fixture();s.rooms.push({...s.rooms[0],id:'other',shape:f({kind:'rectUnion',rectangles:[{x:10000,y:10000,w:1000,d:1000}]})});s.walls=[{id:'wall',floor:f(1),start:f({x:0,y:0}),end:f({x:4000,y:0}),thicknessMm:f(120)}];s.openings=[{id:'door',floor:f(1),hostWallId:f('wall'),adjacentRoomIds:f(['living',null]),start:f({x:1000,y:0}),end:f({x:1900,y:0}),mechanism:f('opening'),heightMm:f(2100)}];s.connections=[{id:'connection',rooms:f(['living','other']),openingId:f('door'),requiredTraversable:f(true)}];const r=approved(s);assert.equal(r.canApply,false);assert.ok(codes(r).includes('missing_traversable_connection'));});
test('a changed editor datum invalidates earlier review even when source evidence is unchanged',()=>{const s=fixture(),r=Scene.compile(s,base),opts={...base,acceptedReviewGroups:r.reviewGroups.map(g=>g.id),reviewedEntities:Object.fromEntries(r.reviewGroups.map(g=>[g.entityId,g.reviewKey]))};assert.equal(Scene.compile(s,opts).canApply,true);assert.equal(Scene.compile(s,{...opts,defaultFloorOffset:()=>500}).canApply,false);});
test('opening adjacency checks every boundary interval, not just endpoints and midpoint',()=>{const s=fixture();s.rooms[0].boundaryBasis=f('wall-centerline');s.rooms[0].shape=f({kind:'orthogonalPolygon',outer:[{x:0,y:0},{x:800,y:0},{x:800,y:500},{x:1200,y:500},{x:1200,y:0},{x:4000,y:0},{x:4000,y:4000},{x:0,y:4000}]});s.walls=[{id:'wall',floor:f(1),start:f({x:0,y:0}),end:f({x:4000,y:0}),thicknessMm:f(120)}];s.openings=[{id:'door',floor:f(1),hostWallId:f('wall'),adjacentRoomIds:f(['living',null]),start:f({x:100,y:0}),end:f({x:3900,y:0}),mechanism:f('opening'),heightMm:f(2100)}];const r=approved(s);assert.equal(r.canApply,false);assert.ok(codes(r).includes('wrong_adjacent_room'));});
test('plain source pattern uses untextured material, and unsupported known plank module blocks',()=>{const s=fixture();s.rooms[0].appearance={pattern:f('plain'),diagramColor:f('#888888')};s.bindings=[{id:'room-color',sourceEntityId:'living',catalogId:u,sizingPolicy:'native',appearanceMode:'match-diagram-appearance'}];const r=approved(s);assert.equal(r.canApply,true);assert.equal(r.plan.rooms[0].floorDiagramPattern,'plain');s.rooms[0].appearance.pattern=f('plank-lines');s.rooms[0].appearance.moduleMm=f(120);assert.equal(approved(s).canApply,false);});
test('actual floor material renderer honors plain source without native wood/tile textures',async()=>{const vm=require('vm'),{topLevelFunction}=require('./height-runtime.cjs'),THREE=await import('../../assets/vendor/three/build/three.module.js'),c=vm.createContext({THREE});vm.runInContext(topLevelFunction('makeRoomFloorMaterial'),c);const m=c.makeRoomFloorMaterial({floorDiagramPattern:'plain',floorColor:'#888888',w:1000,d:1000,n:'トイレ'});assert.equal(m.map,null);assert.equal(m.color.getHexString(),'888888');});
test('extracted catalog choice cannot authorize its own mapping, even when every source dimension is known',()=>{const s=fixture(),d=desk();delete d.appearance;d.heightMm=f(730);s.objects=[d];s.bindings=[{...binding(),catalogId:{value:'desk',status:'inferred',source:'guess',reason:'looks similar'}}];const first=Scene.compile(s,base),roomGroup=first.reviewGroups.find(g=>g.entityId==='living'),r=Scene.compile(s,{...base,acceptedReviewGroups:[roomGroup.id],reviewedEntities:{living:roomGroup.reviewKey}});assert.equal(r.canApply,false);assert.ok(r.reviewGroups.find(g=>g.entityId==='desk-source').reviewPaths.some(p=>p.endsWith('.binding')));});
test('actual PlanImport Apply keeps logical polygon and source overlay through additive placement and one undo',()=>{const {runtime}=require('./scene-fixtures.cjs'),c=runtime();c.RoomGeometry=Geometry;const s=fixture();s.siteRegions=[{id:'parking',role:f('parking'),shape:f({kind:'rectUnion',rectangles:[{x:-3000,y:0,w:2500,d:5000}]})}];c.DATA.rooms.push({id:'existing',type:'room',floor:1,x:0,y:0,w:1000,d:1000,n:'Keep'});c.DATA.items.push({id:'existing-roof',type:'roof',floor:1,x:0,y:0,w:1000,d:1000});const before=JSON.stringify(c.DATA),first=c.PlanImport.previewSceneIR(s,{materialization:'bounded-v3'}),opts={materialization:'bounded-v3',acceptedReviewGroups:first.reviewGroups.map(g=>g.id),reviewedEntities:Object.fromEntries(first.reviewGroups.map(g=>[g.entityId,g.reviewKey]))};const staged=c.PlanImport.stageSceneIR(s,opts);assert.equal(staged.canApply,true,JSON.stringify(staged.diagnostics));assert.equal(JSON.stringify(c.DATA),before);c.applyPlanImport();assert.equal(c.HISTORY.length,1);assert.equal(c.DATA.rooms.length,2);const made=c.DATA.rooms.find(r=>r.id!=='existing');assert.equal(Geometry.area(made),12000000);assert.equal(made.x,4000);assert.equal(made.shape.outer[0].x,4000);assert.equal(Geometry.contains(made,7000,3000),false);assert.ok(c.DATA.items.some(i=>i.id==='existing-roof'));assert.equal(c.DATA.items.length,1,'No invented roof/foundation from source walls');const report=c.DATA.sceneReconstructionReports[0];assert.equal(report.version,3);assert.equal(report.translation.x,4000);assert.equal(report.originalIR.rooms[0].shape.value.rectangles[0].x,0);assert.ok(report.sourcePreview.polygons.some(p=>p.id==='parking'));const restored=JSON.parse(c.HISTORY[0]);assert.equal(JSON.stringify(restored),before);});
test('separate binding decisions preserve raw extraction and invalidate on changed source',()=>{const s=fixture();s.objects=[desk()];const raw=JSON.stringify(s),b={binding:binding(),sourceSnapshot:JSON.stringify(s.objects[0])};const opts={bindingDecisions:[b]},r=approved(s,opts);assert.equal(r.canApply,true,JSON.stringify(r.diagnostics));assert.equal(JSON.stringify(s),raw);assert.equal(r.sourceScene.bindings.length,0);assert.equal(r.plan.items[0].type,'desk');s.objects[0].sourceFootprint.value.center.x+=10;assert.ok(codes(approved(s,opts)).includes('stale_binding_decision'));});
test('v3 Apply refuses active shared sessions even after source review',()=>{const {runtime}=require('./scene-fixtures.cjs'),c=runtime();c.SHARED={roomId:'active'};const r=c.PlanImport.previewSceneIR(fixture(),{materialization:'bounded-v3'});assert.equal(r.canApply,false);assert.ok(codes(r).includes('shared_v3_disabled'));});
test('local v3 plan cannot create or update a shared room while mixed-client protection is absent',async()=>{const vm=require('vm'),{topLevelFunction}=require('./height-runtime.cjs'),c=vm.createContext({DATA:{rooms:[{shape:{kind:'orthogonalPolygon'}}]},SHARED:{roomId:'active'},sharedSetStatus:()=>{},fetch:()=>{throw Error('must not transmit');}});vm.runInContext(topLevelFunction('sceneV3LocalOnlyPlan'),c);const html=require('fs').readFileSync(require('path').resolve(__dirname,'../../index.html'),'utf8');for(const name of ['createSharedRoom','sharedSyncNow']){const at=html.indexOf('async function '+name+'('),end=html.indexOf('\n}',at);vm.runInContext(html.slice(at,end+2),c);}await c.createSharedRoom();await c.sharedSyncNow();});
test('exterior source car must remain in parking and outside the building footprint',()=>{const s=fixture();s.rooms=[];s.siteRegions=[{id:'parking',role:f('parking'),shape:f({kind:'rectUnion',rectangles:[{x:0,y:0,w:5000,d:6000}]})}];s.buildingFootprints=[{id:'building',shape:f({kind:'rectUnion',rectangles:[{x:0,y:0,w:1500,d:3000}]}),boundaryBasis:f('outer-face')}];s.objects=[{id:'car',objectType:f('car'),semanticExtent:f('asset'),placement:f({domain:'exterior',regionId:'parking'}),sourceFootprint:f({center:{x:3000,y:3000},sizeMm:{w:1800,d:4400},axisX:{x:1,y:0}}),frontDirection:f({x:0,y:-1})}];s.bindings=[{id:'car-map',sourceEntityId:'car',catalogId:f('car'),sizingPolicy:'native'}];const extra={registry:{get:()=>({kind:'car',w:1800,d:4400,h:1620,front:'+Z',semanticExtent:'asset',finishChannels:[],genericColor:true})}};assert.equal(approved(s,extra).canApply,true);s.objects[0].sourceFootprint.value.center.x=1400;assert.ok(codes(approved(s,extra)).includes('exterior_asset_intersects_building'));s.objects[0].sourceFootprint.value.center.x=4800;assert.ok(codes(approved(s,extra)).includes('asset_outside_exterior_region'));});
