const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const Flow=require('../../assets/js/scene-review-flow.js');
const {runtime,fixture}=require('./scene-fixtures.cjs');
const {createReviewDocument,ReviewEvent}=require('./scene-review-dom.cjs');
const raw=fs.readFileSync('local-preview/frozen-page-2.json','utf8');
function setup(){const c=runtime();c.document=createReviewDocument();c.Event=ReviewEvent;for(const id of ['plan-import-modal','plan-import-step3','plan-import-summary','plan-import-notes','plan-import-apply','scene-review-files']){const e=c.document.createElement(id==='scene-review-files'?'details':'div');e.id=id;c.document.body.appendChild(e);}vm.runInContext(fs.readFileSync('assets/js/scene-review-flow.js','utf8'),c);c.SceneReviewFlow.mount();return c;}
test('review packets retain immutable source and choices but never target plan or approvals',()=>{const scene=JSON.parse(raw),binding={sourceSnapshot:'test',binding:{id:'manual'}};const body={sceneIR:scene,sceneOptions:{bindingDecisions:[binding],partialSelection:{objectIds:['obj-fridge']},acceptedReviews:['old'],acceptedReviewGroups:['old'],reviewedEntities:{old:'x'},unresolvedDecisions:['old'],targetSnapshot:{secret:'existing-user-plan'}},extraction:{rawResponse:raw}};const out=Flow.packet(body,{name:'reference.pdf',pages:['data:image/a','data:image/b']});assert.deepEqual(out.sceneIR,scene);assert.equal(out.extraction.rawResponse,raw);assert.deepEqual(out.sceneOptions.bindingDecisions,[binding]);assert.equal(out.sceneOptions.targetSnapshot,undefined);assert.deepEqual(out.sceneOptions.acceptedReviewGroups,[]);assert.deepEqual(out.sceneOptions.reviewedEntities,{});assert.doesNotMatch(JSON.stringify(out),/existing-user-plan|data:image/);assert.deepEqual(Flow.decode(JSON.stringify(out)).options,out.sceneOptions);assert.equal(body.sceneOptions.acceptedReviews.length,1);});
test('native plan routing and supported older v2 preserve separate import contracts',()=>{assert.equal(Flow.isReviewData({walls:[],rooms:[],items:[],sceneReconstructionReports:[{originalIR:JSON.parse(raw)}]}),false);assert.equal(Flow.decode(JSON.stringify(fixture())).sceneIR.sceneVersion,2);assert.throws(()=>Flow.decode('{'),/構文/);assert.throws(()=>Flow.decode(JSON.stringify({format:Flow.format,version:2})),/版/);assert.throws(()=>Flow.decode('{"pages":[]}'),/統合/);assert.throws(()=>Flow.decode('{"walls":[],"rooms":[],"items":[]}'),/JSON読込/);});
test('invalid scene or malformed building fails before replacing current review or plan',()=>{const c=setup();c.SceneReviewFlow.importText(raw);const body=c.PlanImport.state.result,data=JSON.stringify(c.DATA);assert.throws(()=>c.SceneReviewFlow.importText('{"sceneVersion":3}'),/不正/);assert.strictEqual(c.PlanImport.state.result,body);c.PlanRegistration={compile(){throw Error('bad frame');}};assert.throws(()=>c.SceneReviewFlow.importText('{"sourceLocal":{"floors":[null]}}'),/複数階JSON/);assert.strictEqual(c.PlanImport.state.result,body);assert.equal(JSON.stringify(c.DATA),data);});
test('late file reading after a different review or cancel cannot overwrite it',async()=>{for(const cancel of [false,true]){const c=setup();c.SceneReviewFlow.importText(raw);let resolve;const input=c.document.querySelector('[data-scene-review-file]');input.files=[{size:raw.length,text:()=>new Promise(r=>resolve=r)}];input.dispatchEvent(new ReviewEvent('change'));if(cancel)c.closePlanImport();else c.SceneReviewFlow.importText(JSON.stringify(fixture()));const body=c.PlanImport.state.result;resolve(raw);await new Promise(r=>setImmediate(r));assert.strictEqual(c.PlanImport.state.result,body);}});
test('saved native evidence reopens original source with fresh approvals, not manually edited placement',()=>{const c=setup(),source=JSON.parse(raw);c.DATA.items=[{id:999,x:9876,manual:true}];c.DATA.sceneReconstructionReports=[{originalIR:source,reviewDecisions:{acceptedReviewGroups:['old'],bindingDecisions:[]},extraction:{rawResponse:raw}}];c.SceneReviewFlow.render(null);const before=JSON.stringify(c.DATA);c.document.querySelector('[data-scene-resume-report]').click();assert.equal(JSON.stringify(c.DATA),before);assert.equal(JSON.stringify(c.PlanImport.state.result.sceneIR),JSON.stringify(source));assert.equal(c.PlanImport.state.result.sceneOptions.acceptedReviewGroups.length,0);});
test('saved building evidence restores actual report proposals and requests fresh registration',()=>{const c=setup();let staged;c.PlanRegistration={compile(){return {};}};c.PlanImport.stageBuildingReview=b=>{staged=b;c.PlanImport.state.result=b;};c.DATA.sceneReconstructionReports=[{sourceLocal:{floors:[{floor:1}]},proposals:{version:1,floors:[{floor:1,quarterTurns:2}]},decisions:{reviewed:true}}];c.SceneReviewFlow.render(null);c.document.querySelector('[data-scene-resume-report]').click();assert.equal(staged.buildingRegistration.floors[0].quarterTurns,2);assert.equal(staged.buildingDecisions,undefined);});
test('real sink review exposes installation limits alongside successful catalogue choices',()=>{const c=setup();c.SceneReviewFlow.importText(raw);const advice=c.document.querySelector('[data-scene-guidance="objects:obj-kitchen-sink"]');assert.ok(advice);assert.match(advice.textContent,/取付高さ・支持する天板・天板の切欠き/);assert.match(advice.textContent,/再現完了ではありません/);});
test('legacy multi-floor review retains source notes, image annotations and exact input bytes without replaying approvals',()=>{const source=fs.readFileSync('local-preview/sample.json','utf8'),decoded=Flow.decode(source),body=decoded.body;assert.equal(body.registrationExtraction.rawResponse,source);assert.deepEqual(body.sourceImageAnnotations,JSON.parse(source).sourceImageAnnotations);body.buildingDecisions={floors:[{reviewed:true}]};const saved=Flow.packet(body);assert.deepEqual(saved.notes,body.notes);assert.equal(saved.registrationExtraction.rawResponse,source);assert.equal(saved.buildingDecisions,undefined);assert.deepEqual(Flow.decode(JSON.stringify(saved)).body.sourceLocal,body.sourceLocal);});
test('late PDF failure cannot replace feedback for a newer review',async()=>{const c=setup();let reader,reject;c.FileReader=class{constructor(){reader=this;}readAsDataURL(){}};c.PdfPages={renderPages:()=>new Promise((_,r)=>reject=r)};c.SceneReviewFlow.importText(raw);const input=c.document.querySelector('input[aria-label="照合するPDFか画像"]');input.files=[{size:10,type:'application/pdf',name:'old.pdf'}];input.dispatchEvent(new ReviewEvent('change'));reader.onload({target:{result:'data:application/pdf;base64,'}});await new Promise(r=>setImmediate(r));c.SceneReviewFlow.importText(raw);const expected=c.document.getElementById('scene-review-file-status').textContent;reject(Error('old decode failed'));await new Promise(r=>setImmediate(r));assert.equal(c.document.getElementById('scene-review-file-status').textContent,expected);});
function deferredPdf(c){const reads=[],jobs=[];c.FileReader=class{constructor(){reads.push(this);}readAsDataURL(){}};c.PdfPages={renderPages:()=>new Promise((resolve,reject)=>jobs.push({resolve,reject}))};return {jobs,async start(name='reference.pdf'){const input=c.document.querySelector('input[aria-label="照合するPDFか画像"]');input.files=[{size:10,type:'application/pdf',name}];input.dispatchEvent(new ReviewEvent('change'));reads.at(-1).onload({target:{result:'data:application/pdf;base64,'}});await new Promise(r=>setImmediate(r));}};}
function editFridge(c){c.document.querySelector('[data-scene-mapping="obj-refrigerator"]').click();const input=c.document.querySelector('[data-scene-sizing]');input.value='fit-source';input.dispatchEvent(new ReviewEvent('change'));return input;}
const flush=()=>new Promise(r=>setImmediate(r));
test('PDF completion preserves open unsaved mapping inputs and current review identity',async()=>{const c=setup();c.SceneReviewFlow.importText(raw);const d=deferredPdf(c),body=c.PlanImport.state.result,data=JSON.stringify(c.DATA);await d.start();const input=editFridge(c),editor=c.PlanImport.state.mappingEditor;d.jobs[0].resolve(['new-reference']);await flush();assert.strictEqual(c.PlanImport.state.result,body);assert.strictEqual(c.PlanImport.state.mappingEditor,editor);assert.strictEqual(c.document.querySelector('[data-scene-sizing]'),input);assert.equal(input.value,'fit-source');assert.match(c.document.getElementById('scene-review-file-status').textContent,/入力は保持.*選び直して/);assert.equal(JSON.stringify(c.DATA),data);assert.equal(JSON.stringify(body.sceneIR),JSON.stringify(JSON.parse(raw)));});
test('opening then cancelling a mapping does not revive a previously pending PDF',async()=>{const c=setup();c.SceneReviewFlow.importText(raw);const d=deferredPdf(c),body=c.PlanImport.state.result;await d.start();editFridge(c);c.document.querySelector('[data-scene-mapping-cancel]').click();assert.equal(c.PlanImport.state.mappingEditor,null);d.jobs[0].resolve(['obsolete']);await flush();assert.strictEqual(c.PlanImport.state.result,body);assert.equal(c.document.querySelector('[data-scene-reference-image]').getAttribute('src'),null);assert.match(c.document.getElementById('scene-review-file-status').textContent,/反映していません/);});
test('PDF responses in reverse order retain only the newest reference and close discards pending work',async()=>{const c=setup();c.SceneReviewFlow.importText(raw);const d=deferredPdf(c);await d.start('old.pdf');await d.start('new.pdf');d.jobs[1].resolve(['new-page']);await flush();const body=c.PlanImport.state.result;d.jobs[0].resolve(['old-page']);await flush();assert.strictEqual(c.PlanImport.state.result,body);assert.equal(c.document.querySelector('[data-scene-reference-image]').src,'new-page');await d.start('cancelled.pdf');c.closePlanImport();d.jobs[2].resolve(['cancelled-page']);await flush();assert.strictEqual(c.PlanImport.state.result,body);assert.equal(body.extraction.rawResponse,raw);assert.deepEqual(Array.from(body.sceneOptions.acceptedReviewGroups),[]);});
test('real floor-change hook invalidates pending reference even after switching back',async()=>{const c=setup();const {topLevelFunction}=require('./height-runtime.cjs');for(const id of ['props','props-body','st-floor']){const e=c.document.createElement('div');e.id=id;c.document.body.appendChild(e);}c.clearMultiSelection=()=>{};c.resetPickCycle=()=>{};c.draw2d=()=>{};c.DRAG={};vm.runInContext(topLevelFunction('onFloorChange'),c);c.SceneReviewFlow.importText(raw);const d=deferredPdf(c),body=c.PlanImport.state.result;await d.start();c.onFloorChange(2);c.onFloorChange(1);d.jobs[0].resolve(['obsolete-floor']);await flush();assert.equal(c.ST.floor,1);assert.strictEqual(c.PlanImport.state.result,body);assert.equal(c.document.querySelector('[data-scene-reference-image]').getAttribute('src'),null);assert.match(c.document.getElementById('scene-review-file-status').textContent,/反映していません/);});
test('pending PDF cannot replace a partial Apply transaction during opening or after success',async()=>{for(const finishFirst of [false,true]){const c=setup(),source=JSON.parse(raw);c.PlanImport.stageSceneIR(source,{materialization:'bounded-v3',partialSelection:c.SceneIR.createPartialSelection(source,[],true,['wall-west']),extraction:{rawResponse:raw}});c.document.querySelector('[data-scene-partial-accept]').click();assert.equal(c.PlanImport.state.result.sceneCompilation.canApply,true);const d=deferredPdf(c),body=c.PlanImport.state.result;await d.start();let opened;c.ParallelEditors={openPlan:()=>new Promise(r=>opened=r)};const applying=c.applyPlanImport();assert.equal(c.PlanImport.state.busy,true);if(finishFirst){opened('review-plan');await applying;assert.equal(body.scenePartialOpened,true);}d.jobs[0].resolve(['too-late']);await flush();assert.strictEqual(c.PlanImport.state.result,body);if(!finishFirst){opened('review-plan');await applying;}assert.equal(body.scenePartialOpened,true);assert.equal(body.partialPlanId,'review-plan');assert.equal(c.document.getElementById('plan-import-modal').classList.contains('show'),false);assert.equal(body.extraction.rawResponse,raw);}});
test('terminal applied states and busy state independently reject late PDF completion',async()=>{for(const key of ['sceneApplied','scenePartialOpened','buildingApplied','busy']){const c=setup();c.SceneReviewFlow.importText(raw);const d=deferredPdf(c),body=c.PlanImport.state.result;await d.start();if(key==='busy')c.PlanImport.state.busy=true;else body[key]=true;d.jobs[0].resolve(['old-reference']);await flush();assert.strictEqual(c.PlanImport.state.result,body);assert.equal(key==='busy'?c.PlanImport.state.busy:body[key],true);}});
test('5.6MB schema-valid Unicode source exports a bounded v2 memo and retains exact raw on resume',()=>{const source=JSON.parse(raw),text='図'.repeat(2000);source.annotations=source.annotations.concat(Array.from({length:256-source.annotations.length},(_,i)=>({id:'large-note-'+i,kind:'label',literalText:{value:text,status:'inferred',source:text,reason:text}})));const compact=JSON.stringify(source),target=5685751;assert.ok(Buffer.byteLength(compact)<target);const original=compact+' '.repeat(target-Buffer.byteLength(compact));assert.equal(Buffer.byteLength(original),target);assert.equal(require('../../assets/js/scene-ir-v3.js').compile(source).valid,true);const parsed=Flow.decode(original),saved=Flow.packet({sceneIR:parsed.sceneIR,sceneOptions:parsed.options,extraction:parsed.extraction}),encoded=JSON.stringify(saved);assert.equal(saved.version,2);assert.equal(saved.sceneIR,undefined);assert.ok(Buffer.byteLength(encoded)<=Flow.maxFileBytes);const resumed=Flow.decode(encoded);assert.deepEqual(resumed.sceneIR,source);assert.equal(resumed.extraction.rawResponse,original);assert.deepEqual(resumed.options.acceptedReviewGroups,[]);assert.equal(Flow.packet({sceneIR:resumed.sceneIR,sceneOptions:resumed.options,extraction:resumed.extraction}).version,2);});
test('UTF-8 byte limit handles exact boundaries, Unicode and surrogate pairs consistently',()=>{for(const s of ['ascii','図','😀','\ud800','\udc00','図😀\ud800'])assert.equal(Flow.byteLength(s),Buffer.byteLength(s));const prefix='{"sceneVersion":2,"note":"図😀"}',padding=Flow.maxFileBytes-Buffer.byteLength(prefix),atLimit=prefix+' '.repeat(padding);assert.equal(Flow.byteLength(atLimit),Flow.maxFileBytes);assert.equal(Flow.decode(atLimit).sceneIR.sceneVersion,2);assert.throws(()=>Flow.decode(atLimit+' '),/8MB/);assert.throws(()=>Flow.decode('図'.repeat(Math.floor(Flow.maxFileBytes/3)+1)),/8MB/);});
test('oversized or mismatching raw cannot produce an unreadable successful export',()=>{const source=JSON.parse(raw),body={sceneIR:source,extraction:{rawResponse:' '.repeat(Flow.maxFileBytes)+raw}};assert.throws(()=>Flow.packet(body),/書き出していません/);body.extraction.rawResponse=JSON.stringify({...source,units:'wrong'})+' '.repeat(Flow.maxFileBytes);assert.throws(()=>Flow.packet(body),/書き出していません/);assert.throws(()=>Flow.decode(JSON.stringify({format:Flow.format,version:2,sceneEncoding:'raw-response-v1',sceneIR:source,extraction:{rawResponse:raw}})),/不正/);assert.throws(()=>Flow.decode(JSON.stringify({format:Flow.format,version:2,sceneEncoding:'raw-response-v1',extraction:{rawResponse:'{}'}})),/原本/);});
test('oversize save UI does not call download or replace review data',()=>{const c=setup();c.SceneReviewFlow.importText(raw);const body=c.PlanImport.state.result;body.extraction={rawResponse:' '.repeat(Flow.maxFileBytes)+raw};let downloads=0;c.downloadJsonFile=()=>downloads++;c.document.querySelector('[data-scene-review-save]').click();assert.equal(downloads,0);assert.strictEqual(c.PlanImport.state.result,body);assert.match(c.document.getElementById('scene-review-file-status').textContent,/書き出していません/);});
test('large native saved-evidence button uses the canonical bounded codec and preserves the stored report',()=>{const source=JSON.parse(raw),text='図'.repeat(2000);source.annotations=source.annotations.concat(Array.from({length:256-source.annotations.length},(_,i)=>({id:'native-large-note-'+i,kind:'label',literalText:{value:text,status:'inferred',source:text,reason:text}})));const compact=JSON.stringify(source),original=compact+' '.repeat(5685751-Buffer.byteLength(compact));const c=setup(),scope=c.SceneIR.createPartialSelection(source,[],true,['wall-west']);c.DATA.sceneReconstructionReports=[{originalIR:source,extraction:{rawResponse:original},reviewDecisions:{materialization:'bounded-v3',partialSelection:scope,acceptedReviewGroups:['walls:wall-west'],reviewedEntities:{'wall-west':'old'}},deferredEntities:source.objects.map(o=>({id:o.id,source:o})),sourceNotes:['retained native note']}];const before=JSON.stringify(c.DATA);c.SceneReviewFlow.render(null);c.document.querySelector('[data-scene-resume-report]').click();const body=c.PlanImport.state.result;assert.ok(body,c.document.getElementById('scene-review-file-status').textContent);assert.equal(body.extraction.rawResponse,original);assert.equal(JSON.stringify(body.sceneIR),JSON.stringify(source));assert.equal(body.sceneOptions.acceptedReviewGroups.length,0);assert.equal(Object.keys(body.sceneOptions.reviewedEntities).length,0);assert.equal(body.sceneCompilation.canApply,false);assert.equal(JSON.stringify(c.DATA),before);});

// Ownership and retained-source regressions use anonymous synthetic sources and
// actual existing controllers/installers. No browser, AI/provider or live fetch.
const {runtime:paneRuntime,fixture:panePlan,clone:copy}=require('./parallel-view-preferences-support.cjs');
const {libraryContext,makePaneWindow}=require('./plan-library-test-support.cjs');
const importSource=fs.readFileSync('assets/js/plan-import.js','utf8'),finishSource=fs.readFileSync('assets/js/plan-finish.js','utf8');
function syntheticPane(){
 const r=paneRuntime(),c=r.ctx;c.AbortController=AbortController;c.self=c;
 c.document=createReviewDocument();for(const id of ['plan-import-modal','plan-import-step2','plan-import-step3','plan-import-summary','plan-import-notes','plan-import-status','plan-import-run','plan-import-apply','scene-review-files','save-btn','snap-sel','floor-sel','surface-sel','surface-control','surface-context','st-mode']){const e=c.document.createElement(id==='scene-review-files'?'details':'div');e.id=id;c.document.body.appendChild(e);}
 vm.runInContext(importSource,c);vm.runInContext(fs.readFileSync('assets/js/scene-review-flow.js','utf8'),c);c.SceneReviewFlow.mount();c.__editorPlanId='A';
 c.Image=class{naturalWidth=1000;naturalHeight=800;set src(v){this._src=v;Promise.resolve().then(()=>this.onload?.());}get src(){return this._src;}};
 return r;
}
function reading(label='anonymous'){return {plan:{walls:[],rooms:[],items:[]},summary:{walls:0,rooms:0,items:0,floors:[1]},notes:[label],warnings:[],revise:{skipAll:true},extraction:{rawResponse:'{"synthetic":"'+label+'"}'}};}
function stageSynthetic(c,label='A'){const s=c.PlanImport.state;s.pages=['data:image/png;synthetic-'+label];s.pdfData='data:application/pdf;synthetic-'+label;s.fileName=label+'.pdf';s.result=reading(label);c.PlanImport.renderPlanImportResult(s.result);c.document.getElementById('plan-import-modal').classList.add('show');return s.result;}
function later(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
const flushSynthetic=()=>new Promise(setImmediate);
test('actual pane owner rejects same-ID payload replacement/ABA but accepts camera-only viewState',()=>{
 const {ctx:c}=syntheticPane(),context=c.PlanImport.captureContext();c.ST.panX=500;c.DATA.viewState={camera:{x:999}};c.EditorPane.noteImportTargetEdit();assert.equal(context.isCurrent(),true);
 const original=copy(c.DATA);c.applyJsonImport({data:panePlan('changed',45)});c.applyJsonImport({data:original});assert.equal(context.isCurrent(),false);assert.equal(c.__editorPlanId,'A');
});
test('actual import chain cannot issue revise/finish after A→C→A or disposal',async()=>{
 for(const dispose of [false,true]){const r=syntheticPane(),c=r.ctx,pending=later(),calls=[];stageSynthetic(c);c.fetch=(url,opts)=>{calls.push({url,opts});return pending.promise;};const run=c.runPlanImport();assert.equal(calls.length,1);
 if(dispose)c.EditorPane.dispose();else{await c.EditorPane.install(panePlan('C'),{view:{view:'2d'}});await c.EditorPane.install(panePlan('A'),{view:{view:'2d'}});}
 pending.resolve(Response.json({...reading(),revise:{skipAll:false},pages:[{floor:1}],plan:{walls:[],rooms:[{x:0,y:0,w:100,d:100}],items:[]}}));await run;assert.equal(calls.length,1);assert.equal(c.PlanImport.state.result,null);assert.equal(calls[0].opts.signal.aborted,true);}
});
test('close retains completed raw/source and old completion never clears a newer busy request',async()=>{
 const {ctx:c}=syntheticPane(),body=stageSynthetic(c),first=later(),second=later();const calls=[];c.fetch=(url,opts)=>{calls.push({url,opts});return calls.length===1?first.promise:second.promise;};const one=c.runPlanImport();c.PlanImport.state.failedSceneResponse={rawResponse:'anonymous rejected reply'};c.closePlanImport();assert.equal(c.PlanImport.state.pages[0],'data:image/png;synthetic-A');assert.equal(c.PlanImport.state.failedSceneResponse.rawResponse,'anonymous rejected reply');assert.equal(calls[0].opts.signal.aborted,true);
 const two=c.runPlanImport();first.resolve(Response.json(reading('old')));await one;assert.equal(c.PlanImport.state.busy,true);second.resolve(Response.json(reading('new')));await two;assert.equal(c.PlanImport.state.result.notes[0],'new');assert.equal(c.PlanImport.state.busy,false);assert.equal(body.extraction.rawResponse,'{"synthetic":"A"}');
});
test('PlanFinish rechecks the same owner before marks POST and cached result write',async()=>{
 const {ctx:c}=syntheticPane();vm.runInContext(finishSource,c);const first=later(),calls=[];c.fetch=(url,opts)=>{calls.push(url);return first.promise;};c.PlanCheck={typesByRoomId(){c.applyJsonImport({data:panePlan('changed')});return {};},knowledgeWarnings:()=>[],readMarks:()=>({reads:[],ask:[{id:'m1',index:0}]})};
 const pending=c.PlanFinish.analyze({rooms:[{x:0,y:0,w:1000,d:1000,n:'Synthetic'}],items:[]},[{}],c.PlanImport.captureContext());first.resolve(Response.json({rooms:[{id:'r0',use:'other'}]}));assert.equal(await pending,null);assert.deepEqual(calls,['/api/ai/finish-plan']);assert.equal(c.PlanFinish.result,null);
});
test('cancelled import polling timer cannot send another request or change new status',async()=>{
 const {ctx:c}=syntheticPane(),timers=new Map();let sequence=0;c.setTimeout=fn=>{const id=++sequence;timers.set(id,fn);return id;};c.clearTimeout=id=>timers.delete(id);stageSynthetic(c);const calls=[];c.fetch=async(url)=>{calls.push(url);return Response.json(url.endsWith('import-plan')?{jobs:[{jobId:'synthetic'}]}:{pending:true,done:0,total:1});};const pending=c.runPlanImport();await flushSynthetic();assert.equal(timers.size,1);c.closePlanImport();assert.equal(timers.size,0);c.PlanImport.state.busy=true;c.document.getElementById('plan-import-status').textContent='new owner status';await pending;assert.equal(calls.length,2);assert.equal(c.PlanImport.state.busy,true);assert.equal(c.document.getElementById('plan-import-status').textContent,'new owner status');
});
test('actual installer rollback restores DATA, history, raw review and detached reference together',async()=>{
 const r=syntheticPane(),c=r.ctx,body=stageSynthetic(c);c.SceneReviewFlow.restore({name:'anonymous.png',pages:['data:image/png;reference'],index:0});const before=c.EditorPane.captureInstallState(),reference=JSON.stringify(c.SceneReviewFlow.capture());r.fail('draw');await assert.rejects(c.EditorPane.install(panePlan('C'),{view:{view:'2d',twoD:{zoom:1,panX:0,panY:0}}}),/draw fault/);assert.equal(c.DATA,before.data);assert.deepEqual(c.HISTORY,before.history);assert.equal(c.PlanImport.state.result.extraction.rawResponse,body.extraction.rawResponse);assert.equal(JSON.stringify(c.SceneReviewFlow.capture()),reference);assert.equal(c.PlanImport.state.pages[0],'data:image/png;synthetic-A');assert.equal(c.PlanImport.currentReview(c.PlanImport.state.result),true);
});
test('transient memento contains only detached source data and recreates Image in current realm',async()=>{
 const {ctx:c}=syntheticPane();stageSynthetic(c);c.PlanImport.state.pages=null;c.PlanImport.state.image=new c.Image();c.PlanImport.state.image.src='data:image/png;anonymous-source';c.PlanImport.state.crop={x:1,y:2,w:30,h:40};c.SceneReviewFlow.restore({name:'reference',pages:['data:image/png;reference'],index:0});const oldImage=c.PlanImport.state.image,memento=c.PlanImport.capture();assert.equal(memento.state.image,undefined);assert.equal(memento.state.imageSource,oldImage.src);c.PlanImport.restore(memento);await flushSynthetic();assert.notEqual(c.PlanImport.state.image,oldImage);assert.ok(c.PlanImport.state.image instanceof c.Image);assert.equal(c.PlanImport.state.image.src,oldImage.src);assert.equal(c.SceneReviewFlow.capture().pages[0],'data:image/png;reference');memento.state.result.notes.push('outside mutation');assert.deepEqual(Array.from(c.PlanImport.state.result.notes),['A']);
});
async function syntheticHost(){
 const children=[],h=libraryContext({native:false,search:'?planLibrary=1',iframeFactory(){const r=syntheticPane(),ui=makePaneWindow().window,c=r.ctx;c.document.querySelector=ui.document.querySelector.bind(ui.document);c.document.querySelectorAll=ui.document.querySelectorAll.bind(ui.document);c.SHARED={saveBusy:false};c.COMPARISON_PREVIEW=false;c.EDITOR_PANE='pane-'+children.length;c.markDirty=()=>c.DIRTY=true;children.push(r);return c;}});await h.api.ready;
 for(const id of ['A','B','C'])await h.api.repo.save({planId:id,name:id,operationId:'synthetic-'+id,baseRevisionId:null,baseGeneration:0,payload:panePlan(id)});await h.api.openPlan('A');await h.api.openPlan('C');h.api.changed([...h.api.panes.values()][0].id,{cameraChanged:false});await h.api.layout(1);await h.api.openPlan('B');return {h,children,a:[...h.api.panes.values()][0],b:[...h.api.panes.values()][1]};
}
async function decision(h,pending,choice='discard'){let button;for(let i=0;i<200&&!button;i++){await flushSynthetic();button=h.document.querySelector('[data-library-decision="'+choice+'"]');}assert.ok(button);await button.onclick();return pending;}
test('actual host keeps plan-local raw evidence across A→C→A, collapse/remount and close/reopen',async()=>{
 const {h,a,b}=await syntheticHost(),ac=a.frame.contentWindow,bc=b.frame.contentWindow;stageSynthetic(ac,'A');stageSynthetic(bc,'B');ac.SceneReviewFlow.restore({name:'A reference',pages:['data:image/png;A-reference'],index:0});const head=await h.api.repo.read('A');await h.api.switchPlan(a.id,'C');assert.equal(ac.PlanImport.state.result,null);await h.api.switchPlan(a.id,'A');assert.equal(ac.PlanImport.state.result.notes[0],'A');assert.equal(ac.SceneReviewFlow.capture().name,'A reference');assert.equal(bc.PlanImport.state.result.notes[0],'B');assert.deepEqual(await h.api.repo.read('A'),head);
 h.api.changed(a.id,{cameraChanged:false});await decision(h,h.api.layout(1));await h.api.openPlan('B');let restored=[...h.api.panes.values()].find(p=>p.planId==='B');assert.equal(restored.frame.contentWindow.PlanImport.state.result.notes[0],'B');await decision(h,h.api.closePlan(restored.id));await h.api.openPlan('B');restored=[...h.api.panes.values()].find(p=>p.planId==='B');assert.equal(restored.frame.contentWindow.PlanImport.state.result.notes[0],'B');const draft=await h.api.repo.get('drafts',JSON.stringify([h.api.session,'B']));assert.doesNotMatch(JSON.stringify(draft),/data:image\/png;synthetic-B|rawResponse|imageSource/);
});
test('existing dirty-choice Cancel preserves review-only pane and unchanged persistent layout',async()=>{
 const {h,a}=await syntheticHost(),c=a.frame.contentWindow;stageSynthetic(c);const view=await h.api.repo.get('views',h.api.session),raw=c.PlanImport.state.result.extraction.rawResponse;assert.equal(await decision(h,h.api.closePlan(a.id),'cancel'),false);assert.equal(h.api.panes.has(a.id),true);assert.equal(c.PlanImport.state.result.extraction.rawResponse,raw);assert.deepEqual(await h.api.repo.get('views',h.api.session),view);
});
test('capacity failure and unsaved mapping input reject closure before destructive writes',async()=>{
 const {h,a}=await syntheticHost(),c=a.frame.contentWindow;stageSynthetic(c);const original=c.PlanImport.capture,view=await h.api.repo.get('views',h.api.session);c.PlanImport.state.mappingEditor={body:c.PlanImport.state.result,sourceId:'anonymous'};await assert.rejects(h.api.closePlan(a.id),/入力.*確定か取消/);assert.equal(h.api.panes.has(a.id),true);c.PlanImport.state.mappingEditor=null;c.PlanImport.capture=()=>({version:1,state:{pdfData:'x'.repeat(64*1024*1024)}});await assert.rejects(h.api.closePlan(a.id),/64MB/);assert.equal(h.api.panes.has(a.id),true);assert.deepEqual(await h.api.repo.get('views',h.api.session),view);c.PlanImport.capture=original;
});
test('in-place edit→draw→undo-draw advances independent ownership; new read synchronizes lazy edits',async()=>{
 const {ctx:c}=syntheticPane(),owner=c.PlanImport.captureContext(),name=c.DATA.rooms[0].n;c.DATA.rooms[0].n='temporary edit';c.draw2d();c.DATA.rooms[0].n=name;c.draw2d();assert.equal(owner.isCurrent(),false);
 stageSynthetic(c);c.DATA.rooms[0].n='edit after dirty checkpoint';let calls=0;c.fetch=async()=>{calls++;return Response.json(reading('fresh'));};await c.runPlanImport();assert.equal(calls,1);assert.equal(c.PlanImport.state.busy,false);assert.equal(c.PlanImport.state.result.notes[0],'fresh');
});
test('source-only PDF survives cancellation/reopen without an automatic locate or read',async()=>{
 const {ctx:c}=syntheticPane(),pending=later();c.FileReader=class{readAsDataURL(){this.onload({target:{result:'data:application/pdf;anonymous-original'}});}};c.PdfPages={renderPages:()=>pending.promise};let sends=0;c.fetch=()=>{sends++;throw Error('must remain local');};c.onPlanImportFile({files:[{name:'anonymous.pdf',type:'application/pdf'}]});assert.equal(c.PlanImport.state.pdfData,'data:application/pdf;anonymous-original');c.closePlanImport();c.openPlanImport();assert.equal(c.PlanImport.state.pdfData,'data:application/pdf;anonymous-original');assert.match(c.document.getElementById('plan-import-status').textContent,/保持.*選び直して/);pending.resolve(['late-page']);await flushSynthetic();assert.equal(c.PlanImport.state.pages,null);assert.equal(sends,0);
});
test('actual Apply rejects a target change inside confirmation before Undo or geometry mutation',()=>{
 const c=setup(),legacy=reading('apply');legacy.plan.rooms=[{id:'r',floor:1,x:0,y:0,w:1000,d:1000,n:'Anonymous'}];c.DATA.rooms=[{id:'existing',floor:1,x:5000,y:0,w:1000,d:1000}];c.PlanImport.state.result=legacy;c.PlanImport.renderPlanImportResult(legacy);const history=c.HISTORY.length;c.confirm=()=>{c.DATA.rooms[0].n='edit inside confirm';return true;};c.applyPlanImport();assert.equal(c.HISTORY.length,history);assert.equal(c.DATA.rooms.length,1);assert.equal(c.DATA.rooms[0].n,'edit inside confirm');assert.equal(legacy.importApplied,undefined);
});
test('consumed legacy Apply retains raw evidence and cannot repeat after close/reopen',()=>{
 const c=setup(),body=reading('consumed');body.plan.rooms=[{id:'r',floor:1,x:0,y:0,w:1000,d:1000,n:'Anonymous'}];c.PlanImport.state.result=body;c.PlanImport.renderPlanImportResult(body);c.applyPlanImport();assert.equal(body.importApplied,true);const data=JSON.stringify(c.DATA),history=c.HISTORY.length;c.openPlanImport();c.applyPlanImport();assert.equal(JSON.stringify(c.DATA),data);assert.equal(c.HISTORY.length,history);assert.equal(c.PlanImport.state.result.extraction.rawResponse,body.extraction.rawResponse);
});
test('host view commit failure rolls back exact DATA and the original plan raw review',async()=>{
 const {h,a}=await syntheticHost(),c=a.frame.contentWindow;stageSynthetic(c,'A');const before=JSON.stringify(c.DATA),setView=h.api.repo.setView;let once=true;h.api.repo.setView=async function(...args){if(once){once=false;throw Error('synthetic view fault');}return setView.apply(this,args);};await assert.rejects(h.api.switchPlan(a.id,'C'),/view fault/);assert.equal(a.planId,'A');assert.equal(JSON.stringify(c.DATA),before);assert.equal(c.PlanImport.state.result.notes[0],'A');assert.equal(c.PlanImport.currentReview(c.PlanImport.state.result),true);
});
test('pending raw reply during close-choice cannot replace the frozen retained evidence',async()=>{
 const {h,a}=await syntheticHost(),c=a.frame.contentWindow,pending=later();stageSynthetic(c,'original');c.fetch=()=>pending.promise;const running=c.runPlanImport(),closing=h.api.closePlan(a.id);let cancel;for(let i=0;i<200&&!cancel;i++){await flushSynthetic();cancel=h.document.querySelector('[data-library-decision="cancel"]');}assert.ok(cancel);pending.resolve(Response.json(reading('late')));await running;await cancel.onclick();assert.equal(await closing,false);assert.equal(h.api.panes.has(a.id),true);assert.equal(c.PlanImport.state.result,null);assert.equal(c.PlanImport.state.pdfData,'data:application/pdf;synthetic-original');assert.equal(c.PlanImport.state.busy,false);
});
test('source-free pane closures do not consume transient-review count budget',async()=>{
 const h=libraryContext({native:false,search:'?planLibrary=1',iframeFactory(){const c=syntheticPane().ctx,ui=makePaneWindow().window;c.document.querySelector=ui.document.querySelector.bind(ui.document);c.SHARED={saveBusy:false};return c;}});await h.api.ready;for(let i=0;i<18;i++){const id='empty-'+i;await h.api.repo.save({planId:id,name:id,operationId:'empty-seed-'+i,baseRevisionId:null,baseGeneration:0,payload:panePlan(id)});await h.api.openPlan(id);await h.api.closePlan([...h.api.panes.keys()][0]);}assert.equal(h.api.panes.size,0);
});
test('multi-floor close/reopen keeps exact source/proposals and permits fresh registration only',async()=>{
 const c=setup(),{source,proposals}=require('./fixtures/registration/three-floor-setback.cjs').fixture();c.PlanRegistration=require('../../assets/js/plan-registration.js');c.PlanStructure=require('../../assets/js/plan-structure.js');c.PlanImport.state.pages=['anonymous-floor-1','anonymous-floor-2','anonymous-floor-3'];const body={sourceLocal:source,buildingRegistration:proposals,plan:{walls:[],rooms:[],items:[]},summary:{floors:[1,2,3]}};c.PlanImport.stageBuildingReview(body);const original=JSON.stringify(source),proposal=JSON.stringify(proposals);c.closePlanImport();c.openPlanImport();assert.equal(JSON.stringify(c.PlanImport.state.result.sourceLocal),original);assert.equal(JSON.stringify(c.PlanImport.state.result.buildingRegistration),proposal);assert.equal(c.PlanImport.currentReview(c.PlanImport.state.result),true);assert.equal(c.PlanImport.state.result.buildingDecisions.floors.length,0);let calls=0;c.fetch=async(url,opts)=>{calls++;assert.equal(url,'/api/ai/register-plan');const request=JSON.parse(opts.body);return Response.json({sourceSnapshot:request.sourceSnapshot,buildingRegistration:proposals,rawResponse:'anonymous joint result'});};await c.PlanImport.requestBuildingRegistration(c.PlanImport.state.result);assert.equal(calls,1);assert.equal(c.PlanImport.state.result.registrationExtraction.rawResponse,'anonymous joint result');assert.equal(c.PlanImport.state.result.buildingCompilation.canApply,false);
});
test('old quota response/catch cannot replace newer quota or extraction capability',async()=>{
 const {ctx:c}=syntheticPane(),box=c.document.createElement('div');box.id='plan-import-quota';c.document.body.appendChild(box);const first=later(),second=later();let calls=0;c.fetch=()=>++calls===1?first.promise:second.promise;c.PlanImport.showQuota();c.PlanImport.showQuota();second.resolve(Response.json({counted:true,left:5,perUser:5,total:10,sceneIRV3:{enabled:true}}));await flushSynthetic();const text=box.textContent;first.resolve(Response.json({counted:true,left:0,perUser:5,total:10,sceneIRV3:{enabled:false}}));await flushSynthetic();assert.equal(c.PlanImport.state.quotaBlocked,false);assert.equal(c.PlanImport.state.sceneIRV3Available,true);assert.equal(box.textContent,text);
});
test('original image reference survives pending decode cancellation and restores with full crop',async()=>{
 const {ctx:c}=syntheticPane(),images=[];c.FileReader=class{readAsDataURL(){this.onload({target:{result:'data:image/png;anonymous-original'}});}};c.Image=class{naturalWidth=90;naturalHeight=80;set src(v){this._src=v;images.push(this);}get src(){return this._src;}};c.onPlanImportFile({files:[{name:'anonymous.png',type:'image/png'}]});c.closePlanImport();const saved=c.PlanImport.capture();assert.equal(saved.state.imageSource,'data:image/png;anonymous-original');images[0].onload();assert.equal(c.PlanImport.state.image,null);c.PlanImport.restore(saved);images[1].onload();assert.equal(c.PlanImport.state.image.src,'data:image/png;anonymous-original');assert.deepEqual(copy(c.PlanImport.state.crop),{x:0,y:0,w:90,h:80});
});
test('shared identity success archives ordinary source locally and restores no foreign review',async()=>{
 const h=libraryContext({beforeLibrary(c,sandbox){vm.runInContext(importSource,sandbox);}});await h.api.ready;const c=h.context,previous=[...h.api.panes.values()][0].planId;c.PlanImport.state.pages=['data:image/png;anonymous-native'];c.PlanImport.state.result=reading('ordinary source');c.PlanImport.renderPlanImportResult(c.PlanImport.state.result);await h.api.withSharedIdentity('anonymous-room',()=>{c.DATA=panePlan('shared anonymous');c.SHARED.roomId='anonymous-room';});assert.equal(c.PlanImport.state.result,null);assert.equal(c.PlanImport.state.pages,null);c.clearDirty();c.SHARED.roomId=null;await h.api.switchPlan('native-editor',previous);assert.equal(c.PlanImport.state.result.notes[0],'ordinary source');assert.equal(c.PlanImport.state.pages[0],'data:image/png;anonymous-native');
});
test('explicit Reset removes only this plan retained source; peer and saved plan remain intact',async()=>{
 const {h,a,b}=await syntheticHost(),c=a.frame.contentWindow,peer=b.frame.contentWindow;stageSynthetic(c,'A');stageSynthetic(peer,'B');await h.api.switchPlan(a.id,'C');await h.api.switchPlan(a.id,'A');c.EDITOR_PANE=a.id;c.parent.PlanLibrary=h.api;const saved=await h.api.repo.read('A');c.resetPlanImport();assert.equal(c.PlanImport.state.failedSceneResponse,null);await h.api.switchPlan(a.id,'C');await h.api.switchPlan(a.id,'A');assert.equal(c.PlanImport.state.result,null);assert.equal(c.PlanImport.state.pdfData,null);assert.equal(peer.PlanImport.state.result.notes[0],'B');assert.deepEqual(await h.api.repo.read('A'),saved);
});
test('failed shared join restores ordinary DATA, raw source and reference together',async()=>{
 const h=libraryContext({beforeLibrary(c,sandbox){vm.runInContext(importSource,sandbox);vm.runInContext(fs.readFileSync('assets/js/scene-review-flow.js','utf8'),sandbox);}});await h.api.ready;const c=h.context,id=[...h.api.panes.values()][0].planId,before=JSON.stringify(c.DATA);c.PlanImport.state.pages=['data:image/png;anonymous-native'];c.PlanImport.state.result=reading('ordinary source');c.PlanImport.renderPlanImportResult(c.PlanImport.state.result);c.SceneReviewFlow.restore({name:'anonymous-reference',pages:['data:image/png;anonymous-reference'],index:0});const ref=JSON.stringify(c.SceneReviewFlow.capture());await assert.rejects(h.api.withSharedIdentity('anonymous-room',()=>{c.DATA=panePlan('failed-room');c.SHARED.roomId='anonymous-room';throw Error('anonymous failed join');}),/failed join/);assert.equal(JSON.stringify(c.DATA),before);assert.equal(c.__editorPlanId,id);assert.equal(c.PlanImport.state.result.notes[0],'ordinary source');assert.equal(JSON.stringify(c.SceneReviewFlow.capture()),ref);assert.equal(c.PlanImport.currentReview(c.PlanImport.state.result),true);
});
test('legacy crop change stays read-only through Close/reopen and memento restore until a new explicit read',async()=>{
 const c=setup(),s=c.PlanImport.state,body=reading('old crop');s.image={src:'data:image/png;anonymous-original',naturalWidth:1000,naturalHeight:800};s.crop={x:0,y:0,w:1000,h:800};s.fileName='anonymous.png';body.plan.rooms=[{id:'old-room',floor:1,x:0,y:0,w:1000,d:1000,n:'Anonymous old crop'}];s.result=body;c.PlanImport.renderPlanImportResult(body);const before=JSON.stringify(c.DATA),history=c.HISTORY.length,raw=body.extraction.rawResponse;
 s.drag={x:10,y:20,w:100,h:200};c.planImportUp();assert.equal(body.sourceInvalidated,true);c.closePlanImport();c.openPlanImport();assert.equal(c.PlanImport.currentReview(body),false);c.applyPlanImport();assert.equal(JSON.stringify(c.DATA),before);assert.equal(c.HISTORY.length,history);assert.equal(body.importApplied,undefined);assert.equal(body.extraction.rawResponse,raw);
 const saved=c.PlanImport.capture();c.PlanImport.restore(saved);c.applyPlanImport();assert.equal(JSON.stringify(c.DATA),before);assert.equal(c.HISTORY.length,history);assert.equal(c.PlanImport.state.result.sourceInvalidated,true);
 s.pages=['data:image/png;anonymous-new'];c.fetch=async()=>Response.json(reading('fresh explicit read'));await c.runPlanImport();assert.equal(c.PlanImport.state.result.notes[0],'fresh explicit read');assert.equal(c.PlanImport.state.result.sourceInvalidated,undefined);assert.equal(c.PlanImport.currentReview(c.PlanImport.state.result),true);
});
test('ordinary Close/reopen shows cancellation and accepted-work caution rather than stale loading',async()=>{
 const {ctx:c}=syntheticPane(),reply=later();stageSynthetic(c);c.fetch=()=>reply.promise;const pending=c.runPlanImport();c.closePlanImport();c.openPlanImport();const status=c.document.getElementById('plan-import-status').textContent;assert.match(status,/取消.*受付済み/);assert.doesNotMatch(status,/読み取っています/);reply.resolve(Response.json(reading('stale')));await pending;assert.equal(c.PlanImport.state.result,null);assert.equal(c.document.getElementById('plan-import-status').textContent,status);
});
