/* Synthetic structural/window validation, independent of the frozen Astra 2/2. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/tmp/webcad-browser-check/node_modules/playwright'),fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),crypto=require('crypto');
const origin=process.env.APP_URL||'http://127.0.0.1:65350',out=process.env.OUTPUT_DIR||require('node:path').join(require('node:os').tmpdir(), 'webcad-structure-window-evidence');
assert.ok(/^http:\/\/127\.0\.0\.1:\d+$/.test(origin)&&!/:63239$|:65236$|:65348$|:65349$/.test(origin));fs.mkdirSync(out,{recursive:true});
const safe=['wall-west','wall-storage-east','wall-stair-north','wall-kitchen-screen','wall-kitchen-west-return'],ledger=(()=>{const p=process.env.FROZEN_LEDGER_PATH;if(!p)throw Error('FROZEN_LEDGER_PATH must name a locally materialized frozen Astra ledger');return p;})(),ledgerBefore=fs.readFileSync(ledger);
(async()=>{const profile=fs.mkdtempSync(path.join(os.tmpdir(),'webcad-structure-window-')),context=await chromium.launchPersistentContext(profile,{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal'],viewport:{width:1600,height:1000}}),page=await context.newPage(),errors=[],blocked=[];try{
 await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===origin&&!u.pathname.startsWith('/api/'))return r.continue();blocked.push(u.origin+u.pathname);return r.abort();});page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/?internalAPI=1');await page.waitForSelector('#app-loading',{state:'hidden',timeout:60000});await page.waitForFunction(()=>window.WebCADInternalAPI&&window.threeModulesReady);
 const raw=fs.readFileSync('local-preview/frozen-page-2.json','utf8');assert.equal(crypto.createHash('sha256').update(raw).digest('hex'),'c98e9213665b0527fae907a19d145d8a038db8f82bd049c57b74607add05485c');await page.evaluate(raw=>{closePresetChoice();DATA={walls:[],rooms:[],items:[],heightDefaults:{modelVersion:2,floorThickness:180,wallHeight:2400,floorRaise:0,floorRaiseSet:true,perFloor:false},floors:{}};HISTORY.length=0;REDO_HISTORY.length=0;DIRTY=false;document.getElementById('floor-sel').value='2';onFloorChange(2);setView('3d-ext');PlanImport.stageSceneIR(JSON.parse(raw),{materialization:'bounded-v3',pageScope:['frozen-page-2'],extraction:{rawResponse:raw,rawSha256:'c98e9213665b0527fae907a19d145d8a038db8f82bd049c57b74607add05485c',kind:'independent-structure-window-fixture',paidCalls:0}});},raw);await page.waitForFunction(()=>ren&&!hasPendingGltfModels()&&!_gltfRebuildTimer,null,{timeout:60000});await page.evaluate(()=>{camExt.position.set(12,13,14);orbit.target.set(3.5,2.8,2);orbit.update();invalidate3D();});
 async function integrity(){return page.evaluate(async()=>{const stores={};for(const info of await indexedDB.databases()){const db=await new Promise((res,rej)=>{const r=indexedDB.open(info.name);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});for(const name of db.objectStoreNames)stores[info.name+':'+name]=await new Promise((res,rej)=>{const tx=db.transaction(name,'readonly'),st=tx.objectStore(name),k=st.getAllKeys(),v=st.getAll();tx.oncomplete=()=>res({keys:k.result,values:v.result});tx.onerror=()=>rej(tx.error);});db.close();}return {data:serializeDataSnapshot(),history:HISTORY.slice(),redo:REDO_HISTORY.slice(),dirty:DIRTY,source:JSON.stringify(PlanImport.state.result.sceneIR),options:JSON.stringify(PlanImport.state.result.sceneOptions),camera:WebCADInternalAPI.get_scene({planId:'host-draft'}).camera,local:Object.fromEntries(Object.entries(localStorage)),session:Object.fromEntries(Object.entries(sessionStorage)),indexedDB:stores};});}
 const before=await integrity(),responses=[];
 for(const structure of [[...safe,'room-ldk','room-storage'],[...safe,'wall-north','wall-east','room-storage']]){
  const request=await page.evaluate(structure=>({planId:'host-draft',baseRevision:WebCADInternalAPI.get_scene({planId:'host-draft'}).revision,selectedObjectIds:[],selectedEntityIds:structure,incompleteConfirmed:true,displayBindings:['room-ldk','room-storage'].map(sourceEntityId=>({sourceEntityId,catalogId:null,sizingPolicy:'native',appearanceMode:'match-diagram-appearance'}))}),structure);
  const response=await page.evaluate(request=>WebCADInternalAPI.preview_patch(request),request);assert.equal(response.rendered,true,JSON.stringify(response.diagnostics));assert.equal(response.applyAvailable,false);assert.equal(response.fullReconstructionReady,false);assert.equal(response.previewPlan.walls.length,responses.length?7:5);assert.equal(response.previewPlan.items.length,responses.length?3:0);assert.equal(response.previewPlan.rooms.some(r=>r.id==='room-stair-space'),false);
  const frame=page.frames().find(f=>new URL(f.url()).searchParams.get('editorPane')===response.preview.paneId);
  await frame.waitForTimeout(250); // Exceeds the existing floor/view auto-fit timers; camera must stay aligned.
  const native=await frame.evaluate(()=>({walls:DATA.walls.map(w=>({id:w.id,wallHeight:wallHeightMm(w),source:JSON.parse(JSON.stringify(w)),roots:getSelectableRoots3D(w).length})),rooms:DATA.rooms.map(r=>({id:r.id,floorColor:r.floorColor,roots:getSelectableRoots3D(r).length})),windows:DATA.items.filter(i=>i.type==='window').map(it=>{const info=getOpeningWallInfo(it),group=getSelectableRoots3D(info.wall)[0],raw=JSON.parse(JSON.stringify(it)),copy=JSON.parse(JSON.stringify(it));normalizeWindowVerticalProps(copy);const cx=(it.x+it.w/2)*U,cz=(it.y+it.d/2)*U,len=Math.hypot(info.wall.x2-info.wall.x1,info.wall.y2-info.wall.y1),dx=(info.wall.x2-info.wall.x1)/len,dz=(info.wall.y2-info.wall.y1)/len,n=new THREE.Vector3(-dz,0,dx),base=item3DBaseY(it),samples=[];group.updateMatrixWorld(true);for(const q of [.25,.5,.75]){const along=(q-.5)*it.w*U,p=new THREE.Vector3(cx+dx*along,base+(windowSillMm(it)+windowHeightMm(it)/2)*U,cz+dz*along),ray=new THREE.Raycaster(p.clone().addScaledVector(n,.5),n.clone().negate(),0,1),hits=ray.intersectObject(group,true);samples.push({q,wallHits:hits.map(hit=>{const m=Array.isArray(hit.object.material)?hit.object.material[hit.face.materialIndex]:hit.object.material;return {glass:!!hit.object.userData.windowWallGlass,opacity:m.opacity,transparent:m.transparent};})});}return {raw,normalized:copy,maxTop:windowMaxTopMm(it),baseY:base,hostId:info.wall.id,roots:getSelectableRoots3D(it).length,gapSamples:samples};}),camera:EditorPane.view(),nativeEditor:true}));
  for(const w of native.walls){assert.equal(w.wallHeight,2400);assert.ok(w.roots>0);const original=JSON.parse(raw).walls.find(e=>e.id===w.id);assert.deepEqual([w.source.floor,w.source.x1,w.source.y1,w.source.x2,w.source.y2,w.source.thick],[original.floor.value,original.start.value.x,original.start.value.y,original.end.value.x,original.end.value.y,original.thicknessMm.value]);}
  assert.ok(native.rooms.some(r=>r.id==='room-storage'&&r.floorColor==='#F1F0E8'));for(const w of native.windows){assert.deepEqual(w.raw,w.normalized);assert.deepEqual([w.raw.windowHeight,w.raw.windowSill,w.raw.windowKind],[1200,900,'fix']);assert.equal(w.maxTop,2350);assert.ok(w.roots>0);for(const s of w.gapSamples){assert.ok(s.wallHits.length>0,'existing wall glass present');assert.ok(s.wallHits.every(h=>h.glass),'no opaque wall fills the aperture');}}
  assert.deepEqual(native.camera,before.camera);await frame.locator('#c3d-wrap').screenshot({path:path.join(out,responses.length?'02-seven-walls-three-windows.png':'01-five-walls-storage.png')});responses.push({request,response,native});assert.deepEqual(await integrity(),before);
 }
 const rejected=await page.evaluate(async()=>{const scene=WebCADInternalAPI.get_scene({planId:'host-draft'});return WebCADInternalAPI.preview_patch({planId:scene.planId,baseRevision:scene.revision,selectedObjectIds:[],selectedEntityIds:['wall-south'],displayBindings:[{sourceEntityId:'room-ldk',catalogId:null,sizingPolicy:'native',appearanceMode:'match-diagram-appearance'}],incompleteConfirmed:true});});assert.equal(rejected.rendered,false);assert.ok(rejected.selectionScope.entityIds.includes('window-south-stair'));assert.ok(rejected.diagnostics.some(d=>d.code==='unsupported_stair_room_floor'));assert.equal(rejected.previewPlan.rooms.some(r=>r.id==='room-stair-space'),false);assert.deepEqual(await integrity(),before);
 const full=responses[1].response.fullDiagnostics;for(const code of ['wrong_adjacent_room','unsupported_opening_mechanism','unknown_required_geometry','unsupported_stair_reconstruction','unsupported_stair_room_floor'])assert.ok(full.some(d=>d.code===code));assert.equal(full.some(d=>d.code==='missing_window_runtime'),false);assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);assert.deepEqual(fs.readFileSync(ledger),ledgerBefore);
 fs.writeFileSync(path.join(out,'api-responses-and-native-geometry.json'),JSON.stringify(responses,null,2));fs.writeFileSync(path.join(out,'rejected-south-wall.json'),JSON.stringify(rejected,null,2));fs.writeFileSync(path.join(out,'integrity-before.json'),JSON.stringify(before,null,2));fs.writeFileSync(path.join(out,'integrity-after.json'),JSON.stringify(await integrity(),null,2));const report={fixtureKind:'independent-structure-window-fixture',origin,profile,successfulPreviews:2,rejectedSouthWall:true,wallCounts:[5,7],windowCount:3,actualAperturesWithoutOpaqueWall:true,unknownSourceUnchanged:true,assumptions:{wallHeight:2400,windowHeight:1200,windowSill:900,windowKind:'fix'},stairFloorNotCreated:true,legitimateFullUnresolvedRetained:true,fullReadiness:false,applyAvailable:false,sourceAndStorageUnchanged:true,frozenAstraAttempts:JSON.parse(ledgerBefore).attempts,frozenLedgerUnchanged:true,paidCalls:0,errors,blocked};fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }finally{await context.close();}})().catch(e=>{console.error(e);process.exitCode=1});
