/* New synthetic fixture validation, separate from frozen fresh-Astra 2/2. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/tmp/webcad-browser-check/node_modules/playwright'),fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),crypto=require('crypto');
const origin=process.env.APP_URL||'http://127.0.0.1:65349',out=process.env.OUTPUT_DIR||require('node:path').join(require('node:os').tmpdir(), 'webcad-material-diff-evidence');
assert.ok(/^http:\/\/127\.0\.0\.1:\d+$/.test(origin)&&!/:63239$|:65236$|:65348$/.test(origin));fs.mkdirSync(out,{recursive:true});
const TV='im0261-Cabinet-MEGA_PACK_CABINET-cabinet-354290_frame_walnut_brown',SOFA='im0261-Sofa-MEGA_PACK_Sofa-BOLIA_sofa_Ivory',ids=[TV,'original-sideboard','fmp-Sofa01',SOFA],frozenLedger=(()=>{const p=process.env.FROZEN_LEDGER_PATH;if(!p)throw Error('FROZEN_LEDGER_PATH must name a locally materialized frozen Astra ledger');return p;})(),ledgerBefore=fs.readFileSync(frozenLedger);
(async()=>{const profile=fs.mkdtempSync(path.join(os.tmpdir(),'webcad-material-diff-fixture-')),context=await chromium.launchPersistentContext(profile,{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal'],viewport:{width:1600,height:1000}}),page=await context.newPage(),errors=[],blocked=[];try{
 await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===origin&&!u.pathname.startsWith('/api/'))return r.continue();blocked.push(u.origin+u.pathname);return r.abort();});page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/?internalAPI=1');await page.waitForSelector('#app-loading',{state:'hidden',timeout:60000});await page.waitForFunction(()=>window.WebCADInternalAPI&&window.threeModulesReady);
 const raw=fs.readFileSync('local-preview/frozen-page-2.json','utf8');assert.equal(crypto.createHash('sha256').update(raw).digest('hex'),'c98e9213665b0527fae907a19d145d8a038db8f82bd049c57b74607add05485c');await page.evaluate(raw=>{closePresetChoice();DATA={walls:[],rooms:[],items:[],heightDefaults:{modelVersion:2,floorThickness:180,wallHeight:2400,floorRaise:0,floorRaiseSet:true,perFloor:false},floors:{}};HISTORY.length=0;REDO_HISTORY.length=0;DIRTY=false;document.getElementById('floor-sel').value='2';onFloorChange(2);setView('3d-ext');PlanImport.stageSceneIR(JSON.parse(raw),{materialization:'bounded-v3',pageScope:['frozen-page-2'],extraction:{rawResponse:raw,rawSha256:'c98e9213665b0527fae907a19d145d8a038db8f82bd049c57b74607add05485c',kind:'new-material-api-fixture',paidCalls:0}});},raw);await page.waitForFunction(()=>ren&&!hasPendingGltfModels()&&!_gltfRebuildTimer,null,{timeout:60000});await page.evaluate(()=>{camExt.position.set(12,10,12);orbit.target.set(0,0,0);orbit.update();invalidate3D();});
 async function integrity(){return page.evaluate(async()=>{const stores={};for(const info of await indexedDB.databases()){const db=await new Promise((res,rej)=>{const r=indexedDB.open(info.name);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});for(const name of db.objectStoreNames)stores[info.name+':'+name]=await new Promise((res,rej)=>{const tx=db.transaction(name,'readonly'),st=tx.objectStore(name),k=st.getAllKeys(),v=st.getAll();tx.oncomplete=()=>res({keys:k.result,values:v.result});tx.onerror=()=>rej(tx.error);});db.close();}return {data:serializeDataSnapshot(),history:HISTORY.slice(),redo:REDO_HISTORY.slice(),dirty:DIRTY,source:JSON.stringify(PlanImport.state.result.sceneIR),options:JSON.stringify(PlanImport.state.result.sceneOptions),camera:WebCADInternalAPI.get_scene({planId:'host-draft'}).camera,local:Object.fromEntries(Object.entries(localStorage)),session:Object.fromEntries(Object.entries(sessionStorage)),indexedDB:stores};});}
 const before=await integrity(),catalogue=await page.evaluate(ids=>WebCADInternalAPI.read_catalog({ids}),ids);assert.equal(catalogue.entries.filter(e=>e.materialCapability.status==='asset-and-code-audited').length,4);fs.writeFileSync(path.join(out,'read-catalogue-audit.json'),JSON.stringify(catalogue,null,2));
 const responses=[];let frame;
 for(const id of [TV,'original-sideboard']){const response=await page.evaluate(async id=>{const scene=WebCADInternalAPI.get_scene({planId:'host-draft'});return WebCADInternalAPI.preview_patch({planId:scene.planId,baseRevision:scene.revision,selectedObjectIds:['obj-tv-console'],incompleteConfirmed:true,displayBindings:[{sourceEntityId:'room-ldk',catalogId:null,sizingPolicy:'native',appearanceMode:'match-diagram-appearance'},{sourceEntityId:'obj-tv-console',catalogId:id,sizingPolicy:'fit-source',appearanceMode:'match-diagram-appearance'}]});},id);assert.equal(response.rendered,true);frame=page.frames().find(f=>new URL(f.url()).searchParams.get('editorPane')===response.preview.paneId);const actual=await frame.evaluate(()=>{const it=DATA.items.find(i=>i.id==='obj-tv-console'),group=getSelectableRoots3D(it)[0],size=group&&new THREE.Box3().setFromObject(group).getSize(new THREE.Vector3());return {heightMm:getItemHeightValue(it),bboxHeightMm:size&&size.y*1000,camera:EditorPane.view(),item:JSON.parse(JSON.stringify(it))};});assert.equal(actual.heightMm,id===TV?600:760);assert.ok(Math.abs(actual.bboxHeightMm-actual.heightMm)<1);assert.equal(JSON.parse(before.source).objects.find(o=>o.id===itId()).heightMm.status,'unknown');function itId(){return 'obj-tv-console';}await frame.locator('#c3d-wrap').screenshot({path:path.join(out,responses.length?'02-sideboard-760.png':'01-tv-console-600.png')});responses.push({response,actual});assert.deepEqual(await integrity(),before);}
 const diff=responses[1].response.diff.find(d=>d.sourceEntityId==='obj-tv-console').display;assert.equal(diff.heightDeltaMm,160);assert.equal(diff.geometryIdentityChanged,true);assert.equal(diff.after.sourceHeight.status,'unknown');assert.equal(diff.after.effectiveHeight.sourceMeasured,false);assert.deepEqual(responses[0].actual.camera,responses[1].actual.camera);fs.writeFileSync(path.join(out,'api-responses-and-native-heights.json'),JSON.stringify(responses,null,2));
 // Existing material renderer test only: directly install a separate synthetic
 // four-model plan into the same memory-only pane. This is not an AI candidate.
 const materialPlan={walls:[],rooms:[],items:catalogue.entries.map((m,i)=>({id:'audit-'+i,type:m.id,floor:2,x:(i%2)*4000,y:Math.floor(i/2)*3500,w:m.w,d:m.d,rot:0,elev:0,finishColors:Object.fromEntries(m.materialCapability.verifiedChannels.map(c=>[c.key,c.key==='wood'?'#aabbcc':c.key==='fabric'?'#5588aa':c.key==='accent'?'#aa7755':'#ccaa66']))})),heightDefaults:{modelVersion:2,floorThickness:180,wallHeight:2400,floorRaise:0,floorRaiseSet:true,perFloor:false},floors:{}};
 await frame.evaluate(async({plan,view})=>{await EditorPane.install(plan,{history:[],redo:[],dirty:false,view});}, {plan:materialPlan,view:{...before.camera,camera:{...before.camera.camera,pos:[10,10,12],target:[3,0,3]}}});await frame.waitForFunction(()=>ren&&!hasPendingGltfModels()&&!_gltfRebuildTimer,null,{timeout:60000});await frame.evaluate(()=>{camExt.position.set(10,10,12);orbit.target.set(3,0,3);orbit.update();invalidate3D();});await frame.waitForTimeout(200);
 const materials=await frame.evaluate(()=>DATA.items.map(it=>{const group=getSelectableRoots3D(it)[0],values=[];group.traverse(o=>{if(o.isMesh)for(const m of [].concat(o.material))values.push({name:m.name,channel:m.userData.finishChannel||null,hex:m.color&&m.color.getHexString(),map:!!m.map,neutralize:!!m.userData.neutralizeFinish,reference:m.userData.finishReference||null,lockColor:!!m.userData.lockColor});});const native={};_modelCache[getFmpItem(it.type).model].traverse(o=>{if(o.isMesh)for(const m of [].concat(o.material))if(m.userData.lockColor&&!m.userData.finishChannel)native[m.name]=m.color.getHexString();});return {id:it.type,heightMm:getItemHeightValue(it),specified:it.finishColors,materials:values,fixedNativeColors:native};}));
 for(const m of materials){for(const v of m.materials)if(v.channel&&m.specified[v.channel])assert.equal(v.hex,m.specified[v.channel].slice(1));else if(v.lockColor&&!v.channel)assert.equal(v.hex,m.fixedNativeColors[v.name]);}
 const sideboard=materials.find(m=>m.id==='original-sideboard');assert.equal(sideboard.heightMm,760);assert.ok(sideboard.materials.some(m=>m.lockColor&&!m.channel));assert.equal(materials.find(m=>m.id==='fmp-Sofa01').materials.filter(m=>m.channel==='body').length,1);await frame.locator('#c3d-wrap').screenshot({path:path.join(out,'03-existing-material-channels.png')});fs.writeFileSync(path.join(out,'native-material-properties.json'),JSON.stringify(materials,null,2));
 const after=await integrity();assert.deepEqual(after,before);assert.deepEqual(fs.readFileSync(frozenLedger),ledgerBefore);assert.equal(JSON.parse(ledgerBefore).attempts,2);assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);const report={fixtureKind:'post-baseline-material-diff-validation',origin,profile,newFixturePreviewCalls:2,frozenAstraLedgerUntouched:true,frozenAstraAttempts:2,originalUnchanged:true,storageUnchanged:true,rawUnknownHeightPreserved:true,nativeHeightAndBBoxVerified:[600,760],heightDiffDetected:160,geometrySubstitutionDetected:true,sameCamera:true,auditedExactIds:ids,regionalSofaLimit:'fmp-Sofa01 has one material body channel; body/seat cannot independently map to it',newChannelPatchCapability:false,imageQualityJudgmentPerformed:false,paidCalls:0,applyCalls:0,errors,blocked};fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(report,null,2));fs.writeFileSync(path.join(out,'integrity-before.json'),JSON.stringify(before,null,2));fs.writeFileSync(path.join(out,'integrity-after.json'),JSON.stringify(after,null,2));console.log(JSON.stringify(report));
 }finally{await context.close();}})().catch(e=>{console.error(e);process.exitCode=1});
