'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const Scene=require('../../assets/js/scene-ir-v3.js'),Openings=require('../../assets/js/scene-opening-geometry.js'),RoomGeometry=require('../../assets/js/room-geometry.js');
const {runtime}=require('./scene-fixtures.cjs'),{topLevelFunction}=require('./height-runtime.cjs');
const f=value=>({value,status:'observed',source:'anonymous synthetic independent survey; not a source-plan measurement'}),u=()=>({value:null,status:'unknown'}),clone=v=>JSON.parse(JSON.stringify(v));
const base={materialization:'bounded-v3',registry:{get:()=>null},targetPlan:{heightDefaults:{modelVersion:2,floorThickness:180}},defaultFloorOffset:()=>0};
const codes=r=>r.diagnostics.map(d=>d.code);
function fixture(face=-1,travel=1){
 const room=(id,y)=>({id,floor:f(1),shape:f({kind:'rectUnion',rectangles:[{x:0,y,w:4000,d:2000}]}),boundaryBasis:f('wall-centerline')});
 return {sceneVersion:3,units:'mm',coordinateSystem:'x-east-y-south-clockwise',annotations:[],walls:[{id:'host',floor:f(1),start:f({x:0,y:0}),end:f({x:4000,y:0}),thicknessMm:f(120)}],rooms:[room('north',-2000),room('south',0)],
 openings:[{id:'slide',floor:f(1),hostWallId:f('host'),adjacentRoomIds:f(['north','south']),start:f({x:1610,y:0}),end:f({x:2390,y:0}),mechanism:f('slide'),leafRelation:f('single'),heightMm:f(2100),leaves:[{id:'leaf',mechanism:f('slide'),leafWidthMm:f(840),thicknessMm:f(36),closedCenter:f({x:2000,y:face*86}),openCenter:f({x:2000+travel*810,y:face*86}),travelDirection:f({x:travel,y:0}),travelDistanceMm:f(810),openState:f('closed')}]}],objects:[],siteRegions:[],buildingFootprints:[],bindings:[],connections:[]};
}
function accepted(scene,options=base){const r=Scene.compile(scene,options);return {...options,acceptedReviewGroups:(r.reviewGroups||[]).map(g=>g.id),reviewedEntities:Object.fromEntries((r.reviewGroups||[]).map(g=>[g.entityId,g.reviewKey]))};}
function reviewed(scene,options=base){return Scene.compile(scene,accepted(scene,options));}
function walls(scene){return scene.walls.map(w=>({id:w.id,floor:w.floor.value,x1:w.start.value.x,y1:w.start.value.y,x2:w.end.value.x,y2:w.end.value.y,thick:w.thicknessMm.value}));}
function spec(scene){const e=scene.openings[0],l=e.leaves[0],a=e.start.value,b=e.end.value;return {id:e.id,floor:e.floor.value,hostWallId:e.hostWallId.value,kind:'door-slide-s',sourceExactGap:true,center:{x:(a.x+b.x)/2,y:(a.y+b.y)/2},widthMm:Math.hypot(b.x-a.x,b.y-a.y),travelDirection:l.travelDirection.value,doorOpenState:l.openState.value,sourceLeaf:{mechanism:'slide',leafWidthMm:l.leafWidthMm.value,thicknessMm:l.thicknessMm.value,closedCenter:l.closedCenter.value,travelDistanceMm:l.travelDistanceMm.value,...(l.openCenter&&l.openCenter.value?{openCenter:l.openCenter.value}:{})}};}
function direct(scene,all=[]){return Openings.compileOpening(spec(scene),walls(scene),all);}
function samePoints(actual,expected,tolerance=1e-6){assert.equal(actual.length,expected.length);for(const p of actual)assert.ok(expected.some(q=>Math.hypot(p.x-q.x,p.y-q.y)<=tolerance),JSON.stringify({actual,expected}));}
function worldLeaf(item,allWalls,open){const info=Openings.explicitHostWallInfo(item,allWalls),angle=info.rot*Math.PI/180,c=Math.cos(angle),s=Math.sin(angle);return Openings.sourcePlanGeometry(item,open).leaf.map(p=>({x:info.x+c*p.x-s*p.y,y:info.y+s*p.x+c*p.y}));}
function transformed(scene,quarter){const out=clone(scene),vector=p=>{let {x,y}=p;for(let i=0;i<quarter;i++)[x,y]=[-y,x];return {x,y};},point=p=>{const q=vector(p);return {x:q.x+10000,y:q.y+10000};};for(const w of out.walls){w.start.value=point(w.start.value);w.end.value=point(w.end.value);}for(const r of out.rooms)for(const b of r.shape.value.rectangles){const a=point({x:b.x,y:b.y}),c=point({x:b.x+b.w,y:b.y+b.d});b.x=Math.min(a.x,c.x);b.y=Math.min(a.y,c.y);b.w=Math.abs(a.x-c.x);b.d=Math.abs(a.y-c.y);}for(const e of out.openings){e.start.value=point(e.start.value);e.end.value=point(e.end.value);for(const l of e.leaves){l.closedCenter.value=point(l.closedCenter.value);l.openCenter.value=point(l.openCenter.value);l.travelDirection.value=vector(l.travelDirection.value);}}return out;}

test('fully specified independent single slide reuses native envelope without mutating raw, hash or DATA',()=>{
 const scene=fixture(),raw=JSON.stringify(scene),hash=Scene.sourceHash(scene),c=runtime(),before=JSON.stringify(c.DATA),r=reviewed(scene),d=direct(scene);
 assert.equal(r.canApply,true,JSON.stringify(r.diagnostics));assert.equal(d.ok,true,JSON.stringify(d.diagnostics));assert.equal(r.plan.items[0].type,'door-slide-s');
 assert.deepEqual(r.plan.items[0].openingSourceGeometry,{mode:'single',direction:1,leafWidthMm:840,leafThicknessMm:36,closedXmm:0,openXmm:810,leafZmm:-86});
 assert.equal(r.plan.items[0].w,780);assert.equal(Openings.wallCutWidthMm(r.plan.items[0],4000),780);assert.ok(!r.defaults.some(d=>d.path.startsWith('openings[')));
 assert.equal(JSON.stringify(scene),raw);assert.equal(Scene.sourceHash(scene),hash);assert.equal(JSON.stringify(c.DATA),before);assert.deepEqual(r.sourceScene,scene);
 const native=spec(scene);delete native.sourceLeaf;delete native.sourceExactGap;native.wallFace={x:0,y:-1};const n=Openings.compileOpening(native,walls(scene),[]);assert.equal(n.ok,true);assert.deepEqual(d.geometry.parameters,n.geometry.parameters);
});
test('shared engine and materializer world poses agree across cardinal hosts, reversals, faces and travel signs',()=>{
 for(const face of [-1,1])for(const travel of [-1,1])for(const quarter of [0,1,2,3])for(const reverse of [false,true])for(const open of [false,true]){
  const scene=transformed(fixture(face,travel),quarter);if(reverse)[scene.walls[0].start,scene.walls[0].end]=[scene.walls[0].end,scene.walls[0].start];scene.openings[0].leaves[0].openState.value=open?'open':'closed';
  const raw=JSON.stringify(scene),r=reviewed(scene),d=direct(scene);assert.equal(r.canApply,true,JSON.stringify(r.diagnostics));assert.equal(d.ok,true,JSON.stringify(d.diagnostics));
  for(const state of [false,true])samePoints(worldLeaf(r.plan.items[0],r.plan.walls,state),d.geometry[state?'fullOpenLeaf':'closedLeaf']);
  const centre=poly=>({x:poly.reduce((a,p)=>a+p.x,0)/4,y:poly.reduce((a,p)=>a+p.y,0)/4});samePoints([centre(d.geometry.closedLeaf)],[scene.openings[0].leaves[0].closedCenter.value]);samePoints([centre(d.geometry.fullOpenLeaf)],[scene.openings[0].leaves[0].openCenter.value]);assert.equal(JSON.stringify(scene),raw);
 }
});
test('source exact declaration, independent leaf facts and known state are mandatory in the shared adapter',()=>{
 const s=spec(fixture()),w=walls(fixture());for(const [change,code] of [
  [q=>delete q.sourceExactGap,'source-slide-exact-gap-required'],[q=>delete q.sourceLeaf,'missing-independent-source-leaf'],[q=>delete q.sourceLeaf.leafWidthMm,'invalid-source-panel'],[q=>delete q.sourceLeaf.thicknessMm,'invalid-source-panel'],[q=>delete q.sourceLeaf.closedCenter,'invalid-source-slide'],[q=>delete q.sourceLeaf.travelDistanceMm,'invalid-source-slide'],[q=>delete q.travelDirection,'invalid-source-slide'],[q=>delete q.doorOpenState,'invalid-source-slide-state'],[q=>q.doorOpenState='partial','invalid-opening-state']
 ]){const q=clone(s);change(q);const r=Openings.compileOpening(q,w,[]);assert.equal(r.ok,false);assert.ok(codes(r).includes(code),JSON.stringify(r.diagnostics));}
});
test('unknown source fields stay unresolved after reviews, without opening defaults or raw repair',()=>{
 for(const change of [s=>s.openings[0].floor=u(),s=>s.openings[0].hostWallId=u(),s=>s.openings[0].start=u(),s=>s.openings[0].end=u(),s=>s.openings[0].adjacentRoomIds=u(),s=>s.openings[0].leafRelation=u(),s=>s.openings[0].heightMm=u(),...['mechanism','leafWidthMm','thicknessMm','closedCenter','travelDirection','travelDistanceMm','openState'].map(k=>s=>s.openings[0].leaves[0][k]=u())]){
  const s=fixture();change(s);const before=JSON.stringify(s),r=reviewed(s);assert.equal(r.canApply,false);assert.ok(codes(r).includes('unknown_required_geometry'),JSON.stringify(r.diagnostics));assert.equal(r.plan.items.length,0);assert.ok(!r.defaults.some(d=>d.path.startsWith('openings[')));assert.equal(JSON.stringify(s),before);
 }
 const s=fixture();s.openings[0].leaves[0].openCenter=u();assert.equal(reviewed(s).canApply,true,'Independent exact travel permits an unobserved full-open centre');assert.equal(s.openings[0].leaves[0].openCenter.value,null);
});
test('host thickness, source floors and room basis cannot use matching editor or placement defaults',()=>{
 for(const change of [s=>s.walls[0].thicknessMm=u(),s=>s.walls[0].floor=u(),s=>s.rooms[0].floor=u(),s=>s.rooms[0].boundaryBasis=u(),s=>s.openings[0].floor=u()]){
  const s=fixture();change(s);const pageScope=['image:1:anonymous'],options={...base,pageScope,placementContext:Scene.createPlacementContext(s,pageScope,1,true),targetPlan:{...base.targetPlan,walls:[{id:'host',floor:1,x1:0,y1:0,x2:4000,y2:0,thick:120}]},defaultWallHeightMmForFloor:()=>2400};const r=reviewed(s,options);assert.equal(r.canApply,false);assert.equal(r.plan.items.length,0);assert.ok(codes(r).includes('unknown_required_geometry')||codes(r).includes('invalid_opening_host'),JSON.stringify(r.diagnostics));
 }
 const s=fixture();s.walls[0].thicknessMm={value:120,status:'inferred',source:'anonymous independent thickness reconstruction',reason:'Separate source thickness evidence needs review'};const first=Scene.compile(s,base);assert.equal(first.canApply,false);assert.ok(codes(first).includes('inference_review'));assert.equal(reviewed(s).canApply,true);assert.equal(s.walls[0].thicknessMm.status,'inferred');
});
test('every contributing backing wall needs an explicit source floor despite matching runtime placement',()=>{
 const s=fixture();s.walls[0].end.value.x=2500;s.walls.push({id:'continuation',floor:u(),start:f({x:2500,y:0}),end:f({x:4000,y:0}),thicknessMm:f(120)});
 const pageScope=['image:1:anonymous'],options={...base,pageScope,placementContext:Scene.createPlacementContext(s,pageScope,1,true)},raw=JSON.stringify(s),r=reviewed(s,options);
 assert.equal(r.canApply,false);assert.equal(r.plan.items.length,0);assert.ok(r.diagnostics.some(d=>d.code==='unknown_required_geometry'&&d.path==='openings[0].backingSourceFloor.continuation'),JSON.stringify(r.diagnostics));assert.equal(JSON.stringify(s),raw);assert.equal(s.walls[1].floor.value,null);
 s.walls[1].floor=f(1);assert.equal(reviewed(s).canApply,true,'Independent known source continuation supports the envelope');
 const unrelated=fixture();unrelated.walls.push({id:'unrelated',floor:u(),start:f({x:4500,y:0}),end:f({x:5500,y:0}),thicknessMm:f(120)});const unOptions={...base,pageScope,placementContext:Scene.createPlacementContext(unrelated,pageScope,1,true)};assert.equal(reviewed(unrelated,unOptions).canApply,true,'No new source-floor requirement for walls outside the certified panel envelope');
});
test('panel dimensions, closed centre, track offset and travel remain independent from the gap',()=>{
 for(const change of [s=>s.openings[0].end.value.x+=10,s=>s.openings[0].leaves[0].leafWidthMm.value=780,s=>s.openings[0].leaves[0].thicknessMm.value=35.999,s=>s.openings[0].leaves[0].closedCenter.value.x+=.01,s=>s.openings[0].leaves[0].closedCenter.value.y=-85.99,s=>s.openings[0].leaves[0].travelDistanceMm.value=780]){const s=fixture();change(s);const before=JSON.stringify(s),r=reviewed(s);assert.equal(r.canApply,false);assert.ok(codes(r).includes('opening_unsupported-source-slide-envelope'),JSON.stringify(r.diagnostics));assert.equal(JSON.stringify(s),before);}
 const s=fixture(),e=s.openings[0],l=e.leaves[0];e.start.value.x=1600;e.end.value.x=2400;l.leafWidthMm.value=860;l.travelDistanceMm.value=830;l.openCenter.value.x=2830;assert.equal(reviewed(s).canApply,true,'Different independently specified native-matching gap/panel pair');
});
test('pose, travel axis, wall face and extra leaf facts never fall back to defaults',()=>{
 for(const [change,code] of [[s=>s.openings[0].leaves[0].openCenter.value.x+=.001,'opening_source-slide-pose-conflict'],[s=>s.openings[0].leaves[0].openCenter.value.y+=.001,'opening_source-slide-pose-conflict'],[s=>s.openings[0].leaves[0].travelDirection.value={x:0,y:1},'opening_invalid-source-slide'],[s=>s.openings[0].leaves[0].closedAxis=f({x:0,y:1}),'opening_source-slide-axis-conflict'],[s=>s.openings[0].leaves[0].openState.value='partial','unsupported_partial_open_state'],[s=>s.openings[0].leaves[0].observedPolyline=f([{x:1,y:1},{x:2,y:2}]),'unsupported_leaf_polyline'],...['pivot','hingeJamb','swingSide','angleDeg','pocketRegion'].map(k=>[s=>{s.openings[0].leaves[0][k]=f(k==='hingeJamb'?'start':k==='angleDeg'?0:k==='pocketRegion'?{kind:'rectUnion',rectangles:[{x:1,y:1,w:2,d:2}]}:{x:1,y:0});},'inapplicable_source_leaf_fact'])]){const s=fixture();change(s);const r=reviewed(s);assert.equal(r.canApply,false);assert.ok(codes(r).includes(code),JSON.stringify(r.diagnostics));}
 for(const [change,code] of [[q=>q.wallFace={x:0,y:1},'source-slide-face-conflict'],[q=>q.travel={x:780,y:0},'opening-travel-mismatch'],[q=>q.sourceLeaf.extra='ignored','unsupported-source-leaf-field'],[q=>q.sourceLeaf.pocketPolygon=[],'inapplicable-source-leaf-field']]){const q=spec(fixture());change(q);const r=Openings.compileOpening(q,walls(fixture()),[]);assert.equal(r.ok,false);assert.ok(codes(r).includes(code));}
});
test('paired/bypass/fold/pocket and stair cases do not enter the single-slide route',()=>{
 for(const change of [s=>s.openings[0].leafRelation.value='paired',s=>s.openings[0].leafRelation.value='bypass',s=>s.openings[0].leafRelation.value='independent',s=>s.openings[0].leaves.push({...clone(s.openings[0].leaves[0]),id:'leaf2'}),s=>s.openings[0].mechanism.value='bypass-slide',s=>s.openings[0].mechanism.value='fold',s=>s.openings[0].leaves[0].mechanism.value='pocket']){const s=fixture();change(s);assert.equal(reviewed(s).canApply,false);}
 const q=spec(fixture());q.kind='door-slide';assert.ok(codes(Openings.compileOpening(q,walls(fixture()),[])).includes('unsupported-source-mechanism'));
 const s=fixture();s.objects.push({id:'stairs',objectType:f('stair'),semanticExtent:f('asset'),placement:f({domain:'room',roomId:'south'}),sourceFootprint:f({center:{x:1000,y:1000},sizeMm:{w:900,d:1200},axisX:{x:1,y:0}})});assert.ok(codes(reviewed(s)).includes('unsupported_stair_reconstruction'));
});
test('unique exact host, complete span and named adjacent boundaries remain mandatory',()=>{
 for(const [change,code] of [[s=>s.walls.push(clone(s.walls[0])),'invalid_id'],[s=>s.openings[0].end.value.y=.01,'invalid_opening_span'],[s=>{s.openings[0].start.value.y=.01;s.openings[0].end.value.y=.01;},'wrong_adjacent_room'],[s=>s.rooms[0].shape.value.rectangles[0].y+=.01,'wrong_adjacent_room'],[s=>s.openings[0].adjacentRoomIds.value=[null,null],'invalid_slide_adjacency'],[s=>s.openings[0].adjacentRoomIds.value=['north','north'],'invalid_slide_adjacency']]){const s=fixture();change(s);const r=reviewed(s);assert.equal(r.canApply,false);assert.ok(codes(r).includes(code),JSON.stringify(r.diagnostics));}
 const s=fixture();s.openings[0].adjacentRoomIds.value=['south',null];assert.equal(reviewed(s).canApply,true,'Known room and explicit exterior/null');const q=spec(fixture()),ww=walls(fixture());assert.ok(codes(Openings.compileOpening(q,[...ww,clone(ww[0])],[])).includes('ambiguous-host-wall'));q.center.y=.001;assert.ok(codes(Openings.compileOpening(q,ww,[])).includes('opening-off-host'));
});
test('3200 mm wall still lacks exactly 30 mm backing/envelope and end contact tolerance is unchanged',()=>{
 const s=fixture();s.walls[0].end.value.x=3200;const d=direct(s),r=reviewed(s);assert.equal(d.ok,false);assert.equal(r.canApply,false);for(const code of ['insufficient-slider-backing','insufficient-slider-envelope']){const diag=d.diagnostics.find(d=>d.code===code);assert.equal(diag.missingMm,30);assert.deepEqual(diag.missingIntervalsMm,[[3200,3230]]);assert.ok(codes(r).includes('opening_'+code));}assert.equal(s.walls[0].end.value.x,3200);
 const contact=fixture();contact.walls[0].end.value.x=3230;assert.equal(direct(contact).ok,true);assert.equal(reviewed(contact).canApply,true);contact.walls[0].end.value.x-=.001;assert.equal(direct(contact).ok,false);assert.equal(reviewed(contact).canApply,false);
});
test('continuous equal-thickness backing rejects tiny gaps, shifted walls and end overhang',()=>{
 for(const face of [-1,1]){
  const s=fixture(face);s.walls[0].end.value.x=2500;s.walls.push({id:'continuation',floor:f(1),start:f({x:2500,y:0}),end:f({x:4000,y:0}),thicknessMm:f(120)});assert.equal(direct(s).ok,true);assert.equal(reviewed(s).canApply,true);
  for(const change of [s=>s.walls[1].start.value.x+=.001,s=>s.walls[1].thicknessMm.value=119.999,s=>{s.walls[1].start.value.y=.001;s.walls[1].end.value.y=.001;}]){const q=clone(s);change(q);const r=reviewed(q);assert.equal(r.canApply,false);assert.ok(codes(r).includes('opening_insufficient-slider-envelope'),JSON.stringify(r.diagnostics));}
  for(const travel of [-1,1]){const q=fixture(face,travel);q.walls[0].start.value.x=travel<0?770.001:1580.001;assert.equal(direct(q).ok,false);assert.ok(codes(reviewed(q)).includes('opening_insufficient-slider-envelope'));}
 }
});
test('other actual aperture cuts and overlapping openings still remove backing',()=>{
 const s=fixture();s.openings.push({id:'other',floor:f(1),hostWallId:f('host'),adjacentRoomIds:f(['north','south']),start:f({x:2600,y:0}),end:f({x:3000,y:0}),mechanism:f('opening'),heightMm:f(2100)});const r=reviewed(s);assert.equal(r.canApply,false);assert.ok(codes(r).includes('opening_insufficient-slider-backing'));assert.ok(codes(r).includes('opening_insufficient-slider-envelope'));
 const other={id:'other',floor:1,kind:'door-opening',hostWallId:'host',center:{x:3500,y:0},widthMm:500},d=direct(fixture(),[other]);assert.equal(d.ok,false);assert.deepEqual(d.geometry.missingBackingIntervalsMm,[[3210,3230]],'Legacy actual cut keeps 40 mm per-side margin');other.sourceExactGap=true;assert.equal(direct(fixture(),[other]).ok,true);other.center.x=2390;other.widthMm=20;assert.ok(codes(direct(fixture(),[other])).includes('overlapping-openings'));
});
test('crossing walls and narrow intermediate sweep obstacles remain rejected for both faces/travel signs',()=>{
 for(const face of [-1,1])for(const travel of [-1,1]){const s=fixture(face,travel),x=2000+travel*700,y=face*86;s.walls.push({id:'blocker',floor:f(1),start:f({x:x-1,y:y-.1}),end:f({x:x+1,y:y-.1}),thicknessMm:f(.4)});const d=direct(s),r=reviewed(s);assert.equal(d.ok,false);assert.equal(r.canApply,false);assert.ok(codes(d).includes('opening-sweep-collision'));assert.ok(codes(r).includes('opening_opening-sweep-collision'));}
});
test('any source/hash or review-context change invalidates accepted slider approvals',()=>{
 for(const change of [s=>s.openings[0].leaves[0].openCenter.value.x+=1,s=>s.openings[0].leaves[0].openState.value='open',s=>s.walls[0].end.value.x=3900,s=>s.annotations.push({id:'annotation',kind:'label',literalText:f('new anonymous note')})]){const s=fixture();s.openings[0].leaves[0].closedCenter.status='inferred';s.openings[0].leaves[0].closedCenter.reason='Independent source review is required';const o=accepted(s),hash=Scene.sourceHash(s);assert.equal(Scene.compile(s,o).canApply,true);change(s);const r=Scene.compile(s,o);assert.notEqual(Scene.sourceHash(s),hash);assert.equal(r.canApply,false);assert.equal(r.reviewGroups.find(g=>g.entityId==='slide').accepted,false);}
});
test('actual Apply, cancel/reopen and save/Undo preserve immutable source/hash and revoke approvals',()=>{
 const s=fixture(),raw=JSON.stringify(s),hash=Scene.sourceHash(s),c=runtime(),before=JSON.stringify(c.DATA),first=c.PlanImport.previewSceneIR(s,{materialization:'bounded-v3'}),fresh={materialization:'bounded-v3',acceptedReviewGroups:first.reviewGroups.map(g=>g.id),reviewedEntities:Object.fromEntries(first.reviewGroups.map(g=>[g.entityId,g.reviewKey]))};
 const get=c.document.getElementById;c.document.getElementById=id=>{const node=get(id);node.classList.toggle=()=>{};node.classList.contains=()=>false;return node;};
 assert.equal(c.PlanImport.stageSceneIR(s,fresh).canApply,true);assert.equal(JSON.stringify(c.DATA),before);c.closePlanImport();assert.equal(c.PlanImport.previewSceneIR(s,c.PlanImport.state.result.sceneOptions).canApply,false);assert.equal(c.PlanImport.state.result.sceneOptions.acceptedReviewGroups.length,0);c.applyPlanImport();assert.equal(c.HISTORY.length,0);
 const resume=c.PlanImport.capture();c.PlanImport.restore(resume);assert.equal(c.PlanImport.state.result.sceneCompilation.canApply,false);assert.equal(JSON.stringify(c.DATA),before);
 c.PlanImport.stageSceneIR(s,fresh);c.applyPlanImport();assert.equal(c.HISTORY.length,1);assert.equal(JSON.stringify(JSON.parse(c.HISTORY[0])),before);const item=c.DATA.items[0];assert.equal(item.type,'door-slide-s');assert.deepEqual(clone(item.openingSourceGeometry),clone(direct(s).item.openingSourceGeometry));const report=c.DATA.sceneReconstructionReports[0];assert.equal(JSON.stringify(report.originalIR),raw);assert.equal(Scene.sourceHash(report.originalIR),hash);const saved=clone(c.DATA);assert.equal(JSON.stringify(saved.items[0].openingSourceGeometry),JSON.stringify(item.openingSourceGeometry));assert.equal(JSON.stringify(s),raw);c.DATA=JSON.parse(c.HISTORY[0]);assert.equal(JSON.stringify(c.DATA),before);
});
test('actual source-slider shape edits are blocked while state/translation and Undo preserve geometry and provenance',()=>{
 const {createRequire}=require('node:module'),helperPath=path.join(__dirname,'scene-opening-lifecycle.test.cjs');let helper=fs.readFileSync(helperPath,'utf8');helper=helper.slice(0,helper.indexOf("test('completed 2D drag"))+'\nmodule.exports={runtime,load};';const h={require:createRequire(helperPath),module:{exports:{}},__dirname,console};vm.runInNewContext(helper,h);const c=h.module.exports.runtime(),s=fixture(),raw=JSON.stringify(s),item=direct(s).item;c.DATA.items=[item];c.ST.selected=item;c.DATA.sceneReconstructionReports=[{originalIR:clone(s)}];c.alerts=[];c.alert=m=>c.alerts.push(m);const before=JSON.stringify(c.DATA),geometry=JSON.stringify(item.openingSourceGeometry);
 for(const key of ['w','d','rot','flipX','flipY','type','openingModel','openingSourceGeometry','openingHostWallId','doorHeight'])c.updateSelectedProp(key,1);
 assert.equal(JSON.stringify(c.DATA),before);assert.equal(c.HISTORY.length,0);assert.equal(c.alerts.length,10);c.updateSelectedProp('doorOpenState','open');assert.equal(item.doorOpenState,'open');assert.equal(item.openingPlacementEdited,undefined);assert.equal(c.HISTORY.length,1);c.updateSelectedProp('x',item.x+100);assert.equal(item.openingPlacementEdited,true);assert.equal(item.openingHostWallId,'host');assert.equal(JSON.stringify(item.openingSourceGeometry),geometry);assert.equal(JSON.stringify(c.DATA.sceneReconstructionReports[0].originalIR),raw);c.undoAction();assert.equal(c.DATA.items[0].doorOpenState,'open');assert.equal(c.DATA.items[0].openingPlacementEdited,undefined);c.undoAction();assert.equal(JSON.stringify(c.DATA),before);c.redoAction();assert.equal(c.DATA.items[0].doorOpenState,'open');assert.equal(JSON.stringify(c.DATA.items[0].openingSourceGeometry),geometry);assert.equal(JSON.stringify(s),raw);
});
async function renderedPlan(plan){
 const THREE=await import('../../assets/vendor/three/build/three.module.js');const c=vm.createContext({THREE,RoomGeometry,SceneOpeningGeometry:Openings,DATA:plan,U:.001,_doorAnims:[],sc3:new THREE.Scene(),isOpeningItemType:t=>t==='door-slide-s',isWindowLikeType:()=>false,isArchOpeningType:()=>false,isNoDoorOpeningType:()=>false,item3DBaseY:()=>0,makeItemTextureMaterial:()=>null,getOpeningModelItem:()=>null,getWallExteriorSpans:()=>[],doorLeafFaceMaterials:m=>m,mark3DSelectable:()=>{},makeRoomFloorMaterial:()=>new THREE.MeshStandardMaterial()});for(const name of ['doorHeightMm','doorOpenState','doorOpenWant','getOpeningWallInfo'])vm.runInContext(topLevelFunction(name),c);c.ST={view:'3d-int'};c.isWalkView=()=>false;c._doorWantByItem=new WeakMap();vm.runInContext(topLevelFunction('buildWinFrames'),c);c.buildWinFrames();assert.equal(c._doorAnims.length,1);const anim=c._doorAnims[0],mesh=anim.slideMesh.children[0];c.sc3.updateMatrixWorld(true);const pos=mesh.geometry.attributes.position,points=[];for(let i=0;i<pos.count;i++){const v=new THREE.Vector3().fromBufferAttribute(pos,i).applyMatrix4(mesh.matrixWorld),p={x:v.x*1000,y:v.z*1000};if(!points.some(q=>Math.hypot(p.x-q.x,p.y-q.y)<.0001))points.push(p);}return {anim,mesh,points};
}
test('unchanged actual THREE native renderer preserves exact panel poses and dimensions in both states',async()=>{
 for(const face of [-1,1])for(const travel of [-1,1])for(const quarter of [0,1,2,3])for(const reverse of [false,true])for(const open of [false,true]){const s=transformed(fixture(face,travel),quarter);if(reverse)[s.walls[0].start,s.walls[0].end]=[s.walls[0].end,s.walls[0].start];s.openings[0].leaves[0].openState.value=open?'open':'closed';const r=reviewed(s),rendered=await renderedPlan(r.plan);assert.equal(rendered.mesh.geometry.parameters.width,.84);assert.equal(rendered.mesh.geometry.parameters.depth,36*.001);samePoints(rendered.points,direct(s).geometry[open?'fullOpenLeaf':'closedLeaf'],.0001);assert.equal(rendered.anim.openX,r.plan.items[0].openingSourceGeometry.openXmm*.001);assert.equal(rendered.anim.closedX,r.plan.items[0].openingSourceGeometry.closedXmm*.001);}
});
test('public frozen raw remains unchanged and bypass, missing facts and stairs are still unresolved',()=>{
 const p=path.join(__dirname,'../../local-preview/frozen-page-2.json'),bytes=fs.readFileSync(p),hash=crypto.createHash('sha256').update(bytes).digest('hex'),s=JSON.parse(bytes),before=JSON.stringify(s),r=reviewed(s);assert.equal(r.canApply,false);assert.ok(codes(r).some(c=>['unsupported_opening_mechanism','unsupported_leaf_group','unsupported_leaf_relation'].includes(c)));assert.ok(codes(r).includes('unsupported_stair_reconstruction')||codes(r).includes('unsupported_stair_room_floor'));assert.equal(JSON.stringify(s),before);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),hash);
});
