const test=require('node:test'),assert=require('node:assert/strict');
const Scene=require('../../assets/js/scene-ir-v3.js'),Overlay=require('../../assets/js/scene-source-overlay.js');
const f=value=>({value,status:'observed',source:'synthetic diagram'}),u=()=>({value:null,status:'unknown',unknownReason:'not-shown'});
function fixture(){return {sceneVersion:3,units:'mm',coordinateSystem:'x-east-y-south-clockwise',annotations:[],walls:[],rooms:[{id:'room',floor:f(1),shape:f({kind:'rectUnion',rectangles:[{x:0,y:0,w:4000,d:4000}]}),boundaryBasis:f('clear-face')}],openings:[],objects:[{id:'symbol',objectType:f('unidentified-symbol'),semanticExtent:f('symbol-only'),placement:f({domain:'room',roomId:'room'}),sourceFootprint:u(),heightMm:u(),appearance:{pattern:f('square-grid'),moduleMm:f(150)}}],siteRegions:[],buildingFootprints:[],bindings:[],connections:[]};}
const options={materialization:'bounded-v3',registry:{get:()=>null},targetPlan:{heightDefaults:{modelVersion:2,floorThickness:180}},defaultFloorOffset:()=>0};
function reviewed(s){const first=Scene.compile(s,options);return Scene.compile(s,{...options,acceptedReviewGroups:first.reviewGroups.map(g=>g.id),reviewedEntities:Object.fromEntries(first.reviewGroups.map(g=>[g.entityId,g.reviewKey]))});}
const codes=r=>r.diagnostics.map(d=>d.code);
test('explicit symbol-only unknown footprint retains source and review without creating physical or invented outline',()=>{
 const s=fixture(),raw=JSON.stringify(s),r=reviewed(s);assert.equal(r.valid,true);assert.equal(r.plan.items.length,0);assert.equal(r.plan.rooms.length,1);assert.equal(r.canApply,true);assert.equal(r.reconstructionStatus,'incomplete-source-overlays');assert.ok(codes(r).includes('source_annotation_retained'));assert.ok(codes(r).includes('source_overlay_geometry_unknown'));assert.equal(codes(r).includes('unknown_required_geometry'),false);assert.equal(codes(r).includes('unsupported_asset_pattern'),false);assert.equal(JSON.stringify(s),raw);assert.equal(JSON.stringify(r.sourceScene),raw);assert.equal(r.sourcePreview.objects[0].sourceFootprint.value,null);assert.equal(r.reviewGroups.find(g=>g.entityId==='symbol').evidence.some(e=>e.path.endsWith('.sourceFootprint')&&e.status==='unknown'),true);assert.equal(Overlay.primitives({originalIR:s,sourcePreview:r.sourcePreview},true).some(p=>p.id==='symbol'),false);
});
test('symbol alone is not an applicable physical plan; known source segments stay read-only',()=>{
 const s=fixture();s.rooms=[];s.objects[0].placement=u();s.objects[0].diagramSegments=f([{points:[{x:10,y:20},{x:30,y:20}],visibility:'solid'}]);const r=reviewed(s);assert.equal(r.canApply,false);assert.ok(codes(r).includes('empty_materialization'));assert.equal(r.plan.items.length,0);assert.equal(r.sourceScene.objects[0].sourceFootprint.value,null);const lines=Overlay.primitives({originalIR:s,sourcePreview:r.sourcePreview},true).filter(p=>p.id==='symbol');assert.equal(lines.length,1);assert.equal(lines[0].kind,'line');assert.deepEqual(lines[0].points,s.objects[0].diagramSegments.value[0].points);
});
test('paired physical/unidentified asset or unknown classification still requires footprint geometry',()=>{
 for(const [type,extent] of [['unidentified-symbol','asset'],['desk','asset'],['desk','symbol-only'],[null,'symbol-only'],['unidentified-symbol',null]]){const s=fixture();s.objects[0].objectType=type===null?u():f(type);s.objects[0].semanticExtent=extent===null?u():f(extent);const raw=JSON.stringify(s),r=reviewed(s);assert.equal(r.canApply,false);assert.ok(codes(r).includes('unknown_required_geometry'));assert.equal(r.plan.items.length,0);assert.equal(JSON.stringify(s),raw);}
});
test('symbol retention cannot turn a selected catalogue binding into a physical object',()=>{
 const s=fixture();s.bindings=[{id:'map',sourceEntityId:'symbol',catalogId:f('some-asset'),sizingPolicy:'native'}];const r=reviewed(s);assert.equal(r.plan.items.length,0);assert.deepEqual(r.sourceScene.bindings,s.bindings);assert.equal(r.reconstructionStatus,'incomplete-source-overlays');assert.ok(codes(r).includes('source_annotation_retained'));
});
test('symbol-only shortcut does not bypass schema, references, opening hosts or unknown entry height',()=>{
 const bad=fixture();bad.objects[0].sourceFootprint={value:null,status:'observed',source:'diagram'};assert.equal(Scene.compile(bad,options).valid,false);
 const ref=fixture();ref.objects[0].placement=f({domain:'room',roomId:'missing'});assert.equal(Scene.compile(ref,options).valid,false);
 const host=fixture();host.openings=[{id:'opening',floor:f(1),hostWallId:u(),adjacentRoomIds:f(['room',null]),start:f({x:0,y:0}),end:f({x:900,y:0}),mechanism:f('opening')}];const r=reviewed(host);assert.equal(r.canApply,false);assert.ok(codes(r).includes('unknown_required_geometry'));
 const entry=fixture();entry.rooms[0].relativeElevation={offsetMm:u(),relativeToId:f('reference')};entry.rooms.push({id:'reference',floor:f(1),shape:f({kind:'rectUnion',rectangles:[{x:4500,y:0,w:1000,d:1000}]}),boundaryBasis:f('clear-face')});const e=reviewed(entry);assert.equal(e.canApply,false);assert.ok(e.diagnostics.some(d=>d.code==='unknown_required_geometry'&&d.path==='rooms[0].relativeElevation.offsetMm'));
});
