/* Dedicated offline browser, user-visible import/review/apply/save/resume. */
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {openImportReview}=require('./plan-import-browser-helpers.cjs');
const origin=process.env.APP_URL||'http://127.0.0.1:65372',out=process.env.OUTPUT_DIR||'/tmp/webcad-review-flow';fs.mkdirSync(out,{recursive:true});assert.match(origin,/^http:\/\/127\.0\.0\.1:\d+$/);
const raw=fs.readFileSync('local-preview/frozen-page-2.json');assert.equal(crypto.createHash('sha256').update(raw).digest('hex'),'c98e9213665b0527fae907a19d145d8a038db8f82bd049c57b74607add05485c');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']}),context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),errors=[],blocked=[];
 try{await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===origin&&!u.pathname.startsWith('/api/'))return r.continue();blocked.push(u.origin+u.pathname);return r.abort();});const p=await context.newPage();context.setDefaultTimeout(30000);p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto(origin);await p.waitForSelector('#app-loading',{state:'hidden',timeout:60000});await p.evaluate(()=>closePresetChoice());
 const integrity=()=>p.evaluate(()=>({data:serializeDataSnapshot(),history:JSON.stringify(HISTORY),redo:JSON.stringify(REDO_HISTORY),dirty:DIRTY}));const before=await integrity();
 await p.locator('#plan-import-toolbar-btn').click();await p.locator('#scene-review-files > summary').click();
 // PDF comparison is local-only; page choice does not silently recrop or re-extract.
 await p.locator('[data-scene-reference] > summary').click();await p.getByLabel('照合するPDFか画像',{exact:true}).setInputFiles('tools/tests/fixtures/madori-3f.pdf');await p.waitForFunction(()=>document.querySelector('[data-scene-reference-page]').options.length===3);await p.locator('[data-scene-reference-page]').selectOption('1');
 const image=await p.locator('[data-scene-reference-image]').getAttribute('src');await p.locator('#plan-import-file').setInputFiles({name:'public-legacy-page2.png',mimeType:'image/png',buffer:Buffer.from(image.split(',')[1],'base64')});await p.waitForFunction(()=>!!PlanImport.state.image);
 // Standard JSON toolbar dispatches SceneIR to review, not native replacement.
 await p.locator('#import-file').setInputFiles({name:'frozen-v3-page2.json',mimeType:'application/json',buffer:raw});await p.waitForSelector('[data-scene-full-status]');await openImportReview(p);assert.deepEqual(await integrity(),before);
 assert.equal(await p.evaluate(()=>PlanImport.state.result.sceneFullCompilation.canApply),false);const rawErrors=await p.evaluate(()=>PlanImport.state.result.sceneFullCompilation.diagnostics.filter(d=>d.severity==='error').length);assert.equal(rawErrors,26);
 await p.locator('[data-scene-review-search]').fill('no match');await p.locator('[data-scene-error-focus="openings[6]"]').click();assert.equal(await p.locator('[data-scene-review-search]').inputValue(),'');assert.ok(await p.locator('details[data-scene-group="openings:door-balcony-north"]').evaluate(e=>e.open));assert.match(await p.locator('[data-scene-guidance="openings:door-balcony-north"]').innerText(),/未対応/);
 await p.screenshot({path:path.join(out,'actionable-door-error.png')});
 for(const id of ['obj-refrigerator','room-ldk']){await p.locator('[data-scene-review-search]').fill(id);const g=p.locator('details[data-scene-group="'+(id==='room-ldk'?'rooms':'objects')+':'+id+'"]');await g.locator(':scope > summary').click();await p.locator('[data-scene-mapping="'+id+'"]').click();if(id==='obj-refrigerator'){await p.locator('[data-scene-catalogue]').selectOption(await p.evaluate(()=>SceneCatalogue.refrigeratorCertificate.id));await p.locator('[data-scene-sizing]').selectOption('fit-source');}await p.locator('[data-scene-appearance]').selectOption('match-diagram-appearance');await p.locator('[data-scene-mapping-confirm]').click();}
 const mappedErrors=await p.evaluate(()=>PlanImport.state.result.sceneFullCompilation.diagnostics.filter(d=>d.severity==='error').length);assert.equal(mappedErrors,24);console.log('mapped');
 // Cancel a mapping edit preserves confirmed choices.
 const choices=await p.evaluate(()=>JSON.stringify(PlanImport.state.result.sceneOptions.bindingDecisions));await p.locator('[data-scene-mapping="room-ldk"]').click();await p.locator('[data-scene-mapping-cancel]').click();assert.equal(await p.evaluate(()=>JSON.stringify(PlanImport.state.result.sceneOptions.bindingDecisions)),choices);
 await p.locator('[data-scene-partial-enable]').check();if(!await p.locator('[data-scene-partial-options]').evaluate(e=>e.open))await p.locator('[data-scene-partial-options] > summary').click();const ids=await p.locator('[data-scene-partial-object]').evaluateAll(es=>es.map(e=>e.getAttribute('data-scene-partial-object')));for(const id of ids)if(id!=='obj-refrigerator')await p.locator('[data-scene-partial-object="'+id+'"]').uncheck();await p.locator('[data-scene-partial-accept]').check();assert.equal(await p.locator('#plan-import-apply').isEnabled(),true);
 console.log('partial accepted');await openImportReview(p);const downloadPromise=p.waitForEvent('download');await p.locator('[data-scene-review-save]').click();const download=await downloadPromise;const sessionPath=path.join(out,'source-review.json');await download.saveAs(sessionPath);const session=JSON.parse(fs.readFileSync(sessionPath));assert.equal(JSON.stringify(session.sceneIR),JSON.stringify(JSON.parse(raw)));assert.deepEqual(session.sceneOptions.acceptedReviewGroups,[]);assert.equal(session.sceneOptions.bindingDecisions.length,2);
 console.log('downloaded');
 // Close/back and reopen saved review preserve choices, require fresh acceptance.
 await p.locator('#plan-import-modal .unity-render-close').click();await p.locator('#plan-import-toolbar-btn').click();await openImportReview(p);await p.locator('[data-scene-review-file]').setInputFiles(sessionPath);await p.waitForFunction(()=>PlanImport.state.result?.sceneOptions?.bindingDecisions.length===2);assert.equal(await p.locator('#plan-import-apply').isDisabled(),true);assert.deepEqual(await integrity(),before);
 const oldBody=await p.evaluate(()=>JSON.stringify(PlanImport.state.result.sceneIR));await p.locator('[data-scene-review-file]').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{')});await p.waitForFunction(()=>document.getElementById('scene-review-file-status').textContent.includes('構文'));assert.equal(await p.evaluate(()=>JSON.stringify(PlanImport.state.result.sceneIR)),oldBody);
 if(!await p.locator('[data-scene-partial-options]').evaluate(e=>e.open))await p.locator('[data-scene-partial-options] > summary').click();await p.locator('[data-scene-partial-accept]').check();
 // Changing reference invalidates approvals while retaining immutable source.
 await openImportReview(p);
 await p.locator('[data-scene-reference] > summary').click();await p.getByLabel('照合するPDFか画像',{exact:true}).setInputFiles('tools/tests/fixtures/madori-3f.pdf');await p.waitForFunction(()=>document.getElementById('scene-review-file-status').textContent.includes('画像を変えた'));assert.equal(await p.locator('#plan-import-apply').isDisabled(),true);await p.locator('[data-scene-reference-page]').selectOption('2');await p.locator('[data-scene-reference-zoom]').click();assert.equal(await p.locator('[data-scene-reference-image]').evaluate(e=>e.style.width),'200%');await p.locator('[data-scene-reference-zoom]').click();await p.locator('[data-scene-reference-zoom]').click();assert.equal(await p.evaluate(()=>JSON.stringify(PlanImport.state.result.sceneIR)),oldBody);
 await p.setViewportSize({width:390,height:844});await p.locator('[data-scene-reference-image]').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,'mobile-source-comparison.png')});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.setViewportSize({width:1440,height:1000});
 await p.locator('[data-scene-partial-accept]').check();await p.locator('#plan-import-apply').click();await p.waitForFunction(()=>!!PlanImport.state.result?.partialPlanId);assert.equal(await p.locator('#plan-import-modal').isVisible(),false);await p.waitForFunction(()=>Array.from(document.querySelectorAll('iframe')).some(f=>f.contentWindow?.DATA?.sceneReconstructionReports?.length));
 let frame;for(const f of p.frames().slice(1))if(await f.evaluate(()=>!!window.DATA?.sceneReconstructionReports?.length))frame=f;assert.ok(frame);await frame.waitForFunction(()=>!!window.EditorPane&&DATA.sceneReconstructionReports?.length===1,null,{timeout:60000});assert.deepEqual(await integrity(),before);
 console.log('native open');const native=await frame.evaluate(()=>({plan:EditorPane.snapshot(),report:DATA.sceneReconstructionReports[0]}));assert.equal(native.plan.items.length,1);assert.equal(native.report.fullReconstructionReady,false);assert.equal(JSON.stringify(native.report.originalIR),oldBody);
 // Actual native edit, save button and saved workspace reload, all in fresh test profile.
 await frame.evaluate(()=>{ST.selected=DATA.items[0];updateSelectedProp('x',DATA.items[0].x+37);});await frame.locator('#floor-sel').selectOption('1');await frame.locator('#floor-sel').selectOption('2');assert.equal(await frame.evaluate(()=>DATA.items[0].floor),2);await frame.locator('#save-btn').click();await frame.waitForFunction(()=>DIRTY===false);const edited=await frame.evaluate(()=>EditorPane.snapshot());await p.locator('[data-parallel-save]').click();await p.locator('[data-parallel-load]').click();await p.waitForFunction(()=>document.querySelector('[data-parallel-status]').textContent==='保存した比較セットを開きました。');await p.waitForFunction(()=>Array.from(document.querySelectorAll('iframe')).some(f=>f.contentWindow?.DATA?.sceneReconstructionReports?.length));let resumed;for(const f of p.frames().slice(1))if(await f.evaluate(()=>!!window.DATA?.sceneReconstructionReports?.length))resumed=f;assert.ok(resumed);await resumed.waitForFunction(()=>!!window.EditorPane&&DATA.sceneReconstructionReports?.length===1);const reloaded=await resumed.evaluate(()=>EditorPane.snapshot());assert.equal(reloaded.items[0].x,edited.items[0].x);assert.equal(JSON.stringify(reloaded.sceneReconstructionReports[0].originalIR),oldBody);
 await resumed.locator('#plan-import-toolbar-btn').click();await resumed.locator('#scene-review-files > summary').click();await resumed.locator('[data-scene-resume-report]').click();assert.equal(await resumed.locator('#plan-import-apply').isDisabled(),true);assert.equal(await resumed.evaluate(()=>PlanImport.state.result.sceneOptions.acceptedReviewGroups.length),0);assert.equal(await resumed.evaluate(()=>DATA.items[0].x),edited.items[0].x);await p.screenshot({path:path.join(out,'saved-native-evidence-resume.png')});
 // Separate public legacy/native contract, not the missing v3 pages 1/3.
 const legacy=await context.newPage();legacy.on('pageerror',e=>errors.push(e.message));await legacy.goto(origin);await legacy.waitForSelector('#app-loading',{state:'hidden',timeout:60000});await legacy.evaluate(()=>closePresetChoice());const legacyBefore=await legacy.evaluate(()=>serializeDataSnapshot());await legacy.locator('#import-file').setInputFiles('local-preview/sample.json');await legacy.waitForSelector('[data-building-floor="3"]',{state:'attached'});await openImportReview(legacy);assert.equal(await legacy.locator('[data-building-floor]').count(),3);assert.equal(await legacy.locator('#plan-import-apply').isDisabled(),true);const legacySource=await legacy.evaluate(()=>JSON.stringify(PlanImport.state.result.sourceLocal));const savedLegacy=legacy.waitForEvent('download');await legacy.locator('[data-scene-review-save]').click();const legacyDownload=await savedLegacy,legacyPath=path.join(out,'legacy-review.json');await legacyDownload.saveAs(legacyPath);await legacy.locator('[data-scene-review-file]').setInputFiles(legacyPath);await legacy.waitForFunction(()=>PlanImport.state.result?.registrationExtraction?.kind==='local-json-import');assert.equal(await legacy.evaluate(()=>JSON.stringify(PlanImport.state.result.sourceLocal)),legacySource);assert.equal(await legacy.evaluate(()=>PlanImport.state.result.buildingDecisions.floors.length),0);assert.equal(await legacy.evaluate(()=>serializeDataSnapshot()),legacyBefore);await legacy.locator('[data-building-floor="3"]').scrollIntoViewIfNeeded();await legacy.screenshot({path:path.join(out,'legacy-three-floor-separate-review.png')});await legacy.close();
 assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);assert.deepEqual(await integrity(),before);
 fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({rawSha256:crypto.createHash('sha256').update(raw).digest('hex'),sourceHash:await resumed.evaluate(()=>SceneIR.sourceHash(PlanImport.state.result.sceneIR)),nativeObjectCount:1,rawErrors,mappedErrors,originalPlanPreserved:true,referencePages:3,referenceIsSeparateLegacyPublicPDF:true,legacySourceLocalFloors:3,nativeFloorSwitch:[1,2],saveReloadEditedX:edited.items[0].x,reopenedApprovals:0,fullReconstructionReady:false,paidCalls:0,errors,blocked},null,2));console.log(JSON.stringify({out,errors,blocked,saveResume:true,fullReconstructionReady:false}));
 }finally{await context.close();await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
