/* Real PDF decode with controlled completion order; existing UI, fresh offline profile. */
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const origin=process.env.APP_URL||'http://127.0.0.1:65372',out=process.env.OUTPUT_DIR||'/tmp/webcad-reference-race';assert.match(origin,/^http:\/\/127\.0\.0\.1:\d+$/);fs.mkdirSync(out,{recursive:true});
const raw=fs.readFileSync('local-preview/frozen-page-2.json'),pdf=fs.readFileSync('tools/tests/fixtures/madori-3f.pdf');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']}),context=await browser.newContext({viewport:{width:1440,height:1000}}),errors=[],blocked=[],cases=[];
 try{await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===origin&&!u.pathname.startsWith('/api/'))return r.continue();blocked.push(u.origin+u.pathname);return r.abort();});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(origin);await p.waitForSelector('#app-loading',{state:'hidden',timeout:60000});await p.evaluate(()=>{closePresetChoice();window.__jobs=[];const decode=PdfPages.renderPages;PdfPages.renderPages=async(...args)=>{const pages=await decode(...args);return new Promise(resolve=>__jobs.push({pages,resolve}));};});
 const before=await p.evaluate(()=>({data:serializeDataSnapshot(),history:JSON.stringify(HISTORY),redo:JSON.stringify(REDO_HISTORY),dirty:DIRTY}));
 async function load(){if(await p.locator('#plan-import-modal').isVisible())await p.locator('#plan-import-modal .unity-render-close').click();await p.locator('#import-file').setInputFiles({name:'fixed.json',mimeType:'application/json',buffer:raw});await p.waitForSelector('[data-scene-full-status]');await p.evaluate(()=>window.__body=PlanImport.state.result);}
 async function start(name){if(!await p.locator('[data-scene-reference]').evaluate(e=>e.open))await p.locator('[data-scene-reference] > summary').click();const index=await p.evaluate(()=>__jobs.length);await p.getByLabel('照合するPDFか画像',{exact:true}).setInputFiles({name,mimeType:'application/pdf',buffer:pdf});await p.waitForFunction(i=>__jobs.length===i+1,index);return index;}
 async function complete(index){await p.evaluate(i=>__jobs[i].resolve(__jobs[i].pages),index);}
 async function mapping(){await p.locator('[data-scene-review-search]').fill('obj-refrigerator');const g=p.locator('[data-scene-group="objects:obj-refrigerator"]');if(!await g.evaluate(e=>e.open))await g.locator('summary').click();await p.locator('[data-scene-mapping="obj-refrigerator"]').click();await p.locator('[data-scene-sizing]').selectOption('fit-source');await p.locator('[data-scene-appearance]').selectOption('match-diagram-appearance');await p.evaluate(()=>window.__editor=PlanImport.state.mappingEditor);}
 async function retained(){assert.equal(await p.evaluate(()=>PlanImport.state.result===__body),true);}
 await load();let job=await start('mapping-pending.pdf');await mapping();await complete(job);await p.waitForFunction(()=>document.getElementById('scene-review-file-status').textContent.includes('反映していません'));await retained();assert.equal(await p.evaluate(()=>PlanImport.state.mappingEditor===__editor),true);assert.equal(await p.locator('[data-scene-sizing]').inputValue(),'fit-source');assert.equal(await p.locator('[data-scene-appearance]').inputValue(),'match-diagram-appearance');await p.screenshot({path:path.join(out,'pending-pdf-keeps-unsaved-mapping.png')});cases.push('mapping inputs and body preserved');await p.locator('[data-scene-mapping-cancel]').click();
 await load();job=await start('mapping-cancelled.pdf');await mapping();await p.locator('[data-scene-mapping-cancel]').click();await complete(job);await p.waitForFunction(()=>document.getElementById('scene-review-file-status').textContent.includes('反映していません'));await retained();cases.push('mapping cancellation does not revive older PDF');
 await load();const first=await start('older.pdf'),second=await start('newer.pdf');await complete(second);await p.waitForFunction(()=>document.querySelector('[data-scene-reference-page]').textContent.includes('newer.pdf'));await p.evaluate(()=>window.__body=PlanImport.state.result);await complete(first);await retained();assert.match(await p.locator('[data-scene-reference-page]').innerText(),/newer.pdf/);cases.push('reverse PDF order keeps newer file');
 await load();job=await start('closed.pdf');await p.locator('#plan-import-modal .unity-render-close').click();await complete(job);assert.equal(await p.evaluate(()=>PlanImport.state.result),null);assert.equal(await p.locator('#plan-import-modal').isVisible(),false);cases.push('close discards pending PDF');
 await load();job=await start('floor-roundtrip.pdf');await p.locator('#floor-sel').selectOption('2');await p.locator('#floor-sel').selectOption('1');await complete(job);await p.waitForFunction(()=>document.getElementById('scene-review-file-status').textContent.includes('反映していません'));await retained();cases.push('floor roundtrip invalidates operation generation');
 // The ordinary Apply transaction must not be undone by delayed PDF completion.
 await load();await p.locator('[data-scene-partial-enable]').check();if(!await p.locator('[data-scene-partial-options]').evaluate(e=>e.open))await p.locator('[data-scene-partial-options] > summary').click();for(const id of await p.locator('[data-scene-partial-object]').evaluateAll(es=>es.map(e=>e.getAttribute('data-scene-partial-object'))))await p.locator('[data-scene-partial-object="'+id+'"]').uncheck();await p.locator('[data-scene-partial-structure="wall-west"]').check();await p.locator('[data-scene-partial-accept]').check();assert.equal(await p.locator('#plan-import-apply').isEnabled(),true);await p.evaluate(()=>window.__body=PlanImport.state.result);job=await start('after-apply.pdf');await p.locator('#plan-import-apply').click();await p.waitForFunction(()=>PlanImport.state.result?.scenePartialOpened===true);assert.equal(await p.locator('#plan-import-modal').isVisible(),false);await complete(job);await retained();assert.equal(await p.evaluate(()=>PlanImport.state.result.scenePartialOpened),true);assert.equal(await p.locator('#plan-import-modal').isVisible(),false);await p.screenshot({path:path.join(out,'late-pdf-cannot-reopen-applied-review.png')});cases.push('successful Apply remains opened and dialog stays hidden');
 assert.deepEqual(await p.evaluate(()=>({data:serializeDataSnapshot(),history:JSON.stringify(HISTORY),redo:JSON.stringify(REDO_HISTORY),dirty:DIRTY})),before);assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);const result={cases,originalPlanPreserved:true,paidCalls:0,errors,blocked};fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }finally{await context.close();await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
