const test=require('node:test'),assert=require('node:assert/strict'),Scene=require('../../assets/js/scene-ir.js'),API=require('../../assets/js/editor-internal-api.js'),Height=require('../../assets/js/height-model.js'),{runtime}=require('./scene-fixtures.cjs');
const raw=require('../../local-preview/frozen-page-2.json'),registry=runtime().PlanImport.sceneCatalogue(),target={heightDefaults:{modelVersion:2,wallHeight:2400,floorThickness:180,floorRaise:0,floorRaiseSet:true},floors:{}};
function options(source=raw,ids=['wall-north','wall-east']){return {registry,materialization:'bounded-v3',partialSelection:Scene.createPartialSelection(source,[],true,ids),bindingDecisions:[{sourceSnapshot:JSON.stringify(source.rooms[0]),binding:{id:'ldk-display',sourceEntityId:'room-ldk',catalogId:{value:null,status:'unknown'},sizingPolicy:'native',appearanceMode:'match-diagram-appearance'}}]};}
const errors=r=>r.diagnostics.filter(d=>d.severity==='error');
test('three north/east windows use the common native normalizer, explicit unknown defaults and exact host gap geometry',()=>{
 const source=structuredClone(raw),before=JSON.stringify(source),r=Scene.previewSnapshot(source,target,options(source));assert.deepEqual(errors(r),[]);assert.deepEqual(r.plan.items.map(it=>it.id),['window-north-kitchen','window-north-sofa','window-east-living']);assert.equal(r.plan.walls.length,2);
 for(const it of r.plan.items){const e=source.openings.find(e=>e.id===it.id),w=r.plan.walls.find(w=>w.id===it.openingHostWallId),info=require('../../assets/js/scene-opening-geometry.js').explicitHostWallInfo(it,[w]);assert.ok(info);assert.equal(it.w,Math.hypot(e.end.value.x-e.start.value.x,e.end.value.y-e.start.value.y));assert.deepEqual([it.windowHeight,it.windowSill,it.windowKind],[1200,900,'fix']);assert.equal(e.heightMm.status,'unknown');assert.equal(e.sillMm.value,null);const normalized=Height.sceneRuntime(target).normalizeWindow(structuredClone(it),w);assert.deepEqual(normalized,it);}
 assert.equal(r.defaults.filter(d=>d.path.startsWith('openings')&&d.provenance==='editor-default').length,9);assert.equal(JSON.stringify(source),before);assert.ok(r.deferredEntities.some(e=>e.id==='window-south-stair'));assert.equal(r.plan.walls.some(w=>w.id==='wall-south'),false);
});
test('PlanImport and API compile the explicit snapshot even when live DATA cannot be read',()=>{
 const c=runtime();Object.defineProperty(c,'DATA',{get(){throw Error('live DATA read');}});const opts=options(),a=API.previewSceneIRSnapshot(raw,target,opts),b=c.PlanImport.previewSceneIR(raw,{...opts,targetSnapshot:target});assert.equal(JSON.stringify(a.plan),JSON.stringify(b.plan));assert.equal(JSON.stringify(a.diagnostics),JSON.stringify(b.diagnostics));
});
test('floor settings, native rounding and conservative raised-finish/host limits match without normalizing raw source',()=>{
 const high={...target,heightDefaults:{...target.heightDefaults,perFloor:true},floors:{2:{wallHeight:3000.4,floorRaise:0}}};let r=Scene.previewSnapshot(raw,high,options());assert.deepEqual(errors(r),[]);assert.ok(r.plan.walls.every(w=>w.wallHeight===3000));
 for(const height of [2000,2149]){const low={...high,floors:{2:{wallHeight:height,floorRaise:0}}};const failed=Scene.previewSnapshot(raw,low,options());assert.equal(failed.plan.items.length,0);assert.ok(errors(failed).some(d=>d.code==='window_vertical_clamp'));}
 const boundary={...high,floors:{2:{wallHeight:2149.6,floorRaise:0}}};assert.equal(Scene.previewSnapshot(raw,boundary,options()).plan.items.length,3);
 const lifted={...high,floors:{2:{wallHeight:2400,floorRaise:300}}};assert.ok(errors(Scene.previewSnapshot(raw,lifted,options())).some(d=>d.code==='window_vertical_clamp'));
 const decimal=structuredClone(raw);decimal.openings[0].heightMm={value:1200.4,status:'observed',source:'synthetic measured value'};const original=JSON.stringify(decimal);assert.ok(errors(Scene.previewSnapshot(decimal,target,options(decimal))).some(d=>d.code==='window_vertical_clamp'));assert.equal(JSON.stringify(decimal),original);
});
test('floor/height changes invalidate content revision and accepted review, while full legitimate unresolved remain',async()=>{
 const state={snapshot:structuredClone(target),source:structuredClone(raw),options:{},camera:{view:'3d-ext'},state:{history:[],redo:[],dirty:false}},api=API.create({catalogue:()=>registry,readScene:()=>state,renderPreview:async()=>({})}),scene=api.get_scene({planId:'draft'});state.snapshot.floors={2:{wallHeight:3000}};
 await assert.rejects(api.preview_patch({planId:'draft',baseRevision:scene.revision,selectedObjectIds:[],selectedEntityIds:['wall-north'],displayBindings:[],incompleteConfirmed:true}),e=>e.code==='stale_revision');
 const opts=options(),first=Scene.previewSnapshot(raw,target,opts),review={acceptedReviewGroups:first.reviewGroups.map(g=>g.id),reviewedEntities:Object.fromEntries(first.reviewGroups.map(g=>[g.entityId,g.reviewKey]))};assert.equal(Scene.previewSnapshot(raw,target,{...opts,...review}).canApply,true);const changed=Scene.previewSnapshot(raw,{...target,heightDefaults:{...target.heightDefaults,wallHeight:3000}},{...opts,...review});assert.equal(changed.canApply,false);
 const full=Scene.previewSnapshot(raw,target,{...opts,partialSelection:null});assert.equal(full.canApply,false);assert.equal(errors(full).some(d=>d.code==='missing_window_runtime'),false);assert.ok(errors(full).some(d=>d.code==='wrong_adjacent_room'&&d.path==='openings[5].adjacentRoomIds'));assert.ok(errors(full).some(d=>d.code==='unsupported_opening_mechanism'));assert.ok(errors(full).some(d=>d.path==='openings[7].hostWallId'));assert.ok(errors(full).some(d=>d.path==='openings[8].hostWallId'));assert.ok(errors(full).some(d=>d.code==='unsupported_stair_reconstruction'));
});
test('an unhosted known gap on a selected wall is included as unresolved; no host is guessed or filled over',()=>{
 const source=structuredClone(raw);source.openings.push({id:'unhosted-west',floor:{value:2,status:'observed',source:'synthetic'},hostWallId:{value:null,status:'unknown'},adjacentRoomIds:{value:['room-ldk',null],status:'observed',source:'synthetic'},start:{value:{x:0,y:100},status:'observed',source:'synthetic'},end:{value:{x:0,y:600},status:'observed',source:'synthetic'},mechanism:{value:'window',status:'observed',source:'synthetic'}});const before=JSON.stringify(source),opts=options(source,['wall-west']);assert.ok(opts.partialSelection.entityIds.includes('unhosted-west'));const r=Scene.previewSnapshot(source,target,opts);assert.ok(errors(r).some(d=>d.code==='unknown_required_geometry'));assert.equal(r.canApply,false);assert.equal(JSON.stringify(source),before);
});

test('snapshot global and per-floor heights equal the actual native plan loader across missing invalid rounded and bounded values',()=>{
 const vm=require('node:vm'),{topLevelFunction,topLevelVar}=require('./height-runtime.cjs'),source=structuredClone(raw),opts=options(source,['wall-west']);
 function native(plan){const c=runtime();c.DATA=structuredClone(plan);vm.runInContext(['DEFAULT_WALL_H_MM','WALL_H_MIN','DEFAULT_FLOOR_RAISE_MM'].map(topLevelVar).concat(['clampWallHeightMm','resetHeightGlobalsForPlanLoad','ensureHeightDefaults'].map(topLevelFunction)).join('\n'),c);c.resetHeightGlobalsForPlanLoad();c.ensureHeightDefaults();return c;}
 const values=[undefined,null,0,-1,'invalid','4500',1000,1799.49,1799.5,1800,1800.49,1800.5,3999.49,3999.5,4000,4000.5,4500,6000];
 for(const value of values){const snapshot={...target,heightDefaults:{...target.heightDefaults,wallHeight:value}},before=JSON.stringify(snapshot),r=Scene.previewSnapshot(source,snapshot,opts),c=native(snapshot);assert.equal(r.plan.walls[0].wallHeight,c.defaultWallHeightMmForFloor(2),'global '+String(value));assert.equal(Height.sceneRuntime(snapshot).defaultWallHeightMmForFloor(2),c.defaultWallHeightMmForFloor(2));assert.equal(JSON.stringify(snapshot),before);}
 for(const value of [undefined,null,0,-1,'invalid',100,299.49,299.5,300,1000,4500,5999.49,5999.5,6000,6000.5,6500]){const snapshot={...target,heightDefaults:{...target.heightDefaults,perFloor:true,wallHeight:4500},floors:{2:{wallHeight:value}}},r=Scene.previewSnapshot(source,snapshot,opts),c=native(snapshot);assert.equal(r.plan.walls[0].wallHeight,c.defaultWallHeightMmForFloor(2),'perFloor '+String(value));}
 for(const snapshot of [{},{heightDefaults:null},{heightDefaults:[]},{heightDefaults:{wallHeight:'invalid'}},{heightDefaults:{perFloor:true,wallHeight:4500},floors:null},{heightDefaults:{perFloor:true,wallHeight:4500},floors:{2:null}}]){const before=JSON.stringify(snapshot),r=Scene.previewSnapshot(source,snapshot,opts),c=native(snapshot);assert.equal(r.plan.walls[0].wallHeight,c.defaultWallHeightMmForFloor(2));assert.equal(JSON.stringify(snapshot),before);}
 assert.equal(Scene.previewSnapshot(source,{...target,heightDefaults:{...target.heightDefaults,wallHeight:4500}},opts).plan.walls[0].wallHeight,4000);assert.equal(Scene.previewSnapshot(source,{...target,heightDefaults:{...target.heightDefaults,wallHeight:1000}},opts).plan.walls[0].wallHeight,1800);
});
