/* Real frozen source, existing review UI + native isolated editor, no AI or external requests. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const origin=process.env.APP_URL||'http://127.0.0.1:65372',out=process.env.OUTPUT_DIR||'/tmp/webcad-storage-sink-native';assert.match(origin,/^http:\/\/127\.0\.0\.1:\d+$/);fs.mkdirSync(out,{recursive:true});
const ids=['obj-west-cabinet','obj-kitchen-base','obj-tv-console','obj-kitchen-sink'];
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']}),context=await browser.newContext({viewport:{width:1440,height:1000}}),errors=[],blocked=[];
 try{
 await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===origin&&!u.pathname.startsWith('/api/'))return r.continue();blocked.push(u.origin+u.pathname);return r.abort();});
 const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(origin+'/?internalAPI=1');await p.waitForSelector('#app-loading',{state:'hidden',timeout:60000});
 await p.evaluate(()=>{closePresetChoice();DATA.items=[];DATA.walls=[];DATA.rooms=[];DATA.heightDefaults={modelVersion:2,floorThickness:180,floorRaise:27,floorRaiseSet:true};DATA.floors={};HISTORY.length=0;REDO_HISTORY.length=0;DIRTY=false;document.getElementById('floor-sel').value='2';onFloorChange(2);setView('3d-ext');});
 await p.waitForFunction(()=>ren&&!hasPendingGltfModels()&&!_gltfRebuildTimer);
 const audit=[];for(const name of ['cabinetCertificate','sideboardCertificate','sinkCertificate']){
  const cert=await p.evaluate(name=>{const c=SceneCatalogue[name];ensureGltfModel(c.url);return c;},name);await p.waitForFunction(c=>!!_modelCache[c.url]&&!hasPendingGltfModels(),cert);
  for(const side of ['front','back','top']){const shot=await p.evaluate(({cert,side})=>{const model=makeGltfBoxFitClone(cert.url,cert.w/1000,cert.h/1000,cert.d/1000,null),scene=new THREE.Scene();scene.background=new THREE.Color('#e1e5e8');scene.add(model);scene.add(new THREE.HemisphereLight(0xffffff,0x647080,2));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(3,5,4);scene.add(light);const cam=new THREE.PerspectiveCamera(35,ren.domElement.width/ren.domElement.height,.01,100);if(side==='top'){cam.position.set(0,4,0);cam.up.set(0,0,-1);}else cam.position.set(.7,1.7,side==='front'?3.5:-3.5);cam.lookAt(0,.4,0);cam.updateMatrixWorld();ren.render(scene,cam);return {png:ren.domElement.toDataURL(),yaw:ModelQuality.sourceYaw(cert.url)};},{cert,side});fs.writeFileSync(path.join(out,name+'-'+side+'.png'),Buffer.from(shot.png.split(',')[1],'base64'));assert.equal(shot.yaw,cert.sourceYaw);audit.push({name,cert,side,yaw:shot.yaw});}
 }
 await p.getByRole('button',{name:'固定raw 2Fの部分プレビュー（AIなし・未完成）'}).click();await p.waitForSelector('[data-scene-full-status]');
 const integrity=()=>p.evaluate(()=>({data:serializeDataSnapshot(),history:JSON.stringify(HISTORY),redo:JSON.stringify(REDO_HISTORY),dirty:DIRTY,source:JSON.stringify(PlanImport.state.result.sceneIR),raw:JSON.stringify(PlanImport.state.result.extraction),storage:Object.fromEntries(Object.entries(localStorage))}));const before=await integrity();
 const mappings=[];for(const id of [...ids,'room-ldk']){const isRoom=id==='room-ldk';await p.locator('[data-scene-review-search]').fill(id);const g=p.locator('details[data-scene-group="'+(isRoom?'rooms':'objects')+':'+id+'"]');await g.locator('summary').click();await p.locator('[data-scene-mapping="'+id+'"]').click();if(!isRoom){const model=await p.evaluate(id=>id==='obj-kitchen-sink'?SceneCatalogue.sinkCertificate.id:SceneCatalogue.cabinetCertificate.id,id);await p.locator('[data-scene-catalogue]').selectOption(model);await p.locator('[data-scene-sizing]').selectOption('fit-source');mappings.push({id,model});}await p.locator('[data-scene-appearance]').selectOption('match-diagram-appearance');await p.locator('[data-scene-mapping-confirm]').click();}
 assert.deepEqual(await integrity(),before);await p.screenshot({path:path.join(out,'explicit-mapping-review.png')});
 const result=await p.evaluate(async ids=>{const s=WebCADInternalAPI.get_scene({planId:'host-draft'});return WebCADInternalAPI.preview_patch({planId:'host-draft',baseRevision:s.revision,selectedObjectIds:ids,displayBindings:[],incompleteConfirmed:true});},ids);assert.equal(result.rendered,true,JSON.stringify(result.diagnostics));assert.equal(result.fullReconstructionReady,false);
 const frame=p.frames().find(f=>f.url().includes('editorPane='+result.preview.paneId));assert.ok(frame);await frame.waitForFunction(()=>ren&&!hasPendingGltfModels()&&!_gltfRebuildTimer,null,{timeout:60000});
 const rendered=await frame.evaluate(()=>{const source=DATA.sceneReconstructionReports[0].originalIR,rows=DATA.items.map(item=>{const roots=getSelectableRoots3D(item),box=new THREE.Box3(),meshes=[];roots.forEach(r=>{r.updateMatrixWorld(true);box.union(new THREE.Box3().setFromObject(r));r.traverse(n=>{if(n.isMesh){const axis=new THREE.Vector3(0,0,item.type==='fmp-Sink03'?-1:1).transformDirection(n.matrixWorld);meshes.push({front:axis.toArray(),color:n.material.color?.getHexString(),channel:n.material.userData?.finishChannel});}});});return {item,source:source.objects.find(e=>e.id===item.id),bounds:{min:box.min.toArray().map(v=>v*1000),max:box.max.toArray().map(v=>v*1000)},meshes};});const camera=new THREE.PerspectiveCamera(40,ren.domElement.width/ren.domElement.height,.01,100);camera.position.set(8,11,8);camera.lookAt(2.8,3,1.8);camera.updateMatrixWorld();ren.render(sc3,camera);return {plan:EditorPane.snapshot(),rows,png:ren.domElement.toDataURL()};});
 fs.writeFileSync(path.join(out,'four-source-objects-native.png'),Buffer.from(rendered.png.split(',')[1],'base64'));delete rendered.png;assert.equal(rendered.rows.length,4);
 for(const r of rendered.rows){const fp=r.source.sourceFootprint.value,b=r.bounds,expected=[fp.center.x-fp.sizeMm.w/2,fp.center.x+fp.sizeMm.w/2,fp.center.y-fp.sizeMm.d/2,fp.center.y+fp.sizeMm.d/2];[b.min[0],b.max[0],b.min[2],b.max[2]].forEach((v,i)=>assert.ok(Math.abs(v-expected[i])<.01,JSON.stringify(r)));for(const m of r.meshes){assert.ok(Math.abs(m.front[0]-r.source.frontDirection.value.x)<1e-6&&Math.abs(m.front[2]-r.source.frontDirection.value.y)<1e-6);assert.equal(m.color,r.source.appearance.diagramColor.value.slice(1).toLowerCase());}assert.equal(r.item.h,undefined);assert.equal(r.source.heightMm.status,'unknown');}
 // Close-up of actual native sink/counter: height relation remains a display assumption.
 const close=await frame.evaluate(()=>{const c=new THREE.PerspectiveCamera(35,ren.domElement.width/ren.domElement.height,.01,100);c.position.set(-.5,4.8,3.9);c.lookAt(1.85,3.35,1.5);c.updateMatrixWorld();ren.render(sc3,c);return ren.domElement.toDataURL();});fs.writeFileSync(path.join(out,'sink-counter-display-height-assumption.png'),Buffer.from(close.split(',')[1],'base64'));
 assert.equal(await frame.evaluate(async()=>{try{await EditorPane.save();return false;}catch{return true;}}),true);
 await p.addScriptTag({url:origin+'/assets/js/plan-repository-lab.js'});const namespace='webcad-plan-library-lab-storage-audit-'+crypto.randomUUID();const saved=await p.evaluate(async({namespace,plan})=>{const repo=PlanRepositoryLab.create({name:namespace});await repo.save({planId:'audit',operationId:'review',baseRevisionId:null,baseGeneration:0,payload:plan,name:'Test-only storage'});await repo.close();const next=PlanRepositoryLab.create({name:namespace}),v=await next.read('audit');await next.close();await new Promise((resolve,reject)=>{const r=indexedDB.deleteDatabase(namespace);r.onsuccess=resolve;r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('test DB blocked'));});return v.payload;},{namespace,plan:rendered.plan});assert.deepEqual(saved,rendered.plan);
 assert.deepEqual(await integrity(),before);await p.evaluate(()=>ParallelEditors.close());assert.deepEqual(await integrity(),before);assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);
 fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({audit,mappings,api:result,rendered,sourcePreserved:true,originalPlanPreserved:true,isolatedSaveRoundtrip:true,errors,blocked,paidCalls:0,fullReconstructionReady:false},null,2));console.log(JSON.stringify({nativeObjects:4,sourcePreserved:true,worldEnvelopes:true,sourceFronts:true,diagramColors:true,isolatedSaveRoundtrip:true,errors,blocked,fullReconstructionReady:false,out}));
 }finally{await context.close();await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
