const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{createRequire}=require('node:module');
const Scene=require('../../assets/js/scene-ir-v3.js'),Overlay=require('../../assets/js/scene-source-overlay.js');
const f=value=>({value,status:'observed',source:'synthetic direction measurement'}),u=()=>({value:null,status:'unknown'});
function fixture(axis={x:.9659,y:-.2588}){return {sceneVersion:3,units:'mm',coordinateSystem:'x-east-y-south-clockwise',annotations:[],walls:[],rooms:[{id:'room',floor:f(1),boundaryBasis:f('clear-face'),shape:f({kind:'rectUnion',rectangles:[{x:0,y:0,w:4000,d:4000}]})}],openings:[],objects:[{id:'desk',objectType:f('desk'),semanticExtent:f('asset'),placement:f({domain:'room',roomId:'room'}),sourceFootprint:f({center:{x:1500,y:1500},sizeMm:{w:700,d:500},axisX:axis}),frontDirection:u(),heightMm:u()}],siteRegions:[],buildingFootprints:[],bindings:[],connections:[]};}
const options={materialization:'bounded-v3',registry:{get:()=>({id:'desk-asset',kind:'desk',w:700,d:500,h:730,semanticExtent:'asset',front:'+Z',finishChannels:[]})},targetPlan:{heightDefaults:{modelVersion:2,floorThickness:180}},defaultFloorOffset:()=>0};
const approved=s=>{const first=Scene.compile(s,options);return Scene.compile(s,{...options,acceptedReviewGroups:first.reviewGroups.map(g=>g.id),reviewedEntities:Object.fromEntries(first.reviewGroups.map(g=>[g.entityId,g.reviewKey]))});};
test('bounded rounded footprint is valid with explicit derived warning and unchanged raw/evidence; mapping remains required',()=>{
 const s=fixture(),raw=JSON.stringify(s),r=Scene.compile(s,options);assert.equal(r.valid,true);assert.equal(r.canApply,false);assert.ok(r.diagnostics.some(d=>d.code==='mapping_unresolved'));assert.equal(JSON.stringify(s),raw);assert.equal(JSON.stringify(r.sourceScene),raw);const d=r.diagnostics.find(d=>d.code==='rounded_direction_derived');assert.deepEqual(d.original,s.objects[0].sourceFootprint.value.axisX);assert.equal(d.path,'objects[0].sourceFootprint.axisX');assert.equal(d.basis,'four-decimal-component-rounding-bound');assert.ok(Math.abs(Math.hypot(d.derived.x,d.derived.y)-1)<1e-15);assert.ok(Math.abs(d.sourceNorm-1)>1e-6);assert.equal(r.evidence.find(e=>e.path==='scene.objects[0].sourceFootprint').value.axisX.x,.9659);
 const shape=Overlay.primitives({originalIR:s,sourcePreview:r.sourcePreview},true).find(p=>p.id==='desk');assert.ok(Math.abs(Math.hypot(shape.points[1].x-shape.points[0].x,shape.points[1].y-shape.points[0].y)-700)<1e-9);assert.ok(Math.abs(Math.hypot(shape.points[2].x-shape.points[1].x,shape.points[2].y-shape.points[1].y)-500)<1e-9);assert.equal(JSON.stringify(s),raw);
});
test('same source can materialize only after independent catalogue/datum reviews; angle and dimensions are unchanged',()=>{
 const s=fixture();s.bindings=[{id:'map',sourceEntityId:'desk',catalogId:f('desk-asset'),sizingPolicy:'native'}];const r=approved(s);assert.equal(r.canApply,true,JSON.stringify(r.diagnostics));assert.equal(r.plan.items[0].w,700);assert.equal(r.plan.items[0].d,500);assert.ok(Math.abs(r.plan.items[0].rot-Math.atan2(-.2588,.9659)*180/Math.PI)<1e-12);assert.deepEqual(r.sourceScene,s);
});
test('rounding allowance is general, bounded and refuses zero/nonfinite/large true non-unit inputs',()=>{
 for(const degrees of [-179,-91,-65,-45,-30,-15,0,15,30,45,65,91,179]){const a=degrees*Math.PI/180,v={x:Number(Math.cos(a).toFixed(4)),y:Number(Math.sin(a).toFixed(4))},d=Scene.deriveDirection(v);assert.ok(d,JSON.stringify(v));assert.ok(Math.abs(Math.hypot(d.x,d.y)-1)<1e-15);assert.ok(Math.abs(Math.atan2(d.y,d.x)-Math.atan2(v.y,v.x))<1e-15);assert.equal(Scene.compile(fixture(v)).valid,true);}
 const limit=Scene.directionRoundingLimit;assert.ok(Scene.deriveDirection({x:1+limit*.99,y:0}));assert.equal(Scene.deriveDirection({x:1+limit*1.01,y:0}),null);
 for(const v of [{x:0,y:0},{x:NaN,y:0},{x:Infinity,y:0},{x:1e6,y:0},{x:1e308,y:1e308},{x:1.01,y:0},{x:.99,y:0},{x:1,y:1}]){assert.equal(Scene.deriveDirection(v),null);assert.equal(Scene.compile(fixture(v)).valid,false);}
});
const hingeFile=path.join(__dirname,'scene-ir-v3-hinge-pivots.test.cjs'),prefix=fs.readFileSync(hingeFile,'utf8').split("test(")[0],m={exports:{}};vm.runInNewContext(prefix+'\nmodule.exports={fixture,reviewed};',{require:createRequire(hingeFile),module:m,exports:m.exports});
test('normalized leaf axes preserve start/end hinge and both swing signs without changing source gap/leaf width',()=>{
 for(const jamb of ['start','end'])for(const sign of [1,-1]){const s=m.exports.fixture(jamb,50,0),leaf=s.openings[0].leaves[0];leaf.closedAxis.value.x*=.99995;leaf.swingSide.value.y*=.99995;leaf.swingSide.value.y=Math.abs(leaf.swingSide.value.y)*sign;leaf.angleDeg.value=Math.sign(leaf.closedAxis.value.x*leaf.swingSide.value.y)*90;const raw=JSON.stringify(s),r=m.exports.reviewed(s);assert.equal(r.canApply,true,JSON.stringify(r.diagnostics));assert.equal(JSON.stringify(s),raw);assert.equal(r.plan.items[0].openingSourceGeometry.leafWidthMm,900);assert.equal(r.plan.items[0].w,1000);const exact=m.exports.fixture(jamb,50,0);exact.openings[0].leaves[0].swingSide.value.y=sign;exact.openings[0].leaves[0].angleDeg.value=Math.sign(exact.openings[0].leaves[0].closedAxis.value.x*sign)*90;assert.deepEqual(r.plan.items[0].openingSourceGeometry,m.exports.reviewed(exact).plan.items[0].openingSourceGeometry);}
});
test('bounded normalization does not bypass orthogonality, signed angle, source gap or unknown facts',()=>{
 for(const change of [l=>{l.closedAxis.value={x:.99995,y:0};l.swingSide.value={x:.001,y:.99995};},l=>{l.closedAxis.value.x*=.99995;l.angleDeg.value=-l.angleDeg.value;}]){const s=m.exports.fixture();change(s.openings[0].leaves[0]);const r=Scene.compile(s);assert.equal(r.valid,false);assert.ok(r.diagnostics.some(d=>d.code==='source_angle_direction_conflict'));}
 const s=m.exports.fixture();s.openings[0].leaves[0].closedAxis=u();const r=m.exports.reviewed(s);assert.equal(r.canApply,false);assert.equal(r.sourceScene.openings[0].leaves[0].closedAxis.value,null);assert.ok(r.diagnostics.some(d=>d.code==='unknown_required_geometry'));
 const crossed=m.exports.fixture();crossed.openings[0].leaves[0].leafWidthMm.value=1100;crossed.openings[0].leaves[0].closedAxis.value.x*=.99995;assert.equal(m.exports.reviewed(crossed).canApply,false);
});

test('source-only browser compiler derives rounded directions independently of physical materializer loading',()=>{const c=vm.createContext({});c.self=c;vm.runInContext(fs.readFileSync(path.join(__dirname,'../../assets/js/scene-ir-v3.js'),'utf8'),c);const s=fixture(),r=c.SceneIRV3.compile(s);assert.equal(r.valid,true);assert.equal(r.canApply,false);assert.ok(r.diagnostics.some(d=>d.code==='rounded_direction_derived'));assert.equal(JSON.stringify(r.sourceScene),JSON.stringify(s));});
