const test=require('node:test'),assert=require('node:assert/strict'),Catalogue=require('../../assets/js/scene-catalogue.js'),Scene=require('../../assets/js/scene-ir-v3.js');
const f=value=>({value,status:'observed',source:'independent synthetic coordinate contract'}),u={value:null,status:'unknown'};
function scene(front){return {sceneVersion:3,units:'mm',coordinateSystem:'x-east-y-south-clockwise',annotations:[],walls:[],rooms:[{id:'room',floor:f(1),shape:f({kind:'rectUnion',rectangles:[{x:0,y:0,w:3000,d:3000}]}),boundaryBasis:f('clear-face')}],openings:[],objects:[{id:'object',objectType:f('chair'),semanticExtent:f('asset'),placement:f({domain:'room',roomId:'room'}),sourceFootprint:f({center:{x:1000,y:1200},sizeMm:{w:435,d:475},axisX:{x:1,y:0}}),frontDirection:f(front),heightMm:u,appearance:{diagramColor:f('#D6BA92')}}],siteRegions:[],buildingFootprints:[],bindings:[],connections:[]};}
const model={id:'chair',kind:'chair',w:475,d:435,h:703,front:'+Z',semanticExtent:'asset',finishChannels:[{key:'body'}]},registry={get:()=>model};
function run(s,policy='fit-source',extra={}){const obj=s.objects[0],binding={id:'mapping',sourceEntityId:obj.id,catalogId:f('chair'),sizingPolicy:policy,appearanceMode:'match-diagram-appearance'},opts={materialization:'bounded-v3',registry,targetPlan:{heightDefaults:{modelVersion:2,floorThickness:180}},defaultFloorOffset:()=>0,bindingDecisions:[{binding,sourceSnapshot:JSON.stringify(obj)}],...extra};const first=Scene.compile(s,opts);return Scene.compile(s,{...opts,acceptedReviewGroups:first.reviewGroups.map(g=>g.id),reviewedEntities:Object.fromEntries(first.reviewGroups.map(g=>[g.entityId,g.reviewKey]))});}
const sorted=pts=>pts.map(p=>[p.x,p.y].map(v=>Math.round(v*1e7)/1e7)).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);
function corners(cx,cy,w,d,a,fx=1,fy=1){const c=Math.cos(a),s=Math.sin(a);return [[-1,-1],[1,-1],[1,1],[-1,1]].map(([sx,sy])=>{const x=sx*w/2*fx,y=sy*d/2*fy;return {x:cx+x*c-y*s,y:cy+x*s+y*c};});}
test('all quarter-turn/reflection bases preserve non-square world corners without changing source facts',()=>{for(const sourceAngle of [0,.37,-1.1])for(let q=0;q<4;q++)for(const fx of [-1,1])for(const fy of [-1,1]){const fp={center:{x:810,y:-220},sizeMm:{w:435,d:475},axisX:{x:Math.cos(sourceAngle),y:Math.sin(sourceAngle)}},before=JSON.stringify(fp),rot=sourceAngle+q*Math.PI/2,fit=Catalogue.deriveFootprintFit(fp,rot*180/Math.PI);assert.ok(fit);assert.equal(fit.w,q%2?475:435);assert.equal(fit.d,q%2?435:475);assert.deepEqual(sorted(corners(810,-220,fit.w,fit.d,rot,fx,fy)),sorted(corners(810,-220,435,475,sourceAngle)));assert.equal(JSON.stringify(fp),before);}});
test('bounded compiler exchanges local dimensions around same center and preserves front, raw, appearance scope reviews',()=>{for(const front of [{x:1,y:0},{x:-1,y:0},{x:0,y:1},{x:0,y:-1}]){const s=scene(front),before=JSON.stringify(s),r=run(s);assert.equal(r.canApply,true,JSON.stringify(r.diagnostics));const it=r.plan.items[0],a=it.rot*Math.PI/180;assert.deepEqual(sorted(corners(it.x+it.w/2,it.y+it.d/2,it.w,it.d,a)),sorted(corners(1000,1200,435,475,0)));assert.ok(Math.abs(-Math.sin(a)-front.x)<1e-8);assert.ok(Math.abs(Math.cos(a)-front.y)<1e-8);assert.equal(JSON.stringify(s),before);assert.ok(r.diagnostics.some(d=>d.code==='diagram_color_scope_review'));assert.equal(r.diagnostics.some(d=>d.code==='asset_basis_exchange_review'),Math.abs(front.x)===1);}});
test('nonorthogonal/sheared fit rejected, known head-front conflicts retained, native dimensions compared in asset basis',()=>{const fp=scene({x:1,y:0}).objects[0].sourceFootprint.value;assert.equal(Catalogue.deriveFootprintFit(fp,45),null);assert.equal(Catalogue.deriveFootprintFit({...fp,axisX:{x:1,y:.3}},90),null);const s=scene({x:Math.SQRT1_2,y:Math.SQRT1_2}),r=run(s);assert.equal(r.canApply,false);assert.ok(r.diagnostics.some(d=>d.code==='asset_axis_conflict'));const aligned=scene({x:1,y:0});assert.equal(run(aligned,'native').canApply,true,'475x435 native asset rotates into source435x475');assert.equal(run(scene({x:0,y:1}),'native').canApply,false,'unswapped native sizes still differ');const bad=scene({x:1,y:0});bad.objects[0].headDirection=f({x:0,y:1});const conflicting=run(bad,'fit-source',{registry:{get:()=>({...model,head:'-Z'})}});assert.equal(conflicting.canApply,false);assert.ok(conflicting.diagnostics.some(d=>d.code==='asset_head_conflict'));});
test('room containment uses the preserved world envelope after basis exchange',()=>{const s=scene({x:1,y:0});s.rooms[0].shape=f({kind:'rectUnion',rectangles:[{x:780,y:960,w:440,d:480}]});const r=run(s);assert.equal(r.canApply,true,JSON.stringify(r.diagnostics));assert.equal(r.diagnostics.some(d=>d.code==='asset_outside_room'),false);s.rooms[0].shape.value.rectangles[0].w=420;const outside=run(s);assert.equal(outside.canApply,false);assert.ok(outside.diagnostics.some(d=>d.code==='asset_outside_room'));});
