// Independent review regressions: source identity, asynchronous file loads, and stale applicability.
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=require('node:path').resolve(__dirname,'../..');
const Scene=require(root+'/assets/js/scene-ir-v3.js'),{runtime}=require(root+'/tools/tests/scene-fixtures.cjs');
const f=value=>({value,status:'observed',source:'independent adversarial fixture'}),u=()=>({value:null,status:'unknown'});
const fixture=()=>({sceneVersion:3,units:'mm',coordinateSystem:'x-east-y-south-clockwise',annotations:[],walls:[],rooms:[{id:'room',floor:u(),shape:f({kind:'rectUnion',rectangles:[{x:0,y:0,w:4000,d:4000}]}),boundaryBasis:f('clear-face')}],openings:[],objects:[],siteRegions:[],buildingFootprints:[],bindings:[],connections:[]});
const base={materialization:'bounded-v3',registry:{get:()=>null},pageScope:['image:1:content'],defaultFloorOffset:()=>0};
function opts(s,n=2){return {...base,placementContext:Scene.createPlacementContext(s,base.pageScope,n,true)};}
function accepted(s,o){const r=Scene.compile(s,o);return {...o,acceptedReviewGroups:r.reviewGroups.map(g=>g.id),reviewedEntities:Object.fromEntries(r.reviewGroups.map(g=>[g.entityId,g.reviewKey]))};}
function setupFileRuntime(){const c=runtime(),readers=[],images=[];const get=c.document.getElementById;c.document.getElementById=id=>id==='plan-import-canvas'?null:get(id);c.FileReader=function(){readers.push(this);};c.FileReader.prototype.readAsDataURL=function(file){this.file=file;};c.Image=function(){this.naturalWidth=1000;this.naturalHeight=1000;images.push(this);};return {c,readers,images};}
test('SHA-256 matches native digest at block boundaries and for repeated multibyte/surrogate strings',()=>{for(const n of [0,1,53,54,55,56,57,62,63,64,65,119,120,121,127,128,129,1023,65536])for(const ch of ['x','日本語','😀','\ud800']){const v=ch.repeat(n);assert.equal(Scene.sourceHash(v),'sha256:'+crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex'));}assert.notEqual(Scene.sourceHash({x:123}),Scene.sourceHash({x:124}));});
test('changes anywhere in source or exact page scope invalidate previously reviewed context',()=>{for(const change of [s=>s.rooms[0].shape.value.rectangles[0].x++,s=>s.annotations.push({id:'note',kind:'label',literalText:f('new note')}),s=>s.rooms[0].floor.source='new provenance']){const s=fixture(),o=accepted(s,opts(s));change(s);const r=Scene.compile(s,o);assert.equal(r.canApply,false);assert.ok(r.diagnostics.some(d=>d.code==='stale_placement_context'));}const s=fixture(),o=accepted(s,opts(s));o.pageScope=['image:1:different crop'];assert.equal(Scene.compile(s,o).canApply,false);});
test('known observed and inferred floor labels keep precedence; mismatching destination never authorizes overwrite',()=>{for(const status of ['observed','inferred']){const s=fixture();s.rooms[0].floor={value:1,status,source:'printed label',reason:'label evidence'};const o=accepted(s,opts(s,2)),r=Scene.compile(s,o);assert.equal(r.plan.rooms[0].floor,1);assert.equal(r.canApply,false);assert.ok(r.diagnostics.some(d=>d.code==='placement_floor_conflict'));}});
test('old entity approvals and omitted mappings do not survive destination change',()=>{const s=fixture();s.objects=[{id:'desk',objectType:f('desk'),semanticExtent:f('asset'),placement:f({domain:'room',roomId:'room'}),sourceFootprint:f({center:{x:1000,y:1000},sizeMm:{w:1000,d:500},axisX:{x:1,y:0}})}];let o=accepted(s,opts(s,1));o.unresolvedDecisions=[{entityId:'desk',decision:'leave-unplaced',classification:'noncritical-decoration'}];assert.equal(Scene.compile(s,o).canApply,true);o.placementContext=opts(s,2).placementContext;const r=Scene.compile(s,o);assert.equal(r.canApply,false);assert.equal(r.acknowledgedOmissions.length,0);assert.ok(r.reviewGroups.every(g=>!g.accepted));});
test('active editor floor changing while request is pending creates no implicit destination approval',async()=>{const c=runtime(),s=fixture();c.SCENE_IR_V3_IMAGE_IMPORT=true;c.PlanImport.state.sceneIRV3Available=true;c.PlanImport.state.pages=['image'];let done;c.fetch=url=>url.endsWith('/quota')?Promise.resolve({json:async()=>({counted:false})}):new Promise(r=>done=r);const p=c.runPlanImport({extractionContract:'scene-ir-v3'});c.ST.floor=3;done({status:200,text:async()=>JSON.stringify({extractionContract:'scene-ir-v3',sceneIR:s})});await p;assert.equal(c.PlanImport.state.result.sceneOptions.placementContext,null);assert.equal(c.PlanImport.state.result.sceneCompilation.canApply,false);assert.equal(c.HISTORY.length,0);});
test('late older Image.onload cannot replace newer selected source',()=>{const {c,readers,images}=setupFileRuntime();c.onPlanImportFile({files:[{name:'older.png',type:'image/png'}]});readers[0].onload({target:{result:'image-A'}});c.onPlanImportFile({files:[{name:'newer.png',type:'image/png'}]});readers[1].onload({target:{result:'image-B'}});images[1].onload();assert.equal(c.PlanImport.state.image.src,'image-B');images[0].onload();assert.equal(c.PlanImport.state.image.src,'image-B');});
test('late file loader after Cancel/reset must not resurrect selected image',()=>{for(const cancel of ['closePlanImport','resetPlanImport']){const {c,readers,images}=setupFileRuntime();c.onPlanImportFile({files:[{name:'cancelled.png',type:'image/png'}]});readers[0].onload({target:{result:'cancelled-image'}});c[cancel]();images[0].onload();assert.equal(c.PlanImport.state.image,null);}});
test('changing crop of known-floor walls revokes source applicability until fresh extraction',()=>{const c=runtime(),s=fixture();s.rooms=[];s.walls=[{id:'wall',floor:f(1),start:f({x:0,y:0}),end:f({x:2000,y:0}),thicknessMm:f(120)}];const o=opts(s,1),first=c.PlanImport.previewSceneIR(s,o);assert.equal(first.canApply,false);assert.ok(first.defaults.some(d=>d.path==='walls[0].wallHeight'));o.acceptedReviewGroups=first.reviewGroups.map(g=>g.id);o.reviewedEntities=Object.fromEntries(first.reviewGroups.map(g=>[g.entityId,g.reviewKey]));c.PlanImport.stageSceneIR(s,o);assert.equal(c.PlanImport.state.result.sceneCompilation.canApply,true);const get=c.document.getElementById;c.document.getElementById=id=>id==='plan-import-canvas'?null:get(id);c.PlanImport.state.image={naturalWidth:1000,naturalHeight:1000};c.PlanImport.state.crop={x:0,y:0,w:100,h:100};c.planImportSelectAll();assert.equal(c.PlanImport.state.result.sceneCompilation.canApply,false);c.applyPlanImport();assert.equal(c.HISTORY.length,0);});
test('response for B cannot stage after older A callback changes visible image while B is pending',async()=>{const {c,readers,images}=setupFileRuntime();const get=c.document.getElementById;c.document.getElementById=id=>id==='scene-ir-review'?null:get(id);c.document.createElement=()=>{let drawn;return {getContext:()=>({fillRect(){},drawImage(img){drawn=img;}}),toDataURL:()=>drawn.src};};c.onPlanImportFile({files:[{name:'older.png',type:'image/png'}]});readers[0].onload({target:{result:'image-A'}});c.onPlanImportFile({files:[{name:'newer.png',type:'image/png'}]});readers[1].onload({target:{result:'image-B'}});images[1].onload();c.SCENE_IR_V3_IMAGE_IMPORT=true;c.PlanImport.state.sceneIRV3Available=true;let done,sent;c.fetch=(url,arg)=>url.endsWith('/quota')?Promise.resolve({json:async()=>({counted:false})}):new Promise(r=>{done=r;sent=JSON.parse(arg.body).images[0];});const p=c.runPlanImport({extractionContract:'scene-ir-v3'});assert.equal(sent,'image-B');images[0].onload();done({status:200,text:async()=>JSON.stringify({extractionContract:'scene-ir-v3',sceneIR:fixture()})});await p;assert.equal(c.PlanImport.state.image.src,'image-B','visible source must remain B');const result=c.PlanImport.state.result;assert.equal(result.sceneOptions.pageScope[0],'image:1:'+Scene.sourceHash(c.PlanImport.state.image.src));});
test('late PDF rendering after reset cannot repopulate canceled pages',async()=>{const {c,readers}=setupFileRuntime();let done,count=0;c.setTimeout=()=>{};c.fetch=async()=>({json:async()=>({box:null})});c.PdfPages={renderPages:()=>++count===1?new Promise(r=>done=r):Promise.resolve(['small-pdf-page'])};c.onPlanImportFile({files:[{name:'cancelled.pdf',type:'application/pdf'}]});readers[0].onload({target:{result:'pdf-data'}});c.resetPlanImport();done(['canceled-pdf-page']);await new Promise(setImmediate);assert.equal(c.PlanImport.state.pages,null);});
