const test=require('node:test'),assert=require('node:assert/strict');
const {detachSharedTextureListeners,detachRendererTextureListeners}=require('../../assets/js/parallel-editors.js');
function texture(...listeners){return {isTexture:true,_listeners:{dispose:listeners},hasEventListener(e,f){return this._listeners[e].includes(f);},removeEventListener(e,f){this._listeners[e]=this._listeners[e].filter(v=>v!==f);},dispose(){throw Error('Must not invalidate another renderer GPU texture');}};}
test('closing renderer detaches its shared-texture callback and preserves the other renderer and observers',()=>{const owner=()=>{},other=()=>{},observer=()=>{},local=texture(owner),shared=texture(owner,other,observer),geometry={isBufferGeometry:true};const pool=new Set([shared,geometry]);assert.equal(detachSharedTextureListeners(pool,new Set([owner])),1);assert.deepEqual(shared._listeners.dispose,[other,observer]);assert.deepEqual(local._listeners.dispose,[owner]);assert.ok(pool.has(geometry));});
test('a shared texture cannot be used to identify a closing renderer',()=>{const other=()=>{},shared=texture(other);assert.equal(detachSharedTextureListeners(new Set([shared]),new Set([shared])),0);assert.deepEqual(shared._listeners.dispose,[other]);});
test('an unrendered pane does not remove callbacks of an active renderer',()=>{const other=()=>{},shared=texture(other);assert.equal(detachSharedTextureListeners(new Set([shared]),new Set()),0);assert.deepEqual(shared._listeners.dispose,[other]);});
test('multiple local textures identify the same callback once across multiple shared textures',()=>{const owner=()=>{},other=()=>{},a=texture(owner,other),b=texture(owner,other);const pool=new Set([a,b]);assert.equal(detachSharedTextureListeners(pool,new Set([owner])),2);assert.deepEqual(a._listeners.dispose,[other]);assert.deepEqual(b._listeners.dispose,[other]);assert.equal(detachSharedTextureListeners(pool,new Set([owner])),0);});

test('private renderer probe preserves the same unrelated observer on local and shared textures',()=>{const observer=()=>{},other=()=>{},owner=e=>e.target.removeEventListener('dispose',owner),local=texture(owner,observer),shared=texture(owner,other,observer);let released=0,probe;class DataTexture{constructor(data,w,h){assert.equal(data.length,4);assert.equal(w,1);assert.equal(h,1);this.isTexture=true;this._listeners={dispose:[]};}dispose(){released++;for(const f of this._listeners.dispose.slice())f({target:this});}removeEventListener(e,f){this._listeners[e]=this._listeners[e].filter(v=>v!==f);}}const renderer={initTexture(t){probe=t;t._listeners.dispose.push(owner);}};assert.equal(detachRendererTextureListeners(renderer,new Set([shared]),{DataTexture}),1);assert.deepEqual(shared._listeners.dispose,[other,observer]);assert.deepEqual(local._listeners.dispose,[owner,observer]);assert.equal(released,1);assert.equal(probe.needsUpdate,true);assert.deepEqual(probe._listeners.dispose,[]);});
test('failed probe initialization releases the private probe and leaves shared observers intact',()=>{const observer=()=>{},shared=texture(observer);let released=0;class DataTexture{constructor(){this._listeners={dispose:[]};}dispose(){released++;}}const renderer={initTexture(){throw Error('synthetic context loss');}};assert.equal(detachRendererTextureListeners(renderer,new Set([shared]),{DataTexture}),0);assert.deepEqual(shared._listeners.dispose,[observer]);assert.equal(released,1);});
