'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const {libraryContext,fixture,ROOT}=require('./plan-library-test-support.cjs');
const source=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),tick=()=>new Promise(resolve=>setImmediate(resolve)),plain=v=>JSON.parse(JSON.stringify(v));
async function settle(){for(let i=0;i<30;i++)await tick();}
function section(start,end){const a=source.indexOf(start),b=source.indexOf(end,a);assert.ok(a>=0&&b>a);return source.slice(a,b);}
function sharedSocketContext(save){
 const statuses=[],c={DIRTY:true,DATA:fixture(),__editorPlanId:'shared-room-synthetic',SHARED:{roomId:'synthetic',version:1,saveBusy:false},StorageAdapter:{save},serializeDataSnapshot(){return JSON.stringify(c.DATA);},sharedSetStatus:(...args)=>statuses.push(args),clearDirty(){c.DIRTY=false;},sharedHasTrackedChanges:()=>false,renderSharedUi(){},closeSharedSocket(){},sharedClientId:()=> 'synthetic-client',sharedDisplayName:()=> 'fixture',location:{protocol:'https:',host:'synthetic.invalid'},encodeURIComponent,setTimeout,clearTimeout,WebSocket:function(){}};c.SHARED.confirmedSave={roomId:c.SHARED.roomId,planId:c.__editorPlanId,snapshot:JSON.stringify(c.DATA),version:1};c.window=c;vm.createContext(c);vm.runInContext(section('async function sharedAutoSaveLocal(){','function closeSharedSocket(){')+'\n'+section('function connectSharedSocket(){','async function fetchSharedPlan('),c);c.connectSharedSocket();return {c,statuses,event:message=>c.SHARED.socket.onmessage({data:JSON.stringify(message)})};
}
test('real shared checkpoint quota failure keeps dirty and failure status',async()=>{
 const h=sharedSocketContext(async()=>{throw new DOMException('Synthetic quota','QuotaExceededError');});h.event({type:'checkpoint',version:2});await settle();assert.equal(h.c.DIRTY,true);assert.equal(h.statuses.at(-1)[1],true);assert.ok(!h.statuses.some(([text])=>text==='自動保存しました。'));
});
test('real shared checkpoint canClean:false and non-saved repository outcome cannot clear dirty',async()=>{
 for(const result of [{status:'saved',canClean:false},{status:'conflict',canClean:false},{status:'superseded',canClean:true},false]){const h=sharedSocketContext(async()=>result);h.event({type:'checkpoint',version:2});await settle();assert.equal(h.c.DIRTY,true);assert.equal(h.statuses.length,0);}
});
test('real shared checkpoint requires stable payload, room, plan identity and shared version',async()=>{
 for(const change of [c=>c.DATA=fixture(222),c=>c.SHARED.roomId='other',c=>c.__editorPlanId='other-id',c=>c.SHARED.version=3]){let finish;const h=sharedSocketContext(()=>new Promise(resolve=>finish=resolve));h.event({type:'checkpoint',version:2});change(h.c);finish({status:'saved',canClean:true});await settle();assert.equal(h.c.DIRTY,true);assert.equal(h.statuses.length,0);}
});
test('real shared snapshot acknowledgement uses verified local save before cleaning',async()=>{
 const failed=sharedSocketContext(async()=>{throw Error('Synthetic abort');});failed.event({type:'snapshot',version:2,clientId:'synthetic-client'});await settle();assert.equal(failed.c.DIRTY,true);assert.equal(failed.statuses.at(-1)[1],true);const saved=sharedSocketContext(async()=>({status:'saved',canClean:true}));saved.event({type:'snapshot',version:2,clientId:'synthetic-client'});await settle();assert.equal(saved.c.DIRTY,false);assert.equal(saved.statuses.at(-1)[0],'ブラウザとクラウドへ保存しました。');
});
test('real checkpoint cleans only after a current verified save; pending shared changes remain dirty',async()=>{
 const h=sharedSocketContext(async()=>({status:'saved',canClean:true}));h.event({type:'checkpoint',version:2});await settle();assert.equal(h.c.DIRTY,false);assert.equal(h.statuses.at(-1)[0],'自動保存しました。');const pending=sharedSocketContext(async()=>({status:'saved',canClean:true}));pending.c.sharedHasTrackedChanges=()=>true;pending.event({type:'checkpoint',version:2});await settle();assert.equal(pending.c.DIRTY,true);
});
function attachRealJoinLifecycle(h){
 const c=h.context;c.ren=null;c.serializeDataSnapshot=()=>JSON.stringify(c.DATA);c._defaultPlanPending=false;c.sharedSetStatus=()=>{};c.openShareDialog=()=>{};c.sharedRoomFromLocation=()=> 'synthetic-retry-room';c.sharedBaselineFrom=()=>({});c.sharedResetDirtyTracking=()=>{};c.renderSharedUi=()=>{};c.connectSharedSocket=()=>{};c.closeSharedSocket=()=>{};c.history={replaceState(){}};c.confirm=()=>true;c.clearEditHistory=()=>{};
 for(const name of ['syncNorthFromPlan','ensureObjectIds','ensureExteriorWallSettings','ensureInteriorWallSettings','ensureRoofAppearance','syncExteriorWallSettings','normalizeLegacyFurnitureItems','restoreViewState','draw2d','rebuild3D','captureViewState'])c[name]=()=>{};
 vm.runInContext(section('function installSharedPlan(','async function refreshSharedPlan(')+'\n'+section('async function refreshSharedPlan(){','function isUnityRenderableView(){'),vm.createContext(c));return c;
}
async function save(h){const p=h.api.panes.get('native-editor');return h.api.persistPane(p.id,p.planId,h.plan);}
test('real failed join then retry adopts room ID and cannot overwrite ordinary head',async()=>{
 const h=libraryContext();await h.api.ready;await save(h);h.context.clearDirty();const ordinary=h.context.__editorPlanId,before=plain((await h.api.repo.read(ordinary)).payload),c=attachRealJoinLifecycle(h);let attempts=0;c.fetchSharedPlan=async()=>{if(!attempts++)throw Error('Synthetic join failure');return {plan:fixture(999),version:2,savedAt:1};};assert.equal(await c.initSharedRoomFromUrl(),false);assert.equal(c.__editorPlanId,ordinary);await c.retrySharedJoin();assert.equal(c.__editorPlanId,'shared-room-synthetic-retry-room');assert.equal(h.plan.rooms[0].x,999);await save(h);assert.deepEqual(plain((await h.api.repo.read(ordinary)).payload),before);assert.equal((await h.api.repo.read(c.__editorPlanId)).payload.rooms[0].x,999);
 c.leaveSharedRoom();assert.equal(c.SHARED.roomId,null);h.edit(fixture(555));await settle();await save(h);assert.equal(c.__editorPlanId,'shared-room-synthetic-retry-room');assert.deepEqual(plain((await h.api.repo.read(ordinary)).payload),before);
});
test('real shared refresh and creation use the same protected identity lifecycle',async()=>{
 const h=libraryContext();await h.api.ready;await save(h);h.context.clearDirty();const ordinary=h.context.__editorPlanId,before=plain((await h.api.repo.read(ordinary)).payload),c=attachRealJoinLifecycle(h);c.fetchSharedPlan=async()=>({plan:fixture(333),version:2,savedAt:1});await c.initSharedRoomFromUrl();await save(h);c.fetchSharedPlan=async()=>({plan:fixture(444),version:3,savedAt:2});await c.refreshSharedPlan();await save(h);assert.equal(c.__editorPlanId,'shared-room-synthetic-retry-room');assert.equal((await h.api.repo.read(c.__editorPlanId)).payload.rooms[0].x,444);assert.deepEqual(plain((await h.api.repo.read(ordinary)).payload),before);
 c.leaveSharedRoom();c.sharedRoomFromLocation=()=>null;c.sceneV3LocalOnlyPlan=()=>false;c.fetch=async()=>({ok:true,json:async()=>({roomId:'synthetic-created-room',version:1,url:'http://127.0.0.1:65238/?room=synthetic-created-room'})});c.copySharedUrl=async()=>{};await c.createSharedRoom();assert.equal(c.__editorPlanId,'shared-room-synthetic-created-room');await save(h);assert.deepEqual(plain((await h.api.repo.read(ordinary)).payload),before);assert.equal((await h.api.repo.read('shared-room-synthetic-retry-room')).payload.rooms[0].x,444);
});
test('joined-room identity mismatch and missing handoff dependency fail before ordinary save',async()=>{
 const h=libraryContext();await h.api.ready;await save(h);const ordinary=h.context.__editorPlanId,head=(await h.api.repo.read(ordinary)).revision.id;h.context.SHARED.roomId='synthetic-unbound';await assert.rejects(save(h),/保存先の切替/);assert.equal((await h.api.repo.read(ordinary)).revision.id,head);const c={NATIVE_PLAN_EDITOR:true,window:{PlanLibrary:{}},called:false};vm.runInNewContext(section('async function withSharedPlanIdentity(','async function refreshSharedPlan('),c);await assert.rejects(c.withSharedPlanIdentity('room',()=>c.called=true),/保存先を準備/);assert.equal(c.called,false);
});
test('native cached clean activation reads newer head in same lifecycle',async()=>{
 const h=libraryContext();await h.api.ready;await save(h);h.context.clearDirty();const a=h.context.__editorPlanId;await h.api.repo.save({planId:'native-b',name:'B',operationId:'seed',baseRevisionId:null,baseGeneration:0,payload:fixture(200)});await h.api.openPlan('native-b');const prior=await h.api.repo.read(a);await h.api.repo.save({planId:a,operationId:'other-tab',baseRevisionId:prior.revision.id,baseGeneration:prior.head.headGeneration,payload:fixture(999)});await h.api.openPlan(a);assert.equal(h.plan.rooms[0].x,999);assert.equal(h.context.DIRTY,false);assert.equal(h.api.plans.get(a).baseRevisionId,(await h.api.repo.read(a)).revision.id);
});
test('collapsed cached clean comparison pane refreshes newer head on reopen',async()=>{
 const h=libraryContext();await h.api.ready;for(const [id,x]of [['a',100],['b',200]])await h.api.repo.save({planId:id,name:id,operationId:'seed',baseRevisionId:null,baseGeneration:0,payload:fixture(x)});await h.api.repo.setView('cache-layout',{retainedPlanIds:['a','b'],panelPlanIds:['a','b'],sync:false});const cmp=libraryContext({mem:h.mem,native:false,search:'?planLibrary=1&librarySession=cache-layout'});await cmp.api.ready;await cmp.api.layout(1);const prior=await h.api.repo.read('b');await h.api.repo.save({planId:'b',operationId:'updated',baseRevisionId:prior.revision.id,baseGeneration:prior.head.headGeneration,payload:fixture(888)});await cmp.api.layout(2);const pane=[...cmp.api.panes.values()].find(p=>p.planId==='b');assert.equal(pane.frame.contentWindow.EditorPane.snapshot().rooms[0].x,888);assert.equal(pane.frame.contentWindow.DIRTY,false);
});
test('collapsed stale dirty cache remains recoverable instead of being replaced by newer head',async()=>{
 const h=libraryContext();await h.api.ready;for(const [id,x]of [['a',100],['b',200]])await h.api.repo.save({planId:id,name:id,operationId:'seed',baseRevisionId:null,baseGeneration:0,payload:fixture(x)});await h.api.repo.setView('dirty-cache-layout',{retainedPlanIds:['a','b'],panelPlanIds:['a','b'],sync:false});const cmp=libraryContext({mem:h.mem,native:false,search:'?planLibrary=1&librarySession=dirty-cache-layout'});await cmp.api.ready;let pane=[...cmp.api.panes.values()].find(p=>p.planId==='b');await pane.frame.contentWindow.EditorPane.install(fixture(777),{dirty:true});cmp.api.edited(pane.id);await settle();await cmp.api.layout(1);const prior=await h.api.repo.read('b');await h.api.repo.save({planId:'b',operationId:'updated',baseRevisionId:prior.revision.id,baseGeneration:prior.head.headGeneration,payload:fixture(888)});await cmp.api.layout(2);pane=[...cmp.api.panes.values()].find(p=>p.planId==='b');assert.equal(pane.frame.contentWindow.EditorPane.snapshot().rooms[0].x,777);assert.equal(pane.frame.contentWindow.DIRTY,true);await assert.rejects(cmp.api.persistPane(pane.id,'b',pane.frame.contentWindow.EditorPane.snapshot()),/競合/);assert.equal((await h.api.repo.read('b')).payload.rooms[0].x,888);
});
test('checkpoint and own snapshot cannot clean edits made before acknowledgement delivery',async()=>{
 for(const type of ['checkpoint','snapshot']){const h=sharedSocketContext(async()=>({status:'saved',canClean:true}));h.c.DATA=fixture(333);h.event({type,version:2,clientId:'synthetic-client'});await settle();assert.equal(h.c.DIRTY,true);assert.equal(h.statuses.length,0);}
});
test('real manual shared save binds socket acknowledgement to the exact outgoing payload',async()=>{
 const h=sharedSocketContext(async()=>({status:'saved',canClean:true})),c=h.c;let finish,sent;c.alert=()=>{};c.setSaveButtonBusy=v=>c.SHARED.saveBusy=v;c.flushSharedChanges=async()=>{};c.queueSharedSync=()=>{};c.sceneV3LocalOnlyPlan=()=>false;c.sharedBaselineFrom=()=>({});c.sharedResetDirtyTracking=()=>{};
 for(const name of ['normalizeLegacyFurnitureItems','ensureObjectIds','ensureExteriorWallSettings','ensureInteriorWallSettings','ensureRoofAppearance','ensureFloorMetadata','ensureHeightDefaults','syncExteriorWallSettings','captureViewState'])c[name]=()=>{};
 c.fetch=async(url,options)=>{sent=JSON.parse(options.body).plan;return new Promise(resolve=>finish=()=>resolve({ok:true,json:async()=>({version:2,savedAt:1})}));};vm.runInContext(section('async function savePlanToStorage(){','async function loadPlanFromStorage(){'),vm.createContext(c));const pending=c.savePlanToStorage();while(!finish)await tick();c.DATA=fixture(555);finish();assert.equal(await pending,true);assert.equal(sent.rooms[0].x,100);assert.equal(JSON.parse(c.SHARED.confirmedSave.snapshot).rooms[0].x,100);assert.equal(c.DIRTY,true);h.event({type:'snapshot',version:2,clientId:'synthetic-client'});await settle();assert.equal(c.DIRTY,true);h.event({type:'checkpoint',version:2});await settle();assert.equal(c.DIRTY,true);
});
test('real patch save binds automatic checkpoint cleanup to its outgoing serialized state',async()=>{
 for(const editDuringSend of [false,true]){const h=sharedSocketContext(async()=>({status:'saved',canClean:true})),c=h.c;let finish;c.buildSharedPatch=()=>({collections:{rooms:{upserts:[c.DATA.rooms[0]],removes:[]}}});c.sharedResetDirtyTracking=()=>{};c.queueSharedSync=()=>{};c.sharedBaselineFrom=()=>({});c.fetch=async()=>new Promise(resolve=>finish=()=>resolve({ok:true,json:async()=>({version:2,savedAt:1})}));vm.runInContext(section('async function sharedSyncNow(){','async function flushSharedChanges(){'),vm.createContext(c));const pending=c.sharedSyncNow();while(!finish)await tick();if(editDuringSend)c.DATA=fixture(555);finish();await pending;assert.equal(JSON.parse(c.SHARED.confirmedSave.snapshot).rooms[0].x,100);h.event({type:'checkpoint',version:2});await settle();assert.equal(c.DIRTY,editDuringSend);}
});
test('real initial shared join binds room identity during bootstrap without creating ordinary default head',async()=>{
 const h=libraryContext({beforeLibrary:(context)=>{const c=attachRealJoinLifecycle({context});c.fetchSharedPlan=async()=>({plan:fixture(333),version:2,savedAt:1});}});await h.api.ready;assert.equal(h.context.__editorPlanId,'shared-room-synthetic-retry-room');assert.equal(h.plan.rooms[0].x,333);assert.equal(h.context.SHARED.confirmedSave.planId,h.context.__editorPlanId);assert.equal((await h.api.repo.list()).length,0);await save(h);assert.deepEqual(plain((await h.api.repo.list()).map(x=>x.id)),['shared-room-synthetic-retry-room']);
});
test('real first shared draw failure restores dirty native state and identity, then retry and leave are safe',async()=>{
 const h=libraryContext();await h.api.ready;await save(h);h.context.clearDirty();const ordinary=h.context.__editorPlanId,original=plain((await h.api.repo.read(ordinary)).payload);h.edit(fixture(321));await settle();const c=attachRealJoinLifecycle(h),before=plain(c.EditorPane.state());c.fetchSharedPlan=async()=>({plan:fixture(999),version:2,savedAt:1});let fail=true;c.draw2d=()=>{if(fail){fail=false;throw Error('Synthetic first draw failure');}};
 assert.equal(await c.initSharedRoomFromUrl(),false);assert.equal(c.__editorPlanId,ordinary);assert.equal(c.SHARED.roomId,null);assert.deepEqual(plain(c.EditorPane.state()),before);assert.equal(c.DIRTY,true);assert.ok(!c.document.body.inert);assert.deepEqual(plain((await h.api.repo.read(ordinary)).payload),original);
 await c.retrySharedJoin();assert.equal(c.__editorPlanId,'shared-room-synthetic-retry-room');assert.equal(h.plan.rooms[0].x,999);c.leaveSharedRoom();assert.equal(c.SHARED.roomId,null);h.edit(fixture(555));await settle();await save(h);assert.deepEqual(plain((await h.api.repo.read(ordinary)).payload),original);
});
test('shared target draft/view failure rolls native scene, room and view back without advancing either head',async()=>{
 for(const fault of ['draft-abort','view-abort','view-readback']){const h=libraryContext();await h.api.ready;await save(h);h.context.clearDirty();const ordinary=h.context.__editorPlanId,head=(await h.api.repo.read(ordinary)).revision.id;h.edit(fixture(321));await settle();const c=attachRealJoinLifecycle(h),before=plain(c.EditorPane.state()),target='shared-room-synthetic-retry-room';await h.api.repo.save({planId:target,name:'Shared',operationId:'seed',baseRevisionId:null,baseGeneration:0,payload:fixture(800)});const targetHead=(await h.api.repo.read(target)).revision.id;c.fetchSharedPlan=async()=>({plan:fixture(999),version:2,savedAt:1});let injected=false;const draft=h.api.repo.saveDraft,view=h.api.repo.setView;
 h.api.repo.saveDraft=async(...args)=>{if(fault==='draft-abort'&&args[1]===target&&!injected){injected=true;throw Error('Synthetic draft abort');}return draft(...args);};h.api.repo.setView=async(...args)=>{if(fault.startsWith('view')&&c.__editorPlanId===target&&!injected){injected=true;if(fault==='view-readback')await view(...args);throw Error('Synthetic view failure');}return view(...args);};
 assert.equal(await c.initSharedRoomFromUrl(),false);assert.equal(injected,true);assert.equal(c.__editorPlanId,ordinary);assert.equal(c.SHARED.roomId,null);assert.deepEqual(plain(c.EditorPane.state()),before);assert.equal((await h.api.repo.read(ordinary)).revision.id,head);assert.equal((await h.api.repo.read(target)).revision.id,targetHead);assert.deepEqual(plain((await h.api.repo.get('views',h.api.session)).panelPlanIds),[ordinary]);
 await c.retrySharedJoin();assert.equal(c.__editorPlanId,target);assert.equal(h.plan.rooms[0].x,999);assert.equal((await h.api.repo.read(ordinary)).revision.id,head);
 }
});
test('bootstrap never resumes an ordinary plan while a failed room handoff is still joined',async()=>{
 const h=libraryContext({beforeLibrary:c=>{attachRealJoinLifecycle({context:c});delete c.EditorPane.restoreInstallState;c.SHARED.roomId='previous-room';c.fetchSharedPlan=async()=>({plan:fixture(999),version:2});}});await h.api.ready;assert.equal(h.context.presetLoads,undefined);assert.equal(h.plan.rooms[0].x,100);assert.equal((await h.api.repo.list()).length,0);assert.equal(h.context.SHARED.roomId,'previous-room');
});
test('actual common pane rollback restores history, redo, options, selection, walk and view despite recovery draw faults',()=>{
 const pane=fs.readFileSync(path.join(ROOT,'assets/js/parallel-editors.js'),'utf8'),code=pane.slice(pane.indexOf('  function captureInstallState(){'),pane.indexOf('  root.EditorPane='));const data=fixture(321),c={DATA:data,ST:{floor:2,view:'3d-ext',selected:data.rooms[0],multiSelected:[data.rooms[0]],_snapState:{fixture:true},zoom:3,panX:4,panY:5,options:{snap:25}},DRAG:{active:true,origItem:data.rooms[0]},HISTORY:['undo'],REDO_HISTORY:['redo'],DIRTY:true,WALL_H:2850,nextId:42,LIGHT_SETTINGS:{northDeg:80,fixture:7},_defaultPlanPending:false,WALK:{active:true,x:2,z:3,keys:{}},console:{warn(){}},document:{getElementById:()=>null},clone:plain,view:()=>plain(c.camera),camera:{view:'3d-ext',floor:2,twoD:{zoom:3,panX:4,panY:5},camera:{pos:[1,2,3],target:[4,5,6],fov:45}},camExt:null,orbit:null,AssetPackPicker:{getSelection:()=>c.pack,setSelection:v=>c.pack=v},pack:'kept',ren:null};c.root=c;c.applyView=v=>{c.camera=plain(v);throw Error('Synthetic recovery draw');};for(const name of ['syncNorthUi','syncHeightDefaultsUI','updateProps','draw2d','renderSaveButtonState'])c[name]=()=>{};vm.runInNewContext(code,c);const captured=c.captureInstallState();c.DATA=fixture(999);c.ST.zoom=99;c.ST.options.snap=999;c.HISTORY.length=0;c.REDO_HISTORY.length=0;c.DIRTY=false;c.WALL_H=111;c.nextId=999;c.LIGHT_SETTINGS.northDeg=1;c.WALK.x=99;c.pack='lost';c.camera={};c.restoreInstallState(captured);
 assert.equal(c.DATA,data);assert.equal(c.ST.selected,data.rooms[0]);assert.equal(c.ST.multiSelected[0],data.rooms[0]);assert.deepEqual(plain(c.ST.options),{snap:25});assert.deepEqual(Array.from(c.HISTORY),['undo']);assert.deepEqual(Array.from(c.REDO_HISTORY),['redo']);assert.equal(c.DIRTY,true);assert.equal(c.WALL_H,2850);assert.equal(c.nextId,42);assert.equal(c.LIGHT_SETTINGS.northDeg,80);assert.equal(c.WALK.x,2);assert.equal(c.pack,'kept');assert.deepEqual(c.camera,captured.view);
});
test('old socket events cannot mutate a replacement room or same-room connection',async()=>{
 for(const sameRoom of [false,true]){let saves=0,applies=0,refreshes=0,renders=0;const h=sharedSocketContext(async()=>{saves++;return {status:'saved',canClean:true};}),c=h.c,old=c.SHARED.socket;c.applySharedPatch=()=>applies++;c.refreshSharedPlan=()=>refreshes++;c.renderSharedUi=()=>renders++;if(!sameRoom){c.SHARED.roomId='B';c.__editorPlanId='shared-room-B';c.SHARED.roomGeneration=1;}c.SHARED.version=2;c.DATA=fixture(200);c.SHARED.confirmedSave={roomId:c.SHARED.roomId,planId:c.__editorPlanId,snapshot:JSON.stringify(c.DATA),version:2};c.connectSharedSocket();const active=c.SHARED.socket,before=JSON.stringify(c.SHARED);
 for(const message of [{type:'checkpoint',version:99},{type:'snapshot',version:99,clientId:'synthetic-client'},{type:'snapshot',version:99,clientId:'other'},{type:'patch',version:99,patch:{}},{type:'welcome',version:99,expiresAt:999},{type:'presence',people:[{name:'stale'}]}])old.onmessage({data:JSON.stringify(message)});old.onopen();old.onerror();old.onclose();await settle();assert.equal(c.SHARED.socket,active);assert.equal(JSON.stringify(c.SHARED),before);assert.equal(c.DIRTY,true);assert.equal(saves+applies+refreshes+renders,0);assert.equal(h.statuses.length,0);
 }
});
test('a checkpoint admitted on an old connection cannot clean after reconnection during local save',async()=>{
 let finish;const h=sharedSocketContext(()=>new Promise(resolve=>finish=resolve)),c=h.c;h.event({type:'checkpoint',version:2});c.connectSharedSocket();finish({status:'saved',canClean:true});await settle();assert.equal(c.DIRTY,true);assert.equal(h.statuses.length,0);
});
function actualPatchContext(){
 const h=sharedSocketContext(async()=>({status:'saved',canClean:true})),c=h.c;c.SHARED_FIELDS=[];c.sharedClone=plain;c.sharedFastSignature=JSON.stringify;c.SHARED.dirtyIds={walls:{},items:{},rooms:{}};c.SHARED.forceScan=true;c.SHARED.pending=false;c.SHARED.sending=false;c.queueSharedSync=()=>{};vm.runInContext(section('function sharedResetDirtyTracking(){','function sharedClientId(){')+'\n'+section('function sharedBaselineFrom(plan){','function markDirtyUiOnly(){')+'\n'+section('async function sharedSyncNow(){','async function flushSharedChanges(){'),vm.createContext(c));c.SHARED.baseline=c.sharedBaselineFrom(fixture(0));return h;
}
function attachManualSave(c){
 c.alert=()=>{};c.setSaveButtonBusy=v=>c.SHARED.saveBusy=v;c.flushSharedChanges=async()=>{};c.sceneV3LocalOnlyPlan=()=>false;for(const name of ['normalizeLegacyFurnitureItems','ensureObjectIds','ensureExteriorWallSettings','ensureInteriorWallSettings','ensureRoofAppearance','ensureFloorMetadata','ensureHeightDefaults','syncExteriorWallSettings','captureViewState'])c[name]=()=>{};vm.runInContext(section('async function savePlanToStorage(){','async function loadPlanFromStorage(){'),vm.createContext(c));
}
test('real patch and manual responses keep post-send edit in the next outgoing patch',async()=>{
 for(const manual of [false,true]){const h=actualPatchContext(),c=h.c;let finish,sent;c.fetch=async(url,options)=>{sent=JSON.parse(options.body);return new Promise(resolve=>finish=()=>resolve({ok:true,json:async()=>({version:2})}));};if(manual)attachManualSave(c);const pending=manual?c.savePlanToStorage():c.sharedSyncNow();while(!finish)await tick();c.DATA=fixture(555);c.SHARED.dirtyIds.rooms['room-stable']=true;finish();await pending;assert.equal(JSON.parse(c.SHARED.confirmedSave.snapshot).rooms[0].x,100);const patch=c.buildSharedPatch(c.DATA,c.SHARED.baseline);assert.equal(patch.collections.rooms.upserts[0].x,555);assert.ok(c.sharedHasTrackedChanges());assert.equal(c.DIRTY,true);assert.equal(manual?sent.plan.rooms[0].x:sent.patch.collections.rooms.upserts[0].x,100);
 }
});
test('old-room patch/manual HTTP success and errors cannot mutate the new room lifecycle',async()=>{
 for(const manual of [false,true])for(const failure of [false,true]){const h=actualPatchContext(),c=h.c;let finish;c.fetch=async()=>new Promise((resolve,reject)=>finish=()=>failure?reject(Error('Synthetic old response failure')):resolve({ok:true,json:async()=>({version:99,savedAt:99,expiresAt:99})}));if(manual)attachManualSave(c);const pending=manual?c.savePlanToStorage():c.sharedSyncNow();while(!finish)await tick();c.__editorPlanId='shared-room-B';c.DATA=fixture(555);c.SHARED={roomId:'B',roomGeneration:8,version:2,dirtyIds:{walls:{},items:{},rooms:{}},baseline:c.sharedBaselineFrom(c.DATA),forceScan:true,pending:true,sending:true,saveBusy:false};const before=JSON.stringify(c.SHARED),status=h.statuses.length;finish();await pending;assert.equal(JSON.stringify(c.SHARED),before);assert.equal(h.statuses.length,status);assert.equal(c.DIRTY,true);assert.equal(c.DATA.rooms[0].x,555);
 }
});
test('actual native camera recovery runs before a recovery draw can fail',()=>{
 const pane=fs.readFileSync(path.join(ROOT,'assets/js/parallel-editors.js'),'utf8'),helper=pane.slice(pane.indexOf('  function captureInstallState(){'),pane.indexOf('  root.EditorPane=')),apply=pane.slice(pane.indexOf('  function applyView(v){'),pane.indexOf('  function localGeometry('));function vector(a){return {values:a.slice(),fromArray(v){this.values=v.slice();},toArray(){return this.values.slice();}};}const c={DATA:fixture(),ST:{floor:1,view:'3d-ext',selected:null,multiSelected:[],zoom:2},DRAG:{origItem:null},HISTORY:['undo'],REDO_HISTORY:['redo'],DIRTY:true,WALL_H:2850,nextId:7,LIGHT_SETTINGS:{northDeg:90},_defaultPlanPending:false,WALK:{active:false},camExt:{position:vector([1,2,3]),fov:45,updateProjectionMatrix(){}},orbit:{target:vector([4,5,6]),update(){}},document:{getElementById:()=>null},console:{warn(){}},clone:plain,ren:null,applying:false,cameraKey:()=>'',invalidate3D(){},syncNorthUi(){},syncHeightDefaultsUI(){},updateProps(){},renderSaveButtonState(){},draw2d(){throw Error('Synthetic repeated draw failure');}};c.root=c;c.view=()=>({view:c.ST.view,floor:1,twoD:{zoom:c.ST.zoom},camera:{pos:c.camExt.position.toArray(),target:c.orbit.target.toArray(),fov:c.camExt.fov}});vm.runInNewContext(apply+helper,c);const before=c.captureInstallState();c.camExt.position.fromArray([9,9,9]);c.orbit.target.fromArray([8,8,8]);c.camExt.fov=99;c.restoreInstallState(before);assert.deepEqual(c.camExt.position.toArray(),[1,2,3]);assert.deepEqual(c.orbit.target.toArray(),[4,5,6]);assert.equal(c.camExt.fov,45);assert.equal(c.DIRTY,true);
});
test('stale room fetch success/errors and creation results cannot install or mutate a later lifecycle',async()=>{
 for(const route of ['join','refresh','create'])for(const failure of [false,true]){const h=libraryContext();await h.api.ready;const c=attachRealJoinLifecycle(h);let finish,installed=0,statuses=0,dialogs=0;c.sharedSetStatus=()=>statuses++;c.openShareDialog=()=>dialogs++;c.withSharedPlanIdentity=async()=>installed++;
 if(route==='refresh'){c.SHARED.roomId='A';c.SHARED.version=1;}if(route==='create'){c.sharedRoomFromLocation=()=>null;c.fetch=async()=>new Promise((resolve,reject)=>finish=()=>failure?reject(Error('Synthetic old creation failure')):resolve({ok:true,json:async()=>({roomId:'A',version:99,url:'https://synthetic.invalid/?room=A'})}));}else c.fetchSharedPlan=async()=>new Promise((resolve,reject)=>finish=()=>failure?reject(Error('Synthetic old fetch failure')):resolve({plan:fixture(999),version:99}));
 const pending=route==='join'?c.initSharedRoomFromUrl():route==='refresh'?c.refreshSharedPlan():c.createSharedRoom();while(!finish)await tick();c.SHARED={roomId:'B',roomGeneration:8,version:2,refreshing:true,saveBusy:false};c.__editorPlanId='shared-room-B';c.DATA=fixture(555);const before=JSON.stringify(c.SHARED),status=statuses,dialog=dialogs;finish();await pending;assert.equal(installed,0);assert.equal(JSON.stringify(c.SHARED),before);assert.equal(statuses,status);assert.equal(dialogs,dialog);assert.equal(c.DATA.rooms[0].x,555);
 }
});
test('old sync/local timer callbacks cannot act on a later room lifecycle',()=>{
 const callbacks=[],c={SHARED:{roomId:'A',roomGeneration:1,socket:null},setTimeout:fn=>{callbacks.push(fn);return callbacks.length;},clearTimeout(){},sharedSyncNow(){c.syncs++;},sharedAutoSaveLocal(){c.saves++;},syncs:0,saves:0};vm.runInNewContext(section('function queueSharedSync(delay){','async function sharedSyncNow(){')+'\n'+section('function queueSharedLocalAutoSave(){','async function sharedAutoSaveLocal(){'),c);c.queueSharedSync();c.queueSharedLocalAutoSave();c.SHARED={roomId:'B',roomGeneration:2,timer:123,localAutoTimer:456};const before=JSON.stringify(c.SHARED);callbacks.forEach(fn=>fn());assert.equal(c.syncs+c.saves,0);assert.equal(JSON.stringify(c.SHARED),before);
});
test('leave during asynchronous room preflight invalidates the pending join before installation',async()=>{
 const h=libraryContext();await h.api.ready;const c=attachRealJoinLifecycle(h);c.fetchSharedPlan=async()=>({plan:fixture(333),version:2,savedAt:1});await c.initSharedRoomFromUrl();await save(h);c.clearDirty();const id=c.__editorPlanId,before=plain(c.EditorPane.state());c.sharedRoomFromLocation=()=> 'synthetic-next-room';c.fetchSharedPlan=async()=>({plan:fixture(999),version:3,savedAt:2});const read=h.api.repo.read;let finish;h.api.repo.read=async target=>target==='shared-room-synthetic-next-room'?new Promise(resolve=>finish=()=>resolve(null)):read(target);const pending=c.initSharedRoomFromUrl();while(!finish)await tick();c.leaveSharedRoom();finish();assert.equal(await pending,false);assert.equal(c.SHARED.roomId,null);assert.equal(c.__editorPlanId,id);assert.deepEqual(plain(c.EditorPane.state()),before);
});
test('failed same-room refresh preserves the prior shared edit, history and proof while keeping identity bound',async()=>{
 const h=libraryContext();await h.api.ready;const c=attachRealJoinLifecycle(h);c.fetchSharedPlan=async()=>({plan:fixture(333),version:2,savedAt:1});await c.initSharedRoomFromUrl();await save(h);h.edit(fixture(321));await settle();const before=plain(c.EditorPane.state()),id=c.__editorPlanId,baseline=plain(c.SHARED.baseline),proof=plain(c.SHARED.confirmedSave);c.fetchSharedPlan=async()=>({plan:fixture(999),version:3,savedAt:2});c.draw2d=()=>{throw Error('Synthetic refresh draw failure');};await c.refreshSharedPlan();assert.equal(c.__editorPlanId,id);assert.equal(c.SHARED.roomId,'synthetic-retry-room');assert.equal(c.SHARED.version,2);assert.deepEqual(plain(c.SHARED.baseline),baseline);assert.deepEqual(plain(c.SHARED.confirmedSave),proof);assert.deepEqual(plain(c.EditorPane.state()),before);assert.equal(c.DIRTY,true);assert.equal(c.SHARED.refreshing,false);c.leaveSharedRoom();assert.equal(c.SHARED.roomId,null);await save(h);assert.equal((await h.api.repo.read(id)).payload.rooms[0].x,321);
});
test('shared creation baseline retains edits made while its full snapshot is pending',async()=>{
 const h=libraryContext();await h.api.ready;await save(h);h.context.clearDirty();const c=attachRealJoinLifecycle(h);c.sharedRoomFromLocation=()=>null;c.sharedClone=plain;c.sharedFastSignature=JSON.stringify;c.SHARED_FIELDS=[];c.SHARED.dirtyIds={walls:{},items:{},rooms:{}};c.queueSharedSync=()=>{};vm.runInContext(section('function sharedResetDirtyTracking(){','function sharedClientId(){')+'\n'+section('function sharedBaselineFrom(plan){','function markDirtyUiOnly(){'),vm.createContext(c));let finish;c.fetch=async()=>new Promise(resolve=>finish=()=>resolve({ok:true,json:async()=>({roomId:'synthetic-created-room',version:1,url:'https://synthetic.invalid/?room=synthetic-created-room'})}));c.copySharedUrl=async()=>{};const pending=c.createSharedRoom();while(!finish)await tick();h.edit(fixture(555));finish();await pending;assert.equal(c.__editorPlanId,'shared-room-synthetic-created-room');assert.equal(JSON.parse(c.SHARED.confirmedSave.snapshot).rooms[0].x,100);assert.equal(h.plan.rooms[0].x,555);assert.equal(c.buildSharedPatch(c.DATA,c.SHARED.baseline).collections.rooms.upserts[0].x,555);assert.equal(c.DIRTY,true);assert.ok(c.sharedHasTrackedChanges());
});
test('an old flush cannot start a new-room patch after its prior send completes',async()=>{
 let finish,sends=0;const c={SHARED:{roomId:'A',roomGeneration:1,sending:true,sendPromise:new Promise(resolve=>finish=resolve)},__editorPlanId:'shared-room-A',clearTimeout(){},sharedSyncNow(){sends++;},sharedHasTrackedChanges:()=>true};c.window=c;vm.runInNewContext(section('async function flushSharedChanges(){','function queueSharedLocalAutoSave(){'),c);const pending=c.flushSharedChanges();c.SHARED={roomId:'B',roomGeneration:2,sending:false,timer:123};c.__editorPlanId='shared-room-B';finish();await pending;assert.equal(sends,0);assert.equal(c.SHARED.timer,123);
});
