const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),R=require('../../assets/js/source-image-rails.js');const body=()=>JSON.parse(fs.readFileSync('local-preview/sample.json','utf8'));
const decision=(c,change={})=>({sourceId:c.id,annotationSnapshot:c.snapshot,kind:'image-lattice-rail',reviewed:true,acceptDiagramColor:true,display:{...c.annotation.displaySuggestion},...change});
test('manual image annotations bind to original floor/slab/page while source AI stays unchanged',()=>{const b=body(),before=JSON.stringify(b.sourceLocal),c=R.candidates(b.sourceLocal,b.sourceImageAnnotations);assert.equal(c.length,2);const mapped=c.map(c=>R.map(b.sourceLocal,b.sourceImageAnnotations,decision(c)));assert.ok(mapped.every(r=>r.canApply));assert.deepEqual(mapped.map(r=>[r.items[0].floor,r.items[0].w,r.items[0].rot,r.items[0].latticeHeight]),[[2,1820,90,2100],[2,1280,0,1100]]);for(const r of mapped){assert.equal(r.walls.length,0);assert.equal(r.items[0].railInfill,'bars');assert.equal(r.items[0].railFrameColor,'#202020');assert.equal(r.items[0].elev,6);assert.ok(r.items[0].sourceObjectMapping.assumptions.every(a=>a.measured===false||a.physicalFinishVerified===false));assert.equal(r.items[0].sourceObjectMapping.sourceKind,'manual-source-image-annotation');assert.equal(r.items[0].sourceObjectMapping.structuralConnectionVerified,false);}assert.equal(JSON.stringify(b.sourceLocal),before);assert.deepEqual(JSON.parse(JSON.stringify(mapped)),mapped);});
test('source/slab/page/annotation edits invalidate rather than fabricate a new AI candidate',()=>{for(const mutate of [b=>b.sourceLocal.items[b.sourceImageAnnotations[0].slabSourceItemIndex].x++,b=>b.sourceLocal.floors.find(f=>f.floor===2).sourcePageId='other',b=>b.sourceImageAnnotations[0].origin='ai-reading',b=>b.sourceImageAnnotations[0].floor=3,b=>b.sourceImageAnnotations[0].end.y=100000]){const b=body(),original=R.candidates(b.sourceLocal,b.sourceImageAnnotations)[0];mutate(b);const r=R.map(b.sourceLocal,b.sourceImageAnnotations,decision(original));assert.equal(r.canApply,false);}const b=body(),c=R.candidates(b.sourceLocal,b.sourceImageAnnotations)[0];b.sourceImageAnnotations[0].end.y-=10;assert.equal(R.map(b.sourceLocal,b.sourceImageAnnotations,decision(c)).canApply,false);});
test('height/thickness/spacing/elevation and diagram color require explicit finite reviewed display choices',()=>{const b=body(),c=R.candidates(b.sourceLocal,b.sourceImageAnnotations)[0];for(const change of [{reviewed:false},{acceptDiagramColor:false},{kind:'rail'},{display:{...c.annotation.displaySuggestion,heightMm:null}},{display:{...c.annotation.displaySuggestion,thicknessMm:20}},{display:{...c.annotation.displaySuggestion,slatMm:80}},{display:{...c.annotation.displaySuggestion,elevationMm:NaN}}])assert.equal(R.map(b.sourceLocal,b.sourceImageAnnotations,decision(c,change)).canApply,false);});
test('south short rail leaves west solid-band region unfilled and matches east corner without becoming slab or wall',()=>{const b=body(),c=R.candidates(b.sourceLocal,b.sourceImageAnnotations),items=c.map(c=>R.map(b.sourceLocal,b.sourceImageAnnotations,decision(c)).items[0]),south=items.find(i=>i.rot===0),east=items.find(i=>i.rot===90);assert.equal(south.x,6000);assert.equal(south.x+south.w,7280);assert.equal(south.y+south.d/2,4095);assert.equal(east.x+east.w/2,7280);assert.equal(east.y+east.d/2-east.w/2,2275);assert.equal(east.y+east.d/2+east.w/2,4095);assert.equal(items.filter(i=>i.type==='balcony').length,0);assert.ok(b.sourceImageAnnotations.every(a=>a.evidence.precisionMm===100));});
test('current user geometry is compared separately without rewriting imported assumptions',()=>{
 const item={w:1820,latticeHeight:2100,x:5,sourceObjectMapping:{sourceKind:'manual-source-image-annotation',assumptions:[{field:'heightMm',value:2100,measured:false}],importedDisplayGeometry:{w:1820,latticeHeight:2100,x:5}}},original=JSON.stringify(item.sourceObjectMapping);
 assert.equal(R.currentReview(item).status,'unchanged');item.latticeHeight=2300;item.w=2500;assert.deepEqual(R.currentReview(item).changes.map(c=>c.field),['w','latticeHeight']);assert.equal(JSON.stringify(item.sourceObjectMapping),original);item.w=1820;item.latticeHeight=2100;assert.equal(R.currentReview(item).status,'unchanged');delete item.sourceObjectMapping.importedDisplayGeometry;assert.equal(R.currentReview(item).status,'unknown');
});
