const test=require('node:test'),assert=require('node:assert/strict'),M=require('../../assets/js/source-object-mapping.js');
const {runtime}=require('./scene-fixtures.cjs'),{topLevelFunction}=require('./height-runtime.cjs'),vm=require('node:vm');
function source(){return {marks:[{guess:'lattice-rail',floor:2,x:1000,y:2000,w:1800,d:60,start:{x:100,y:2000},end:{x:1900,y:2000},thick:60,heightMm:1200,elevationMm:180,fencePattern:'horizontal',railInfill:'bars',railFrameColor:'#223344',railCapColor:'#887766',latticeCap:true,latticePitch:100,latticeSlat:40}]};}
function decision(s){let c=M.candidates(s)[0];return {sourceId:c.id,sourceSnapshot:c.snapshot,reviewed:true,kind:'lattice-rail'};}
test('explicit source lattice maps real2F editable existing screen dimensions/direction/finish/elevation without source writes',()=>{let s=source(),before=JSON.stringify(s),r=M.map(s,decision(s));assert.equal(r.canApply,true);let it=r.items[0];assert.deepEqual([it.type,it.floor,it.x,it.y,it.w,it.d,it.rot,it.latticeHeight,it.elev],['lattice-screen',2,100,1970,1800,60,0,1200,180]);assert.equal(it.railInfill,'bars');assert.equal(it.railFrameColor,'#223344');assert.equal(it.latticeCap,true);assert.equal(it.sourceObjectMapping.assumptions.length,0);assert.equal(JSON.stringify(s),before);});
test('known source segments stay separate with their opening gap and reversed/vertical endpoints preserve direction',()=>{let s=source(),second=JSON.parse(JSON.stringify(s.marks[0]));second.x=2400;second.w=600;second.start={x:2100,y:2000};second.end={x:2700,y:2000};s.marks.push(second);let items=M.candidates(s).map(c=>M.map(s,{...decision(s),sourceId:c.id,sourceSnapshot:c.snapshot}).items[0]);assert.equal(items.length,2);assert.equal(items[1].x-(items[0].x+items[0].w),200);s.marks[0].start={x:1000,y:1000};s.marks[0].end={x:1000,y:2800};assert.equal(M.map(s,decision(s)).items[0].rot,90);});
test('unknown height/elevation/infill require separate explicit display assumptions and unsupported dimensions/styles reject',()=>{let s=source();delete s.marks[0].heightMm;delete s.marks[0].elevationMm;delete s.marks[0].railInfill;delete s.marks[0].fencePattern;assert.equal(M.map(s,decision(s)).canApply,false);let d={...decision(s),acceptDisplayHeightMm:1100,acceptDisplayElevationMm:0,acceptDisplayRailInfill:'baluster'},r=M.map(s,d);assert.equal(r.canApply,true);assert.equal(r.items[0].sourceObjectMapping.assumptions.length,3);assert.ok(r.items[0].sourceObjectMapping.assumptions.every(a=>a.measured===false));for(const change of [{thick:30},{railInfill:'glass'},{heightMm:3001},{elevationMm:10001},{start:undefined},{fencePattern:'horizontal',railInfill:'baluster'}]){let t=source();Object.assign(t.marks[0],change);assert.equal(M.map(t,decision(t)).canApply,false);}});
test('generic rail cannot silently become solid parapet or lattice; known cap color cannot be hidden',()=>{let s=source();s.marks[0].guess='rail';assert.equal(M.map(s,decision(s)).canApply,false);assert.equal(M.map(s,{...decision(s),acceptLatticeRepresentation:true}).canApply,true);assert.equal(M.map(s,{...decision(s),kind:'rail'}).canApply,false);delete s.marks[0].latticeCap;assert.equal(M.map(s,{...decision(s),acceptLatticeRepresentation:true}).canApply,false);});
test('actual app conversion retains lattice source properties and materializer retains solid wall style',()=>{let s=source(),it=M.map(s,decision(s)).items[0],c=runtime();let center={...it,x:it.x+it.w/2,y:it.y+it.d/2};let made=c.PlanImport.toAppObjects({items:[center],rooms:[],walls:[]}).items[0];for(const k of ['latticeHeight','fencePattern','railInfill','railFrameColor','railCapColor','elev','latticeCap','latticePitch','latticeSlat'])assert.equal(made[k],it[k]);assert.equal(made.floor,2);assert.deepEqual(JSON.parse(JSON.stringify(made.sourceObjectMapping)),it.sourceObjectMapping);let text=require('node:fs').readFileSync('assets/js/plan-import.js','utf8');vm.runInContext(text.slice(text.indexOf('  function materializeSceneObjects(plan)'),text.indexOf('  // その間取りに出てくる階。')),c);let out=c.materializeSceneObjects({items:[],rooms:[],walls:[{id:'sourcewall',x1:0,y1:0,x2:1000,y2:0,floor:2,thick:60,wallStyle:'balcony-fence',sourceObjectMapping:{sourceId:'s'}}]});assert.equal(out.walls[0].wallStyle,'balcony-fence');assert.notEqual(out.walls[0].id,'sourcewall');assert.equal(out.walls[0].sourceObjectMapping.sourceId,'s');});
