const test=require('node:test'),assert=require('node:assert/strict'),M=require('../../assets/js/source-object-mapping.js');
const catalogue={get:id=>id==='sofa'?{id,w:1800,d:800,h:750,front:'+Z',genericColor:true}:null};
const source=()=>({marks:[{guess:'sofa',floor:2,x:1000,y:2000,w:1900,d:850,rot:90,frontDirection:{x:-1,y:0},color:'#aabbcc'}]});
const decision=s=>({sourceId:'marks:0',sourceSnapshot:M.candidates(s)[0].snapshot,reviewed:true,semantic:'sofa',catalogId:'sofa',sizingPolicy:'fit-source',acceptDiagramColor:true});
test('reviewed furniture uses real catalogue, source envelope, rotation, floor and immutable provenance',()=>{let s=source(),before=JSON.stringify(s),r=M.map(s,decision(s),catalogue);assert.equal(r.canApply,true);assert.deepEqual([r.items[0].x,r.items[0].y,r.items[0].w,r.items[0].d,r.items[0].floor,r.items[0].rot],[50,1575,1900,850,2,90]);assert.equal(r.items[0].color,'#aabbcc');assert.equal(r.items[0].sourceObjectMapping.assumptions[0].measured,false);assert.equal(JSON.stringify(s),before);assert.deepEqual(JSON.parse(JSON.stringify(r)),r);});
test('stale evidence, unknown asset, ambiguous sizing and unreviewed finish refuse physical application',()=>{for(const change of [{sourceSnapshot:'old'},{catalogId:'invented'},{sizingPolicy:'native'},{acceptDiagramColor:false},{reviewed:false},{semantic:'bed'}]){let s=source(),r=M.map(s,{...decision(s),...change},catalogue);assert.equal(r.canApply,false);assert.equal(r.items.length,0);}});
test('source front and supplied dimensions are not silently repaired',()=>{let s=source();s.marks[0].frontDirection={x:1,y:0};assert.equal(M.map(s,decision(s),catalogue).canApply,false);s.marks[0].w=NaN;assert.equal(M.candidates(s).length,0);});
test('stairs retain candidates but cannot create unsafe slab cutouts',()=>{let s={items:[{type:'stair',floor:1,x:0,y:0,w:910,d:2730,rot:0}]},c=M.candidates(s)[0],r=M.map(s,{sourceId:c.id,sourceSnapshot:c.snapshot,reviewed:true},catalogue);assert.equal(r.canApply,false);assert.deepEqual(r.diagnostics,['stair_requires_renderer_cutout_isolation']);});
test('reviewed existing balcony fence requires actual endpoints and explicit unmeasured height assumption',()=>{let s={marks:[{guess:'railing',floor:3,x:100,y:0,w:200,d:30,start:{x:0,y:0},end:{x:200,y:0},thick:30}]},c=M.candidates(s)[0],d={sourceId:c.id,sourceSnapshot:c.snapshot,reviewed:true,kind:'rail',acceptSolidParapet:true},before=JSON.stringify(s);assert.equal(M.map(s,d,catalogue).canApply,false);let r=M.map(s,{...d,acceptDisplayHeightMm:1100},catalogue);assert.equal(r.canApply,true);assert.equal(r.walls[0].wallStyle,'balcony-fence');assert.equal(r.walls[0].sourceObjectMapping.assumptions[0].measured,false);assert.equal(JSON.stringify(s),before);s.marks[0].heightMm=900;c=M.candidates(s)[0];assert.equal(M.map(s,{...d,sourceSnapshot:c.snapshot,acceptDisplayHeightMm:1100},catalogue).canApply,false);});

test('unknown rotation is a separate cardinal display assumption; invalid angle and overriding known source rotation refuse',()=>{
 const source={marks:[{guess:'chair',floor:2,x:100,y:200,w:360,d:520}]},candidate=M.candidates(source)[0];
 const catalogue={get:()=>({id:'chair',w:392,d:507,h:703})},d={sourceId:candidate.id,sourceSnapshot:candidate.snapshot,reviewed:true,catalogId:'chair',semantic:'chair',sizingPolicy:'fit-source',displayRotationDeg:90};
 const r=M.map(source,d,catalogue);assert.equal(r.canApply,true);assert.deepEqual([r.items[0].w,r.items[0].d],[520,360]);assert.equal(r.items[0].x+r.items[0].w/2,100);assert.equal(source.marks[0].rot,undefined);
 for(const value of [45,null,-90,360])assert.equal(M.map(source,{...d,displayRotationDeg:value},catalogue).canApply,false);
 source.marks[0].rot=180;assert.equal(M.map(source,{...d,sourceSnapshot:M.candidates(source)[0].snapshot},catalogue).canApply,false);
});
test('generic furniture baseline notices native pose/finish edits and roundtrip retains source provenance',()=>{const s=source(),r=M.map(s,decision(s),catalogue),it=r.items[0];it.sourceObjectMapping.editorDisplayBaseline=M.displayGeometry(it);const original=it.sourceObjectMapping.sourceSnapshot;assert.equal(M.currentStatus(it).edited,false);const loaded=JSON.parse(JSON.stringify(it));assert.equal(M.currentStatus(loaded).edited,false);for(const field of ['x','y','w','d','rot','elev','color','type','finishColors','finishRoughness','finishTextures']){const edited=JSON.parse(JSON.stringify(it));edited[field]=typeof edited[field]==='number'?edited[field]+10:'changed';assert.equal(M.currentStatus(edited).edited,true);assert.equal(edited.sourceObjectMapping.sourceSnapshot,original);}assert.match(M.currentStatus(it).message,/未測定/);});

test('source display baselines own nested finishes rather than aliasing current native material edits',()=>{const it=M.map(source(),decision(source()),catalogue).items[0];it.finishColors={wood:'#aabbcc'};it.sourceObjectMapping.editorDisplayBaseline=M.displayGeometry(it);it.finishColors.wood='#112233';assert.equal(M.currentStatus(it).edited,true);assert.equal(it.sourceObjectMapping.editorDisplayBaseline.finishColors.wood,'#aabbcc');});

test('initial beside translation keeps source and baseline distinct without treating initial placement as a user edit',()=>{const it=M.map(source(),decision(source()),catalogue).items[0];it.sourceObjectMapping.editorDisplayBaseline=M.displayGeometry(it);const raw=it.sourceObjectMapping.sourceSnapshot;it.x+=5000;M.initialTranslation({items:[it]},5000);assert.equal(M.currentStatus(it).edited,false);assert.equal(it.sourceObjectMapping.sourceSnapshot,raw);assert.equal(it.sourceObjectMapping.displayTranslation.x,5000);assert.equal(it.sourceObjectMapping.registrationDisplayBaseline.x,it.x-5000);assert.throws(()=>M.initialTranslation({items:[it]},5000),/来歴/);});

test('failed initial furniture translation leaves every provenance baseline unchanged',()=>{const first=M.map(source(),decision(source()),catalogue).items[0],second=JSON.parse(JSON.stringify(first));for(const it of [first,second]){it.sourceObjectMapping.editorDisplayBaseline=M.displayGeometry(it);it.x+=5000;}second.y+=10;const plan={items:[first,second]},before=JSON.stringify(plan);assert.throws(()=>M.initialTranslation(plan,5000),/来歴/);assert.equal(JSON.stringify(plan),before);});
test('support selection and derived native support height invalidate display provenance without rewriting source',()=>{const it=M.map(source(),decision(source()),catalogue).items[0];it.sourceObjectMapping.editorDisplayBaseline=M.displayGeometry(it);const raw=it.sourceObjectMapping.sourceSnapshot;M.captureSupportBaseline([it],()=>3000);assert.equal(M.currentStatus(it,3000).status,'reviewed-display-baseline');assert.equal(M.currentStatus(it,3600).status,'edited-or-unverified');assert.equal(M.currentStatus(it).status,'support-unverified');it.baseRoom='raised-room';it.baseLevel=600;assert.equal(M.currentStatus(it,3600).edited,true);const loaded=JSON.parse(JSON.stringify(it));assert.equal(M.currentStatus(loaded,3600).edited,true);delete loaded.baseRoom;delete loaded.baseLevel;assert.equal(M.currentStatus(loaded,3000).status,'reviewed-display-baseline');assert.equal(loaded.sourceObjectMapping.sourceSnapshot,raw);M.captureSupportBaseline([loaded],()=>3600);assert.equal(loaded.sourceObjectMapping.supportDisplayBaseline.baseYmm,3000);});

test('unsupported explicit source finish and elevation reject instead of silently materializing defaults',()=>{for(const extra of [{finish:'walnut'},{material:'steel'},{elevationMm:600},{elev:600}]){const s=source();Object.assign(s.marks[0],extra);const before=JSON.stringify(s),r=M.map(s,decision(s),catalogue);assert.equal(r.canApply,false);assert.equal(r.items.length,0);assert.equal(JSON.stringify(s),before);assert.ok(r.diagnostics.some(d=>d==='source_finish_mapping_unresolved'||d==='source_elevation_mapping_unresolved'));}});
