// Isolated click checks; all AI requests are in-page mocks, no live provider.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/tmp/webcad-browser-check/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const output=path.resolve(process.env.OUTPUT_DIR||'/tmp/webcad-source-selector');fs.mkdirSync(output,{recursive:true});const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal']});try{
 const page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[],blocked=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname==='127.0.0.1'&&!u.pathname.startsWith('/api/'))return route.continue();blocked.push(u.origin+u.pathname);return route.abort();});
 await page.goto(process.env.APP_URL||'http://127.0.0.1:60129/');await page.waitForFunction(()=>window.PlanImport&&window.DATA);await page.waitForSelector('#app-loading',{state:'hidden',timeout:60000});
 const png=await page.evaluate(()=>{closePresetChoice();document.querySelector('.offline-preview-banner')?.remove();document.getElementById('plan-import-file').disabled=false;const label=document.createElement('div');label.className='airx-source-note';label.textContent='未公開UIの確認・APIは模擬応答／AI未実行';document.getElementById('plan-import-title').parentElement.after(label);window.__mockGate=false;window.__mockPending=false;window.__mockError='scene_ir_v3_job_mismatch';window.__mockCalls=[];const localFetch=window.fetch;window.fetch=(url,opts)=>{if(url==='/api/ai/quota')return Promise.resolve({json:async()=>({counted:!!window.__mockQuota,left:window.__mockQuota?0:null,sceneIRV3:window.__mockGate?{enabled:true}:undefined})});if(url==='/api/ai/import-plan'){window.__mockCalls.push(JSON.parse(opts.body));const reply=()=>({status:window.__mockSuccess?200:409,text:async()=>JSON.stringify(window.__mockSuccess?{extractionContract:'scene-ir-v3',sceneIR:window.__mockSource,rawResponse:JSON.stringify(window.__mockSource)}:{error:window.__mockError,extractionContract:'scene-ir-v3'})});if(window.__mockPending)return new Promise(r=>window.__mockResolve=()=>r(reply()));return Promise.resolve(reply());}if(typeof url==='string'&&url.startsWith('/api/'))throw Error('Unexpected mocked API '+url);return localFetch(url,opts);};const c=document.createElement('canvas');c.width=400;c.height=300;const g=c.getContext('2d');g.fillStyle='white';g.fillRect(0,0,400,300);g.strokeRect(30,30,200,160);return c.toDataURL('image/png').split(',')[1];});
 const upload=()=>page.locator('#plan-import-file').setInputFiles({name:'synthetic-no-ai.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});
 await page.evaluate(()=>openPlanImport());await upload();await page.waitForSelector('#plan-import-step2',{state:'visible'});assert.equal(await page.locator('#plan-import-mode-wrap').isVisible(),false);
 // Both off and each gate independently off hide the opt-in; normal read still v1.
 await page.locator('#plan-import-run').click();assert.equal(await page.evaluate(()=>__mockCalls[0].extractionContract),undefined);
 await page.evaluate(()=>{SCENE_IR_V3_IMAGE_IMPORT=true;openPlanImport();});assert.equal(await page.locator('#plan-import-mode-wrap').isVisible(),false);
 await page.evaluate(()=>{SCENE_IR_V3_IMAGE_IMPORT=false;__mockGate=true;openPlanImport();});await page.waitForFunction(()=>PlanImport.state.sceneIRV3Available===true);assert.equal(await page.locator('#plan-import-mode-wrap').isVisible(),false);
 await page.evaluate(()=>{SCENE_IR_V3_IMAGE_IMPORT=true;openPlanImport();});await page.waitForSelector('#plan-import-mode-wrap',{state:'visible'});assert.equal(await page.locator('#plan-import-mode').inputValue(),'v1');
 await page.locator('#plan-import-hint').fill('retained legacy hint');await page.locator('#plan-import-mode').selectOption('scene-ir-v3');assert.equal(await page.locator('#plan-import-hint').isDisabled(),true);assert.match(await page.locator('#plan-import-mode-note').textContent(),/実験中/);await page.screenshot({path:path.join(output,'desktop-experimental-selector.png')});
 const before=await page.evaluate(()=>({data:JSON.stringify(DATA),history:HISTORY.length}));await page.evaluate(()=>__mockPending=true);await page.locator('#plan-import-run').click();assert.equal(await page.locator('#plan-import-mode').isDisabled(),true);assert.equal(await page.locator('#plan-import-run').isDisabled(),true);await page.evaluate(()=>__mockResolve());await page.waitForFunction(()=>!PlanImport.state.busy);assert.match(await page.locator('#plan-import-status').textContent(),/新しいAPI呼び出し/);assert.equal(await page.evaluate(()=>__mockCalls.length),2);assert.equal(await page.evaluate(()=>__mockCalls[1].extractionContract),'scene-ir-v3');assert.equal(await page.evaluate(()=>__mockCalls[1].hint),'');
 // Capability disappearance keeps selection visible, but blocks dispatch and permits explicit fallback.
 await page.evaluate(()=>{__mockGate=false;openPlanImport();});await page.waitForFunction(()=>PlanImport.state.sceneIRV3Available===false);assert.equal(await page.locator('#plan-import-run').isDisabled(),true);assert.match(await page.locator('#plan-import-mode-note').textContent(),/現在使えません/);await page.locator('#plan-import-mode').selectOption('v1');assert.equal(await page.locator('#plan-import-mode-wrap').isVisible(),false);assert.equal(await page.locator('#plan-import-hint').inputValue(),'retained legacy hint');
 await page.evaluate(()=>{__mockGate=true;openPlanImport();});await page.waitForSelector('#plan-import-mode-wrap',{state:'visible'});
 // Synthetic two-page state exercises selector guard without locating/reading a PDF.
 await page.evaluate(()=>{PlanImport.state.pages=['first','second'];PlanImport.state.pageReview=null;setPlanImportExtractionMode('v1');});assert.equal(await page.locator('#plan-import-source-mode').isDisabled(),true);assert.match(await page.locator('#plan-import-mode-note').textContent(),/複数ページ/);
 await page.evaluate(()=>{PlanImport.state.pages=null;setPlanImportExtractionMode('v1');});await page.locator('#plan-import-mode').selectOption('scene-ir-v3');await page.locator('#plan-import-step2').getByRole('button',{name:'全体に戻す'}).click();await page.locator('#plan-import-modal .unity-render-close').click();await page.evaluate(()=>openPlanImport());assert.equal(await page.locator('#plan-import-mode').inputValue(),'v1');await page.locator('#plan-import-mode').selectOption('scene-ir-v3');await page.locator('#plan-import-modal').getByRole('button',{name:'やり直す',exact:true}).click();assert.equal(await page.evaluate(()=>PlanImport.state.extractionMode),'v1');await upload();await page.locator('#plan-import-mode').selectOption('scene-ir-v3');
 await page.setViewportSize({width:390,height:844});await page.locator('#plan-import-mode-wrap').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'mobile-experimental-selector.png')});const bounds=await page.locator('#plan-import-mode').boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=390);assert.ok(bounds.height>=40);
 await page.evaluate(()=>{__mockQuota=true;openPlanImport();});await page.waitForFunction(()=>PlanImport.state.quotaBlocked);assert.equal(await page.locator('#plan-import-run').isDisabled(),true);await page.locator('#plan-import-mode').selectOption('v1');assert.equal(await page.locator('#plan-import-run').isDisabled(),true);await page.locator('#plan-import-mode').selectOption('scene-ir-v3');assert.equal(await page.locator('#plan-import-run').isDisabled(),true);await page.evaluate(()=>{__mockQuota=false;openPlanImport();});await page.waitForFunction(()=>!PlanImport.state.quotaBlocked);
 await page.evaluate(()=>{__mockPending=false;__mockSuccess=true;__mockSource={sceneVersion:3,units:'mm',coordinateSystem:'x-east-y-south-clockwise',annotations:[],walls:[],rooms:[],openings:[],objects:[],siteRegions:[],buildingFootprints:[],bindings:[],connections:[]};});await page.locator('#plan-import-run').click();await page.waitForFunction(()=>PlanImport.state.result&&PlanImport.state.result.sceneIR);assert.equal(await page.evaluate(()=>PlanImport.state.result.sceneIR.sceneVersion),3);assert.equal(await page.evaluate(()=>PlanImport.state.result.extraction.rawResponse===JSON.stringify(__mockSource)),true);
 const after=await page.evaluate(()=>({data:JSON.stringify(DATA),history:HISTORY.length}));assert.deepEqual(after,before);assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);const result={mockOnly:true,paidCalls:0,stablePreviewUntouched:true,checks:['both-gates-off','client-only','server-only','default-v1','explicit-source','busy','single-image','multi-page','gate-loss','explicit-fallback','failure-no-retry','close-reset','mobile-fit','data-history-unchanged','successful-source-staging','quota-exhaustion-remains-disabled'],calls:await page.evaluate(()=>__mockCalls.map(c=>({imageCount:c.images.length,hint:c.hint,extractionContract:c.extractionContract||'v1'}))),errors,blocked};fs.writeFileSync(path.join(output,'browser-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
