const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
globalThis.crypto=globalThis.crypto||require('node:crypto').webcrypto;
const finish=require('../../assets/js/tailored-sofa-finish.js'),quality=require('../../assets/js/model-quality.js');
const bytes=fs.readFileSync(path.join(__dirname,'../../',finish.url)),buffer=()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength);
const json=JSON.parse(bytes.subarray(20,20+bytes.readUInt32LE(12)).toString()),binStart=20+bytes.readUInt32LE(12)+8;
const three=import('data:text/javascript;base64,'+fs.readFileSync(path.join(__dirname,'../../assets/vendor/three/build/three.module.js')).toString('base64'));
const opt=(colors={})=>({type:finish.type,tailoredSofaColors:{version:1,colors}});
async function fixture(){
 const T=await three,scene=new T.Group(),types={5126:Float32Array,5123:Uint16Array,5125:Uint32Array},counts={SCALAR:1,VEC2:2,VEC3:3,VEC4:4};
 const normal=new T.Texture(),materials=json.materials.map((m,i)=>{const p=m.pbrMetallicRoughness,c=i===0?new T.MeshPhysicalMaterial():new T.MeshStandardMaterial();c.name=m.name;c.color.fromArray(p.baseColorFactor);c.roughness=p.roughnessFactor;c.metalness=p.metallicFactor;c.side=T.DoubleSide;if(i===0){c.normalMap=normal;c.normalScale.set(m.normalTexture.scale,-m.normalTexture.scale);c.sheen=1;c.sheenColor.setRGB(1,1,1);c.sheenRoughness=.5;}return c;});
 function attr(id){const a=json.accessors[id],v=json.bufferViews[a.bufferView],C=types[a.componentType],size=counts[a.type],start=binStart+v.byteOffset+(a.byteOffset||0),copy=bytes.subarray(start,start+a.count*size*C.BYTES_PER_ELEMENT);return new T.BufferAttribute(new C(Uint8Array.from(copy).buffer),size,!!a.normalized);}
 const nodes=json.nodes.map(n=>{const p=json.meshes[n.mesh].primitives[0],g=new T.BufferGeometry();for(const [key,id]of Object.entries(p.attributes))g.setAttribute({POSITION:'position',NORMAL:'normal',TEXCOORD_0:'uv'}[key],attr(id));g.setIndex(attr(p.indices));const o=new T.Mesh(g,materials[p.material]);o.name=n.name.replace(/ /g,'_').replace(/\./g,'');if(n.translation)o.position.fromArray(n.translation);if(n.rotation)o.quaternion.fromArray(n.rotation);if(n.scale)o.scale.fromArray(n.scale);scene.add(o);return o;});
 await finish.register({scene,parser:{getDependency:async(_,i)=>nodes[i]}},await finish.inspect(buffer()));quality.prepare(scene,finish.url);assert.equal(finish.status(scene).ok,true);return {T,scene,nodes,materials,normal};
}
function fingerprint(scene){const out=[];scene.traverse(o=>{if(o.isMesh)out.push({name:o.name,position:o.position.toArray(),quaternion:o.quaternion.toArray(),scale:o.scale.toArray(),positions:Array.from(o.geometry.attributes.position.array),material:{color:o.material.color.getHexString(),roughness:o.material.roughness,metalness:o.material.metalness,normalMap:o.material.normalMap,normalScale:o.material.normalScale.toArray(),sheen:o.material.sheen,sheenColor:o.material.sheenColor?.getHexString(),sheenRoughness:o.material.sheenRoughness,channel:o.material.userData.finishChannel||null}});});return out;}
function changes(before,after,indices,color){for(let i=0;i<14;i++){const a={...before[i],material:{...before[i].material}},b={...after[i],material:{...after[i].material}};if(indices.includes(i)){assert.equal(b.material.color,color);delete a.material.color;delete b.material.color;delete a.material.channel;delete b.material.channel;}assert.deepEqual(b,a);}}
test('exact full GLB hash gates the audited node/primitive configuration',async()=>{const a=await finish.inspect(buffer());assert.equal(a.ok,true);assert.equal(a.sha256,finish.sha256);const b=new Uint8Array(buffer());b[b.length-1]^=1;const mismatch=await finish.inspect(b.buffer);assert.equal(mismatch.ok,false);assert.equal(mismatch.reason,'asset-hash');});
test('only strict explicit v1 colors opt in; old dormant fields and unsupported settings stay inactive',()=>{assert.equal(finish.colors({type:finish.type,finishColors:{seat:'#ff3300'},finishTextures:{body:'wood_oak'},finishRoughness:{body:.22}}),null);for(const item of [{type:'other',tailoredSofaColors:{version:1,colors:{seat:'#ff3300'}}},{type:finish.type,tailoredSofaColors:{version:'1',colors:{}}},{type:finish.type,tailoredSofaColors:{version:2,colors:{}}},{type:finish.type,tailoredSofaColors:{version:1,colors:{seat:'red'}}},{type:finish.type,tailoredSofaColors:{version:1,colors:{fabric:'#ffffff'}}},{type:finish.type,tailoredSofaColors:{version:1,colors:{constructor:'#ffffff'}}},{type:finish.type,tailoredSofaColors:{version:1,colors:{},roughness:{seat:.22}}}]){assert.equal(finish.colors(item),null);assert.equal(finish.active(item),false);}assert.equal(finish.active(opt()),false);assert.equal(finish.active(opt({seat:'#ff3300'})),true);});
test('color values must be primitive strings; coercible arrays, boxed strings and prototype spoofing are rejected without coercion',()=>{
 let coerced=0;const spoof={toString(){coerced++;return '#ff3300';}},inherited=Object.create({toString(){coerced++;return '#ff3300';}});
 for(const key of ['seat','body'])for(const value of [['#ff3300'],new String('#ff3300'),spoof,inherited,Object.create(String.prototype),null,undefined,0,16724736,NaN,false,Symbol('#ff3300'),()=> '#ff3300']){
  const item=opt({[key]:value});assert.equal(finish.colors(item),null);assert.equal(finish.active(item),false);
 }
 assert.equal(coerced,0);assert.deepEqual(finish.colors(opt({seat:'#FF3300',body:'#0055ff'})),{seat:'#FF3300',body:'#0055ff'});
});
test('only own data fields in plain or null-prototype records are accepted, including real cross-realm saved plans',()=>{
 let reads=0;const inherited=Object.assign(Object.create({seat:'#ff3300'}),{body:'#0055ff'}),accessor={};Object.defineProperty(accessor,'seat',{enumerable:true,get(){reads++;return '#ff3300';}});
 const rootAccessor={version:1};Object.defineProperty(rootAccessor,'colors',{enumerable:true,get(){reads++;return {seat:'#ff3300'};}});
 for(const item of [opt(inherited),opt(accessor),opt(JSON.parse('{"__proto__":"#ff3300"}')),opt({prototype:'#ff3300'}),opt({constructor:'#ff3300'}),opt({[Symbol('seat')]:'#ff3300'}),{type:finish.type,tailoredSofaColors:rootAccessor},{type:finish.type,tailoredSofaColors:Object.assign(Object.create({version:1}),{colors:{seat:'#ff3300'}})}])assert.equal(finish.colors(item),null);
 assert.equal(reads,0);const c=Object.assign(Object.create(null),{seat:'#ff3300'}),v=Object.assign(Object.create(null),{version:1,colors:c});assert.deepEqual(finish.colors({type:finish.type,tailoredSofaColors:v}),{seat:'#ff3300'});
 const cross=vm.runInNewContext('({type:"custom-sofa-tailored",tailoredSofaColors:{version:1,colors:{seat:"#ff3300"}}})');assert.deepEqual(finish.colors(cross),{seat:'#ff3300'});
});
test('malformed saved JSON colors fail before finish/clone calls and preserve native materials and geometry',async()=>{
 const f=await fixture(),before=fingerprint(f.scene),p=f.T.Material.prototype,old=p.clone;let clones=0,finishes=0;p.clone=function(){clones++;return old.call(this);};
 try{for(const raw of ['{"seat":["#ff3300"]}','{"body":null}','{"seat":16724736}','{"seat":"#ff3300","body":["#0055ff"]}','{"__proto__":"#ff3300"}']){
  const item=JSON.parse('{"type":"custom-sofa-tailored","tailoredSofaColors":{"version":1,"colors":'+raw+'}}'),copy=f.scene.clone(true),result=finish.apply(copy,f.scene,item,{applyFinishes(){finishes++;}});assert.equal(result.applied,false);assert.equal(result.reason,'not-opted-in');assert.deepEqual(fingerprint(copy),before);
 }assert.equal(clones,0);assert.equal(finishes,0);assert.deepEqual(fingerprint(f.scene),before);}finally{p.clone=old;}
});
test('seat-only recolors exact nodes 8/11; body, legs, seams and all authored surface/geometry values stay identical',async()=>{const f=await fixture(),before=fingerprint(f.scene),copy=f.scene.clone(true),sourceMaterials=f.nodes.map(o=>o.material);const result=finish.apply(copy,f.scene,opt({seat:'#ff3300'}),quality);assert.equal(result.applied,true);changes(before,fingerprint(copy),[8,11],'ff3300');assert.deepEqual(fingerprint(f.scene),before);for(let i=0;i<14;i++)assert.equal(copy.children[i].material===sourceMaterials[i],![8,11].includes(i));assert(f.materials.every(m=>!m.userData.finishChannel));});
test('body-only recolors exact nodes 0/1/4/7/9/12 while seats, legs and seams stay native',async()=>{const f=await fixture(),before=fingerprint(f.scene),copy=f.scene.clone(true);assert.equal(finish.apply(copy,f.scene,opt({body:'#0055ff'}),quality).applied,true);changes(before,fingerprint(copy),[0,1,4,7,9,12],'0055ff');assert.deepEqual(fingerprint(f.scene),before);});
test('two instances independently own their changed materials without tagging shared templates',async()=>{const f=await fixture(),a=f.scene.clone(true),b=f.scene.clone(true),native=fingerprint(f.scene);finish.apply(a,f.scene,opt({seat:'#ff3300'}),quality);finish.apply(b,f.scene,opt({body:'#0055ff'}),quality);changes(native,fingerprint(a),[8,11],'ff3300');changes(native,fingerprint(b),[0,1,4,7,9,12],'0055ff');assert.notEqual(a.children[8].material,b.children[8].material);assert.notEqual(a.children[0].material,b.children[0].material);assert.deepEqual(fingerprint(f.scene),native);});
test('old plan, opted empty, reset and unknown version create no materials and remain byte-exact native',async()=>{const f=await fixture(),before=fingerprint(f.scene),p=f.T.Material.prototype,clone=p.clone;let calls=0;p.clone=function(){calls++;return clone.call(this);};try{for(const item of [{type:finish.type,finishColors:{body:'#ff3300'},finishTextures:{seat:'tile_floor'},finishRoughness:{seat:.22}},opt(),{type:finish.type,tailoredSofaColors:{version:2,colors:{seat:'#ff3300'}}}]){const copy=f.scene.clone(true);finish.apply(copy,f.scene,item,quality);assert.deepEqual(fingerprint(copy),before);}assert.equal(calls,0);}finally{p.clone=clone;}});
test('repeated color/reset cycles dispose intermediate materials immediately and final materials exactly once',async()=>{const f=await fixture(),p=f.T.Material.prototype,old=p.clone,events=[];p.clone=function(){const m=old.call(this),r={m,count:0};m.addEventListener('dispose',()=>r.count++);events.push(r);return m;};try{for(let j=0;j<12;j++){const copy=f.scene.clone(true);finish.apply(copy,f.scene,opt({seat:'#ff3300',body:'#0055ff'}),quality);for(const m of new Set(copy.children.map(o=>o.material)))if(m.userData.finishChannel)m.dispose();const reset=f.scene.clone(true);finish.apply(reset,f.scene,opt(),quality);}assert.equal(events.length,12*16);assert(events.every(r=>r.count===1));assert(f.materials.every(m=>!m.userData.finishChannel));assert.equal(f.normal.version,0);}finally{p.clone=old;}});
test('private certificate transfers across pane-owned geometry/material clones with no cache tags',async()=>{const f=await fixture(),copy=f.scene.clone(true);copy.traverse(o=>{if(o.isMesh){o.geometry=o.geometry.clone();o.material=o.material.clone();}});finish.transfer(f.scene,copy);assert.equal(finish.status(copy).ok,true);const item=copy.clone(true);assert.equal(finish.apply(item,copy,opt({seat:'#ff3300'}),quality).applied,true);assert(copy.children.every(o=>!o.material.userData.finishChannel));assert(f.scene.children.every(o=>!o.material.userData.finishChannel));});
test('node transform/config mismatch fails closed and preserves existing runtime rendering',async()=>{const f=await fixture(),copy=f.scene.clone(true);copy.children[8].position.x+=.001;const before=fingerprint(copy),result=finish.apply(copy,f.scene,opt({seat:'#ff3300'}),quality);assert.equal(result.applied,false);assert.equal(result.reason,'unreviewed');assert.match(result.message,/未監査/);assert.deepEqual(fingerprint(copy),before);});
test('cache geometry/material/primitive mismatch fails closed',async()=>{for(const mutate of [f=>{f.nodes[8].geometry.attributes.position.array[0]+=.01;},f=>{f.nodes[8].material=f.materials[1];},f=>{f.nodes[8].material=[f.materials[0]];},f=>{f.materials[0].roughness=.22;},f=>{f.materials[0].color.set('#ff3300');},f=>{f.scene.remove(f.nodes[13]);}]){const f=await fixture();mutate(f);assert.equal(finish.status(f.scene).ok,false);const copy=f.scene.clone(true);assert.equal(finish.apply(copy,f.scene,opt({seat:'#ff3300'}),quality).applied,false);}});
test('a forged or mismatched inspection cannot register an audited runtime',async()=>{const f=await fixture();await finish.register({scene:f.scene,parser:{getDependency:async(_,i)=>f.nodes[i]}},{ok:true,sha256:finish.sha256,proof:{}});assert.equal(finish.status(f.scene).ok,false);assert.equal(finish.apply(f.scene.clone(true),f.scene,opt({seat:'#ff3300'}),quality).applied,false);});
test('finish failure rolls back instance material references and disposes every temporary clone',async()=>{const f=await fixture(),copy=f.scene.clone(true),before=fingerprint(copy),p=f.T.Material.prototype,old=p.clone,events=[];p.clone=function(){const m=old.call(this),r={count:0};m.addEventListener('dispose',()=>r.count++);events.push(r);return m;};try{const result=finish.apply(copy,f.scene,opt({seat:'#ff3300'}),{applyFinishes(){throw Error('synthetic finishing failure');}});assert.equal(result.applied,false);assert.deepEqual(fingerprint(copy),before);assert.equal(events.length,2);assert(events.every(r=>r.count===1));}finally{p.clone=old;}});
const source=require('./app-source.cjs').appSource();
function fn(name,sandbox){const a=source.indexOf('function '+name+'('),b=source.indexOf('\nfunction ',a+1);vm.createContext(sandbox);vm.runInContext(source.slice(a,b),sandbox);return sandbox[name];}
test('existing UI exposes exactly two color inputs after explicit opt-in, and no catalogue channels',async()=>{const f=await fixture(),model={id:finish.type},it=opt(),s={ST:{selected:it},getItemFinishModel:()=>model,TailoredSofaFinish:finish,getTailoredSofaFinishRuntime:()=>finish,_modelCache:{[finish.url]:f.scene},selectedKitchenConfigurationHtml:()=>'',escHtml:x=>x,MODEL_FINISH_TEXTURES:[]};const html=fn('selectedModelFinishesHtml',s)(it);assert.equal((html.match(/type="color"/g)||[]).length,2);assert(!html.includes('finish-texture-'));assert(!html.includes('finish-roughness-'));assert.equal(model.finishChannels,undefined);const legacy=fn('selectedModelFinishesHtml',s)({type:finish.type,finishColors:{seat:'#ff3300'}});assert(legacy.includes('enableSelectedTailoredSofaColors'));assert(!legacy.includes('type="color"'));});
test('opt-in color setter and reset preserve dormant old fields; texture/roughness calls remain rejected',async()=>{const f=await fixture(),it={...opt(),finishColors:{seat:'#112233'},finishTextures:{seat:'wood_oak'},finishRoughness:{body:.22}},s={ST:{selected:it},TailoredSofaFinish:finish,getTailoredSofaFinishRuntime:()=>finish,_modelCache:{[finish.url]:f.scene},getItemFinishModel:()=>({}),MODEL_FINISH_TEXTURES:[['wood_oak','Oak']],updateSelectedProp:(k,v)=>it[k]=v};const set=fn('updateSelectedModelFinish',s);set('seat','#ff3300');assert.deepEqual(JSON.parse(JSON.stringify(it.tailoredSofaColors)),{version:1,colors:{seat:'#ff3300'}});fn('updateSelectedModelTexture',s)('seat','wood_oak');fn('updateSelectedModelRoughness',s)('body','.22');fn('updateSelectedModelFinishReset',s)();assert.deepEqual(JSON.parse(JSON.stringify(it.tailoredSofaColors)),{version:1,colors:{}});assert.deepEqual(it.finishColors,{seat:'#112233'});assert.deepEqual(it.finishTextures,{seat:'wood_oak'});assert.deepEqual(it.finishRoughness,{body:.22});});
test('only active explicit sofa colors bypass instancing; unselected opted colors still render normally',()=>{const s={ren:{},ST:{selected:null},GLTF_MODEL_CONFIG:{},FINISH_PROPS:[],TailoredSofaFinish:finish,getGltfNativeBox:()=>null};const queue=fn('queueFmpInstance',s);assert.equal(queue(finish.url,opt({seat:'#ff3300'}),{}),false);let reached=false;s.getGltfNativeBox=()=>{reached=true;return null;};queue(finish.url,opt(),{});assert.equal(reached,true);});
