const {test}=require('node:test'),assert=require('node:assert/strict'),V=require('../../assets/js/walk-tps-mesh-volumes.js'),F=require('../../assets/js/walk-tps-foundation.js');
const three=import('../../assets/vendor/three/build/three.module.js');
function record(T,g,m=new T.Matrix4()){g.computeBoundingBox();const b=g.boundingBox.clone().applyMatrix4(m);return {min:b.min,max:b.max,geometry:g,matrix:m};}
function frame(T){const positions=[];for(const [x,y,w,h] of [[-.45,1,.1,2],[.45,1,.1,2],[0,2,.9,.1]]){const g=new T.BoxGeometry(w,h,.15).toNonIndexed();g.translate(x,y,3);positions.push(...g.attributes.position.array);g.dispose();}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));return g;}
const origin={x:0,y:1,z:0},dir={x:0,y:0,z:1};
test('merged thin frame opens its real doorway while jamb remains a continuous solid',async()=>{const T=await three,r=record(T,frame(T));assert.ok(F.castBoxes(origin,dir,5,.24,[r])<3);assert.equal(V.cast(T,origin,dir,5,.24,[r]),5);assert.ok(V.cast(T,{x:.42,y:1,z:0},dir,5,.24,[r])<3);r.geometry.dispose();});
test('closed thin leaf blocks travel and a sphere starting inside has zero clearance',async()=>{const T=await three,g=new T.BoxGeometry(.8,2,.04);g.translate(0,1,3);const r=record(T,g);assert.ok(V.cast(T,origin,dir,5,.24,[r])<3);assert.equal(V.cast(T,{x:0,y:1,z:3},dir,5,.24,[r]),0);g.dispose();});
test('thick solid interior never becomes a hollow safe region',async()=>{const T=await three,r=record(T,new T.BoxGeometry(2,2,2));assert.equal(V.cast(T,{x:0,y:0,z:0},dir,5,.24,[r]),0);assert.equal(r.triangleBoxes,undefined);r.geometry.dispose();});
test('nonuniform scale and reflection preserve safe thin refinement',async()=>{const T=await three,r=record(T,frame(T),new T.Matrix4().makeScale(-2,1,2));assert.equal(V.cast(T,origin,dir,8,.24,[r]),8);assert.ok(V.cast(T,{x:.9,y:1,z:0},dir,8,.24,[r])<6);r.geometry.dispose();});
test('near-plane enlargement and unsupported geometry retain conservative coverage',async()=>{const T=await three,r=record(T,frame(T));assert.ok(V.cast(T,origin,dir,5,.5,[r])<3);r.geometry.attributes.position.array[0]=NaN;delete r.triangleBoxes;assert.equal(V.cast(T,origin,dir,5,.24,[r]),F.castBoxes(origin,dir,5,.24,[r]));r.geometry.dispose();});
test('bath surface cache never turns a thick camera solid into a hollow volume',async()=>{const T=await three,r=record(T,new T.BoxGeometry(2,2,2));assert.ok(V.surfaceBoxes(T,r).length);assert.equal(V.cast(T,{x:0,y:0,z:0},dir,5,.24,[r]),0);r.geometry.dispose();});
