'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const ROOT=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),css=fs.readFileSync(path.join(ROOT,'assets/ui-refinement.css'),'utf8');
const start=html.indexOf('function positionWalkHud(){'),end=html.indexOf('\n// 立面方向スナップ',start),source=html.slice(start,end);assert.ok(start>0&&end>start);
function rect(left,top,width,height){return {left,top,width,height,right:left+width,bottom:top+height};}
function setup({width=1280,height=900,wrapLeft=0,wrapTop=0,sidebar=280,header=72,nav=0,status=26,safeLeft=0,safeRight=0,safeBottom=0,safeTop=0,panelWidth=210,panelHeight=72,dpad=true}={}){
 const gap=width<=768?8:14,wr=rect(wrapLeft,wrapTop,width,height),elements={},observers=[];
 function fixed(id,r){elements[id]={style:{},_rect:r,getBoundingClientRect(){return this._rect;}};}
 function px(v){if(v?.startsWith('calc('))return Number(v.match(/calc\((\d+)/)[1])+safeRight;return Number.parseFloat(v)||0;}
 fixed('walk-hud',wr);fixed('c3d-wrap',wr);fixed('toolbar',rect(wrapLeft+gap,wrapTop+safeTop+gap,width-2*gap,header));fixed('sidebar',rect(wrapLeft,wrapTop,sidebar,height));fixed('bottom-nav',nav?rect(wrapLeft,wr.bottom-nav,width,nav):rect(0,0,0,0));fixed('statusbar',status?rect(wrapLeft,wr.bottom-status,width,status):rect(0,0,0,0));elements['walk-exit']={style:{},getBoundingClientRect(){return rect(wr.left+px(this.style.left),wr.top+px(this.style.top),192,width<=768?44:46);}};
 elements['walk-minimap']={style:{},getBoundingClientRect(){return rect(wr.right-gap-(width<=768?160:220),wr.top+px(this.style.top),width<=768?160:220,width<=768?128:176);}};
 if(dpad)elements['walk-dpad']={style:{},getBoundingClientRect(){const size=width<=768?162:168;return rect(wr.right-px(this.style.right||String(gap))-size,wr.bottom-px(this.style.bottom||String(gap))-size,size,size);}};
 elements['walk-tps-controls']={style:{},getBoundingClientRect(){const s=this.style,w=Math.min(panelWidth,px(s.maxWidth)||232),h=Math.min(panelHeight+(w<panelWidth?44:0),s.maxHeight!==undefined&&s.maxHeight!==''?px(s.maxHeight):Infinity);return rect(wr.right-px(s.right)-w,wr.bottom-px(s.bottom)-h,w,h);}};
 class ResizeObserver{constructor(fn){this.fn=fn;this.targets=[];observers.push(this);}observe(node){this.targets.push(node);}}
 const insets={'--safe-l':safeLeft,'--safe-r':safeRight,'--safe-bot':safeBottom,'--safe-top':safeTop};
 const context={document:{getElementById:id=>elements[id]||null},window:{innerWidth:width,getComputedStyle:()=>({getPropertyValue:name=>(insets[name]||0)+'px'})},ResizeObserver};vm.createContext(context);vm.runInContext(source,context);context.positionWalkHud();return {context,elements,wr,gap,observers,header,safeLeft,safeRight,safeBottom,safeTop,setPanelSize(w,h){panelWidth=w;panelHeight=h;},resizeHeight(h){height=h;wr.height=h;wr.bottom=wr.top+h;for(const id of ['bottom-nav','statusbar']){const r=elements[id]._rect;if(r.height){r.top=wr.bottom-r.height;r.bottom=wr.bottom;}}}};
}
function overlap(a,b){return a.width>0&&a.height>0&&b.width>0&&b.height>0&&a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top;}
function bounds(h){const tps=h.elements['walk-tps-controls'].getBoundingClientRect(),dp=h.elements['walk-dpad']?.getBoundingClientRect(),toolbar=h.elements.toolbar.getBoundingClientRect();assert.equal(h.elements['walk-tps-controls'].style.top,'auto');assert.equal(h.elements['walk-tps-controls'].style.left,'auto');assert.ok(tps.left>=h.wr.left+h.safeLeft+h.gap-0.001);assert.ok(tps.right<=h.wr.right-h.safeRight-h.gap+0.001);assert.ok(tps.bottom<=h.wr.bottom-h.safeBottom-h.gap+0.001);assert.ok(tps.top>=toolbar.bottom+h.gap-0.001);if(dp)assert.equal(overlap(tps,dp),false,'viewpoint controls do not cover movement buttons');assert.equal(overlap(tps,toolbar),false);assert.equal(overlap(tps,h.elements['walk-exit'].getBoundingClientRect()),false,'viewpoint controls do not cover Exit');assert.equal(overlap(tps,h.elements['walk-minimap'].getBoundingClientRect()),false,'viewpoint controls do not cover minimap');return {tps,dp};}
for(const [name,options] of [
 ['short desktop/tall status/Exit',{width:800,height:300,sidebar:280,status:26,panelHeight:128}],
 ['short desktop/sidebar',{width:1024,height:300,sidebar:280,status:26,panelHeight:108}],
 ['medium desktop/minimap overlap',{width:1280,height:500,sidebar:280,status:26,panelHeight:72}],
 ['desktop/sidebar/statusbar',{width:1280,height:900,sidebar:280,status:26}],
 ['phone portrait/navigation/notch',{width:390,height:844,sidebar:390,header:148,nav:78,status:28,safeLeft:0,safeRight:20,safeBottom:34,safeTop:24}],
 ['short phone/minimap overlap',{width:390,height:480,sidebar:390,header:104,nav:64,status:22,panelHeight:72}],
 ['compact landscape/navigation',{width:667,height:375,sidebar:667,header:148,nav:64,status:22,panelHeight:108}],
 ['narrow compact portrait/action/status',{width:320,height:380,sidebar:320,header:148,nav:64,status:22,panelHeight:108}],
 ['landscape notches',{width:740,height:390,sidebar:740,header:104,nav:64,safeLeft:44,safeRight:44,safeBottom:21,panelHeight:108}],
 ['offset compact comparison canvas',{width:420,height:380,wrapLeft:512,wrapTop:100,sidebar:420,header:104,nav:56,status:20,panelHeight:128}],
 ['offset comparison canvas',{width:420,height:640,wrapLeft:512,wrapTop:100,sidebar:420,header:104,nav:56,status:20,panelHeight:108}]
])test('right-bottom HUD stays in bounds: '+name,()=>{const h=setup(options),{tps,dp}=bounds(h);if(name.startsWith('compact')||name.startsWith('narrow'))assert.ok(tps.right<=dp.left-h.gap);else if(!name.includes('offset'))assert.ok(tps.bottom<=dp.top-h.gap||tps.right<=dp.left-h.gap);});
test('compact landscape also avoids the existing minimap when vertical space forces the side lane',()=>{const h=setup({width:667,height:375,header:148,nav:64,panelHeight:108}),{tps}=bounds(h);assert.equal(overlap(tps,h.elements['walk-minimap'].getBoundingClientRect()),false);});
test('hidden/missing navigation and D-pad place controls at safe right-bottom without inventing an offset',()=>{const h=setup({width:390,height:700,header:104,sidebar:390,nav:0,status:0,safeBottom:34,dpad:false});bounds(h);assert.equal(h.elements['walk-tps-controls'].style.bottom,'42px');});
test('panel action/status reflow and canvas resizing reuse one observer and recalculate safe placement',()=>{const h=setup({width:390,height:600,header:104,nav:64,panelHeight:72});assert.equal(h.observers.length,1);assert.equal(h.observers[0].targets.length,3);const first=bounds(h);assert.ok(first.tps.bottom<=first.dp.top-h.gap);h.setPanelSize(210,150);h.observers[0].fn();const expanded=bounds(h);assert.ok(expanded.tps.right<=expanded.dp.left-h.gap,'expanded TPS action/status clears minimap in side lane');h.resizeHeight(844);h.observers[0].fn();const resized=bounds(h);assert.ok(resized.tps.bottom<=resized.dp.top-h.gap,'taller canvas restores above-D-pad placement');assert.equal(h.observers.length,1);});
test('side-lane height reservation uses canvas-relative Exit coordinates for offset comparison panes',()=>{const h=setup({width:420,height:380,wrapLeft:512,wrapTop:100,sidebar:420,header:104,nav:56,status:20,panelHeight:128});bounds(h);assert.equal(h.elements['walk-tps-controls'].style.maxHeight,'144px');});
test('ultra-short canvas never forces a 60px panel across reserved Exit space; content can require scrolling',()=>{const h=setup({width:320,height:320,sidebar:320,header:148,nav:64,status:22,panelHeight:128});bounds(h);assert.equal(h.elements['walk-tps-controls'].style.maxHeight,'32px');});
test('viewpoint styling uses existing panel/capsule tokens and 44px controls without changing handlers or labels',()=>{assert.match(css,/#walk-tps-controls\{[^}]*background:var\(--hp-panel-strong[^}]*box-shadow:var\(--hp-shadow-soft\)/);assert.match(css,/#walk-tps-controls button\{[^}]*min-height:44px;min-width:44px[^}]*border-radius:var\(--hp-control-radius\)/);assert.match(css,/#walk-tps-controls button\[hidden\][^}]*display:none/);assert.match(html,/id="walk-tps-mode"[^>]*onclick="WalkTps.toggle\(\)"/);assert.match(html,/id="walk-tps-action"[^>]*onclick="WalkTps.action\(\)"/);assert.doesNotMatch(source,/tps\.style\.top=\(topSafe\+54\)|tps\.style\.left=leftSafe/);});
