'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'../..'),F=require('../../assets/js/walk-tps-foundation.js'),Tpromise=import('../../assets/vendor/three/build/three.module.js');
const projection={kind:'perspective',centered:true,near:.1,aspect:16/9,verticalFovDegrees:68};
function gap(c){return Math.hypot(c.position.x-c.target.x,c.position.y-c.target.y,c.position.z-c.target.z);}
function controller(){let p={x:0,y:0,z:0,yaw:0,pitch:0,floor:1},clears=0,casts=0;const host={readPose:()=>p,resolveSocket:()=>null,isSafe:()=>true,findSafe:()=>null,restorePose:()=>{},clearInput:()=>clears++,castCamera:()=>{casts++;return 0;},sweepCameraBoundary:()=>null,readCameraProjection:()=>projection};return {host,c:F.create(host,{version:1,mode:'tps'}),p,counts:()=>({clears,casts})};}
async function runtime(edit){const T=await Tpromise,noop=()=>{},elements={};const c={console,THREE:T,WalkTpsFoundation:F,WalkTpsBoundary:require('../../assets/js/walk-tps-boundary.js'),WalkTpsMeshVolumes:require('../../assets/js/walk-tps-mesh-volumes.js'),WalkTpsOcclusion:require('../../assets/js/walk-tps-occlusion.js'),RoomGeometry:require('../../assets/js/room-geometry.js'),DATA:{walls:[],items:[],rooms:[{id:'main',floor:1,x:0,y:0,w:6000,d:6000},{id:'remote',floor:1,x:8000,y:0,w:6000,d:6000}]},ST:{view:'3d-walk',floor:1},WALK:{active:true,floor:1,x:3,z:3,yaw:0,pitch:0,groundOff:0,keys:{}},iMov:{},U:.001,sc3:new T.Scene(),camExt:new T.PerspectiveCamera(68,16/9,.1,100),WALK_PLAYER_RADIUS_MM:280,_tablet3DRebuildQueued:false,
floorTopY:f=>(f-1)*3,roomFloorTopY:()=>0,floorBaseY:()=>0,roomFloorAt:f=>(f-1)*3,roomCeilingHeightM:()=>3,roomIsVoidCeiling:r=>!!r.void,roomCeilingProfile:r=>r.sloped?{}:null,CeilingDesigner:{areas:r=>r.custom?[{type:'flat'}]:[]},hasPendingGltfModels:()=>!!c.pending,isWalkView:()=>true,walkStairSampleAt:()=>c.stair?{frac:.5}:null,walkLevelStairGroundAt:()=>c.levelStair?.3:null,walkSpawnObstructed:()=>false,walkSpawnClearNear:()=>null,isStairPartType:()=>false,walkUpdateGround:noop,walkSpawn:noop,drawWalkMinimap:noop,onFloorChange:f=>{c.ST.floor=c.WALK.floor=f;},
walkApplyFpsCamera(){c.camExt.position.set(c.WALK.x,c.floorTopY(c.WALK.floor)+1.65,c.WALK.z);c.fpsCalls=(c.fpsCalls||0)+1;},invalidate3D:noop,updateWalkEyePresetButton:noop,addEventListener:noop,removeEventListener:noop,document:{getElementById:id=>elements[id]||(elements[id]={setAttribute:noop,style:{}})}};c.window=c;vm.createContext(c);for(const file of ['walk-tps-avatar.js','walk-tps.js'])vm.runInContext(fs.readFileSync(path.join(root,'assets/js',file),'utf8'),c);edit?.(c,T);c.WalkTps.setMode('tps');return {c,T,elements};}
test('fixed camera maintains 2.6m boom for every yaw/pitch/aspect without calling old obstruction vetoes',()=>{
for(const aspect of [16/9,1,390/844])for(const yaw of [0,.7,Math.PI,-Math.PI/2])for(const pitch of [-1.1,-.2,0,.4,1.1]){const v=F.fixedCamera({x:1,y:3,z:5},yaw,pitch,{...projection,aspect});assert.equal(v.strategy,'fixed-distance');assert.equal(v.verified,true);assert.ok(Math.abs(gap(v)-2.6)<1e-12);}
const h=controller();assert.equal(h.c.tick(.1).camera.verified,true);assert.equal(h.counts().casts,0);
});
test('invalid projection/pose holds last finite TPS composition and recovers without mode changes',()=>{const h=controller(),first=h.c.tick(.1);h.host.readCameraProjection=()=>({...projection,near:NaN});let s=h.c.tick(.1);assert.equal(s.camera.reason,'projection-unverified');assert.equal(s.camera.fallback,'hold-tps');assert.deepEqual(s.camera.position,first.camera.position);assert.deepEqual(s.avatar,first.avatar);assert.ok(h.counts().clears>0);h.host.readCameraProjection=()=>projection;h.p.x=NaN;s=h.c.tick(.1);assert.equal(s.camera.reason,'pose-unverified');assert.deepEqual(s.camera.position,first.camera.position);h.p.x=2;assert.equal(h.c.tick(.1).camera.holding,false);});
test('first invalid pose never invents a camera or automatically selects FPS',()=>{const h=controller();h.p.x=NaN;const s=h.c.tick(.1);assert.equal(s.mode,'tps');assert.equal(s.camera.position,null);assert.equal(s.camera.fallback,'hold-tps');assert.equal(s.avatar,null);});
test('real owner keeps fixed TPS across ordinary rooms, narrow hall, stairs, void/sloped/custom ceilings, hidden/loading/rebuild/invalid geometry',async()=>{
const cases=[['ordinary',()=>{}],['750mm-hall',c=>{c.DATA.rooms=[{id:'hall',floor:1,x:0,y:0,w:750,d:6000}];c.WALK.x=.375;}],['remote-void',c=>c.DATA.rooms[1].void=true],['remote-sloped',c=>c.DATA.rooms[1].sloped=true],['remote-flat-custom',c=>c.DATA.rooms[1].custom=true],['floor-stair',c=>c.stair=true],['level-stair',c=>c.levelStair=true],['hidden-item',c=>c.DATA.items.push({id:'hidden',type:'chair',floor:1,hidden3D:true})],['model-loading',c=>c.pending=true],['queued-rebuild',c=>c._tablet3DRebuildQueued=true],['invalid-remote-geometry',(c,T)=>{const m=new T.Mesh(new T.BoxGeometry(1,1,1),new T.MeshStandardMaterial());m.position.set(10,1,3);m.scale.x=0;m.userData.b=true;c.sc3.add(m);}],['near-wall',(c,T)=>{const m=new T.Mesh(new T.BoxGeometry(6,3,.1),new T.MeshStandardMaterial());m.position.set(3,1.5,3.2);m.userData.b=true;c.sc3.add(m);}]];
for(const [name,edit] of cases){const {c}=await runtime(edit),d=c.WalkTps.debug();assert.equal(d.output.mode,'tps',name);assert.equal(d.output.camera.verified,true,name);assert.ok(Math.abs(gap(d.output.camera)-2.6)<1e-12,name);assert.equal(c.fpsCalls||0,0,name);assert.ok(!/一人称表示/.test(c.document.getElementById('walk-tps-status').textContent),name);c.WalkTps.dispose();}
});
test('near-wall fades preserve physical geometry/visibility; explicit FPS restores materials and ordinary camera',async()=>{let wall,material;const {c}=await runtime((c,T)=>{material=new T.MeshStandardMaterial();wall=new T.Mesh(new T.BoxGeometry(6,3,.1),material);wall.position.set(3,1.5,3.2);wall.userData.b=true;c.sc3.add(wall);});const g=wall.geometry,data=wall.userData;assert.notEqual(wall.material,material);assert.equal(wall.visible,true);assert.equal(wall.geometry,g);assert.equal(wall.userData,data);assert.equal(c.WalkTps.debug().sceneReady,true);assert.ok(c.WalkTps.debug().boxes>=5);c.WalkTps.setMode('fps');assert.equal(wall.material,material);assert.equal(c.WalkTps.debug().footShadowActive,false);assert.equal(c.fpsCalls,1);assert.equal(c.camExt.position.y,1.65);assert.equal(c.WalkTps.debug().output,null);});
test('owner holds real TPS camera/person during invalid projection, then recovers',async()=>{const {c,elements}=await runtime(),before=c.camExt.position.toArray();c.camExt.near=NaN;c.WalkTps.update(.1);assert.deepEqual(c.camExt.position.toArray(),before);assert.equal(c.fpsCalls||0,0);assert.equal(c.WalkTps.enabled(),true);assert.equal(c.sc3.children.find(o=>o.userData.walkTpsAvatar).visible,true);assert.match(elements['walk-tps-status'].textContent,/保持/);c.camExt.near=.1;c.WalkTps.update(.1);assert.equal(c.WalkTps.debug().output.camera.holding,false);c.WalkTps.dispose();});
test('native FPS floor change retains held movement while manual reset and plan replacement clear it',async()=>{const {c}=await runtime();c.WalkTps.setMode('fps');c.WalkTps.beforeMove();c.iMov.w=true;c.WALK.keys.fwd=true;const keys=c.WALK.keys,movement=c.iMov;c.WALK.floor=c.ST.floor=2;c.WalkTps.beforeMove();assert.equal(c.iMov.w,true);assert.equal(c.WALK.keys.fwd,true);assert.equal(c.WALK.keys,keys);assert.equal(c.iMov,movement);c.WalkTps.reset(false);assert.equal(c.iMov.w,false);assert.equal(c.WALK.keys.fwd,undefined);c.iMov.w=true;c.WALK.keys.fwd=true;c.DATA={...c.DATA};c.WalkTps.beforeMove();assert.equal(c.iMov.w,false);assert.equal(c.WALK.keys.fwd,undefined);c.WalkTps.dispose();});
test('rebuild invalidation restores owned fade before native scene disposal',async()=>{let wall,source;const {c}=await runtime((c,T)=>{source=new T.MeshStandardMaterial();wall=new T.Mesh(new T.BoxGeometry(6,3,.1),source);wall.position.set(3,1.5,4);wall.userData.b=true;c.sc3.add(wall);});assert.notEqual(wall.material,source);c.WalkTps.invalidate();assert.equal(wall.material,source);assert.equal(c.WalkTps.debug().presentation.ownedRecords,0);c.WalkTps.update(.1);assert.notEqual(wall.material,source);c.WalkTps.dispose();assert.equal(wall.material,source);});
test('free TPS native floor change also preserves held movement; action and explicit reset semantics remain separate',async()=>{const {c}=await runtime();c.iMov.w=true;c.WALK.keys.fwd=true;c.WALK.floor=c.ST.floor=2;c.WalkTps.beforeMove();assert.equal(c.iMov.w,true);assert.equal(c.WALK.keys.fwd,true);c.WalkTps.update(.016);assert.equal(c.WalkTps.debug().output.avatar.floor,2);assert.ok(Math.abs(gap(c.WalkTps.debug().output.camera)-2.6)<1e-12);c.WalkTps.dispose();});
test('foot-depth cue follows the native stair/raised ground, and repeated mode entry/exit retains no private presentation objects',async()=>{const {c}=await runtime();c.WALK.groundOff=.74;c.WalkTps.update(.016);assert.ok(Math.abs(c.sc3.children.find(o=>o.userData.walkTpsFootShadow).position.y-.747)<1e-12);const before=JSON.stringify(c.DATA);for(let i=0;i<30;i++){c.WalkTps.setMode('fps');assert.equal(c.sc3.children.filter(o=>o.userData.walkTpsAvatar||o.userData.walkTpsFootShadow).length,0);assert.equal(c.WalkTps.debug().presentation.ownedRecords,0);c.WalkTps.setMode('tps');assert.equal(c.sc3.children.filter(o=>o.userData.walkTpsAvatar).length,1);assert.equal(c.sc3.children.filter(o=>o.userData.walkTpsFootShadow).length,1);}assert.equal(JSON.stringify(c.DATA),before);c.WalkTps.dispose();assert.equal(c.sc3.children.filter(o=>o.userData.walkTpsAvatar||o.userData.walkTpsFootShadow).length,0);});
function actionController(kind){
 const p={x:0,y:0,z:0,yaw:0,pitch:0,floor:1};
 let support=true,safe=true,currentProjection={kind:'perspective',centered:true,near:.1,aspect:1,verticalFovDegrees:68};
 const socket={kind,signature:'socket-v1',pose:{x:0,y:kind==='mirror-pose'?0:.5,z:-.3,yaw:0,floor:1},approach:p,reachable:true,supportY:kind==='bath-pose'?.14:null};
 const host={readPose:()=>p,resolveSocket:()=>support?socket:null,isSafe:()=>safe,findSafe:()=>null,
  restorePose:value=>Object.assign(p,value),clearInput:()=>{},castCamera:()=>0,readCameraProjection:()=>currentProjection};
 const c=F.create(host,{version:1,mode:'tps'});
 return {c,p,socket,loseSupport:()=>{support=false;safe=false;},invalidProjection:()=>{currentProjection={...currentProjection,near:NaN};}};
}
for(const kind of ['sit','bath-pose','mirror-pose']){
 test(kind+': invalid projection camera hold cannot restore a previous visible action after support is lost',()=>{
  const h=actionController(kind);h.c.tick(.01);assert.equal(h.c.requestAction('target'),true);const before=h.c.tick(.1);
  h.loseSupport();h.invalidProjection();const out=h.c.tick(.1);
  assert.equal(out.state,'blocked');assert.equal(out.reason,'no-safe-exit');assert.equal(out.avatarHidden,true);assert.equal(out.locked,true);
  assert.equal(out.actionKind,kind);assert.equal(out.camera.holding,true);assert.deepEqual(out.camera.position,before.camera.position);
  assert.deepEqual(out.avatar,before.avatar);
 });
 test(kind+': a newly requested action keeps current state and support while only the camera holds',()=>{
  const h=actionController(kind),before=h.c.tick(.01);h.invalidProjection();assert.equal(h.c.requestAction('target'),true);
  const out=h.c.tick(.1);assert.equal(out.locked,true);assert.equal(out.actionKind,kind);assert.notEqual(out.state,'idle');
  assert.equal(out.avatarHidden,false);assert.deepEqual(out.avatar,h.socket.pose);assert.equal(out.supportY,kind==='bath-pose'?.14:null);
  assert.equal(out.camera.holding,true);assert.deepEqual(out.camera.position,before.camera.position);
 });
 test(kind+': ended actions cannot inherit a previous lock/avatar through invalid projection hold',()=>{
  const h=actionController(kind);h.c.tick(.01);h.c.requestAction('target');const before=h.c.tick(.1);h.invalidProjection();assert.equal(h.c.cancel(),true);
  const out=h.c.tick(.1);assert.equal(out.locked,false);assert.equal(out.actionKind,null);assert.equal(out.avatarHidden,false);
  assert.equal(out.state,'idle');assert.deepEqual(out.avatar,{x:0,y:0,z:0,yaw:0,floor:1});assert.equal(out.supportY,null);
  assert.equal(out.camera.holding,true);assert.deepEqual(out.camera.position,before.camera.position);
 });
 test(kind+': invalid live pose still resolves lost-support safety before hiding and holding',()=>{
  const h=actionController(kind);h.c.tick(.01);h.c.requestAction('target');const before=h.c.tick(.1);h.loseSupport();h.p.x=NaN;
  const out=h.c.tick(.1);assert.equal(out.state,'blocked');assert.equal(out.reason,'no-safe-exit');assert.equal(out.avatarHidden,true);
  assert.equal(out.locked,true);assert.equal(out.camera.reason,'pose-unverified');assert.deepEqual(out.avatar,before.avatar);
 });
}
