const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const base=process.env.APP_URL||'http://127.0.0.1:8950',out=process.env.EVIDENCE_DIR||fs.mkdtempSync(path.join(require('node:os').tmpdir(),'webcad-tps-actions-panes-'));fs.mkdirSync(out,{recursive:true});
const room={id:'actions-room',floor:1,x:0,y:0,w:7000,d:7000},bath={walls:[],rooms:[room],items:[{id:'bath-pane',type:'original-bathtub',floor:1,x:2600,y:2800,w:1600,d:750,rot:0}]},mirror={walls:[],rooms:[room],items:[{id:'mirror-pane',type:'original-shoe-tall',floor:1,x:3000,y:2800,w:800,d:410,rot:0,showMirror:true}]};
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:1280,height:820}}),page=await context.newPage();page.setDefaultTimeout(120000);const result={checks:[],errors:[]};page.on('pageerror',e=>result.errors.push(e.message));page.on('dialog',d=>d.accept());await context.route('**/*',r=>new URL(r.request().url()).origin===base&&!new URL(r.request().url()).pathname.startsWith('/api/')?r.continue():r.abort());const check=n=>{result.checks.push(n);console.log('PASS '+n);};
try{await page.goto(base+'/?preset=blank');await page.evaluate(async()=>{await comparisonCatalogueReady;document.getElementById('preset-choice-modal')?.remove();_defaultPlanPending=false;ParallelEditors.open();ParallelEditors.setSync(false);});await page.waitForFunction(()=>ParallelEditors.panes.size===2&&[...ParallelEditors.panes.values()].every(p=>p.ready));const frames=page.frames().filter(f=>f.url().includes('editorPane='));assert.equal(frames.length,2);
for(let i=0;i<2;i++){const f=frames[i];await f.evaluate(async plan=>{await comparisonCatalogueReady;await EditorPane.install(plan);setView('3d-walk');},i?mirror:bath);await f.waitForFunction(()=>{if(!threeModulesReady||hasPendingGltfModels()||!sc3)return false;let found=false;sc3.traverse(o=>{if(o.userData.walkActionSocket)found=true;});return found;});await f.evaluate(()=>{sc3.updateMatrixWorld(true);let g;sc3.traverse(o=>{if(o.userData.walkActionSocket)g=o;});const a=g.localToWorld(new THREE.Vector3().fromArray(g.userData.walkActionSocket.approach));WALK.x=a.x;WALK.z=a.z;WALK.yaw=0;walkUpdateGround(true);});await f.locator('#walk-tps-mode').dispatchEvent('click');await f.waitForFunction(()=>WalkTps.debug().candidate!==null);await f.locator('#walk-tps-action').dispatchEvent('click');await f.waitForFunction(()=>['bathing','posed'].includes(WalkTps.debug().output.state));}
assert.equal(await frames[0].evaluate(()=>WalkTps.debug().output.actionKind),'bath-pose');assert.equal(await frames[1].evaluate(()=>WalkTps.debug().output.actionKind),'mirror-pose');await page.screenshot({path:path.join(out,'bath-and-mirror-placeholder-panes.png')});check('two real editor panes independently hold bath and mirror actions');
for(let i=0;i<2;i++){const data=await frames[i].evaluate(async()=>{await EditorPane.save();return {saved:await StorageAdapter.load(),snapshot:EditorPane.snapshot()};});assert.deepEqual(data.saved,data.snapshot);assert.equal(Object.hasOwn(data.saved,'actionKind'),false);}check('saving either active action preserves ordinary plan JSON only');
await frames[0].locator('#walk-tps-mode').dispatchEvent('click');assert.deepEqual(await frames[0].evaluate(()=>({enabled:WalkTps.enabled(),query:WalkTps.debug().bathQueryActive})),{enabled:false,query:false});assert.equal(await frames[1].evaluate(()=>WalkTps.debug().output.locked),true);check('FPS return releases bath query ownership without cancelling sibling pose');
await frames[0].locator('#walk-tps-mode').dispatchEvent('click');await frames[0].waitForFunction(()=>WalkTps.debug().candidate!==null);await frames[0].locator('#walk-tps-action').dispatchEvent('click');await frames[0].evaluate(async()=>EditorPane.install({walls:[],items:[],rooms:[{id:'replacement-room',floor:1,x:9000,y:0,w:6000,d:6000}]}));assert.equal(await frames[0].evaluate(()=>WalkTps.debug().bathQueryActive),false);assert.equal(await frames[0].evaluate(()=>WalkTps.enabled()),false);check('pane plan replacement clears bath action and its private query actor');
await frames[1].evaluate(()=>{WALK.keys.w=true;EditorPane.dispose();EditorPane.dispose();});assert.equal(await frames[1].evaluate(()=>WalkTps.debug().disposed),true);assert.equal(await frames[1].evaluate(()=>Object.values(WALK.keys).some(Boolean)),false);assert.equal(await frames[0].evaluate(()=>WalkTps.debug().disposed),false);await page.evaluate(()=>ParallelEditors.close());assert.equal(await page.evaluate(()=>ParallelEditors.panes.size),0);check('pose disposal is idempotent and comparison closure finishes both runtimes');result.status=result.errors.length?'failed':'passed';}catch(e){result.status='failed';result.error=e.stack;console.error(e);}finally{fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(result,null,2));await context.close();await browser.close();}if(result.status!=='passed')process.exitCode=1;})().catch(e=>{console.error(e);process.exitCode=1;});
