"""Build a local, read-only comparison sheet from verified Three.js renders."""
import json
from pathlib import Path
from html import escape
root=Path(__file__).resolve().parents[2]
items=[i for i in json.loads((root/'assets/models/custom/manifest.json').read_text())['items'] if i.get('provenance')=='original']
old=['fmp-Sofa01','fmp-Chair01','fmp-Bed01','fmp-Table01','fmp-Drawer01','fmp-Closet01']
rows=[]
for item,legacy in zip(items,old):
 ident=item['id'];rows.append(f'''<section><div class="heading"><div><small>ORIGINAL COLLECTION</small><h2>{escape(item['name'])}</h2></div><p>{item['w']} × {item['d']} × {item['h']} mm</p></div><div class="pair"><figure><img data-model="{legacy}" src="{legacy}-front.png"><figcaption>既存モデル <span>{legacy}</span></figcaption></figure><figure><img data-model="{ident}" src="{ident}-front.png"><figcaption>オリジナル <span>素材ごとに色変更できます</span></figcaption></figure></div></section>''')
html='''<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>オリジナル家具の比較 | house-planner</title><style>
*{box-sizing:border-box}body{margin:0;background:#f6f4ef;color:#293931;font:15px/1.7 system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:48px 24px}small{font-size:10px;letter-spacing:.16em;color:#738075}h1{font-size:clamp(25px,4vw,42px);letter-spacing:-.04em;margin:12px 0}h2{font-size:20px;margin:4px 0}p{color:#788078}nav{display:flex;gap:8px;position:sticky;top:0;background:#f6f4eff0;padding:16px 0;z-index:1}button,a{font:inherit;border-radius:999px;padding:8px 20px;border:1px solid #d4d9d0;background:transparent;color:inherit;text-decoration:none;cursor:pointer}button[aria-pressed=true]{background:#304c3e;color:white;border-color:#304c3e}section{border-top:1px solid #d8dcd3;margin-top:24px;padding-top:26px}.heading{display:flex;justify-content:space-between;align-items:center}.pair{display:grid;grid-template-columns:1fr 1fr;gap:16px}figure{margin:0}img{display:block;width:100%;background:#eeeae3;border-radius:20px}figcaption{padding:12px 4px}figcaption span{display:block;color:#879086;font-size:12px}@media(max-width:600px){main{padding:28px 16px}.heading{display:block}.pair{gap:8px}nav{gap:5px}button{padding:8px 12px;font-size:13px}h2{font-size:18px}figcaption{font-size:13px}}
</style><main><small>HOUSE-PLANNER · MATERIAL STUDY</small><h1>住まいに置いて、比べる。</h1><p>代表6モデルを既存カタログに追加しました。家具検索で「オリジナル」と入力して配置し、詳細設定の「素材・カラー」で色を変更できます。</p><p>比較画像は同じ照明・カメラ条件。各モデルの元の比率を保持しており、既存と新作の寸法・意匠は異なります。既存モデルの置換は行っていません。</p><nav aria-label="比較する面"><button aria-pressed="true" data-view="front">正面側</button><button aria-pressed="false" data-view="back">背面側</button><button aria-pressed="false" data-view="custom">色変更の例</button></nav>'''+''.join(rows)+'''<p>前面 +Z / 上方向 +Y。編集可能なBlenderソースと再生成スクリプトを保存しています。</p></main><script>document.querySelectorAll('button[data-view]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('button[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelectorAll('img[data-model]').forEach(img=>{const view=button.dataset.view==='custom'&&!img.dataset.model.startsWith('original-')?'front':button.dataset.view;img.src=img.dataset.model+'-'+view+'.png';});}));</script></html>'''
(root/'docs/quality-review/original-collection/index.html').write_text(html)
