"""Original, bloodless mystery props; existing key/envelope are reused unchanged.

Blender --background --factory-startup --python tools/blender/rpg_mansion/mystery_props/build.py
Common model_kit.run() checks every new mesh. Images are generated by render.py.
"""
import math
import sys
from pathlib import Path
import bpy
import bmesh
from mathutils import Vector,Matrix

HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[3]
sys.path.insert(0,str(ROOT/'tools/blender'))
import model_kit as kit
from model_kit import box,cylinder,combine,matp

kit.GLB_DIR=ROOT/'assets/models/packs/rpg-mansion/models'
kit.PREVIEW_DIR=ROOT/'assets/models/packs/rpg-mansion/previews'
kit.WORK_DIR=HERE/'sources'


def mat(name,colour,channel=None,rough=.5,metallic=0):
    m=matp(name,colour,rough=rough,metal=metallic)
    if channel:m['finishChannel']=channel
    return m


def glass(name='Glass',colour='#dfe8ea',alpha=.42):
    m=mat(name,colour,rough=.12)
    b=m.node_tree.nodes.get('Principled BSDF')
    rgba=list(b.inputs['Base Color'].default_value);rgba[3]=alpha
    b.inputs['Base Color'].default_value=rgba;b.inputs['Alpha'].default_value=alpha
    b.inputs['Transmission Weight'].default_value=.80
    b.inputs['IOR'].default_value=1.46
    m.surface_render_method='DITHERED';m.use_transparency_overlap=False
    return m


def mesh(name,verts,faces,material):
    data=bpy.data.meshes.new(name);data.from_pydata(verts,[],faces);data.update()
    o=bpy.data.objects.new(name,data);bpy.context.collection.objects.link(o)
    data.materials.append(material)
    return o


def polygon(name,points,z0,z1,material):
    n=len(points)
    verts=[(x,y,z) for z in (z0,z1) for x,y in points]
    faces=[tuple(reversed(range(n))),tuple(range(n,2*n))]
    for i in range(n):
        j=(i+1)%n;faces.append((i,j,n+j,n+i))
    return mesh(name,verts,faces,material)


def lathe(name,profile,material,sides=48,notches=False):
    rings=[]
    for r,z in profile:
        points=[]
        for i in range(sides):
            a=math.tau*i/sides
            # Four real rim depressions; the basin floor remains intact.
            cut=.006*max(0,math.cos(a*4))**12 if notches and z>.024 else 0
            points.append((r*math.cos(a),r*math.sin(a),z-cut))
        rings.append(points)
    return kit.shell(name,rings,[material],[0]*(len(rings)-1))


def pipe(name,points,radius,material,closed=False,sides=8,flatten=1):
    curve=bpy.data.curves.new(name,'CURVE');curve.dimensions='3D';curve.resolution_u=1
    curve.bevel_depth=radius;curve.bevel_resolution=1;curve.use_fill_caps=True
    spline=curve.splines.new('POLY');spline.points.add(len(points)-1)
    for p,co in zip(spline.points,points):p.co=(*co,1)
    spline.use_cyclic_u=closed
    o=bpy.data.objects.new(name,curve);bpy.context.collection.objects.link(o)
    curve.materials.append(material);kit.activate(o);bpy.ops.object.convert(target='MESH')
    o=bpy.context.object
    if flatten!=1:
        for v in o.data.vertices:v.co.z*=flatten
    return o


def torus(name,center,major,minor,material,rotation=(0,0,0),segments=24):
    bpy.ops.mesh.primitive_torus_add(major_segments=segments,minor_segments=6,
        location=center,rotation=rotation,major_radius=major,minor_radius=minor)
    o=bpy.context.object;o.name=name;bpy.ops.object.transform_apply(location=True,rotation=True,scale=True)
    o.data.materials.append(material)
    for p in o.data.polygons:p.use_smooth=True
    return o


def text(name,body,position,xaxis,yaxis,size,material,depth=.00015):
    curve=bpy.data.curves.new(name,'FONT');curve.body=body;curve.size=size
    curve.align_x='CENTER';curve.align_y='CENTER';curve.extrude=depth;curve.resolution_u=2
    o=bpy.data.objects.new(name,curve);bpy.context.collection.objects.link(o);curve.materials.append(material)
    kit.activate(o);bpy.ops.object.convert(target='MESH');o=bpy.context.object
    x=Vector(xaxis);y=Vector(yaxis);z=x.cross(y);origin=Vector(position)
    for v in o.data.vertices:v.co=origin+x*v.co.x+y*v.co.y+z*v.co.z
    return o


def finish(parts,size):
    # Keep independent closed shells separate while joining their material slots.
    for o in parts:
        bm=bmesh.new();bm.from_mesh(o.data)
        bmesh.ops.remove_doubles(bm,verts=list(bm.verts),dist=1e-8)
        bmesh.ops.dissolve_degenerate(bm,edges=list(bm.edges),dist=1e-8)
        bmesh.ops.triangulate(bm,faces=list(bm.faces));bmesh.ops.recalc_face_normals(bm,faces=list(bm.faces))
        assert all(e.is_manifold for e in bm.edges),o.name
        bm.to_mesh(o.data);bm.free();o.data.update()
    obj=combine(parts)
    pts=[obj.matrix_world @ v.co for v in obj.data.vertices]
    lo=[min(p[i] for p in pts) for i in range(3)];hi=[max(p[i] for p in pts) for i in range(3)]
    for v in obj.data.vertices:
        v.co.x=(v.co.x-(lo[0]+hi[0])/2)*size[0]/1000/(hi[0]-lo[0])
        v.co.y=(v.co.y-(lo[1]+hi[1])/2)*size[1]/1000/(hi[1]-lo[1])
        v.co.z=(v.co.z-lo[2])*size[2]/1000/(hi[2]-lo[2])
    obj.data.update()
    obj['front']='+Z';obj['originalProceduralAsset']=True;obj['bloodlessGameProp']=True
    return obj


def chalk():
    chalk=mat('White chalk','#e8e5dc',rough=.97)
    # Generic human outline; neither a corpse nor a depiction of an injury.
    outline=[(-.07,.64),(-.17,.59),(-.28,.44),(-.47,.37),(-.59,.12),(-.54,.03),
             (-.39,.18),(-.25,.24),(-.18,.07),(-.20,-.06),(-.24,-.71),(-.40,-.82),
             (-.40,-.90),(-.22,-.86),(-.14,-.78),(-.02,-.32),(.14,-.80),(.20,-.91),
             (.36,-.88),(.30,-.78),(.22,-.05),(.19,.12),(.26,.27),(.49,.36),
             (.53,.65),(.47,.69),(.42,.50),(.33,.42),(.19,.58),(.10,.64)]
    # Tube cross-section is flattened to 3mm; all of it sits above the floor.
    # Fit the centre-line before adding the 12mm stroke, so its cross-section
    # is not squeezed merely to fit a nominal adult outline footprint.
    def place(x,y):return ((x+.03)*.938/1.12,(y+.034)*1.838/1.752,.007)
    body=pipe('Chalk body outline',[place(x,y) for x,y in outline],.006, chalk,True,flatten=.25)
    head=pipe('Chalk head outline',[place(.025+.096*math.cos(a),.742+.10*math.sin(a))
                                  for a in [math.tau*i/40 for i in range(40)]],.006,chalk,True,flatten=.25)
    return finish([body,head],(950,1850,3))


def knife():
    steel=mat('Polished steel','#aeb5b9','metal',.24,.88)
    wood=mat('Dark wood grip','#38271f','wood',.42)
    rivet=mat('Brass rivets','#a58a4b','metal',.32,.80)
    # A generic game prop: silhouette and material division, no manufacturing detail.
    blade=polygon('Steel blade',[(-.150,0),(-.113,-.022),(.028,-.023),(.040,-.012),(.040,.019),(-.100,.022)],.009,.012,steel)
    parts=[kit.bevel(blade,.0005,2)]
    parts.append(box('Wood handle',(.032,-.013,0),(.150,.013,.022),wood,.007,4))
    parts.append(box('Steel bolster',(.022,-.016,.003),(.043,.016,.018),steel,.002,2))
    for x in (.058,.093,.129):
        parts.append(cylinder('Handle rivet',(x,0,.0225),.003,.001,rivet,sides=12))
    return finish(parts,(300,48,24))


def ashtray(is_glass):
    if is_glass:
        m=glass('Glass cut crystal','#dfe8ea',.40)
        profile=[(.049,0),(.060,.006),(.070,.021),(.070,.040),(.059,.039),(.054,.020),(.040,.009)]
        size=(140,140,40)
    else:
        m=mat('Dark glazed ceramic','#4d463d',rough=.22)
        profile=[(.052,0),(.066,.005),(.075,.029),(.074,.040),(.062,.040),(.057,.020),(.036,.007)]
        size=(150,150,40)
    o=lathe('Ashtray basin with four rim grooves',profile,m,64,True)
    return finish([o],size)


def marker():
    yellow=mat('Evidence card yellow','#f4cc26',rough=.7)
    ink=mat('Printed numeral black','#151515',rough=.8)
    parts=[];angle=math.atan2(.03,.09);length=math.hypot(.03,.09)
    for sign in (-1,1):
        o=box('Folded evidence card',(-.04,-.001,-length/2),(.04,.001,length/2),yellow,.0005,2)
        o.rotation_euler.x=sign*angle;o.location=(0,sign*.015,.045)
        kit.activate(o);bpy.ops.object.transform_apply(location=True,rotation=True,scale=True);parts.append(o)
    for sign in (-1,1):
        # Front is -Y. Both faces carry one readable number, not a texture.
        numeral=[(-.012,-.025),(.013,-.025),(.013,-.018),(.004,-.018),(.004,.027),
                 (-.002,.027),(-.013,.016),(-.007,.010),(-.003,.015),(-.003,-.018),(-.012,-.018)]
        glyph=polygon('Evidence numeral 1',numeral,0,.0003,ink)
        x=Vector((-sign,0,0));y=Vector((0,-sign*math.sin(angle),math.cos(angle)))
        z=x.cross(y);origin=Vector((0,sign*.0185,.045))
        for v in glyph.data.vertices:v.co=origin+x*v.co.x+y*v.co.y+z*v.co.z
        parts.append(glyph)
    obj=finish(parts,(80,60,90));obj['evidenceNumber']=1
    return obj


def watch():
    brass=mat('Antique watch brass','#b0924e','metal',.3,.85)
    dial=mat('Ivory clock dial','#eee5cf',rough=.62)
    ink=mat('Clock numerals','#24211d',rough=.65)
    parts=[cylinder('Pocket watch case',(-.029,0,.006),.025,.012,brass,sides=48),
           cylinder('Inset ivory dial',(-.029,0,.012),.0214,.001,dial,sides=48),
           torus('Watch bezel',(-.029,0,.0125),.0223,.0013,brass,segments=48)]
    # Raised Arabic numerals use Blender's built-in font converted into geometry.
    for i in range(1,13):
        a=math.tau*i/12
        parts.append(text('Watch hour '+str(i),str(i),(-.029+.0167*math.sin(a),.0167*math.cos(a),.0130),
                          (1,0,0),(0,1,0),.0042,ink,.00008))
    for label,angle,length,width,z in [('Hour hand',math.radians(54),.012,.001,.0133),
                                    ('Minute hand',math.radians(-60),.017,.0007,.0138)]:
        a=(-.029,0,z);b=(-.029+math.sin(angle)*length,math.cos(angle)*length,z)
        parts.append(pipe(label,[a,b],width/2,ink))
    parts.append(cylinder('Watch pivot',(-.029,0,.0143),.0014,.0006,brass,sides=12))
    parts.append(cylinder('Winding crown',(-.029,.027,.006),.003,.006,brass,'Y',16))
    parts.append(torus('Crown bow',(-.029,.033,.006),.0045,.0008,brass))
    for i in range(13):
        x=-.023+i*.0055;y=.037-.0045*i+.001*math.sin(i)
        parts.append(torus('Short chain link',(x,y,.0036),.0028,.00065,brass,
                           rotation=(math.pi/2 if i%2 else 0,0,0),segments=16))
    return finish(parts,(105,68,15))


def fallen_glass():
    g=glass('Glass wine glass','#dfe8ea',.42)
    parts=[lathe('Wine glass foot',[(.014,0),(.026,.002),(.025,.004),(.006,.006)],g,48),
           cylinder('Wine glass stem',(0,0,.040),.0035,.070,g,sides=24)]
    profile=[(.008,.074),(.025,.103),(.034,.150),(.031,.150),(.022,.105),(.006,.080)]
    # Capped break surfaces keep the broken bowl a watertight solid.
    steps=44;verts=[]
    for r,z in profile:
        for i in range(steps+1):
            a=math.radians(32+296*i/steps);verts.append((r*math.cos(a),r*math.sin(a),z))
    faces=[];n=steps+1
    for k in range(len(profile)):
        nxt=(k+1)%len(profile)
        for i in range(steps):faces.append((k*n+i,k*n+i+1,nxt*n+i+1,nxt*n+i))
    faces.extend([tuple(k*n for k in reversed(range(len(profile)))),tuple(k*n+steps for k in range(len(profile)))])
    parts.append(mesh('Broken open glass bowl',verts,faces,g))
    for o in parts:
        for v in o.data.vertices:v.co=Matrix.Rotation(math.pi/2,4,'Y')@v.co+Vector((-.11,0,.034))
    for i,(x,y) in enumerate([(.084,.048),(.105,-.018),(.125,.022)]):
        parts.append(polygon('Small glass shard',[(x-.014,y-.010),(x+.016,y-.004),(x+.006,y+.017)],.001,.0035,g))
    return finish(parts,(250,150,68))


def bottle():
    g=glass('Glass amber bottle','#a96e27',.52)
    cork=mat('Natural cork','#997446',rough=.9)
    paper=mat('Blank paper label','#ded7bd',rough=.86)
    parts=[lathe('Amber glass bottle',[(.020,0),(.024,.005),(.025,.017),(.025,.083),
           (.023,.092),(.011,.104),(.010,.114),(.007,.114),(.007,.104),(.020,.084),(.020,.006)],g,48),
           cylinder('Cork stopper',(0,0,.112),.008,.016,cork,sides=24)]
    # A curved, blank label on -Y; no text, brand, contents, or secret information.
    verts=[];steps=16
    for r in (.0252,.0256):
        for z in (.036,.071):
            for i in range(steps+1):
                a=math.radians(230+80*i/steps);verts.append((r*math.cos(a),r*math.sin(a),z))
    n=steps+1;faces=[]
    for i in range(steps):
        faces.extend([(i,i+1,n+i+1,n+i),(2*n+i,3*n+i,3*n+i+1,2*n+i+1),
                      (i,2*n+i,2*n+i+1,i+1),(n+i,n+i+1,3*n+i+1,3*n+i)])
    faces.extend([(0,n,3*n,2*n),(steps,2*n+steps,3*n+steps,n+steps)])
    parts.append(mesh('Blank curved label',verts,faces,paper))
    return finish(parts,(50,50,120))


ENTRIES=[
 ('rpg-mansion-mystery-chalk-outline-01',(950,1850,3),chalk,None,12000),
 ('rpg-mansion-mystery-knife-01',(300,48,24),knife,{'wood','metal'},12000),
 ('rpg-mansion-mystery-glass-ashtray-01',(140,140,40),lambda:ashtray(True),None,12000),
 ('rpg-mansion-mystery-ceramic-ashtray-01',(150,150,40),lambda:ashtray(False),None,12000),
 ('rpg-mansion-mystery-evidence-marker-01',(80,60,90),marker,None,12000),
 ('rpg-mansion-mystery-pocket-watch-01',(105,68,15),watch,{'metal'},12000),
 ('rpg-mansion-mystery-fallen-wine-glass-01',(250,150,68),fallen_glass,None,12000),
 ('rpg-mansion-mystery-corked-bottle-01',(50,50,120),bottle,None,12000),
]


if __name__=='__main__':
    selected=sys.argv[sys.argv.index('--')+1:] if '--' in sys.argv else []
    kit.run([entry for entry in ENTRIES if not selected or entry[0] in selected],do_icons=False)
