"""Refresh final deliverable totals/provenance only after QA succeeds."""
from pathlib import Path
import json,hashlib
H=Path(__file__).resolve().parent;ROOT=H.parents[3];P=ROOT/'assets/models/packs/rpg-mansion'
manifest=json.loads((H/'storage-items.json').read_text());items=manifest['items'];a=json.loads((H/'qa-actual-bytes.json').read_text());s=json.loads((H/'qa-authoring-sources.json').read_text());g=json.loads((H/'generic-source-qa/source-checkpoint.json').read_text());j=json.loads((H/'qa-glazing-joints.json').read_text())
assert not a['errors'] and not any(r['errors'] for r in s+g)
assert len(items)==len(a['items'])==len(s)==len(g)==15
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
for i in items:i['sha256']=sha(ROOT/i['model']);i['sourceSha256']=sha(ROOT/i['sourceBlend'])
(H/'storage-items.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
summary={'modelFiles':15,'triangles':a['totalTriangles'],'glbBytes':a['totalGlbBytes'],'maxAssetTriangles':max(r['triangles'] for r in a['items']),'maxAssetGlbBytes':max(r['bytes'] for r in a['items']),'under4000TriangleAssets':sum(r['triangles']<4000 for r in a['items']),'under6000TriangleAssets':sum(r['triangles']<6000 for r in a['items']),'previewFiles':len(list((P/'previews').glob('*.png'))),'evidenceImages':len(list((H/'evidence').glob('*.png'))),'canonicalSources':len(list((H/'export_sources').glob('*.blend'))),'canonicalSourceBytes':sum((ROOT/i['sourceBlend']).stat().st_size for i in items),'authoringOnlyCheckpoints':len(list((H/'authoring_sources').glob('*.blend'))),'authoringParts':sum(r['authoringParts'] for r in s),'sourceQaErrors':0,'genericSourceQaErrors':0,'actualByteQaErrors':0,'glazedPanesWithNativeFrameContact':sum(bool(r['physicallyIntersectingFrameParts']) for r in j),'declaredStandardFootprintMatches':sum(bool(i.get('standardFootprintMatches')) for i in items),'nativeContactGroups':15,'unsupportedNativeGroups':0,'strictOneMeshOneSceneGlbs':15,'rerenderedGeometryChangedAssets':11,'reusedUnchangedFourViewAssets':4,'verificationReexports':30,'browserRuntimeTested':False}
(H/'delivery-totals.json').write_text(json.dumps(summary,indent=2)+'\n')
rights={'authoring':'Original procedural Blender geometry authored for this project','thirdPartyGeometry':False,'thirdPartyTextures':False,'paidGeneration':False,'license':'Original project-authored assets for this repository; no separate public reuse license granted','measurementPolicy':'10 assets match declared standard catalogue footprints; legacy model geometry has not been independently measured. 5 other assets use intended design footprints. Footprint matching does not prove functional or geometric equivalence.','authoringModules':{p.name:sha(p) for p in [H/f for f in ['build.py','forms.py','joinery.py','export_contract.py','repair_delivery.py','qa_support.py','standard-footprints.json']]},'reusedRepositoryHelpers':{p.name:sha(p) for p in [H.parents[1]/'model_kit.py',H.parents[1]/'shape_kit.py',H.parents[1]/'exterior_build.py',H.parents[1]/'build_decor.py',H.parent/'png_metadata.py']},'assets':[{'id':i['id'],'glbSha256':i['sha256'],'canonicalSourceSha256':i['sourceSha256'],'authoringOnlySha256':sha(ROOT/i['authoringBlend']),'glbBytes':(ROOT/i['model']).stat().st_size} for i in items]}
(H/'rights-and-provenance.json').write_text(json.dumps(rights,indent=2)+'\n');print(json.dumps(summary,indent=2))
