/* Offline, read-only fact/capability census. A diagnostic, source entity and missing field are different units. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {runtime}=require('./tests/scene-fixtures.cjs'),V=require('../assets/js/scene-ir-v3.js'),C=require('../assets/js/scene-catalogue.js');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),count=rows=>rows.reduce((m,r)=>(m[r.cause]=(m[r.cause]||0)+1,m),{});
function audit(){
 const bytes=fs.readFileSync(path.join(__dirname,'../local-preview/frozen-page-2.json')),s=JSON.parse(bytes),c=runtime();c.CONTEXT_CAR_GLB=C.carCertificate.url;const registry=c.PlanImport.sceneCatalogue(),r=c.PlanImport.previewSceneIR(s,{materialization:'bounded-v3',registry});
 const objectRows=s.objects.map((o,i)=>{const choices=c.PlanImport.sceneMappingCandidates(o,registry),type=o.objectType.value;let cause=o.semanticExtent.value==='symbol-only'?'schema-or-physical-capability':type==='stair'?'schema-or-physical-capability':type==='unidentified-symbol'?'schema-or-source-identification':type==='cabinet-like'?'existing-feature-wiring-fixed':type==='kitchen-sink'?'model-audit-fixed':choices.candidates.length?'explicit-user-mapping-required':'model-audit-missing';return {id:o.id,path:'objects['+i+']',type,extent:o.semanticExtent.value,cause,candidates:choices.candidates.map(m=>m.id),sourceFootprint:o.sourceFootprint,frontDirection:o.frontDirection,heightMm:o.heightMm,appearance:o.appearance,physical:!!r.plan.items.find(it=>it.id===o.id),priorCandidateCount:(type==='cabinet-like'||type==='kitchen-sink')?0:choices.candidates.length};});
 const errors=r.diagnostics.filter(d=>d.severity==='error').map(d=>{let cause;if(d.code==='mapping_unresolved'){const i=Number(d.path.match(/^objects\[(\d+)\]/)?.[1]);cause=objectRows[i]?.cause||'unclassified';}else if(d.code==='appearance_mapping_required')cause='explicit-user-mapping-required';else if(d.code==='unknown_required_geometry')cause='source-unknown';else if(d.code==='wrong_adjacent_room')cause='source-inconsistent';else if(d.code==='missing_traversable_connection')cause='downstream-of-unresolved-opening';else if(d.code.startsWith('unsupported_'))cause='schema-or-physical-capability';else cause='unclassified';return {...d,cause};});
 const unknown=[];function walk(v,p){if(!v||typeof v!=='object')return;if(v.status==='unknown'&&Object.hasOwn(v,'value')){unknown.push({path:p,reason:v.unknownReason||null});return;}Object.entries(v).forEach(([k,x])=>walk(x,p+(Array.isArray(v)?'['+k+']':'.'+k)));}walk(s,'scene');
 const rawBytes=fs.readFileSync(path.join(__dirname,'tests/fixtures/registration/native-astra-three-floor.raw.json')),raw=JSON.parse(rawBytes),reviews=require('./tests/fixtures/registration/native-astra-opening-image-review.json'),reviewResults=require('./tests/fixtures/registration/source-image-door-review-results.json');
 const pages=raw.pages.map(page=>{const f=page.reading.floors[0],items=f.items,marks=f.marks||[],doors=items.filter(i=>/^door-/.test(i.type)),moving=doors.filter(i=>i.type!=='door-opening'),sourceOnly=marks.map((m,i)=>({index:i,guess:m.guess,looks:m.looks,label:m.label,cause:'explicit-identification-and-mapping-required',poseFields:Object.keys(m).filter(k=>['x','y','w','d','rot','frontDirection','headDirection','color','height'].includes(k))})),pageReviews=reviews.filter(x=>x.sourcePageId===page.sourcePageId),results=reviewResults.filter(x=>x.sourcePageId===page.sourcePageId);
  return {floor:f.floor,sourcePageId:page.sourcePageId,items:items.length,rooms:f.rooms.length,sourceOnlyMarks:sourceOnly,unresolvedUnits:{deferredStairItems:items.filter(i=>/^stair/.test(i.type)).length,movingDoorsWithoutMotionFields:moving.filter(i=>!Object.hasOwn(i,'hingeSide')&&!Object.hasOwn(i,'travelDirection')).length,roomsWithoutMeasuredFloorDatum:f.rooms.filter(r=>!Object.hasOwn(r,'relativeElevation')&&!Object.hasOwn(r,'floorRaiseMm')).length,roomsWithoutFloorAppearance:f.rooms.filter(r=>!Object.hasOwn(r,'floorMaterial')&&!Object.hasOwn(r,'floorColor')&&!Object.hasOwn(r,'appearance')).length,sourceOnlyMarks:marks.length},focusedFacts:{entries:f.rooms.filter(r=>r.use==='entry').map(r=>({name:r.name,level:r.level,relativeOffset:null,tilePattern:null,tileModule:null,explanation:'Legacy level:0 does not establish a measured entry drop, tile or finish datum'})),cars:items.filter(i=>i.type==='car').length,desks:items.filter(i=>i.type==='desk').length,retainedItemColors:items.filter(i=>Object.hasOwn(i,'color')||Object.hasOwn(i,'finishColors')).length,markColors:marks.filter(i=>Object.hasOwn(i,'color')).length},separateImageReview:{count:pageReviews.length,appliedDirectionCount:results.filter(x=>x.applied).length,nativeEnvelopePass:results.filter(x=>x.physicalValidation==='native-envelope-pass').length,readerGeometryUnresolved:results.filter(x=>x.physicalValidation==='reader-geometry-unresolved').length,unresolvedIntent:results.filter(x=>!x.applied).length,records:pageReviews.map((v,i)=>({sourceItemIndex:v.sourceItemIndex,observedKind:v.observedKind,hingeSide:v.hingeSide,openSide:v.openSide,travelSide:v.travelSide,reviewed:v.reviewed,validation:results[i]})),limit:'Separate retained image review; not raw measurements or a fresh physical completeness claim'}};});
 return {version:1,paidCalls:0,sourceChanged:false,scope:{fixedV3PagesAvailable:[2],otherFrozenV3Pages:'Unavailable: authorized Library materialize returned proxy tunnel 403; no bypass or reconstructed raw',legacyPagesAvailable:[1,2,3],differentContracts:true},fixed2f:{rawSha256:hash(bytes),sourceHash:V.sourceHash(s),canApply:r.canApply,fullReconstructionReady:r.fullReconstructionReady,diagnosticUnit:'one error occurrence; counts are not source accuracy percentages',errorCount:errors.length,errorsByCause:count(errors),errors,objectUnit:'one source object including symbol-only and stair',objectsByCause:count(objectRows),objects:objectRows,unknownFieldCount:unknown.length,unknownFields:unknown},legacy:{rawSha256:hash(rawBytes),fullReconstructionReady:false,unit:'field gaps and source entities overlap; do not sum into an accuracy score',pages},limits:['No new extraction, raw or frozen contract edits','Candidate availability does not approve mapping or infer source height/material','Cabinet type wiring fixed; same binding could already compile in earlier API, so do not claim a new geometric engine','Sink model is a basin/faucet/drain display representation; catalogue height and vertical support remain unmeasured defaults','Physical bypass, stair void, uncertain door intent and inconsistent adjacency remain unresolved']};
}
module.exports={audit};if(require.main===module)console.log(JSON.stringify(audit(),null,2));
