(function(){
const originalFetch=window.fetch.bind(window);
window.fetch=function(input,options){const u=new URL(typeof input==='string'?input:input.url,location.href);if(u.origin!==location.origin||u.pathname.startsWith('/api/'))return Promise.reject(new Error('ローカル確認: AI・共有・外部通信は接続していません'));return originalFetch(input,options);};
window.WebSocket=function(){throw new Error('ローカル確認: 共有は接続していません');};
window.SCENE_IR_V3_IMAGE_IMPORT=false;
window.addEventListener('DOMContentLoaded',function(){
const bar=document.createElement('div');bar.className='offline-preview-banner';const style=document.createElement('style');style.textContent='@media(max-width:700px){.offline-preview-banner{bottom:72px!important;max-width:90vw!important;font-size:10px!important}}';document.head.append(style);bar.style='position:fixed;bottom:8px;left:8px;z-index:100000;background:#fff8e3;color:#222;padding:9px 14px;border:1px solid #cda75e;border-radius:12px;box-shadow:0 2px 8px #0003;font:12px sans-serif;max-width:75vw';
if(typeof EDITOR_PANE!=='undefined'&&EDITOR_PANE)bar.style.display='none';
bar.append(document.createTextNode('改善試作・サンプル再生／AIは実行していません（quality-lab） '));
const b=document.createElement('button');b.textContent='読み取り済み3階サンプルを確認';b.onclick=async function(){const body=await(await originalFetch('/local-preview/sample.json')).json();openPlanImport();PlanImport.stageBuildingReview(body);document.getElementById('plan-import-status').textContent='読み取り済みサンプルの再生です。AIは実行していません。各階を確認して部分適用できます。';};bar.append(b);const frozen=document.createElement('button');frozen.textContent='固定raw 2Fの部分プレビュー（AIなし・未完成）';frozen.onclick=async function(){const response=await originalFetch('/local-preview/frozen-page-2.json'),raw=await response.text(),bytes=new TextEncoder().encode(raw),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(n=>n.toString(16).padStart(2,'0')).join('');if(hash!=='c98e9213665b0527fae907a19d145d8a038db8f82bd049c57b74607add05485c')throw new Error('固定rawのhashが一致しません');openPlanImport();PlanImport.stageSceneIR(JSON.parse(raw),{materialization:'bounded-v3',pageScope:['frozen-page-2'],extraction:{rawResponse:raw,rawSha256:hash,kind:'local-readonly-frozen-replay',paidCalls:0}});document.getElementById('plan-import-status').textContent='固定rawの再生です。AIなし。候補・表示仮定を確認し、未配置部分を保持する新しい案で試してください。';};bar.append(frozen);const a=document.createElement('a');a.href='/tools/tests/fixtures/madori-3f.pdf';a.target='_blank';a.textContent=' 元図面PDF';bar.append(a);document.body.append(bar);
for(const [name,id] of [['openShareDialog','share-create-btn'],['openUnityRenderModal','ai-render-run'],['openVideoRenderDialog','video-render-run']]){const original=window[name];window[name]=function(){const result=original.apply(this,arguments),run=document.getElementById(id);if(run){run.disabled=true;run.title='ローカル確認ではAI生成・共有接続を実行しません';}return result;};}
for(const id of ['plan-import-file','plan-import-run','share-create-btn','ai-render-run','video-render-run']){const e=document.getElementById(id);if(e){e.disabled=true;e.title='ローカル確認ではAI生成・共有接続を実行しません';}}
});
})();
