/* Opt-in loopback experiment: native editor, isolated repository, no implicit legacy import. */
(function(){
'use strict';
if(location.hostname!=='127.0.0.1'||new URLSearchParams(location.search).get('planLibrary')!=='1')return;
const copy=v=>JSON.parse(JSON.stringify(v)),uid=()=>crypto.randomUUID(),q=(s,r=document)=>r.querySelector(s);
if(EDITOR_PANE){
 const parent=window.parent.PlanLibrary,toolbar=q('#toolbar'),label=document.createElement('div'),select=document.createElement('select'),dirty=document.createElement('span');
 label.className='library-current';label.append('編集中：',select,dirty);select.dataset.libraryCurrent='';select.setAttribute('aria-label','編集中のプラン');dirty.dataset.libraryDirty='';toolbar.prepend(label);
 for(const [action,title] of [['duplicate','⧉ 複製'],['history','↶ 履歴']]){const b=document.createElement('button');b.className='tbtn';b.textContent=title;b.dataset.libraryAction=action;b.onclick=()=>parent.run(()=>parent[action](EDITOR_PANE));q('#save-btn').after(b);}
 label.append(q('#save-btn'));
 select.onchange=()=>{const target=select.value;parent.run(()=>parent.switchPlan(EDITOR_PANE,target));};
 const oldSaveBusy=setSaveButtonBusy;setSaveButtonBusy=function(value){oldSaveBusy(value);parent.refresh();};
 const oldMark=markDirty,oldClear=clearDirty;markDirty=function(){oldMark();queueMicrotask(()=>parent.edited(EDITOR_PANE));};clearDirty=function(){oldClear();parent.refresh();};
 for(const name of ['applyJsonImport','undoAction','redoAction','markDirtyUiOnly']){const original=window[name];window[name]=function(){const result=original.apply(this,arguments);parent.edited(EDITOR_PANE);return result;};}
 window.loadPlanFromStorageButton=()=>parent.run(()=>parent.reloadPlan(EDITOR_PANE));
 const style=document.createElement('style');style.textContent='.library-current{position:sticky;left:0;z-index:3;background:white;border-radius:18px;padding:0 8px;flex-shrink:0;display:flex;align-items:center;gap:4px;font-size:12px;white-space:nowrap}.library-current select{min-height:40px;max-width:210px;border:0;border-radius:18px;background:#f4f5f3;padding:6px}.library-current span{color:#ac5d13}.library-current #save-btn{flex-shrink:0}@media(max-width:600px){.library-current select{max-width:140px}.library-current{padding:0 4px;gap:3px;font-size:11px}}';document.head.append(style);
 parent.childReady(EDITOR_PANE);return;
}
const repo=PlanRepositoryLab.create({name:'webcad-plan-library-lab-ui-v1'}),plans=new Map(),panes=new Map(),pool=createEditorModelPool();
let session=sessionStorage.getItem('webcad-plan-library-lab-session');if(!session){session=uid();sessionStorage.setItem('webcad-plan-library-lab-session',session);}
let retained=[],activeId=null,sync=true,busy=false,transitionBusy=false,authorizedSavePane=null,dialog=null,viewQueue=Promise.resolve(),sequence=0;
const shell=document.createElement('section');shell.className='parallel-editors library-host';shell.innerHTML='<div class="parallel-heading"><strong>複数プラン比較モード</strong></div><header class="parallel-controls" aria-label="共通操作"><div class="library-group"><span>① プラン</span><button class="tbtn" data-library-open>▤ 開く</button><button class="tbtn" data-library-new>＋ 新規</button></div><div class="library-group"><span>② 配置</span><button class="tbtn" data-library-layout="1">▣ 1画面</button><button class="tbtn" data-library-layout="2">▥ 2画面</button></div><div class="library-group"><span>③ 画角</span><label><input type="checkbox" data-parallel-sync checked>同期</label><button class="tbtn" data-parallel-align>◎ 一度だけ揃える</button></div></header><p data-library-status role="status">隔離プレビュー：旧保存には書き込みません。AI・共有接続なし。</p><div class="parallel-grid" data-library-grid></div><footer class="library-notice">隔離したローカル試作 · AI／共有接続なし · 旧保存の自動移行なし</footer>';
const brand=q('#toolbar>.brand-mark')?.cloneNode(true);if(brand)q('.parallel-heading',shell).prepend(brand);document.body.append(shell);document.documentElement.classList.add('parallel-open');
const style=document.createElement('style');style.textContent='.library-notice{font-size:11px;color:#657065;padding:4px 18px}.library-group{display:flex;align-items:center;gap:8px;padding-right:16px;border-right:1px solid #e0e4e2}.library-group>span{font-size:12px;color:#647069}.library-host[data-layout="1"] .parallel-grid{grid-template-columns:1fr}.library-dialog{position:fixed;inset:0;z-index:100003;background:#182a3544;display:grid;place-items:center}.library-dialog>section{background:white;border-radius:24px;padding:20px;max-width:680px;width:calc(100% - 40px);max-height:80vh;overflow:auto;box-shadow:0 8px 40px #0003}.library-dialog button,.library-dialog select{min-height:40px;margin:4px;padding:8px 14px;border:0;border-radius:18px}.library-dialog h2{font-size:18px}.library-row{display:flex;align-items:center;gap:8px;border-bottom:1px solid #edf0ed;padding:8px 0}.library-row span{flex:1}.library-dialog input{min-height:40px;width:90%;padding:4px 10px}.library-pane>header{justify-content:flex-end}.library-pane>header span{margin-right:auto;font-size:11px;color:#647069}.library-host [data-library-status]{margin:6px 18px;font-size:12px;color:#657065}';document.head.append(style);
function status(value){q('[data-library-status]',shell).textContent=value?.message||String(value);}
function child(p){return p.frame.contentWindow.EditorPane;}
function anyPaneBusy(){return [...panes.values()].some(p=>p.busy||p.frame.contentWindow?.SHARED?.saveBusy);}
function valid(p,fromNativeSave=false){if(!p?.ready||p.busy||!fromNativeSave&&p.frame.contentWindow?.SHARED?.saveBusy)throw Error('編集画面の処理完了をお待ちください。');return p;}
// Host-owned copies keep saved state without retaining a detached editor realm.
function state(p){return copy(child(p).state());}
function record(p){return plans.get(p.planId);}
function snapshot(p){const r=record(p),s=state(p),encoded=JSON.stringify(s.plan);if(r.lastPayload!==encoded){r.generation++;r.lastPayload=encoded;}r.state=s;r.plan=s.plan;return s;}
async function persistDraft(p){const r=record(p),s=snapshot(p);await repo.saveDraft(session,r.id,{...s,payload:s.plan,generation:r.generation,baseRevisionId:r.baseRevisionId,baseGeneration:r.baseGeneration});}
function viewState(){return {retainedPlanIds:retained.slice(),panelPlanIds:[...panes.values()].map(p=>p.planId),sync,cameras:Object.fromEntries([...panes.values()].filter(p=>p.ready).map(p=>[p.planId,child(p).view()]))};}
function persistView(){viewQueue=viewQueue.catch(()=>{}).then(()=>repo.setView(session,viewState()));return viewQueue;}
function modal(title){dialog?.remove();dialog=document.createElement('div');dialog.className='library-dialog';const box=document.createElement('section'),heading=document.createElement('h2');heading.textContent=title;box.append(heading);dialog.append(box);document.body.append(dialog);return box;}
function closeDialog(){dialog?.remove();dialog=null;}
function button(box,title,action){const b=document.createElement('button');b.className='tbtn';b.textContent=title;b.onclick=action;box.append(b);return b;}
async function chooseDirty(p){if(!state(p).dirty)return true;return new Promise(resolve=>{const box=modal('「'+record(p).name+'」の未保存の編集');const finish=v=>{closeDialog();resolve(v);};button(box,'保存して続ける',()=>finish('save')).dataset.libraryDecision='save';button(box,'保存せず続ける',()=>finish('discard')).dataset.libraryDecision='discard';button(box,'キャンセル',()=>finish(false)).dataset.libraryDecision='cancel';}).then(async choice=>{if(!choice)return false;if(choice==='save'){authorizedSavePane=p.id;try{if(!await p.frame.contentWindow.savePlanToStorage())return false;return !state(p).dirty;}finally{authorizedSavePane=null;}}
 const r=record(p),s=snapshot(p);await repo.saveDraft('discard:'+uid(),r.id,{...s,payload:s.plan,generation:r.generation,baseRevisionId:r.baseRevisionId,baseGeneration:r.baseGeneration});const saved=await repo.read(r.id);await child(p).install(saved.payload);r.state=state(p);r.generation++;r.lastPayload=JSON.stringify(r.state.plan);r.baseRevisionId=saved.revision.id;r.baseGeneration=saved.head.headGeneration;await persistDraft(p);return true;});}
async function loadRecord(id){if(plans.has(id))return plans.get(id);const saved=await repo.read(id);if(!saved)throw Error('プランがありません。');const draft=await repo.get('drafts',JSON.stringify([session,id]));const recovery=(!draft&&saved.head.recoveredUnsaved)?await repo.get('drafts',JSON.stringify(['recovery:'+saved.head.origin.snapshotId,id])):null,s=draft||recovery;const r={id,name:saved.head.name,plan:s?.plan||s?.payload||saved.payload,state:s?{plan:s.plan||s.payload,history:s.history||[],redo:s.redo||[],view:s.view,dirty:!!s.dirty}:null,generation:s?.generation||0,baseRevisionId:s?.baseRevisionId||saved.revision.id,baseGeneration:s?.baseGeneration||saved.head.headGeneration};r.lastPayload=JSON.stringify(r.plan);plans.set(id,r);return r;}
function refresh(){const locked=busy||transitionBusy||anyPaneBusy();shell.dataset.layout=panes.size===1?'1':'2';for(const p of panes.values()){p.remove.disabled=locked||!p.ready;if(!p.ready)continue;const w=p.frame.contentWindow,select=q('[data-library-current]',w.document);if(!select)continue;select.replaceChildren();for(const id of retained){const r=plans.get(id);if(!r)continue;const op=document.createElement('option');op.value=id;op.textContent=r.name;op.disabled=[...panes.values()].some(other=>other!==p&&other.planId===id);select.append(op);}select.value=p.planId;select.disabled=locked;const save=q('#save-btn',w.document);if(save)save.disabled=locked;for(const b of w.document.querySelectorAll('[data-library-action]'))b.disabled=locked;q('[data-library-dirty]',w.document).textContent=w.DIRTY?'● 未保存':'✓ 保存済み';p.label.textContent='';}for(const b of shell.querySelectorAll('.parallel-controls button'))b.disabled=locked;}
async function mount(id){if(panes.size>=2)throw Error('同時に開ける画面は2つです。');const r=await loadRecord(id),paneId='library-pane-'+(++sequence)+'-'+uid(),card=document.createElement('section'),header=document.createElement('header'),label=document.createElement('span'),remove=document.createElement('button'),frame=document.createElement('iframe');card.className='parallel-pane library-pane';remove.className='tbtn parallel-pane-remove';remove.textContent='×';remove.title='このプランの画面を閉じる';remove.dataset.libraryClose='';remove.setAttribute('aria-label','このプランの画面を閉じる');header.append(label,remove);card.append(header,frame);frame.title=r.name+'の既存エディター';const p={id:paneId,planId:id,card,frame,label,remove,ready:false};panes.set(paneId,p);q('[data-library-grid]',shell).append(card);remove.onclick=()=>api.run(()=>api.closePlan(paneId));frame.onpointerenter=()=>activeId=paneId;const loaded=new Promise(resolve=>frame.onload=resolve);frame.src='/index.html?editorPane='+paneId+'&planLibrary=1';await loaded;await child(p).ready;frame.contentWindow.__editorPlanId=id;await child(p).install(r.plan,r.state);p.ready=true;activeId=activeId||paneId;refresh();if(sync)api.align();return p;}
async function dispose(p){child(p)?.dispose();p.card.remove();panes.delete(p.id);if(activeId===p.id)activeId=panes.keys().next().value||null;if(!panes.size)await pool.dispose();refresh();}
const api=window.PlanLibrary=window.ParallelEditors={repo,plans,panes,modelPool:pool,get activeId(){return activeId;},get session(){return session;},get retained(){return retained.slice();},childReady(){refresh();},refresh,
 async run(fn){if(busy||anyPaneBusy()){status('保存／読込中の画面があります。完了後に操作してください。');return false;}busy=true;refresh();try{return await fn();}catch(e){status(e);return false;}finally{busy=false;refresh();}},
 edited(id){const p=panes.get(id);if(p?.ready){snapshot(p);refresh();persistDraft(p).catch(status);}},
 changed(id){activeId=id;const source=panes.get(id);if(sync&&source?.ready)for(const p of panes.values())if(p!==source&&p.ready){const v=child(p).view(),from=child(source).view();v.twoD=from.twoD;if(from.camera&&v.camera&&((from.view==='3d-walk')===(v.view==='3d-walk')))v.camera=from.camera;child(p).applyView(v);}clearTimeout(api.cameraTimer);api.cameraTimer=setTimeout(()=>{const cameras=viewState().cameras;viewQueue=viewQueue.catch(()=>{}).then(()=>repo.updateView(session,previous=>({...previous,cameras,sync}))).catch(status);},200);},
 align(){api.changed(activeId||panes.keys().next().value);},
 async openPlan(id){if([...panes.values()].some(p=>p.planId===id))return status('このプランは既に開いています。');if(!retained.includes(id)&&retained.length>=4)throw Error('作業中の4案から画面を閉じてから開いてください。保存済み一覧の案は削除されません。');if(panes.size>=2)throw Error('開いている画面を閉じてから別のプランを開いてください。');await loadRecord(id);if(!retained.includes(id))retained.push(id);await mount(id);await persistView();status('プランを開きました。');},
 async switchPlan(paneId,id){const p=valid(panes.get(paneId));if(p.planId===id)return true;if([...panes.values()].some(other=>other!==p&&other.planId===id))throw Error('このプランはもう一方で開いています。');await loadRecord(id);if(!await chooseDirty(p)){refresh();return false;}await persistDraft(p);const r=plans.get(id);p.ready=false;try{await child(p).install(r.plan,r.state);p.planId=id;p.frame.contentWindow.__editorPlanId=id;}finally{p.ready=true;refresh();}await persistView();status('編集中のプランを切り替えました。');return true;},
 async closePlan(paneId){if(anyPaneBusy())throw Error('保存中の画面があります。完了後に閉じてください。');const p=valid(panes.get(paneId));if(!await chooseDirty(p))return false;await persistDraft(p);const captured=viewState();captured.panelPlanIds=captured.panelPlanIds.filter(id=>id!==p.planId);captured.retainedPlanIds=captured.retainedPlanIds.filter(id=>id!==p.planId);await repo.setView(session,captured);retained=captured.retainedPlanIds;await dispose(p);status('画面を閉じました。保存済みプランと履歴は一覧に残っています。');return true;},
 async persistPane(paneId,id,data){if((busy||transitionBusy)&&authorizedSavePane!==paneId)throw Error('画面の配置／読込を処理中です。編集は保持しています。完了後に保存してください。');const p=valid(panes.get(paneId),true);if(p.planId!==id)throw Error('保存対象が変わりました。');const r=record(p),s=snapshot(p),generation=r.generation,baseRevisionId=r.baseRevisionId,baseGeneration=r.baseGeneration;p.busy=true;refresh();try{const draftResult=await repo.saveDraft(session,id,{...s,plan:copy(data),payload:copy(data),generation,baseRevisionId,baseGeneration});if(draftResult.status==='conflict')throw Error('下書きの世代が競合しました。編集内容を保全しました。');const result=await repo.save({planId:id,payload:data,operationId:uid(),baseRevisionId,baseGeneration,sessionId:session,draftGeneration:generation});if(result.status!=='saved')throw Error('別画面の保存と競合しました。編集内容と競合版を保持しました。履歴で確認してください。');r.baseRevisionId=result.revisionId;r.baseGeneration=result.head.headGeneration;snapshot(p);if(r.generation===generation){r.state.dirty=false;r.plan=copy(data);}else await persistDraft(p);status('「'+r.name+'」を同じプランIDへ保存しました。');return result;}finally{p.busy=false;refresh();}},
 async readSavedPane(id){return (await repo.read(id))?.payload||null;},
 async reloadPlan(paneId){const p=valid(panes.get(paneId));if(!await chooseDirty(p))return false;const r=record(p),saved=await repo.read(r.id);await child(p).install(saved.payload);r.baseRevisionId=saved.revision.id;r.baseGeneration=saved.head.headGeneration;r.generation++;r.lastPayload=JSON.stringify(child(p).snapshot());await persistDraft(p);refresh();status('保存したプランを開き直しました。');return true;},
 async duplicate(paneId){const p=valid(panes.get(paneId));if(!await chooseDirty(p))return false;const r=record(p),id='plan-'+uid();await repo.duplicate(r.id,id,r.name+'（複製）',uid());status('複製を別のプランIDで保存しました。共通一覧から開けます。');await api.list();},
 async history(paneId){const p=valid(panes.get(paneId)),r=record(p),box=modal('「'+r.name+'」の保存履歴');for(const rev of (await repo.history(r.id)).reverse()){const row=document.createElement('div');row.className='library-row';const span=document.createElement('span');span.textContent=rev.kind+' · '+rev.id.split(':').at(-1).slice(0,8)+(rev.id===r.baseRevisionId?'（現在の基準）':'');row.append(span);button(row,'この版を復元',()=>{closeDialog();api.run(async()=>{if(!await chooseDirty(p))return;const current=record(p);const result=await repo.restore(current.id,rev.id,current.baseRevisionId,current.baseGeneration,uid());if(result.status!=='saved')throw Error('復元が競合しました。現在の編集は変更していません。');const restored=await repo.read(current.id);await child(p).install(restored.payload);current.baseRevisionId=result.revisionId;current.baseGeneration=result.head.headGeneration;current.generation++;current.lastPayload=JSON.stringify(child(p).snapshot());await persistDraft(p);status('履歴を新しい保存版として復元しました。以前の版も残っています。');refresh();});}).dataset.libraryRestore=rev.id;box.append(row);}button(box,'閉じる',closeDialog);},
 async list(){const box=modal('共通プラン一覧');for(const head of (await repo.list()).filter(h=>h.verified!==false)){const row=document.createElement('div');row.className='library-row';const text=document.createElement('span');text.textContent=head.name+(panes.size&&[...panes.values()].some(p=>p.planId===head.id)?'（編集中）':'');row.append(text);button(row,'開く',()=>{closeDialog();api.run(()=>api.openPlan(head.id));}).dataset.libraryOpenPlan=head.id;box.append(row);}button(box,'旧保存を読み取り専用で一覧',()=>api.legacyList());button(box,'閉じる',closeDialog);},
 async legacyList(){const sources=await repo.readLegacySources();const box=modal('旧保存：読み取り専用 → コピー → 検証');const note=document.createElement('p');note.textContent='旧保存を削除・更新しません。選んだ原本の非破壊コピーを新しい一覧へ追加します。';box.append(note);for(const source of sources){const row=document.createElement('div');row.className='library-row';const span=document.createElement('span');span.textContent=source.sourceId;row.append(span);button(row,'非破壊コピーして検証',()=>api.run(async()=>{const result=await repo.importSource(source);if(result.diagnostic&&!result.plans.length)throw Error('原本を回収しましたが、この形式を開けません: '+result.diagnostic);status(result.plans.length+'案を検証してコピーしました。旧原本は保持しています。'+(result.entryDiagnostics?.length?' '+result.entryDiagnostics.length+'案は形式を確認できないため原本保全のみです。':''));await api.list();})).dataset.libraryCopySource=source.sourceId;box.append(row);}if(!sources.length){const p=document.createElement('p');p.textContent='旧保存はありません。';box.append(p);}button(box,'戻る',()=>api.list());},
 async newPlan(){const box=modal('新しいプラン');const input=document.createElement('input');input.placeholder='プラン名';input.value='新しいプラン';box.append(input);button(box,'作成して開く',()=>{const name=input.value.trim()||'新しいプラン';closeDialog();api.run(async()=>{const id='plan-'+uid();await repo.save({planId:id,name,operationId:uid(),baseRevisionId:null,baseGeneration:0,payload:{walls:[],rooms:[],items:[],startMode:'blank'}});await api.openPlan(id);});});button(box,'読み取り済み3階サンプルを確認（AIなし）',()=>{closeDialog();api.run(async()=>{const body=await(await fetch('/local-preview/sample.json')).json(),id='plan-'+uid();await repo.save({planId:id,name:'読み取り済み3階サンプル',operationId:uid(),baseRevisionId:null,baseGeneration:0,payload:{walls:[],rooms:[],items:[],startMode:'blank'}});await api.openPlan(id);const p=[...panes.values()].find(p=>p.planId===id),w=p.frame.contentWindow;w.openPlanImport();w.PlanImport.stageBuildingReview(body);w.document.getElementById('plan-import-status').textContent='読み取り済みのテストサンプルです。AIは実行していません。階を確認して部分適用できます。';status('読み取り済みサンプルを既存の取り込み確認UIで開きました。');});}).dataset.librarySample='';button(box,'図面で扉5点を確認した設定例（6点未確認・AIなし）',()=>{closeDialog();api.run(async()=>{if(panes.size>=2||retained.length>=4)throw Error('画面を1つ閉じてから設定例を開いてください。保存済み案は保持されます。');const payload=await(await fetch('/local-preview/source-reviewed-doors.json')).json(),id='plan-'+uid();await repo.save({planId:id,name:'図面確認例：扉5点／6点未確認',operationId:uid(),baseRevisionId:null,baseGeneration:0,payload});await api.openPlan(id);status('手動で図面を確認した方向設定例です。位置・幅は未実測で、4点に壁との干渉が残ります。既存案は上書きしていません。');});}).dataset.libraryReviewedDoors='';button(box,'キャンセル',closeDialog);},
 async layout(count){if(anyPaneBusy())throw Error('保存中の画面があります。完了後に配置を変更してください。');if(count===1&&panes.size===2){const p=[...panes.values()].find(p=>p.id!==activeId)||[...panes.values()][1];await persistDraft(p);const v=viewState();v.panelPlanIds=v.panelPlanIds.filter(id=>id!==p.planId);await repo.setView(session,v);await dispose(p);return;}if(count===2&&panes.size<2){const id=retained.find(id=>![...panes.values()].some(p=>p.planId===id));if(id)await mount(id);else return api.list();await persistView();}},
 hasUnsaved(){return [...panes.values()].some(p=>p.ready&&state(p).dirty);}
};
// One transition owns its pane until all awaited persistence/install work completes.
for(const name of ['openPlan','switchPlan','closePlan','reloadPlan','layout']){const original=api[name];api[name]=async function(){if(transitionBusy||anyPaneBusy())throw Error('保存／画面切替の完了後に操作してください。');transitionBusy=true;refresh();try{return await original.apply(api,arguments);}finally{transitionBusy=false;refresh();}};}
q('[data-library-open]',shell).onclick=()=>api.run(()=>api.list());q('[data-library-new]',shell).onclick=()=>api.run(()=>api.newPlan());for(const b of shell.querySelectorAll('[data-library-layout]'))b.onclick=()=>api.run(()=>api.layout(Number(b.dataset.libraryLayout)));q('[data-parallel-sync]',shell).onchange=e=>{sync=e.target.checked;if(sync)api.align();persistView().catch(status);};q('[data-parallel-align]',shell).onclick=()=>{const old=sync;sync=true;api.align();sync=old;};
window.addEventListener('beforeunload',e=>{if(api.hasUnsaved()){e.preventDefault();e.returnValue='';}});
(async()=>{const view=await repo.get('views',session);if(view){retained=view.retainedPlanIds;sync=view.sync!==false;q('[data-parallel-sync]',shell).checked=sync;for(const id of retained)await loadRecord(id);for(const id of view.panelPlanIds){const p=await mount(id);if(view.cameras?.[id])child(p).applyView(view.cameras[id]);}}if(!panes.size)status('「開く」から保存済みプラン、「新規」から新しいプランを選んでください。旧保存は自動移行しません。');refresh();})().catch(status);
})();
